### ISSUE TITLE
Unable to upload cover

### ISSUE THREAD

**Issue by ahmadawais** [ultimatemember/ultimatemember#1]
Clicking the cover doesn't load anything for me to add image. 
Nice plugin, I hope to include it in future list of WPMetaList.com

**Comment by ultimatemember** [comment]
Do you get the modal when you try to change profile photo? Or none of the modals get loaded? Also did you try please a clean setup (Disabling all other plugins, switching to default theme) to see if it is a plugin/theme conflict?

**Comment by ahmadawais** [comment]
I was trying out at a local theme which I am still coding and no pop up or modals were getting loaded. 
On clean setup it was working.

**Comment by ultimatemember** [comment]
I'd suspect some local js errors, preventing the modal from loading up.

**Comment by ahmadawais** [comment]
Close the ticket, I guess you are right.
