### ISSUE TITLE
Unify all textdomains to "ultimatemember"

### ISSUE THREAD

**Issue by deckerweb** [ultimatemember/ultimatemember#10]
By improving the German translations for my projects I found out a few issues with your current translation implementation.

1) I did my own scanning of strings - excluding the Redux Framework library (!) - and some strings are not yet in your default .pot file!

2) Most important: please UNIFY all textdomains to the one and only "ultimatemember" -- currently there are other textdomains in use also:
- "edd-recurring" (1 string!)
- "edd" (1 string!)
- "default" (101 strings currently!!!!) ---> those strings have no textdomain yet in your plugin, but WordPress interprets it as "default"!

--> for all 3 textdomains translations CANNOT be displayed YET, so please unify to "ultimatemember"

3) Please add the proper entries in plugin header for translations/ textdomain - this for example makes the plugin's description translateable.

Like so:
/*
Plugin Name: Ultimate Member
Plugin URI: http://ultimatemember.com/
Description: The easiest way to create powerful online communities and beautiful user profiles with WordPress
Version: 1.2.98
Author: Ultimate Member
Author URI: http://ultimatemember.com/
Text Domain: ultimatemember   <--- THIS ONE
Domain Path: /languages/   <--- THIS ONE
*/

4) You should provide an UP TO DATE default .pot file with the plugin or prominently for download on your site... :)

THANKS IN ADVANCE!

--David :)

**Comment by champsupertramp** [comment]
Hi @deckerweb ,

We are working on the internationalization with WPML support. Please check out the latest version!  

Thank you,

**Comment by deckerweb** [comment]
WPML support will not help this much -- if you fully implement the suggestions above it will be WPML compatible anyways. It is better to follow the real i18n implementation after WordPress standards and best practices.
- this includes the above suggestion
- this also includes full compatibility to WordPress language packs

WPML might be a popular plugin but it is an "island solution". There are many other language plugins, more cleaner, better coded and totally lightweight.

Making something WPML compatible is NOT bad, don't get me wrong, but this could only be an additional step not the first one.

Thank you!!
-Dave :)

**Comment by champsupertramp** [comment]
Hi @deckerweb 

I'm unifying the textdomain. We are preparing the plugin with the WordPress standards to enhance with WPML support. :)

see the progress: 
https://github.com/ultimatemember/ultimatemember/pull/27

Thank you!
