### ISSUE TITLE
Version 1.3.39 defaults ALL profile pics to gravatars if the Gravatar setting is on

### ISSUE THREAD

**Issue by nickburne** [ultimatemember/ultimatemember#100]
Now, if Settings > Users > Use Gravatars? setting is switched on, ALL profile photos that don't have gravatars show a gravatar logo and not the default profile pic, making sites look aweful.

I have tested this on a new install with just UM core installed and Twenty 16 theme

Thanks, N

**Comment by champsupertramp** [comment]
Hi @nickburne , Did you try our new Gravatar tool to fix this issue? 

Please see UM > Settings > Extensions > Tools > Enable Gravatar.
And then go to /wp-admin/admin.php?page=gravatar_transfer

I already pushed changes to change Gravatar image with UM default image: 
https://github.com/ultimatemember/ultimatemember/commit/573b35566c9de6d3362cdc1a355f55af500d4dcb

This will be pushed tonight.

**Comment by nickburne** [comment]
@champsupertramp - thanks. Yes I have run this. Looks like https://github.com/ultimatemember/ultimatemember/commit/573b35566c9de6d3362cdc1a355f55af500d4dcb will solve the problem.

**Comment by nickburne** [comment]
My guess is that this will drive a lot of support requests as I guess most people will have ettings > Users > Use Gravatars? setting switched on : (

**Comment by champsupertramp** [comment]
Hi, 

We've received 2 complains about this default gravatar image. I hope we can release tonight or on Monday.

**Comment by nickburne** [comment]
Thanks!

**Comment by abdusfauzi** [comment]
Hi @champsupertramp, I'm still facing issue with Gravatar even tough I've enabled Gravatar in the User settings and Extension settings.

It seems it only output `https://gravatar.com/avatar/?s=400&d=mm`. Notice the missing hash.

Could the line 54 here in `um-filters-avatars.php` is the issue?

```
$avatar_url  = um_get_domain_protocol().'gravatar.com/avatar/'.um_user('synced_gravatar_hashed_id');
```
