### ISSUE TITLE
New Sort By option in Member Directories

### ISSUE THREAD

**Issue by nickburne** [ultimatemember/ultimatemember#101]
We are happy to do this as a pull request if you think it would be useful for core. My guess is that lots of people would want this:

Under Member Directories > General Options > Sort Users By, have an extra option that says:

"Users with profile photos first (new users first)"

Thoughts?

**Comment by champsupertramp** [comment]
Hi @nickburne Feel free to send pull request and we'll have a look. Thank your for your great contributions.
