### ISSUE TITLE
Display of `user_url` in header using code snippet.

### ISSUE THREAD

**Issue by alexlancaster** [ultimatemember/ultimatemember#1011]
**Expected behavior**

Display of `user_url` in header using code snippet.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**

I have tried posting this report on the WordPress forum but it keeps being marked as spam (it clearly is not spam), hence I am trying to post it as a github issue.

I am running UM 2.3.2 with the following WordPress version

WordPress 6.0
PHP version: 7.4.29.
MySQL version: 10.3.35-MariaDB

I was previously successfully using the code snippets here:

https://wordpress.org/support/topic/profile-page-website-url-logo-with-social-links-in-the-header/

specifically this snippet:

```add_filter("um_builtin_all_user_fields","um_092221_website_url_social");
function um_092221_website_url_social( $fields ){

    foreach ( $fields as $field => $args ) {
        if ( isset( $field ) && $field == 'user_url' ) {
            $fields[ $field ]['advanced'] = 'social';
            $fields[ $field ]['icon'] = 'um-faicon-globe';
            $fields[ $field ]['match'] = 'https://';
            $fields[ $field ]['color'] = '#96979a';          
        }
    }
    return $fields;
}
```

to display the user_url in the header. But after moving from WordPress 5.9 to WordPress 6.0, now all the links include this (preprended before the expected user_url:

`<br /><b>Warning</b>: strstr(): Empty needle in <b>/home/ronininstitute/public_html/wp-content/plugins/ultimate-member/includes/um-short-functions.php</b> on line <b>926</b><br />`

**To Reproduce**
1. Add a `user_url` to the user
2. Add the above code snippet using the code snippets plugin
3 Visit the profile
4. See the error above

**Do you use UM extensions?**

**WordPress Environment**
<details>
```
WordPress 6.0
PHP version: 7.4.29.
MySQL version: 10.3.35-MariaDB
```
</details>

**Comment by alexlancaster** [comment]
I was able to fix this with the workaround mentioned in this forum post: https://wordpress.org/support/topic/adding-user_url-to-header-no-longer-works/#post-15687467

essentially to replace

`$fields[ $field ]['match'] = 'https://';`

with

`$fields[ $field ]['match'] = ' ';`

**Comment by MissVeronica** [comment]
I will answer your Forum question here about this code snippet.
Yes it was wrong coded from the very beginning. 
When having a link like https://facebook.com the UM match will test against facebook.com for the validity of the link. With custom URL's there is no URL to test and removing the https:// or http:// will get a test against an empty string which PHP is giving a warning for. I don't think that WP 6.0 changed the PHP Warning but maybe your web hosting updated your PHP version at about the same time.

**Comment by alexlancaster** [comment]
> I will answer your Forum question here about this code snippet. Yes it was wrong coded from the very beginning. When having a link like https://facebook.com the UM match will test against facebook.com for the validity of the link. With custom URL's there is no URL to test and removing the https:// or http:// will get a test against an empty string which PHP is giving a warning for. I don't think that WP 6.0 changed the PHP Warning but maybe your web hosting updated your PHP version at about the same time.

Thanks for the information @MissVeronica. Since you mention validation I was wondering how I can emulate the validation of the the other social media handles (like Twitter), since I am adding custom social media handles, like ORCID.   For example in the case of Twitter:

- `@handle` in the field, it will automatically expand to `https://twitter.com/@handle`, 
-  but it will also work if you put in the full handle directly: `https://twitter.com/handle`
- and I believe it will reject incorrect URLs, like `https://tweet.com/@handle`

I would like to validate my additional social media handles in the same way.  So the following would all work:
- `https://orcid.org/0000-0001-7604-8041`
- `0000-0001-7604-8041` (would expand to `https://orcid.org/0000-0001-7604-8041`)

But it would reject, say:
- `https://notorcid.com/0000-0001-7604-8041`

can this be done by enhancing my custom PHP?

**Comment by MissVeronica** [comment]
_can this be done by enhancing my custom PHP? Is it as simple as using:_

Yes this is how all social links are validated including Twitter

**Comment by alexlancaster** [comment]
> _can this be done by enhancing my custom PHP? Is it as simple as using:_
> 
> Yes this is how all social links are validated including Twitter

Thanks, but don't I also need to create a custom validation item for my new social media icon so it appears in the drop-down list in the form builder? I see that there is one for each built-in type. When I put in a just the ID it doesn't automatically fix the URL nor do I get an error if the URL prefix is wrong.

My code only creates the icon in the header, based on the existence of the metakey.  Not sure how to do that.

**Comment by alexlancaster** [comment]
This is my current code:

`add_filter("um_builtin_all_user_fields","um_orcid");
function um_orcid( $fields ){

    foreach ( $fields as $field => $args ) {
        if ( isset( $field ) && $field == 'um_orcid_url' ) {
            $fields[ $field ]['advanced'] = 'social';
            $fields[ $field ]['icon'] = 'ai ai-orcid';
            $fields[ $field ]['match'] = ' ';
            $fields[ $field ]['color'] = '#A6CE39';                        
        }
    }
    return $fields;
}`
