### ISSUE TITLE
users.php status links

### ISSUE THREAD

**Issue by GetIT-GotIT-Good** [ultimatemember/ultimatemember#1046]
User role links are unnecessarily displayed when the current user has no role editing capability, thus no need to view or sort roles.

Same for UM Actions.  Status links shouldn't be displayed for dropdown options that have been unset via `um_admin_bulk_user_actions_hook`.

Also, user count in the link parentheses includes users who are restricted from view in UM role settings.  This can cause confusion and when a link is clicked for which there are no viewable users, the result is, of course, "No users found.", despite the number saying differently.

The status links are apparently hard-coded, so a hook would be nice for removing irrelevant links at least.

**Comment by nikitasinelnikov** [comment]
@GetIT-GotIT-Good 

It's removed in https://github.com/ultimatemember/ultimatemember/releases/tag/2.8.7

Please let me know if you have any questions.
Best Regards!
