### ISSUE TITLE
Field Labels are not translatable when set to required

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#1047]
We need to make the labels translatable when they are set to require:
https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/um-filters-fields.php#L17

WP Forum topic:
https://wordpress.org/support/topic/labels-for-required-fields-dont-get-translated/

**Comment by nikitasinelnikov** [comment]
Hi @champsupertramp 

I think that the label translation cannot be implemented via *.po and *.mo files translations, but through hook's callback:

```
function um_custom_edit_label_all_fields( $label, $data ) {
    if ( '{some key}' === $data['metakey'] && {current_lang_variable_checking} ) {
        $label = 'Translated text';
    }
    return $label;
}
add_filter( 'um_edit_label_all_fields', 'um_custom_edit_label_all_fields', 9, 2 );
```

**Comment by Reloecc** [comment]
Hello @nikitasinelnikov 

I believe there is a basic issue in the plugin itself. Where the $label is firstly filtered through um_edit_label_all_fields function, which adds .um-req span. And only after that it's being translted via __( $label, 'utlimate-member' ) when

$label = 'Username <span class="um-req" title="Required">*</span>';

This two callbacks needs to be reordered so the $asterisk is being added AFTER the $label is translated, not before.

![label-trans-order](https://github.com/ultimatemember/ultimatemember/assets/1162775/f8dddc92-2040-44c4-96bd-34e5efb01898)
