### ISSUE TITLE
Password reset request via WP All Users should use the UM email template

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1056]
**Is your feature request related to a problem? Please describe.**
A site administrator requesting a password reset email via WP All Users "Send password reset" on behalf of a registered user will not send the UM email template but a basic non customizable standard WP text is sent to the user instead.

**Describe the solution you'd like**
Use the UM template customized  by the site owner .

**Describe alternatives you've considered**
Code snippet

```
add_filter( 'send_retrieve_password_email', 'send_retrieve_password_email_custom', 10, 3 );

function send_retrieve_password_email_custom( $true, $user_login, $user_data ) {

    um_fetch_user( $user_data->ID );
    UM()->user()->password_reset();

    return false;
}
```

**Additional context**
UM Support Forum issue:
https://wordpress.org/support/topic/manual-password-resets-not-using-um-email-template/

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

Our team prepared the docs.
https://docs.ultimatemember.com/article/1790-send-um-reset-password-email-when-admin-send-password-reset-to-user

Best Regards!
