### ISSUE TITLE
Roles Capabilities

### ISSUE THREAD

**Issue by xotizm** [ultimatemember/ultimatemember#106]
its possible to make other wordpress roles such editor, author , etc. can manage user registration? in this case like can see pending user registration and can see their info (submitted form info)

thankyou.

best regards

**Comment by champsupertramp** [comment]
hi @xotizm, can you provide steps to recreate the issue?

**Comment by champsupertramp** [comment]
Fixed: https://github.com/ultimatemember/ultimatemember/commit/a5aa428ede562f522c4ef9be6b9957b9691c6412
