### ISSUE TITLE
Select2 locale not loaded

### ISSUE THREAD

**Issue by phildittrich** [ultimatemember/ultimatemember#1063]
**Expected behavior**
When using a different language setting than English, the Select2 locale should be loaded, but Select2 keeps its English error messages.

**Describe the bug**
In https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-enqueue.php the locale is never loaded, but should be in the same manner as the datetime locale.

**Workaround**
I added the local using my functions.php in this way:

```
/** 
 * Load select2 locale
*/

add_action( 'wp_enqueue_scripts', function() {
  $locale = get_locale();
  $um_path = WP_PLUGIN_DIR . '/ultimate-member/';
  $js_baseurl = plugins_url() . '/ultimate-member/assets/js/';
  if ( $locale ) {
    if ( file_exists( $um_path . 'assets/js/select2/i18n/' . substr($locale, 0, 2) . '.js' ) ) {
      wp_register_script( 'select2_locale', $js_baseurl . 'select2/i18n/' . substr($locale, 0, 2) . '.js', array( 'jquery', 'select2' ), '4.0.13', true );
      wp_enqueue_script( 'select2_locale' );
    }
  }
}, 10 );
```

Is this a bug and would you be interested in a pull request with a fix for class-enqueue.php?

**Comment by nikitasinelnikov** [comment]
Hi @phildittrich 

It works properly since 2.8.2 version.
https://github.com/ultimatemember/ultimatemember/commit/c5931289b7f647dd02cdecde2464ea0e0e77cee5

https://github.com/ultimatemember/ultimatemember/releases/tag/2.8.2

Thanks for your suggestion.
