### ISSUE TITLE
PHP Warning:  Undefined array key "label"

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1065]
PHP 8.0.21
UM 2.5.0

PHP Warning:  Undefined array key "label" in class-member-directory.php on line 551
PHP Warning:  Undefined array key "label" in class-member-directory.php on line 553

**Comment by champsupertramp** [comment]
Hi @MissVeronica 

Thank you for reporting the issue. Could you please provide screenshots of the Member Directory settings? I'll try to reproduce the issue on my end.

Thanks

**Comment by MissVeronica** [comment]
https://imgur.com/a/m03zTt0

My trace output saved from line 548
```
2022-08-17 15:45:23
Function: show_filter (0)
Variable: attrs
Count 8

Array
(
    [help] => help text
    [metakey] => tablepress_id
    [placeholder] => tablepress
    [public] => 1
    [roles] => Array
        (
            [0] => administrator
        )

    [title] => tablepress
    [type] => text
    [visibility] => all
)
```

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

There is a possible fix for the issue mentioned above.

Let me know if that works for you,
Best Regards!

**Comment by MissVeronica** [comment]
@nikitasinelnikov

Yes, this fixed my issue.
Thanks.

**Comment by nikitasinelnikov** [comment]
Thanks for verifying!
