### ISSUE TITLE
error message should be "email already registered" for the condition of <$mode == 'register' && email_exists( $args[ $key ]> )

### ISSUE THREAD

**Issue by shankch** [ultimatemember/ultimatemember#1069]
error message should be "email already registered" for the condition of <$mode == 'register' && email_exists( $args[ $key ]> )

**Comment by 0xsuid** [comment]
Kindly Check PR #1058

**Comment by shankch** [comment]
Thanks Godhani!

**Comment by shankch** [comment]
Nevermind I just modified the plugin code on my side and all worked quite well.
