### ISSUE TITLE
Disable auto-login after Admin user registration

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1070]
**Is your feature request related to a problem? Please describe.**
Admin registering users via the frontend while auto approve is enabled, and to prevent the auto login after the registration.
https://wordpress.org/support/topic/disable-auto-login-after-registration-3/

**Describe the solution you'd like**
Make this new feature Admin selectable in UM Settings -> Appearance -> Registration Form

**Describe alternatives you've considered**
Code Snippet
```
add_action( 'um_registration_complete', 'um_registration_complete_custom', 10, 2 );

function um_registration_complete_custom( $user_id, $args ) {

    $url = UM()->permalinks()->get_current_url();
    exit( wp_redirect( $url ) );
}
```

**Comment by nikitasinelnikov** [comment]
@AngeliMae we have an in-box solution to avoid auto-login for logged-in users since 2.5.1
Maybe deprecate this article https://docs.ultimatemember.com/article/1768-how-disable-auto-login-after-registration
