### ISSUE TITLE
web page refreshes after clicking on the register / login button

### ISSUE THREAD

**Issue by shankch** [ultimatemember/ultimatemember#1076]
The page refreshes after clicking on the register / login button in case of a failed register/login . How do I disable the whole page refresh?

**Comment by champsupertramp** [comment]
Hi @shankch 
This repository is not suitable for support. Please don't use our issue tracker for support requests, but for Ultimate Member core plugin issues only. Support can take place through the appropriate channels:

If you have a problem, you may want to start with the [support page](https://ultimatemember.com/support/).
The [Ultimate Member premium extensions' support portal](https://ultimatemember.com/support/ticket/) for customers who have purchased themes or extensions.
[Our community forum on wp.org](https://wordpress.org/support/plugin/ultimate-member/) which is available for all Ultimate Member users.
Support requests in issues on this repository will be closed on sight.
