### ISSUE TITLE
"PHP warning when nav menu is empty" not being fixed yet

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1077]
**Expected behavior**
"PHP warning when nav menu is empty" still not fixed in UM Version 2.5.0 as promised in the UM 2.4.0 release notes.

**Describe the bug**
https://wordpress.org/support/topic/php-8-compatibility-54/

The bug fix must still be used in `um-filters-navmenu.php`:

```
foreach ( $sorted_menu_items as &$menu_item ) {
			if ( $menu_item->title ) {
				$menu_item->title = UM()->shortcodes()->convert_user_tags( $menu_item->title );
			}
			if ( !empty( $menu_item->attr_title )) {  // BUG FIX
				$menu_item->attr_title = UM()->shortcodes()->convert_user_tags( $menu_item->attr_title );
			}
			if ( !empty( $menu_item->description )) {    // BUG FIX
				$menu_item->description = UM()->shortcodes()->convert_user_tags( $menu_item->description );
			}
		}
```

**Comment by Awilson089** [comment]
Cheers @MissVeronica.

To make this work i also had to change the description line as well:
 
`if ( !empty( $menu_item->description )) { `

**Comment by MissVeronica** [comment]
Here is the history of this issue https://github.com/ultimatemember/ultimatemember/issues/1000

**Comment by fidoboy** [comment]
This is not fixed. There is still issues/compatibility problems with themes like TagDiv Newspaper using the megamenu on main menu. Problem is with code in um-filters-navmenu.php If I comment out all code here, all works fine as expected.
