### ISSUE TITLE
UTF-8 safe display name capitalization

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1079]
**Is your feature request related to a problem? Please describe.**
Code exists in UM core but  `'force_display_name_capitlized'` not found in Admin Settings.

**Describe the solution you'd like**
UTF-8 safe display name capitalization with addition of language dependent prepositions

**Describe alternatives you've considered**
Code snippet using the  `'um_user_display_name_filter'` hook
```
add_filter( 'um_user_display_name_filter', 'um_user_display_name_filter_capitalization', 10, 3 );

function um_user_display_name_filter_capitalization( $name, $user_id, $html ) {

    if( !extension_loaded( 'mbstring' )) return $name;

    $chars = mb_str_split( mb_strtolower( $name ));

    $cap = true;
    $cap_flags = array( ' ', '-', "'" );
    $cap_name = '';

    foreach( $chars as $char ) {
        if( $cap ) {
            $cap_name .= mb_strtoupper( $char );
            $cap = false;
        } else {
            $cap_name .= $char;
            if( in_array( $char, $cap_flags )) $cap = true;
        }
    }

    $cap_language = array();
    $cap_language['lower'] = array( ' von ', ' de ', ' duc ', " d'", ' da ', ' del ', ' y ' );
    $cap_language['upper'] = array( ' Von ', ' De ', ' Duc ', " D'", ' Da ', ' Del ', ' Y ' );

// Filter hook to add more local language prepositions

    $cap_name = str_replace( $cap_language['upper'], $cap_language['lower'], $cap_name );

    if( mb_strpos( $cap_name, 'Mc' ) !== false ) {
        $strings = explode( 'Mc', $cap_name );        
        $cap_name = $strings[0] . 'Mc' . mb_strtoupper( mb_substr( $strings[1], 0, 1 )) . mb_substr( $strings[1], 1 );
    }

    return $cap_name;
}
```
**Additional context**

UM Support Forum issue
https://wordpress.org/support/topic/user-registration-126/

**Comment by champsupertramp** [comment]
Hi @MissVeronica 

Thank you for provind snippets. We've created a basic extension based on this with improvements. You can check it in https://github.com/ultimatemember/Extended/tree/main/um-capitalize-name

Also, added you in the credits in the changelog.txt and https://github.com/ultimatemember/Extended#contributors

Kindest Regards,
