### ISSUE TITLE
Improve backend count_users with the new user status caching

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1080]
**Expected behavior**
UM backend performance improvement.
Sites having 5 seconds increase in response time due to current usage of count_users.

**Describe the bug**
The UM function count_users is calling WP function count_users which returns both number of users in each role and the total number of users.
UM is only using total_users to the cost of having WP also calculating users per role.

**Expected behavior**
Use the user status cached number of users.
Add the cached number of users in each account status to get the total number of users.

**UM Support Forum**
https://wordpress.org/support/topic/horrible-performance-of-users-php/

**UM History**
https://github.com/ultimatemember/ultimatemember/pull/1021

**Comment by polucorus** [comment]
Got this problem on dozens of my websites, each page in the admin panel takes an additional 1.8s because of the count_users() call. Fixing it is incredibly simple, don't understand why it still hasn't been done.

**Comment by MissVeronica** [comment]
I have posted a code snippet fix now https://github.com/ultimatemember/ultimatemember/issues/1271

**Comment by nikitasinelnikov** [comment]
I think this issue is fixed since 2.8.7 where we rewrite the user statuses filter
https://github.com/ultimatemember/ultimatemember/releases/tag/2.8.7
