### ISSUE TITLE
Password is incorrect. Please try again

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1091]
Read this UM Support Forum thread:
https://wordpress.org/support/topic/password-is-incorrect-please-try-again/

with a solution here by @ZuFusion:
https://wordpress.org/support/topic/password-is-incorrect-please-try-again/page/3/#post-16050440

This issue is moved from https://github.com/ultimatemember/recaptcha/issues/7

Code snippet with the suggested solution.
Install the code snippet into your active theme’s functions.php file
or use the “Code Snippets” plugin.

https://wordpress.org/plugins/code-snippets/

```
remove_action( 'um_submit_form_errors_hook_login', 'um_submit_form_errors_hook_login', 10 );
add_action( 'um_submit_form_errors_hook_login', 'um_submit_form_errors_hook_login_replaced', 10 );

function um_submit_form_errors_hook_login_replaced( $args ) {
	$is_email = false;

	$form_id = $args['form_id'];
	$mode = $args['mode'];
	$user_password = $args['user_password'];


	if ( isset( $args['username'] ) && $args['username'] == '' ) {
		UM()->form()->add_error( 'username', __( 'Please enter your username or email', 'ultimate-member' ) );
	}

	if ( isset( $args['user_login'] ) && $args['user_login'] == '' ) {
		UM()->form()->add_error( 'user_login', __( 'Please enter your username', 'ultimate-member' ) );
	}

	if ( isset( $args['user_email'] ) && $args['user_email'] == '' ) {
		UM()->form()->add_error( 'user_email', __( 'Please enter your email', 'ultimate-member' ) );
	}

	if ( isset( $args['username'] ) ) {
		$authenticate = $args['username'];
		$field = 'username';
		if ( is_email( $args['username'] ) ) {
			$is_email = true;
			$data = get_user_by('email', $args['username'] );
			$user_name = isset( $data->user_login ) ? $data->user_login : null;
		} else {
			$user_name  = $args['username'];
		}
	} elseif ( isset( $args['user_email'] ) ) {
		$authenticate = $args['user_email'];
		$field = 'user_email';
		$is_email = true;
		$data = get_user_by('email', $args['user_email'] );
		$user_name = isset( $data->user_login ) ? $data->user_login : null;
	} else {
		$field = 'user_login';
		$user_name = $args['user_login'];
		$authenticate = $args['user_login'];
	}

	if ( $args['user_password'] == '' ) {
		UM()->form()->add_error( 'user_password', __( 'Please enter your password', 'ultimate-member' ) );
	}

    $user = apply_filters( 'authenticate', null, $authenticate, $args['user_password'] );

	if (is_wp_error( $user )) {
		UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
	} else {
		UM()->login()->auth_id = username_exists( $user_name );
	}

	// if there is an error notify wp
	if ( UM()->form()->has_error( $field ) || UM()->form()->has_error( $user_password ) || UM()->form()->count_errors() > 0 ) {
		do_action( 'wp_login_failed', $user_name, UM()->form()->get_wp_error() );
	}
}
```

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

The line in the code snippet above can back to vulnerability when via WP native login errors the user data can be traced:

`if (is_wp_error( $user )) {
		UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
`

`$user->get_error_message()` can return messages based on 'invalid_username', 'incorrect_password' error codes. Therefore, someone who tries to guess the password may know more details than necessary.

So this [commit](https://github.com/ultimatemember/ultimatemember/commit/43d2fe6a45fd33dbb0a80f4e3b056fae63a54e3d) can be a solution for the issue above when you need to handler 3rd-party errors.

Let me know you thoughts,
Best Regards!

**Comment by MissVeronica** [comment]
Your solution sounds OK to me.

**Comment by hiepvq** [comment]
@MissVeronica 
I think this solution is not clear and loop code . I saw code in new version:
```
       $user = get_user_by( 'login', $user_name );
	if ( $user && wp_check_password( $args['user_password'], $user->data->user_pass, $user->ID ) ) {
		UM()->login()->auth_id = username_exists( $user_name );
	} else {
		UM()->form()->add_error( 'user_password', __( 'Password is incorrect. Please try again.', 'ultimate-member' ) );
	}

	// Integration with 3rd-party login handlers e.g. 3rd-party reCAPTCHA etc.
	$third_party_codes = apply_filters( 'um_custom_authenticate_error_codes', array() );

	// @since 4.18 replacement for 'wp_login_failed' action hook
	// see WP function wp_authenticate()
	$ignore_codes = array( 'empty_username', 'empty_password' );

	$user = apply_filters( 'authenticate', null, $authenticate, $args['user_password'] );
	if ( is_wp_error( $user ) && ! in_array( $user->get_error_code(), $ignore_codes ) ) {
		if ( ! empty( $third_party_codes ) && in_array( $user->get_error_code(), $third_party_codes ) ) {
			UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
		} else {
			UM()->form()->add_error( $user->get_error_code(), __( 'Password is incorrect. Please try again.', 'ultimate-member' ) );
		}
	}

	$user = apply_filters( 'wp_authenticate_user', $user, $args['user_password'] );
	if ( is_wp_error( $user ) && ! in_array( $user->get_error_code(), $ignore_codes ) ) {
		if ( ! empty( $third_party_codes ) && in_array( $user->get_error_code(), $third_party_codes ) ) {
			UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
		} else {
			UM()->form()->add_error( $user->get_error_code(), __( 'Password is incorrect. Please try again.', 'ultimate-member' ) );
		}
	}
```
These steps was processed by core WP, look at **wp_authenticate_username_password** function
```
..\wp-includes\default-filters.php

// Default authentication filters.
add_filter( 'authenticate', 'wp_authenticate_username_password', 20, 3 );
add_filter( 'authenticate', 'wp_authenticate_email_password', 20, 3 );
```
replace them with this code is done:

```
       $user = apply_filters( 'authenticate', null, $authenticate, $args['user_password'] );

	if (is_wp_error( $user )) {
		UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
	} else {
		UM()->login()->auth_id = username_exists( $user_name );
	}
```
the 3rd partys often use **authenticate** filter of WP as they don't know **um_custom_authenticate_error_codes** filter

This message will be displayed : **Password is incorrect. Please try again**. whenever plugins hook to **authenticate** filter

**Comment by nikitasinelnikov** [comment]
Hi @hiepvq 

`add_action( 'um_submit_form_errors_hook_login', 'um_submit_form_errors_hook_login', 10 );` hook and the `um_submit_form_errors_hook_login` callback is used only via the UM Login form.

We had many support requests about security and decided to lock displaying WP native login errors (e.g. username doesn't exist, incorrect password, etc.) on the Ultimate Member Login Form.

If you want to use some 3rd-party plugin with Ultimate Member Login form please add the necessary error codes inside the callback for `um_custom_authenticate_error_codes` hook.

See the code snippet below:

`function my_custom_authenticate_error_codes( $codes ) {
    $codes = array( 'my_error_code_1', 'my_error_code_2' ); // replace to your 3rd-party error codes
    return $codes;
}
add_filter( 'um_custom_authenticate_error_codes', 'my_custom_authenticate_error_codes', 10, 1 );`

**Comment by knicks-lyu** [comment]
@hiepvq @nikitasinelnikov sorry for that ,Is this "Wrong password - please try again" problem solved? Because I recently created a website and used ultimate-member as the member management system, after the user registration is completed, I need to authenticate, but when the authentication is passed, the user log into the website, there will be a "password error - please try again" message, reset the password is ineffective, I have already tried N times, and I have also installed the code-snippets as described above, but it is not solved. I would like to ask what is the specific solution? Thank you very much.

**Comment by knicks-lyu** [comment]
@hiepvq and i also can't find the  wp_authenticate_username_password function in the plugin-editor.php would u like to tell me where is it? thanks u so much

**Comment by hiepvq** [comment]
@knicks-lyu try my best:

``` PHP
remove_action('um_submit_form_errors_hook_login', 'um_submit_form_errors_hook_login');
add_action('um_submit_form_errors_hook_login', 'zf_submit_form_errors_hook_login');

function zf_submit_form_errors_hook_login($submitted_data) {

    $user_password = $submitted_data['user_password'];

	if ( isset( $submitted_data['username'] ) && $submitted_data['username'] == '' ) {
		UM()->form()->add_error( 'username', __( 'Please enter your username or email', 'ultimate-member' ) );
	}

	if ( isset( $submitted_data['user_login'] ) && $submitted_data['user_login'] == '' ) {
		UM()->form()->add_error( 'user_login', __( 'Please enter your username', 'ultimate-member' ) );
	}

	if ( isset( $submitted_data['user_email'] ) && $submitted_data['user_email'] == '' ) {
		UM()->form()->add_error( 'user_email', __( 'Please enter your email', 'ultimate-member' ) );
	}

	if ( isset( $submitted_data['username'] ) ) {
		$authenticate = $submitted_data['username'];
		$field = 'username';
		if ( is_email( $submitted_data['username'] ) ) {
			$data = get_user_by('email', $submitted_data['username'] );
			$user_name = isset( $data->user_login ) ? $data->user_login : null;
		} else {
			$user_name  = $submitted_data['username'];
		}
	} elseif ( isset( $submitted_data['user_email'] ) ) {
		$authenticate = $submitted_data['user_email'];
		$field = 'user_email';
		$data = get_user_by('email', $submitted_data['user_email'] );
		$user_name = isset( $data->user_login ) ? $data->user_login : null;
	} else {
		$field = 'user_login';
		$user_name = $submitted_data['user_login'];
		$authenticate = $submitted_data['user_login'];
	}

	if ( $submitted_data['user_password'] == '' ) {
		UM()->form()->add_error( 'user_password', __( 'Please enter your password', 'ultimate-member' ) );
	}

	$user = apply_filters( 'authenticate', null, $authenticate, $submitted_data['user_password'] );

	if (is_wp_error( $user )) {
		UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
	} else {
		UM()->login()->auth_id = username_exists( $user_name );
	}

	// if there is an error notify wp
	if ( UM()->form()->has_error( $field ) || UM()->form()->has_error( $submitted_data['user_password'] ) || UM()->form()->count_errors() > 0 ) {
		do_action( 'wp_login_failed', $user_name, UM()->form()->get_wp_error() );
	}
}
```

**Comment by knicks-lyu** [comment]
@hiepvq thank u so much ,but i still understand ,i copy this code and then ,where should i past then ?

**Comment by hiepvq** [comment]
@knicks-lyu place it in functions.php of theme

**Comment by knicks-lyu** [comment]
@hiepvq u mean here? 
![影像 (1)](https://github.com/ultimatemember/ultimatemember/assets/149471509/6c925420-864a-4e4e-8863-5cb9ee241668)

**Comment by knicks-lyu** [comment]
i think is here right? and is to replace the original or continue posting?
![螢幕擷取畫面 2023-10-31 172057](https://github.com/ultimatemember/ultimatemember/assets/149471509/b47a64b0-7d3f-402e-bf1a-b14ca8e2db07)

**Comment by knicks-lyu** [comment]
@hiepvq  well when i past to code in the end, and refresh the file ,there has show the wrong message 

Due to a code error on line 709 of file wp-content/themes/twentyfifteen/functions.php, the associated PHP code change was not applied, please fix it and save it again.
Cannot redeclare zf_submit_form_errors_hook_login() (previously declared in wp-content/plugins/code-snippets/php/snippet-ops.php(581) : eval()'d code:4)

**Comment by knicks-lyu** [comment]
Hello, @hiepvq when I copy and paste the code into Tenty Fifteen function.php(attach) and save it, and try to log in at the same time, I get the message "Your IP has been flagged as spam/malicious." I'm wondering if there's something in the code that needs to be fixed?
![functionPHP2023-11-01 091257](https://github.com/ultimatemember/ultimatemember/assets/149471509/4b96bfc8-78b9-43f7-9fb3-989be3ce0a49)
![loginfail2023-11-01 091130](https://github.com/ultimatemember/ultimatemember/assets/149471509/a2363423-9b4f-4f82-89bb-28b86b63bf0c)

**Comment by MissVeronica** [comment]
@knicks-lyu
I have posted a code snippet for debugging this issue 
and a recommendation for you to disable your web hosting server caching for the UM pages
in the UM Support Forum.

**UM Support Forum issue**
https://wordpress.org/support/topic/password-is-incorrect-please-try-again-7/

**Comment by hiepvq** [comment]
> Hello, @hiepvq when I copy and paste the code into Tenty Fifteen function.php(attach) and save it, and try to log in at the same time, I get the message "Your IP has been flagged as spam/malicious." I'm wondering if there's something in the code that needs to be fixed?
> ![functionPHP2023-11-01 091257](https://github.com/ultimatemember/ultimatemember/assets/149471509/4b96bfc8-78b9-43f7-9fb3-989be3ce0a49)
> ![loginfail2023-11-01 091130](https://github.com/ultimatemember/ultimatemember/assets/149471509/a2363423-9b4f-4f82-89bb-28b86b63bf0c)
> 

Check your hosting security

**Comment by hiepvq** [comment]
@knicks-lyu check your hosting security

**Comment by c-orazio** [comment]
Same problem with UM 2.8.0, unable to login using teh login page of UM, but possible through other channels. No reCapcha installed (is it an option from core? I did not look at teh good place?) 
Thanks for you help.

**Comment by c-orazio** [comment]
> Same problem with UM 2.8.0, unable to login using teh login page of UM, but possible through other channels. No reCapcha installed (is it an option from core? I did not look at the good place?) Thanks for you help.
I suspect a conflict with an other extension requiring capcha..

**Comment by nikitasinelnikov** [comment]
Hi @c-orazio 

Please make the conflict test. Maybe you have 3rd-party plugins and they use native wp-login.php hooks for some login not-a-bot verifications.

Ref. https://docs.ultimatemember.com/article/96-how-to-do-a-plugin-theme-conflict-test
