### ISSUE TITLE
Email needs a validation/confirmation input on registration, as like password confirmation

### ISSUE THREAD

**Issue by toshodin** [ultimatemember/ultimatemember#1095]
**Is your feature request related to a problem? Please describe.**
We seem to have a lot of users who fly through registration inputs, but end up mistyping their emails, prime examples:

- example@exampl.com
- example@example.cm

Because the above technically still conform to valid email format - something@something.something, they get accepted, but the users never receive their activation links, and are unable to log in, as they try and log in using the email they have, rather than the email stored with a typo.

**Describe the solution you'd like**
These errors would be caught with a secondary "confirm email" validation input box, as you have with password entry field. It feels this is definitely necessary for such an important field on registration, ie the main way they id to login.

**Describe alternatives you've considered**
As far as I am aware there is no alternative to this above tried and tested method of entry validation.

**Additional context**
N/A

**Comment by MissVeronica** [comment]
@toshodin
I have made a code snippet for your email confirmation.
https://github.com/MissVeronica/UM-Confirm-email-address-at-Registration

**Comment by toshodin** [comment]
This has solved the issue for me perfectly and elegantly, thank you Miss Veronica! 
It would be great if this was a standard tick box in the email form field, like in the password field options.
