### ISSUE TITLE
Need a check for array on line 53 of um-actions-profile.php

### ISSUE THREAD

**Issue by perkster** [ultimatemember/ultimatemember#11]
We've integrated UM with IgnitionDeck and now that members are sometimes added via js, an error occurs on line 53 or core/um-actions-profile.php. Since the items handled in that loop are only from when a form is submitted, by adding in a simple if( is_array( $fields ) ) { } around the foreach loop, this eliminates the issue.

P.S. Been really liking this plugin!

**Comment by ultimatemember** [comment]
Patched.
