### ISSUE TITLE
feature request: Disable Payment Method for a Coupon Code

### ISSUE THREAD

**Issue by lalindeluis** [ultimatemember/ultimatemember#1102]
I am brainstorming... how to Disable filling out Payment details and Method for a Coupon Code? E.g. a coupon with full discount by percentage or fixed amount are applied at checkout, customers are insisted to update the payment information by default. In order to skip the putting payment information and payment method, maybe there should be an option in settings "Allow customers to checkout without payment details" enabled when Full Discount coupons are applied.

**Comment by nikitasinelnikov** [comment]
Hi @lalindeluis 

Please clarify what you mean. It looks like you select the wrong repo for making the Issue.

Thanks, 
Best Regards!
