### ISSUE TITLE
Version 1.3.39 screwed up a few things

### ISSUE THREAD

**Issue by i2000s** [ultimatemember/ultimatemember#111]
I think the core team is working on solving some of the issues brought about by the recent release. I am not sure if all of them have been noticed, I just list here a few things I have encountered. Feel free to chime in:

1. Using multiple short codes of UM forms on one page do not work any more. Only the first short code worked in my case. 

2. There seems to be a conflict with papercite plugin so that the shortcode for papercite doesn't render correctly (may need further inspection, but I have rolled back).

3. When a user name has a hyphen inside, the link to the user's profile doesn't work. 

I have rolled back to V1.3.36, and everything works as before. This is not a good way to solve those problems, but it works temporarily for those who have encountered similar problems. 

Thanks for working on these.
Bests,
Qi

**Comment by champsupertramp** [comment]
hi @i2000s, have you tried the dev version? https://github.com/ultimatemember/ultimatemember/archive/master.zip

**Comment by i2000s** [comment]
That I haven't checked. Since I will be busy this week and our website will be visited by a lot of our perspective students, I am afraid I cannot help test the dev version on our website until next week. But I will be happy to try if you still need helpers by the end of next week. Thanks.

**Comment by champsupertramp** [comment]
hi @i2000s We've released version 1.3.40. 

Let us know if the update resolve the issues.

**Comment by champsupertramp** [comment]
I'll work on this issue: 
`When a user name has a hyphen inside, the link to the user's profile doesn't work.`

**Comment by champsupertramp** [comment]
Please check the pre-release version: https://github.com/ultimatemember/ultimatemember/releases/

**Comment by i2000s** [comment]
Just updated to the latest version from 1.3.36, and everything went crazy! 

```
Warning: require_once(/home/xyz/public_html/xyz.unm.edu/wp-content/plugins/ultimate-member/core/widgets/um-search-widget.php): failed to open stream: No such file or directory in /home/xyz/public_html/xyz.unm.edu/wp-content/plugins/ultimate-member/um-init.php on line62

Fatal error: require_once(): Failed opening required '/home/xyz/public_html/cquic.unm.edu/wp-content/plugins/ultimate-member/core/widgets/um-search-widget.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/xyz/public_html/cquic.unm.edu/wp-content/plugins/ultimate-member/um-init.php on line 62
```

**Comment by champsupertramp** [comment]
Hi @i2000s,

We've pushed fixes. the new directory didn't get through on our update. It should be fixed now with version 1.3.46:
https://wordpress.org/plugins/ultimate-member/

Thank you,

**Comment by i2000s** [comment]
Well, the warnings have changed with this new version (1.3.46):

```
Warning: require_once(/home/cquic/public_html/cquic.unm.edu/wp-content/plugins/ultimate-member/core/um-filters-language.php): failed to open stream: No such file or directory in /home/cquic/public_html/cquic.unm.edu/wp-content/plugins/ultimate-member/um-init.php on line 145

Fatal error: require_once(): Failed opening required '/home/cquic/public_html/cquic.unm.edu/wp-content/plugins/ultimate-member/core/um-filters-language.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/cquic/public_html/cquic.unm.edu/wp-content/plugins/ultimate-member/um-init.php on line 145
```

Now v1.3.44 is working.

**Comment by champsupertramp** [comment]
Hi @i2000s,

We've released version 1.3.47. Let us know if the update resolves the issue.

**Comment by i2000s** [comment]
@champsupertramp Yeap, it seems working now. Thank you for working on this issue promptly!

**Comment by champsupertramp** [comment]
@i2000s Thanks for letting us know.
