### ISSUE TITLE
Remove UM role meta DB queries when you know return will be "Not found"

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1133]
**Expected behavior**
Avoid doing DB queries with invalid role meta key arguments.

Don't expect to find UM Role meta value by using RoleID when the UM Role meta value being saved with UM Role key, this will result in extra DB queries for each UM Role always with the "Not found" return value.

UM Role ID and UM Role Key variable names are used in UM without difference for the content, which results in confusion.

Example:
RoleID `um_prospect`
Role key `prospect`
Role Name `Prospect`

**Describe the bug**
The addition of `if ( substr( $roleID, 0, 3 ) == 'um_' ) continue;` will remove DB queries for the UM roles when they are saved with UM Role keys and not saved with UM Role ID's and the second foreach will get these UM roles via WP caching and UM Role keys when "autoload" is set to "yes".

**Solution**
```
		function um_roles_init( $wp_roles = null ) {

			//Add UM role data to WP Roles
			foreach ( $wp_roles->roles as $roleID => $role_data ) {
				if ( substr( $roleID, 0, 3 ) == 'um_' ) continue;   // BUG FIX
				$role_meta = get_option( "um_role_{$roleID}_meta" );

				if ( ! empty( $role_meta ) ) {
					$wp_roles->roles[ $roleID ] = array_merge( $role_data, $role_meta );
				}
			}


			//Add custom UM roles
			$roles = array();

			$role_keys = get_option( 'um_roles', array() );
			foreach ( $role_keys as $role_key ) {
				$role_meta = get_option( "um_role_{$role_key}_meta" );
				if ( $role_meta ) {
					$roles[ 'um_' . $role_key ] = $role_meta;
				}
			}
```

**Comment by nikitasinelnikov** [comment]
I'm not sure why UM custom role exists in your $wp_roles->roles at the start of this callback function (maybe 3rd-party plugins enabled) because UM custom roles are added dynamically to $wp_roles->roles in the 3rd foreach of the `um_roles_init` function.

But I have added your suggested `continue;` to the first foreach to avoid double queried `get_option( "um_role_{$role_id}_meta" );`

**Comment by MissVeronica** [comment]
I have the "User Role Editor" plugin installed
https://www.role-editor.com/

**Comment by nikitasinelnikov** [comment]
Yes, for some reason 'wp_roles_init' hook is run twice when the "User Role Editor" plugin is active.

I guess it can be related to re-init roles and running `new WP_Roles()` inside their code. But for now, we skip 1 loop with meta queries for UM custom roles.
