### ISSUE TITLE
JavaScript large jpg image cropping in Windows 11

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1149]
**Describe the bug**
Cropping a large profile or cover photo with the height larger than the width 
results in a damaged image when type is `jpg` but not with same image and type is `png`.
Rotating the `jpg` image before cropping and upload will give a valid profile or cover photo.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active,
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
See this UM Extended plugin issue: https://github.com/ultimatemember/Extended/issues/21
This issue was first found in the Profile Photo upload Extended plugin but have afterwards been verified also for the default UM profile Photo upload.

`jquery.js?ver=3.6.1:5282 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.`

Screens for testing are non-touch units in Windows 11.
This issue is not occurring in Windows 10.
Same issue with iPhone and Android phone.

**Comment by ashubawork** [comment]
Hello @MissVeronica 

Could you check this issue with the latest version? We updated JS cropping script.

Regards.

**Comment by MissVeronica** [comment]
The user with this issue didn't reply when asked in the UM Extended issue.
I will close this issue
