### ISSUE TITLE
Member Directory Numerical sorting order incorrect

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1150]
**Expected behavior**

Only as "Default sort users" Numerical fields are sortable correct as ASC or DESC in the Members Directory.
When adding a Numerical field as "Choose field(s) to enable in sorting" will sorting be made as strings with 33 before 4 etc and without User option to select either ASC or DESC.

**Solution Code Snippet**

```
add_filter( 'um_member_directory_pre_display_sorting', 'um_member_directory_pre_display_sorting_numbers', 10, 2 );

function um_member_directory_pre_display_sorting_numbers( $sorting_options, $args ) {

    $number_sort = array();

    foreach ( $sorting_options as $option => $label ) {

        if ( UM()->fields()->get_field_type( $option ) == 'number' ) {

            unset( $sorting_options[$option] );
            $number_sort[$option . '_asc']  = $label . '<i class="um-faicon-sort-numeric-asc"></i>';
            $number_sort[$option . '_desc'] = $label . '<i class="um-faicon-sort-numeric-desc"></i>';
        }
    }

    $sorting_options = array_merge( $sorting_options, $number_sort );

    return $sorting_options;
}
```

**UM Support Forum Issue**

https://wordpress.org/support/topic/member-directory-page-custom-numerical-sorting-order/

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

The code snippet above makes the effect only for the displaying on the member directory, but doesn't for the query. 
I have checked the sorting options in the recently prepared for the release 2.6.0 version and it seems that all work fine. Number-type fields are sorted in numerical order as numbers, but not as a string.

And it works for both cases: wp_usermeta and wp_um_usermeta (custom UM metatable) tables using.

See code in the class-member-directory.php file:
https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-member-directory.php#L1297-L1314
https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-member-directory.php#L1386-L1420

Probably the customer from the wp.org topic hasn't upgraded the custom members.php file in the theme order and changes for the sorting fields are not applied on the frontend.

Let me know your results,
Best Regards!

**Comment by MissVeronica** [comment]
@nsinelnikov
As I remember my work to reproduce with current template file and finding a solution is this:

There are two different cases for the numbers at the Members Directory.
1.  This option is first in the MD user dropdown list. In Forms Builder it's marked as "Default sort users" and Numerical fields are sortable correct as ASC or DESC. 
2. When adding a numerical field as an additional sort field ie not first in MD sort list dropdown there is no option to select ASC or DESC and the sorting order from Query is changed to be character sorting. Forms Builder "Choose field(s) to enable in sorting" with extra entry of    `Meta key: `   `Label: ` on two lines without sorting order and no Remove link as other entries in this list. See the screenshot https://imgur.com/a/TrBdpt4

**Comment by nikitasinelnikov** [comment]
@MissVeronica 

And for the 2nd "Choose field(s) to enable in sorting" setting there is possible to select numeric fields registered as UM Form fields. https://www.screencast.com/t/icvFoZq8

The case ,when Meta key: and Label: are visible after "Other" option is selected, has been made for custom fields that aren't registered as UM Form field (e.g. ACF usermeta, etc.).

I can agree that there can be added these settings lines when  "Choose field(s) to enable in sorting" = "Other":
1. "Data type" (with these options https://www.screencast.com/t/VwbsxD8EAGr8)
2. "Order": ASC or DESC options

Let me know your thoughts,
Best Regards!

**Comment by MissVeronica** [comment]
@nsinelnikov

My filter code snippet is testing the field type for number and adds both ASC and DESC user selection for these fields.
You don't need to add anything to the Forms Builder if using my filter code snippet.
