### ISSUE TITLE
Member Directory block in Widgets doesn't display a preview of the list of users

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#1165]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
In WP-Admin > Appearance > Widgets, added UM Member Directory block doesn't display users list preview and error in console.
Also error in debug.log:

PHP Warning:  Attempt to read property "ID" on null in C:\OpenServer5.4\domains\wordpress\wp-content\plugins\ultimate-member\templates\members.php on line 214

**Screenshots**
https://www.screencast.com/t/lxJdfbiuplE

**Comment by nikitasinelnikov** [comment]
Fixed in 2.6.5
