### ISSUE TITLE
The UM account block on the another profile page

### ISSUE THREAD

**Issue by ashubawork** [ultimatemember/ultimatemember#1176]
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [ ] I can reproduce this bug consistently using the steps above.

**Describe the bug**
If the UM account block is placed on another profile page - it shows another account details.

**Comment by denisbaranov** [comment]
Similar error is reproduced for the Form - Default Profile block
