### ISSUE TITLE
get_current_url fails on local server which is dependent on a port

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#118]
I'm running a dev machine in docker and exposing port on localhost 8080.

A number of functions use `get_current_url`, which works fine in most cases, but in my case, it strips the `:8080` from the url in my dev environment, which then bricks the entire url.

Any chance you can switch this to `get_bloginfo('siteurl')` instead so that it preserves the port (when defined)?

**Comment by champsupertramp** [comment]
@dsifford hi, did you try enabling the `port forwarding option` ?

See Admin > UM > Settings > Advanced > Allow Port forwarding in URL

**Comment by dsifford** [comment]
@champsupertramp Interesting. Nope, haven't done that. 

Is this a new option? I don't recall ever setting it (or having to set it) in local environments in the past.

Closing for now. Will reopen this if that option doesn't work. Thanks.

**Comment by dsifford** [comment]
Having this same issue again suddenly. I've tried setting, unsetting, and resetting the port forwarding option you mentioned as well with no luck.

Only recent changes we've made is that we've moved to an nginx server from an apache server.

**Comment by mrbm** [comment]
Do you have fastcache set up in your ngnix host file?

**Comment by dsifford** [comment]
I sure do. Know issues with that?

**Comment by mrbm** [comment]
You might be caching a stored URL....so clear that cache.

https://www.jverdeyen.be/devops/nginx-clear-fastcgi-cache/

**Comment by dsifford** [comment]
Cleared the cache and tried again. Still no luck.

If it makes a difference, we're using an [EasyEngine](https://easyengine.io/) setup.

**Comment by mrbm** [comment]
Hmm I have no idea then...nginx is great but very tricky. Gotta be aware of every line and block. Not sure, sorry

**Comment by dsifford** [comment]
@mrbm If you're ever inclined to look into this, you can duplicate our build exactly using our [docker-compose](https://github.com/dsifford/wordpress/tree/nginx) orchestration.

**Comment by mrbm** [comment]
i wont be able to do that...got a few things cooking of my own!

**Comment by dsifford** [comment]
I hear ya there! No worries. Just tossing it out there in the event anybody feels like investigating 👍
