### ISSUE TITLE
um\core\mail->locate_template has a private accessor after the last update 

### ISSUE THREAD

**Issue by TheNthDev** [ultimatemember/ultimatemember#1196]
**Expected behavior**
mail->locate_template should have a public accessor. It has always been publicly accessible, but the last update accidentally changed this accessor to private. The PHPDoc even has @access public, so this is clearly unintended functionality. 

This change was not documented as a breaking change, and this has broken all external access to this method, which is causing WordPress errors for any sites that may be using this in functions.php or plugins with UltimateMember integrations. It is a simple one word change.

**Comment by MissVeronica** [comment]
UM Support Forum issue 

https://wordpress.org/support/topic/release-2-6-1-breaks-add_filter-um_email_notifications/

**Comment by TheNthDev** [comment]
What is the reason for why it was marked as private without any mention in the documentation of it being a breaking change or without updating the PHPDoc comment? Accessors were added to every method in that file, it seems more likely that it was a mistake.

**Comment by MissVeronica** [comment]
Changes made for all functions to be public except locate_template

https://github.com/ultimatemember/ultimatemember/commit/a460146958d320e710a1234ea8c5c31ea0c90b6c

**Comment by TheNthDev** [comment]
Yes, I saw that in the commit history. I am looking at all the evidence and assuming that the private accessor was a mistake and while explicitly adding the `public` accessor to every other method in that file, one accidentally got `private`. I am basing this on:

- The PHPDoc comment on line 116 still says `* @access public`

- The documentation for the release had no mention of this clearly breaking change

- There was already one hot-fix with respect to the emails
