### ISSUE TITLE
Permissions issue being thrown on additional user profile tabs in WP backend

### ISSUE THREAD

**Issue by baden03** [ultimatemember/ultimatemember#1223]
We have created various tabs for the user profiles in the WP backend that handle additional 'profile' pages such as:
`/wp-admin/users.php?page=private_address&user_id=123`
`/wp-admin/users.php?page=workplace&user_id=123`

1. If logged in as admin, all tabs of own profile and others can be updated.
2. if not admin and modifying own profile, all tabs can be updated.
3. if not admin and modifying another user with a role that allows editing, all tabs will update (save the changes)... but all tabs _except_ the core profile tab: `page=profile` will throw a 'Sorry, you are not allowed to access this page.' screen.
Note: after saving it is trying to redirect to the following:
`/wp-admin/admin.php?user_id=123&page=workplace`
rather than the correct:
`/wp-admin/users.php?page=workplace&user_id=123`

This happens regardless of WP role permissions, as we have attempted to grant all capabilities to the non-admin 'manager' role.
This happens regardless of UM role permissions, including can view and edit everyone.

It would seem that anything being saved on the user profile pages that do not originate from the page=profile is throwing the error, except this is not the case for admin or when a manager edits their own profile tabs.

We have tried to troubleshoot extensively the includes/core/class-user.php
but do not see where UM is filtering the redirect page after profile save.

Update:
Even the default user profile URL in the WP Dashboard is being modified when UM is activated.
w/o UM a user profile  url takes the format of:
`/wp-admin/users.php?user_id=123&page=profile`
w/ UM activated user profile links are formatted:
`/wp-admin/admin.php?user_id=123&page=profile`

Update 2:
The default user profile URL is only being modified for non-admin users:
admin viewing a user's profile with UM activated _and_ non-admins viewing their own profile:
`/wp-admin/users.php?user_id=123`
non-admin viewing another user's profile with UM activated:
`/wp-admin/admin.php?user_id=123`

This seems to be the root of the issue.

`Issue is located under includes/admin/core/class-admin-users.php` under the function:
`function map_caps_by_role( $allcaps, $cap, $args, $user )`
specifically:
```
elseif ( isset( $cap[0] ) && $cap[0] == 'list_users' ) {
	if ( isset( $args[0] ) && isset( $args[1] ) && ! user_can( $args[1], 'administrator' ) && $args[0] == 'list_users' ) {
		if ( ! um_user( 'can_view_all' ) ) {
			$allcaps[ $cap[0] ] = false;
		}
	}
}
```

if we have the ability to `list_users`
but we are not an administrator
but we can _not view all uesrs_ (true in this case as we don't want managers viewing admins
then... computer says no.

Would be nice to be able to at least override this default behavior with a filter.

Sorry, this thread is a bit convoluted stream-of-debugging. But in short. the issue is:
 if a non-admin has the ability to list_users and can view, edit and delete a user, even if they do not have 'can_view_all' we still want them to retain the ability to list_users.

**Comment by champsupertramp** [comment]
Hi @baden03 

have you tried detaching the UM function from the filter hook? I suggest that you add the detachment code only when saving your data:

```
remove_filter( 'user_has_cap', array( UM()->users(), 'map_caps_by_role' ), 10, 4 );
```

and then add it back right after the form has been saved with:

```
add_filter( 'user_has_cap', array( UM()->users(), 'map_caps_by_role' ), 10, 4 );
```

You can also try removing that function with above remove_filter and attach your own function with the modified version of: https://github.com/ultimatemember/ultimatemember/blob/master/includes/admin/core/class-admin-users.php#L92-L114

Kindest Regards,

**Comment by baden03** [comment]
Of course, that is the optimal solution. thank you. Sometimes you look at a thing so long you can't see the obvious things.

The solution I went with is as follows:
```
if( class_exists('UM')){
	remove_filter( 'user_has_cap', array( UM()->users(), 'map_caps_by_role' ), 10, 4 );
	add_filter( 'user_has_cap', array( $this, 'map_caps_by_role' ), 10, 4 );
}
```
This way we first check if the UM class exists before bothering with injecting our function overwrite.

Thank you. Thread resolved... with a bullet (bang! bang!)
