### ISSUE TITLE
Custom sorting fields of Member Directory shows meta_key as Label

### ISSUE THREAD

**Issue by mansurahamed** [ultimatemember/ultimatemember#1238]
**Expected behavior**
Custom sorting fields of member directory should show the Label as the Label

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [ x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
I add some (other) custom sorting fields in my user directory, and they are working fine, but the labels I add aren't showing, they named like the meta-keys.

**To Reproduce**
1. Go to any directory->Edit
2. Click on "Enable custom sorting" under sorting
3. Add an ( Other Custom field types) put the values.
4. See error in the member directory filter, metakey shows as filter title

**Expected behavior**
Label should show as Label not metakey

**Comment by champsupertramp** [comment]
confirmed fixed.
