### ISSUE TITLE
Bio description field update not solved in UM 2.6.8

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1245]
**Describe the bug**
Using a code snippet to add the meta_key `description` to the hook `um_whitelisted_meta_keys` will not solve the UM 2.6.7 bug in some cases.

See UM 2.6.8 code update: https://github.com/ultimatemember/ultimatemember/pull/1235/commits/12167f8612e439529f97f9c5e0b65a0e8321b79f

UM Support Forum issue: https://wordpress.org/support/topic/biography-not-saving-on-profile-update-v2-6-7/

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

Thanks for your investigations. For now, this issue looks strange, but I'll take a look.

**Comment by nikitasinelnikov** [comment]
It looks like that customer has some customizations (CSS, maybe PHP) which block the Ultimate Member native functionality. He get worked description field update only by the Profile form individual options,
