### ISSUE TITLE
Template differences

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1257]
**Is your feature request related to a problem? Please describe.**
The UM error text: 
"Your templates are out of date. Please visit [override templates status page](https://bisex.tranza.se/wp-admin/admin.php?page=um_options&tab=override_templates) and update templates."

**Describe the solution you'd like**
The possibility to see the differences between the customized template and the current UM template file like the GitHub source comparisons of current and last source files.

**Describe alternatives you've considered**
There are both apps available for download to your PC and online services available to make these comparisons.
Examples are WinMerge: https://winmerge.org/ and Diffchecker: https://www.diffchecker.com/

**UM Support Forum issues**
https://wordpress.org/support/topic/ultimate-member-plugin-erroe/
https://wordpress.org/support/topic/ultimate-member-template-outdated/

**Comment by nikitasinelnikov** [comment]
Hi @AngeliMae 

Please update our docs here:
https://docs.ultimatemember.com/article/1847-fixing-outdated-ultimate-member-templates

Section "How to update outdated templates". Please add the suggested solutions and link to them where customers can check the differences. See: Examples are WinMerge: https://winmerge.org/ and Diffchecker: https://www.diffchecker.com/
