### ISSUE TITLE
2.6.8 broke everything

### ISSUE THREAD

**Issue by MrEAlderson** [ultimatemember/ultimatemember#1258]
**Expected behavior**
There to be login / register / account / user or any form whatsoever

**Describe the bug**
Nobody is able to login, logout, register, manage their account or do anything ever since I updated to 2.6.8. I had to downgrade to 2.6.7 to make it work again. There were no warnings or errors, the forms literally only output blank.
![image](https://github.com/ultimatemember/ultimatemember/assets/8513034/159c72c3-20b7-467c-8d80-4b18c26ec3ee)

**To Reproduce**
1. Update to 2.6.8

**Expected behavior**
Forms to appear.
![image](https://github.com/ultimatemember/ultimatemember/assets/8513034/b0f878fb-6d09-479b-bed0-78d2f3b84551)
(2.6.7)

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [X] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [X] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [X] WooCommerce

**Comment by nikitasinelnikov** [comment]
Hi @MrEAlderson 

Could you try to add this line inside your functions.php file in theme/child-theme when 2.6.8 version is active

`add_filter( 'um_ultimatemember_shortcode_disable_singleton', '__return_true' );`

Please let me know how it works,
Best Regards!

**Comment by MrEAlderson** [comment]
Hello,

thank you for your quick response. This has actually fixed the login and register pages. However, the account page isn't affected and is still malfunctioning. I use the "[ultimatemember_account]" tag on that page

**Comment by nikitasinelnikov** [comment]
Hi @MrEAlderson 

Please check this PR with the recent hotfixes:
https://github.com/ultimatemember/ultimatemember/pull/1252

Let me know if that works,
Best Regards!
