### ISSUE TITLE
UM and Elementor page builder conflict in UM 2.6.8

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1259]
**Describe the bug**
UM Account page is reduced to a narrow column when the UM Account page is built with Elementor.
See this screenshot https://imgbb.com/1LCvCTZ

Deactivating Elementor will give the normal display of the UM Account page.

I have reproduced this issue at my test site too.

**UM Support Forum issues**
https://wordpress.org/support/topic/shortcode-ultimatemember_account/
https://wordpress.org/support/topic/shortcode-outdated-ultimatemember_account/

**Comment by nikitasinelnikov** [comment]
The fast solution for 2.6.8 is using this snippet inside the functions.php:

`add_filter( 'um_ultimatemember_shortcode_disable_singleton', '__return_true' );`

Will be default set to `true` since 2.6.9.

**Comment by MissVeronica** [comment]
The code snippet above will not make any changes to the narrow UM Account page.
I have made a trace of the `ultimatemember` function and it's never executed for the Account page but the Profile and Members Directory pages.

**Comment by MissVeronica** [comment]
Shortcode [ultimatemember_account] not rendering properly with Astra & Spectra
Screenshot: https://imgur.com/a/fcC6aMB#LSacjEf
https://wordpress.org/support/topic/shortcode-ultimatemember_account-not-rendering-properly/

**Comment by nikitasinelnikov** [comment]
There is a fix for account shortcode:
https://github.com/ultimatemember/ultimatemember/pull/1252/commits/bf2ddacb73db78a47f983cd5678d831b8976d871

**Comment by MissVeronica** [comment]
Solution here https://github.com/ultimatemember/ultimatemember/issues/1258
