### ISSUE TITLE
Upgrade Select2 to v4 and remove !important style rules

### ISSUE THREAD

**Issue by danieliser** [ultimatemember/ultimatemember#127]
This has become more and more of an issue as more plugins begin using Select2. Each using their own versions, no body updating regularly. It has become quite nightmarish for another plugin developer to deal with.

WP Core has already discussed including Select2 v4 into core and even contributed over the last year to get Select2 v4 ready with major enhancements to Accessibility and function, such as including AJAX methods without having to write custom ones like WC does.

The problem is you guys are still using an older version and because of your customizations it is not backward compatible with the latest versions.

Since WP Core will never include Select2 v3.5 due to lack of accessibility Ultimate Member should follow suit,  mainly due to the sheer number of your users it is nearly impossible to avoid issues and they will continue to pile up over the next year.

You can't blame every other plugin for wanting to use the better versions, and can't point your users to us each time they have a problem saying we need to fix it. (Not saying that is what is happening, but I can say not a single one of my users posted any issues on the Ultimate Member forums saying that UM broke Popup Makers admin, even though that is what was happening).

Lastly I can personally attest that you guys are using !important CSS overrides on select2 elements which breaks standard usage. IE the dropdowns should be absolutely positioned but get set to static because of these !important rules. Due to this rather than appearing correctly like a select box, the dropdown expands the metabox height, moves everything down and appears 20-30px below the select box. Maybe try more specificity rather than using !important.

Plus Accessibility rocks. Hear that at every WordCamp.

**Comment by danieliser** [comment]
Will add that I have been mentioning this issue to all plugins I find using it. I mentioned this same issue to WooCommerce and they have already committed to resolving it in the next major (2.7) update.

**Comment by champsupertramp** [comment]
Hi,
I updated the select2.js to version 4.0.2

Can you please try the pre-release version 1.3.53?
https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.53.7

Regards,

**Comment by danieliser** [comment]
@champsupertramp - Just got back from Prestige Conf and am catching up on support but will do.

**Comment by champsupertramp** [comment]
Hi,

We have released version 1.3.54 which has the updated select2.


Regards,
