### ISSUE TITLE
Too many Counting Users in the WP backend

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1271]
**Describe the bug**
At `WP Admin -> All Users` UM is counting all users two times in addition to WP counting the Users once.
Verified by the "Query Monitor" plugin: https://imgur.com/a/Ch9eqS3

There is an easy solution for this issue by replacing the SQL Query with the sum of current transient values for the User statuses proposed here https://github.com/ultimatemember/ultimatemember/issues/1080

**UM Support Forum Issue**
https://wordpress.org/support/topic/slow-query-in-admin-dashboard-after-update-to-2-6-7/

**Comment by MissVeronica** [comment]
New Support Forum issue about the UM bad performance in the WP backend

https://wordpress.org/support/topic/slow-count_users-query-on-all-admin-pages/

**Comment by MissVeronica** [comment]
A new code snippet fix for this issue with UM backend calls to count_users function for each WP Admin page.
The code snippet will break WP preparation for doing the slow Query if there is a previous call from UM and the UM account status  counts are added and returned to UM instead.

Install the code snippet into your active theme’s `functions.php` file
or use the “Code Snippets” plugin.

https://wordpress.org/plugins/code-snippets/

```
add_filter( 'pre_count_users', 'um_count_users_with_performance', 10, 3 );

function um_count_users_with_performance( $result, $strategy, $site_id ) {

    $e = new \Exception;
    if ( strpos( $e->getTraceAsString(), '/plugins/ultimate-member/' )) {
        $account_status = array( 'approved', 'rejected', 'awaiting_admin_review', 'awaiting_email_confirmation', 'inactive' );
        $result['total_users'] = 0;

        foreach( $account_status as $status ) {
            $count = UM()->query()->count_users_by_status( $status );
            $result['total_users'] = $result['total_users'] + $count;
        }
    }
    return $result;
}
```

**Comment by nikitasinelnikov** [comment]
@MissVeronica this future version doesn't have some redundant count_users queries:
https://github.com/ultimatemember/ultimatemember/pull/1521

So, the wp-admin > Users list table should perform better.
