### ISSUE TITLE
Registration attempt with a duplicate username 

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1273]
**Describe the bug**
UM is not verifying the `user_login/username` being unique before calling `wp_insert_user` in `um-actions-register.php:495`

WP issues a WP-error with code `existing_user_login` and message `Sorry, that username already exists!` in `wp_insert_user` in `user.php:2126`.

UM is not showing any UM error message and the Registration form is re-displayed again with fields retained.

**Comment by ashubawork** [comment]
Hello @MissVeronica 

I can't reproduce this issue. I see a "The username you entered is incorrect" error notice if I fill in a duplicate username.

Regards.

**Comment by MissVeronica** [comment]
I have made  tests with the "Twenty Twenty" Theme and these active plugins
```
--- WordPress Active Plugins ---
Really Simple SSL: 7.0.7
Smart Custom 404 error page [404page]: 11.4.3
Ultimate Member: 2.6.9
Ultimate Member - reCAPTCHA: 2.3.3
Ultimate Member - Terms & Conditions: 2.1.5
```
Additional testing:
Test with only  "Ultimate Member: 2.6.9" active same result: No error message
After a Reinstall WP 6.2.2: No error message
After a Reinstall "Ultimate Member: 2.6.9": No error message
Test with PHP 7.4.33 and PHP 8.2.8: No error message

Web server: LiteSpeed V8.1 Cloudlinux 1.3

**Comment by ashubawork** [comment]
Hello @MissVeronica 

Could you send me a screenshot of your form fields and form settings?

Regards.

**Comment by MissVeronica** [comment]
The Registration form I used first had 30 fields which I now have reduced to Username, email and password and still no error message for duplicate Username.

**Comment by MissVeronica** [comment]
Found the issue: 
Without `unique_username` being set there is no error message when WP triggers an error `existing_user_login` there is no error message from UM only a reload of the page.
