### ISSUE TITLE
Relabel Script & Style handles correctly without the um_ prefix.

### ISSUE THREAD

**Issue by danieliser** [ultimatemember/ultimatemember#128]
This definitely needs to be resolved.

Currently you load everything under that prefix. That is definitely leading to many issues.

WP obviously recommends using a standardized handle for everything to prevent these issues. Not sure why it was done this way up til now, but it should definitely be corrected.

Also if you are going to namespace the handles, you should also likely namespace the JS itself. For example you are loading Select2 v3.4 under the handle um_select, but you still load the jQuery plugin itself under .select2() meaning every other plugin using select2 will likely generate errors, or more precisely UM will generate errors in those plugins that are doing it correctly.

I read quite a few issues in your support forums that could be alleviated by fixing this issue.

Hope that helps.

**Comment by champsupertramp** [comment]
Hi,

Can you please try the pre-release version 1.3.53?

Regards,

**Comment by danieliser** [comment]
Will do.

**Comment by champsupertramp** [comment]
Hi,

We have released version 1.3.54 which has the updated select2.


Regards,
