### ISSUE TITLE
Conflicts with the "Restrict Content Pro" plugin's UM Integration in Account tab

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1288]
**Expected behavior**
In the UM Account Subsription tab I would expect the generation of the receipt or to be redirect on the subsription page, instead a red message “`An error has been encountered`” ( redirect URL: `/?err=account` ) appear on the same page (Membership account page). 
When I do a right click on the buttons and chose “`Open in a new tab`” it works. 
But I doubt my customer will do this tricks to get it works

**Describe the bug**
Restrict Content Pro description:
```
This is an issue on the UM end. UM does not recognize it. 
They capture every single click event in their pages and they don’t handle correctly shortcodes links 
With that, you may have to contact the UM plugin author to fix the issue with the click event 
and ask them to let the links inside the tabs to work properly. They have to do this in the JS code.
```
**UM Support Forum issues**
https://wordpress.org/support/topic/members-can-upgrade-or-renew/
https://wordpress.org/support/topic/issue-with-the-click-event/

**Comment by MissVeronica** [comment]
Conflict test.
Test with a basic code snippet with links in an Account tab works OK with the "Restrict Content Pro" plugin deactivated.
With "Restrict Content Pro" plugin activated the test code snippet links are failing as described.

Code snippet for conflict test

```
add_filter( 'um_account_page_default_tabs_hook', 'my_custom_tab_test_link', 100 );

function my_custom_tab_test_link( $tabs ) {

    $tabs[800]['test_link']['icon']         = 'um-faicon-external-link';
    $tabs[800]['test_link']['title']        = __( 'Test of Links', 'ultimate-member' );
    $tabs[800]['test_link']['custom']       = true;
    $tabs[800]['test_link']['show_button']  = true;
    $tabs[800]['test_link']['submit_title'] = 'UM Account Update';

    return $tabs;
}
```

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

I have contacted RCP Team support. Want to investigate this conflict on my side.

I'll be in touch.

**Comment by nikitasinelnikov** [comment]
The main reason that RCP uses <button> HTML tag inside the UM Account <form> and <button> automatically triggers form submission. 
https://imgur.com/cUqvESG

If they add to the <button type="button"> attribute it will work as expected. The customer will report RCP team about this issue. There isn't an issue on the Ultimate Member side.
