### ISSUE TITLE
Wrong fields in the login form displayed on the User page

### ISSUE THREAD

**Issue by yuriinalivaiko** [ultimatemember/ultimatemember#1292]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The plugin displays the profile form fields inside the login form displayed on the User page.

**To Reproduce**
1. Go to _wp-admin > Ultimate Member > Forms_ and copy the login form shortcode.
2. Go to _wp-admin > Pages > User_ and add the login form shortcode below the profile form shortcode.
3. Visit the site as a logged out user.
4. Go to someone's profile and look at the login form. This form displays wrong fields.

**Expected behavior**
The login form displayed on the User page should contain the login form fields such as "Username or E-mail" and "Password".

**Screenshots**
Image 1 - The login form shortcode below the profile form shortcode on the User page.
![image 1 - forms](https://github.com/ultimatemember/ultimatemember/assets/78854651/9b95a443-3dc6-45f2-88d6-0657a4362659)

Image 2 - The login form displayed on the User page.
![Image 2 - The login form displayed on the User page](https://github.com/ultimatemember/ultimatemember/assets/78854651/02b6683b-7d98-4c39-a1ed-48fb0e1a814c)

**Comment by nikitasinelnikov** [comment]
Fixed by https://github.com/ultimatemember/ultimatemember/pull/1282/commits/a2b52cdd0cec283bb0ddcb7627bcc9a63115c09e
