### ISSUE TITLE
Bug when entering the username or email incorrectly

### ISSUE THREAD

**Issue by hiepvq** [ultimatemember/ultimatemember#1296]
This is a bug:

I checked your code whenever i enter username or email incorrectly then it always showing the **Password is incorrect. Please try again.**

if you see in code it will go to lines code :  see "**go here 1**", "**go here 2**", "**go here 3**"

```
$user = get_user_by( 'login', $user_name );
	if ( $user && wp_check_password( $submitted_data['user_password'], $user->data->user_pass, $user->ID ) ) {
		UM()->login()->auth_id = username_exists( $user_name );
	} else {
		// var_dump('go here 1');
		UM()->form()->add_error( 'user_password', __( 'Password is incorrect. Please try again.', 'ultimate-member' ) );
	}
	
	// Integration with 3rd-party login handlers e.g. 3rd-party reCAPTCHA etc.
	$third_party_codes = apply_filters( 'um_custom_authenticate_error_codes', array() );

	// @since 4.18 replacement for 'wp_login_failed' action hook
	// see WP function wp_authenticate()
	$ignore_codes = array( 'empty_username', 'empty_password' );

	$user = apply_filters( 'authenticate', null, $authenticate, $submitted_data['user_password'] );
	if ( is_wp_error( $user ) && ! in_array( $user->get_error_code(), $ignore_codes ) ) {
		if ( ! empty( $third_party_codes ) && in_array( $user->get_error_code(), $third_party_codes ) ) {
			UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
		} else {
			// var_dump('go here 2');
			UM()->form()->add_error( 'user_password', __( 'Password is incorrect. Please try again.', 'ultimate-member' ) );
		}
	}

	$user = apply_filters( 'wp_authenticate_user', $user, $submitted_data['user_password'] );
	if ( is_wp_error( $user ) && ! in_array( $user->get_error_code(), $ignore_codes ) ) {
		if ( ! empty( $third_party_codes ) && in_array( $user->get_error_code(), $third_party_codes ) ) {
			UM()->form()->add_error( $user->get_error_code(), $user->get_error_message() );
		} else {
			//var_dump('go here 3');
			UM()->form()->add_error( 'user_password', __( 'Password is incorrect. Please try again.', 'ultimate-member' ) );
		}
	}
```

**My tips:** 

Please remove all codes above and replace with this code : 

```$user = apply_filters( 'authenticate', null, $authenticate, $submitted_data['user_password'] );```

It will be solved the problem when the user enter username or email incorrectly.

When you use this hook it will show the message errors of built on WP Core when the user enter input information incorrectly.

**Comment by nikitasinelnikov** [comment]
Hi @hiepvq 

I'll mark this Issue as a workaround because there were a lot of requests for security enhancements to lock detailed login errors which are provided by WordPress native 'authenticate'.

I know that the WordPress team ignored these security enhancement requests but we decided on the UM Login form to hide these errors for more security.

As an alternative for your case, I can suggest removing the UM native handler:
`remove_action( 'um_submit_form_errors_hook_login', 'um_submit_form_errors_hook_login' );`
And adding the custom handler:
```
function um_custom_submit_form_errors_hook_login( $submitted_data ) {
// your necessary content.
}
add_action( 'um_submit_form_errors_hook_login', 'um_custom_submit_form_errors_hook_login' );
```

These snippets can be placed to a child-theme.
Best Regards!
