### ISSUE TITLE
Conflict with the Bookly plugin

### ISSUE THREAD

**Issue by yuriinalivaiko** [ultimatemember/ultimatemember#1305]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
Fields in the Form Builder can not be edited if the [Bookly](https://wordpress.org/plugins/bookly-responsive-appointment-booking-tool/) plugin is installed. 

**To Reproduce**
1. Install the [Bookly](https://wordpress.org/plugins/bookly-responsive-appointment-booking-tool/) plugin.
2. Go to _wp-admin > Ultimate Member > Forms > Edit Form_.
3. Try to edit any field - click the pencil icon.
4. See error in console.

**Expected behavior**
The Edit Field modal should be shown. No JavaScript error.

**Screenshots**
Image - An error in console.
![Image - An error in console](https://github.com/ultimatemember/ultimatemember/assets/78854651/dd05b547-fa98-44b6-a5db-3b982a6fe99d)

Image - Expected behavior.
![Image - Expected behavior](https://github.com/ultimatemember/ultimatemember/assets/78854651/670a5988-65c7-49f7-8fd4-27812c921d06)

**Comment by nikitasinelnikov** [comment]
Related to Bookly plugin:
https://wordpress.org/support/topic/conflict-with-ultimate-member-plugin-5/

**Comment by MissVeronica** [comment]
UM Support Forum issue
https://wordpress.org/support/topic/bookly-plugin-conflict/
