### ISSUE TITLE
Notification options not in Profile/Account menu

### ISSUE THREAD

**Issue by TonyGravagno** [ultimatemember/ultimatemember#1318]
Set Notifications to appear in Profile. Go to Member Profile. Click Gear icon to see Edit Profile, My Account, and ... no Notifications.

UM 2.3.3
ReCaptcha extension
WordPress 6.3.1
PHP 8.2
Theme : TwentyTwenty Three (vanilla w/Gutenberg)

**Comment by nikitasinelnikov** [comment]
Hi @TonyGravagno 

The notifications tab setting is required here for use inside the extensions where is possible to disable email notifications.
Default Ultimate Member core notifications cannot be disabled on the user's side so the notifications tab is hidden.

We have added the condition to hide the setting when there aren't active extensions that provide the users notifications.

Best Regards!
