### ISSUE TITLE
Add fields not predefined in the account page

### ISSUE THREAD

**Issue by MisTerM7** [ultimatemember/ultimatemember#1323]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.ultimatemember.com

If you have a problem, you may want to start with the self help guide here: https://docs.ultimatemember.com/article/1507-ultimate-member-self-service-guide/

**Technical support for premium extensions or if you're a UltimateMember.com customer**
Please submit a ticket via the support page
https://ultimatemember.com/support/ticket/

**General questions**
- WordPress.org Forums: https://wordpress.org/support/plugin/ultimate-member/

The tutorial link for this video no longer exists, which is a shame.
https://www.youtube.com/watch?v=Uv3JwAi50iM

As my subject title indicates, I'm trying to display the fields that I've added to my account registration page. I'm looking for the tutorial but I can't find it.

Mz

**Comment by yuriinalivaiko** [comment]
Hello @MisTerM7 

There are articles in the Ultimate Member documentation that describes how to extend the Account with additional fields and/or tabs:

- [How to display custom fields in Account](https://docs.ultimatemember.com/article/1504-how-to-display-custom-fields-in-account)
- [Extend Ultimate Member Account page with custom tabs/content](https://docs.ultimatemember.com/article/65-extend-ultimate-member-account-page-with-custom-tabs-content)

As mentioned in the article you may use a free extension [Ultimate Member - Account tabs](https://github.com/umdevelopera/um-account-tabs) to add your custom tab to the Account page. This extension can embed a profile form into the custom account tab. I think this is the simplest way to display your custom fields in Account. Just create the additional profile form, add fields you need to this form then embed this form to Account.

Usually you don't need to display custom fields in Account. It's better to display custom fields in Profile. It's easy to do. Just read the article [Adding existing fields from Register form to Profile form](https://docs.ultimatemember.com/article/1719-adding-existing-fields-from-register-form-to-profile-form) and follow instructions.

Regards

**Comment by MisTerM7** [comment]
Hello yuriinalivaiko

I've found the right vision, but I can't display the email address using this snippes code.

`/* Add fields to account page */
add_action('um_after_account_general', 'showExtraFields', 100);
function showExtraFields()
{
	$custom_fields = [
		"birth_date" => "Email adress",
	];

	foreach ($custom_fields as $key => $value) {

		$fields[ $key ] = array(
				'title' => $value,
				'metakey' => $key,
				'type' => 'select',
				'label' => $value,
		);

		apply_filters('um_account_secure_fields', $fields, 'general' );

		$field_value = get_user_meta(um_user('ID'), $key, true) ? : '';

		$html = '<div class="um-field um-field-'.$key.'" data-key="'.$key.'">
		<div class="um-field-label">
		<label for="'.$key.'">'.$value.'</label>
		<div class="um-clear"></div>
		</div>
		<div class="um-field-area">
		<input class="um-form-field valid "
		type="text" name="'.$key.'"
		id="'.$key.'" value="'.$field_value.'"
		placeholder=""
		data-validate="" data-key="'.$key.'">
		</div>
		</div>';

		echo $html;

	}
}`

How can I display it, because I can't.

Mz
