### ISSUE TITLE
Bug Don’t show icons in /login/ form

### ISSUE THREAD

**Issue by BlackStar1991** [ultimatemember/ultimatemember#1324]
Hi, I set icons for files into /login/ form
https://monosnap.com/file/fjst54apQzzsVOl4odEUmXJw09wrJ6
But I don’t see them into this form. Can you fix it ?
https://monosnap.com/file/Po0eciO3pWig2czpunjXOgeoiD84cj

I don't see like these near inputs on a /login/ form
<div class="um-field-icon"><i class="um-faicon-user"></i></div>

**Comment by MissVeronica** [comment]
Solved and can be closed.
https://wordpress.org/support/topic/bug-dont-show-icons-in-account-form/
