### ISSUE TITLE
Problem of login log & Chinese 

### ISSUE THREAD

**Issue by echexnation** [ultimatemember/ultimatemember#133]
There are two questions i wanted to ask.

Q1:How can the accounts create the login record or log when using the Ultimate Member to login?

*I try to search some reference. Then i found the Ultimate Member doesn't contain any login log at the backend.

https://wordpress.org/support/topic/question-about-last-login-and-joined-date?replies=9

https://ultimatemember.com/forums/topic/last-login-of-users

*And i found a hook that seems to be solve this problem. However, i have no idea where to put the code in.

https://ultimatemember.com/forums/topic/login-log-activity/

*So i want to update that if the login log function has been added to the newest version and where do i put the code if the hooks can work.

Q2:What can i do to show back the chinese character after update the plugin?

*I keep stop update and just using the 1.3.39 version. It is beacuse that version is the newest one to support showing chinese character. After that all of the new version plugin just turn the chinese character to symbols.

**Comment by champsupertramp** [comment]
#1 - We are still working on this feature. This is on normal priority and we'll let you know if this has been added into the master repository.

#2 - There's a new option to fix this issue. Go to `Admin > Ultimate Member > Settings > Advanced > Turn on 'Force Strings to UTF-8 Encoding`.

Regards,

**Comment by echexnation** [comment]
<img width="556" alt="chinese_field" src="https://cloud.githubusercontent.com/assets/19393338/15450001/51322fca-1fc1-11e6-89c4-c35d14515f88.png">
I type in chinese character choices into a dropdown list. When I am trying to turn on the Force Strings to UTF-8 Encoding, the chinese characters in the choices become a question marks.
<img width="353" alt="force_utf8" src="https://cloud.githubusercontent.com/assets/19393338/15450002/513505ec-1fc1-11e6-9eed-b4618beabbf2.png">
However, the following picture is the right view that I expected to see.It appears when I turn off the Force Strings to UTF-8 Encoding. 
<img width="361" alt="expected_output" src="https://cloud.githubusercontent.com/assets/19393338/15450003/5135dc10-1fc1-11e6-9a44-6d2a681e7d09.png">
Yes.I can show up the characters. In fact, when I setup a field that related with that field I fail to run the rules.
<img width="555" alt="setting_rule" src="https://cloud.githubusercontent.com/assets/19393338/15450046/b736845a-1fc2-11e6-919f-5b1b11fc435a.png">
It's mean that when I choosed "狩神傳", the field that contains the rule doesn't show up. 

So...How do I show up the chinese characters and it can be a value the active the rules at the same time?

**Comment by champsupertramp** [comment]
Hi @echexnation, Sorry for the delay. We've been busy with testing all extensions and fixing bugs in the core.

Can you please provide screenshot of the html elements of the form? Which has the `data-key` attribute ?

Regards,

**Comment by champsupertramp** [comment]
Hi @echexnation 

>>> Q1:How can the accounts create the login record or log when using the Ultimate Member to login?

Did you try adding the code in your theme's functions.php ?

Regards,

**Comment by echexnation** [comment]
> Hi @echexnation, Sorry for the delay. We've been busy with testing all extensions and fixing bugs in the core.
Can you please provide screenshot of the html elements of the form? Which has the data-key attribute ?

![chi002](https://cloud.githubusercontent.com/assets/19393338/15806800/6dd6a91c-2b7e-11e6-8bcd-3951a67a15c3.png)
![chi007](https://cloud.githubusercontent.com/assets/19393338/15806789/465403c6-2b7e-11e6-864f-a5484a82498e.png)
![chi008](https://cloud.githubusercontent.com/assets/19393338/15806790/465b0edc-2b7e-11e6-9a9d-8eafe578c43e.png)

> Did you try adding the code in your theme's functions.php ?

Yes. I did. But still got the information of logout only.
![act001](https://cloud.githubusercontent.com/assets/19393338/15806814/c6496f76-2b7e-11e6-8323-95e2641d1d14.png)

**Comment by champsupertramp** [comment]
Hi @echexnation,

Can you please try the pre-released version in the link?
https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.65.5

Let us know if you're still encountering issues.

Regards,
