### ISSUE TITLE
Sync user roles reloads to blank page

### ISSUE THREAD

**Issue by JWLKR** [ultimatemember/ultimatemember#134]
If I choose a role to from "Sync with wordpress role" on the user roles page, I am reloaded to a blank screen and the role is not updated or synced. I looked in the PHP file for sync and it looks fine, everything else seems to work as well.

This is the slug I get returned:
`wp-admin/post.php?post=182250&action=edit&um_adm_action=mass_role_sync&um_role=employer&wp_role`

Any thoughts? I need to sync these users up for the testing phase of our project.

Any help would be appreciated.

**Comment by champsupertramp** [comment]
Hi @JWLKR ,

How many users did you try to sync?

**Comment by JWLKR** [comment]
@champsupertramp 
I only have one user registered as an "employer" to test.

**Comment by JWLKR** [comment]
@champsupertramp I have resolved the issue. It was my bad on the Community Member setting. Thanks
