### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1341]
Add the requirement of whitelisting meta keys in order to use the code snippet at
https://docs.ultimatemember.com/article/128-add-a-hidden-field-to-your-register-form

Support Forum issue
https://wordpress.org/support/topic/ultimate-member-hidden-custom-field-values-not-getting-updated-in-acf/

**Comment by yuriinalivaiko** [comment]
The article [Add a hidden field to your register form](https://docs.ultimatemember.com/article/128-add-a-hidden-field-to-your-register-form) has been updated.

Fields added to the form manually (bypassing the Form Builder) must not be processed via the form handler. Adding these fields to the whitelisted usermeta keys list is a security vulnerability. Input data requires validation and sanitization. It's better to add a custom function to sanitize and save manually added fields.
