### ISSUE TITLE
YouTube Video field does not support all YouTube links

### ISSUE THREAD

**Issue by yuriinalivaiko** [ultimatemember/ultimatemember#1345]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The "YouTube Video" field works wrong if the YouTube link has additional parameters, for example the `list` parameter.

**To Reproduce**
1. Go to _wp-admin > Ultimate Member > Forms > Default Profile_
2. Add the "YouTube Video" field to the profile form and update the form.
3. Go to the profile "edit" mode.
4. Enter a link with additional parameters (a link https://www.youtube.com/watch?v=eVTXPUF4Oz4&list=WL&index=28&pp=gAQBiAQB8AUB for example) and click the "Update Profile" button to save changes.
5. Look at the "YouTube Video" field. It does not work.

**Expected behavior**
The "YouTube Video" field should work correctly if there are additional parameters in the link.

**Screenshots**

Image - The "YouTube Video" field settings.
![UM Forms, Edit Form, Edit Field - YouTube Video](https://github.com/ultimatemember/ultimatemember/assets/78854651/dbfcfef3-c281-4e7b-aef6-670ba9c33416)

Image - The profile "edit" mode.
![im1](https://github.com/ultimatemember/ultimatemember/assets/78854651/29d2dbda-1ad0-41b1-bf36-28e7387e953f)

Image - The profile "view" mode.
![im2](https://github.com/ultimatemember/ultimatemember/assets/78854651/cb4ceca6-c40b-40c3-a1d5-1c44ac6faf2b)

**Comment by champsupertramp** [comment]
Hi @yuriinalivaiko - The provider's discoverability has been discussed before. Please check the existing WP's oEmbed class to discover providers and validate them:
https://developer.wordpress.org/reference/classes/wp_oembed/get_provider/

https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-includes/class-wp-oembed.php#L54-L58

**Comment by champsupertramp** [comment]
Please also see: https://github.com/ultimatemember/ultimatemember/issues/1331
