### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1348]
**Is your feature request related to a problem? Please describe.**
Error message which don't advice admins the solution in UM Forms Builder modal.

**Describe the solution you'd like**
Change `Your meta key already exists in your fields list`
to `Your meta key already exists make your selection from the modal Custom Fields list`

**Describe alternatives you've considered**
Update UM Documentation
https://docs.ultimatemember.com/article/188-how-to-add-fields-to-a-form
https://docs.ultimatemember.com/article/1719-adding-existing-fields-from-register-form-to-profile-form

**UM Support Forum issue**
https://wordpress.org/support/topic/adding-existing-fields-from-register-form-to-profile-form/

**Comment by nikitasinelnikov** [comment]
@AngeliMae could you verify that this issue was fixed?

**Comment by AngeliMae** [comment]
> @AngeliMae could you verify that this issue was fixed?

Hi @nikitasinelnikov The issue has been fixed and the documentation has been updated. I apologize for the delay in addressing this. Thank you for your understanding!

https://docs.ultimatemember.com/article/1719-adding-existing-fields-from-register-form-to-profile-form
https://docs.ultimatemember.com/article/188-how-to-add-fields-to-a-form
