### ISSUE TITLE
Profile um-faicon-cog z-order issue

### ISSUE THREAD

**Issue by TonyGravagno** [ultimatemember/ultimatemember#1352]
Open the profile page in responsive mode for a view width that causes a navigation menu to go into minimized icon mode. Click on the hamburger menu.

- The Cog/Gear icon/link is visible in the div with class="wp-block-navigation__responsive-container is-menu-open has-modal-open". The z-index of that dialog is "100000"! It should be floating above **everything** else.
- The z-index of the div with class="um-profile-edit um-profile-headericon um-trigger-menu-on-click" is 66, and not tagged as "!important". So I'm not understanding yet why that icon is visible.

This might be browser-specific or due to some upper limit on z-index where it's ignored beyond a specific value.
I'm reporting this for the latest Firefox over Windows. This might not be seen in other browsers.

![image](https://github.com/ultimatemember/ultimatemember/assets/499473/5f7be596-c2e6-412f-ac75-053c125af0e6)

**Comment by ashubawork** [comment]
Hello @TonyGravagno 

What theme are you using?

Regards.

**Comment by nikitasinelnikov** [comment]
This issue has been inactive for a while so we’re going to go ahead and mark it Closed.
Please feel free to re-open this thread if any other questions come up and we’d be happy to help. 🙂
Regards

**Comment by TonyGravagno** [comment]
Missed the last follow-up: This was seen in the default 'twenty-twentythree'.
