### ISSUE TITLE
Please, please remove !important rule from your stylesheets

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#136]
Hello,

Please consider removing all cases of `!important` from your stylesheets as it is extremely [bad practice](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity), breaks the cascade, and prevents the styles from being adjusted (without also using `!important`).

Thanks for considering.

**Comment by freelancesam** [comment]
Please sort this!

**Comment by jameshahn2** [comment]
This is STILL a problem!! Please address!!
