### ISSUE TITLE
UM login by "user_email" field and PHP null error in WP

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1360]
**Describe the bug**
`Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in .../wp-includes/class-wp-user.php on line 211`

when `get_user_by('email', $submitted_data['.......'] )` is not found
and `$user_name` is set to `null` before `$user = get_user_by( 'login', $user_name );`
in function `um_submit_form_errors_hook_login`

```
		if ( is_email( $submitted_data['username'] ) ) {
			$data = get_user_by('email', $submitted_data['username'] );
			$user_name = isset( $data->user_login ) ? $data->user_login : null;
		} else {
			$user_name  = $submitted_data['username'];
		}
	} elseif ( isset( $submitted_data['user_email'] ) ) {
		$authenticate = $submitted_data['user_email'];
		$field = 'user_email';
		$data = get_user_by('email', $submitted_data['user_email'] );
		$user_name = isset( $data->user_login ) ? $data->user_login : null;
	} else {
		$field = 'user_login';
		$user_name = $submitted_data['user_login'];
		$authenticate = $submitted_data['user_login'];
	}

	if ( $submitted_data['user_password'] == '' ) {
		UM()->form()->add_error( 'user_password', __( 'Please enter your passwordx', 'ultimate-member' ) );
	}

	$user = get_user_by( 'login', $user_name );
```

**Comment by ashubawork** [comment]
Hello @MissVeronica 

I can't reproduce this issue. Could you describe it in more detail?

Regards.

**Comment by MissVeronica** [comment]
I'm using PHP 8.2.11 for these tests and WP is failing on a `trim( null );`

In the UM Login Form use the `user_email` field for user identification and not `username` or `user_login` fields.
Enter a not registered email address or some random characters and a random password for a login test.
Click Login button.

Looking at the UM code the WP function `get_user_by` can be called with 2nd parameter equal to `null` from the `isset` tests at lines 31 and 39.

Solution should be to do a test like this:

```
$user = false;
if ( ! empty(  $user_name )) {
   $user = get_user_by( 'login', $user_name );
}
```
