### ISSUE TITLE
Aws Lightsail template overwrites issue

### ISSUE THREAD

**Issue by code2prog** [ultimatemember/ultimatemember#1376]
Do you know why on AWS Lightsail and the Bitnami WordPress image, the custom login.php is not loading? It works locally and also on WP Engine, but not on AWS Lightsail. 
Any php errors, warnings. Same php version (8.2). Only an empty space appears where the form should be.  It's the same even if I take the login.php file unchanged from the Ultimate Member plugin and place it in the theme.

**Comment by nikitasinelnikov** [comment]
Hi @code2prog 

Sorry for the delay, we had a lot of stuff related to the release. And thanks for the details.
Could you clarify some info? Is this issue related only to the login page and its template or do you have the same one with the member directory or other Ultimate Member predefined pages?

**Comment by code2prog** [comment]
Hi @nikitasinelnikov 
Sooo...It seems that the problem only occurs on the login and registration page for non-logged-in users. We have some custom templates but when i try diagnose issue and i copy original templates from plugin directory the effect was the same.
I think the problem is not related to custom templates

**Comment by nikitasinelnikov** [comment]
Hi @code2prog 

1. You can be sure that there aren't any 3rd-party issues after making the conflict test.
Ref. https://docs.ultimatemember.com/article/96-how-to-do-a-plugin-theme-conflict-test

2. What is the structure of templates do you have? Ultimate Member uses these rules for templates overriding
https://docs.ultimatemember.com/article/1516-templates-map

Maybe the reason for the issue is related to the specific paths to the templates directory on AWS Lightsail and the Bitnami WordPress image. May you share the path where your custom templates are stored?

**Comment by code2prog** [comment]
@nikitasinelnikov paths:
Core path - wp-content/plugins/ultimate-member/templates/login.php
Theme path - wp-content/themes/tastybrands/ultimate-member/templates/login.php

**Comment by nikitasinelnikov** [comment]
@code2prog 
I meant that Amazon Lightsail can have a different structure of WordPress folders inside the Bitnami WordPress image. Sometimes the WordPress images have a different structure from the original WordPress.

But let's deep inside the code and find the place where the custom templates in the theme folder break the loading. It's great that original files from the plugin are loaded properly. Probably you can place some `var_dump()` here https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-shortcodes.php#L325-L332

And let me know if the condition has been passed and what variable values you have for `$file`, `$theme_file`, `$real_file`
Thanks!

**Comment by code2prog** [comment]
$file: `/opt/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/login.php`
$theme_file: `/opt/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/login.php`
$real_file: `/opt/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/login.php`

**Comment by nikitasinelnikov** [comment]
@code2prog 
Thanks, I guess this line should include the necessary file because the condition has to be passed with shared values https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-shortcodes.php#L330

Can you see these HTML lines instead of a shortcode for the login form?

`<div class="um-form">
		<form method="post" action="" autocomplete="off">`

**Comment by code2prog** [comment]
@nikitasinelnikov only this 
https://share.cleanshot.com/1tq4zBHNGhjK3PLxqsVn

Injected some css and empty paragraph

**Comment by nikitasinelnikov** [comment]
@code2prog 
Please paste after this line https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-shortcodes.php#L325
this code:
`var_dump( 0 === strpos( $real_file, wp_normalize_path( get_stylesheet_directory() . DIRECTORY_SEPARATOR . 'ultimate-member' . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR ) ) );`

And replace https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-shortcodes.php#L330
to
`var_dump('test line that we include');
include $file;`

Let me know what you see,
Best Regards!

**Comment by code2prog** [comment]
@nikitasinelnikov 
bool(false)
Second var_dump not executed

**Comment by nikitasinelnikov** [comment]
Thanks @code2prog . Then the reason is a failed condition. Ok, and what about this code result:

`var_dump( wp_normalize_path( get_stylesheet_directory() . DIRECTORY_SEPARATOR . 'ultimate-member' . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR ) );`

You can paste it after the first var_dump from previous message.

**Comment by code2prog** [comment]
@nikitasinelnikov 
string(79) "/opt/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/"

**Comment by code2prog** [comment]
@nikitasinelnikov 
`string(79) "/opt/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/"`

**Comment by nikitasinelnikov** [comment]
It looks the same...strange.
If you have PHP version >= 8.0
Please try this function instead:

`str_starts_with( $real_file, wp_normalize_path(...`

It should return true...I hope

Thanks!

**Comment by code2prog** [comment]
@nikitasinelnikov Are you thinking of replacing strpos with str_starts_with? If so it still doesn't work

**Comment by nikitasinelnikov** [comment]
And without 0 ===

Please dump these lines;

`var_dump( str_starts_with( $real_file, wp_normalize_path( get_stylesheet_directory() . DIRECTORY_SEPARATOR . 'ultimate-member' . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR ) ) );`

And separately:
`var_dump( $real_file );`
`var_dump( wp_normalize_path( get_stylesheet_directory() . DIRECTORY_SEPARATOR . 'ultimate-member' . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR ) );`

And share the result.
Thanks!

**Comment by code2prog** [comment]
@nikitasinelnikov 
bool(false) 
string(84) "/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/login.php" 
string(79) "/opt/bitnami/wordpress/wp-content/themes/themename/ultimate-member/templates/"


mhhhh.... `/bitnami/wordpress/wp-content/` and `/opt/bitnami/wordpress/wp-content/`

Bitnami image has wp-content folder linked using symbolic link

I think we are close to finding the cause of the problem

**Comment by nikitasinelnikov** [comment]
Hi @code2prog 

Thanks for the detalis! Could you contact AWS Lightsail support?
Strangely, the theme root or WP_CONTENT_DIR constant has a path without directory level `/opt/` returned by PHP native `realpath` function. Maybe they have some customizations for `get_stylesheet_directory()` function via mu-plugins or something else.

Best Regards!

**Comment by code2prog** [comment]
@nikitasinelnikov Amazon AWS has nothing to do with it. The image is provided by Bitnami. I will try to contact them

**Comment by code2prog** [comment]
@nikitasinelnikov 
soooo... for now i add this code in functions.php in theme directory a all start working 
```php
if (!function_exists('custom_stylesheet_directory')) {
    function custom_stylesheet_directory() {
        return '/bitnami/wordpress/wp-content/themes/themename/';
    }

    // Override the original function
    remove_filter('stylesheet_directory', 'get_stylesheet_directory');
    add_filter('stylesheet_directory', 'custom_stylesheet_directory');
}
```

**Comment by nikitasinelnikov** [comment]
Hi @code2prog 

Thanks for letting me know. I hope Bitnami will fix the issue with 'stylesheet_directory' soon.
Appreciate your help in debugging on your side.

I'll mark this issue as closed
Best Regards!
