### ISSUE TITLE
Not possible to change password in account without first/last name

### ISSUE THREAD

**Issue by MartNytrm** [ultimatemember/ultimatemember#138]
Hi there, 

Thanks for fixing the password changing bug today! But in my opinion it is not completely gone:
If a user does not have a first and a last name in his/her account, which is not mandatory on our site, and wants to change his/her password and presses the "Update Password" button, the user is switched from the "Change Password" tab to the "Account" tab and is encouraged with red hints to enter first and last name. **So the user can't change password without first and last name.** 

Can you reproduce this behavior? Is this on purpose?

I'm using:
Wordpress 4.5.2–de_DE
with plugins:
- All In One WP Security	4.1.0	https://www.tipsandtricks-hq.com/wordpress-security-and-firewall-plugin
- Contact Form 7	4.4.2	http://contactform7.com/jonradio 
- Multiple Themes	7.1	http://zatzlabs.com/plugins/
- Newsletter	4.2.2	http://www.thenewsletterplugin.com/plugins/newsletter
- Ultimate Member	1.3.58	http://ultimatemember.com/
- Ultimate Member - Google reCAPTCHA	1.0.2	http://ultimatemember.com/
- Yoast SEO	3.2.5	https://yoast.com/wordpress/plugins/seo/#utm_source=wpadmin&utm_medium=plugin&utm_campaign=wpseoplugin
- WP-Mail-SMTP	0.9.5	http://www.callum-macdonald.com/code/wp-mail-smtp/

Thanks!

Greets

**Comment by MartNytrm** [comment]
Additional test for this behavior:
Tested it with fresh database, fresh wordpress installation and with only Ultimate Member installed as plugin.
It stays the same: you can not change you password in Ultimate Member without having first and last name.

**Comment by champsupertramp** [comment]
Hi @MartNytrm, please check the latest version 1.3.60. 

Regards,

**Comment by MartNytrm** [comment]
Confirmation: fixed in version 1.3.60 (June 22, 2016)!

But: Please look at this similar/related issue: https://wordpress.org/support/topic/no-email-change-without-first-and-last-name-in-account
