### ISSUE TITLE
Cropper JS error

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1385]
**Describe the bug**
```
jquery-migrate.min.js?ver=3.4.1:2 JQMIGRATE: Migrate is installed, version 3.4.1
cropper.min.js?ver=1.6.1:10 Uncaught TypeError: Cannot read properties of undefined (reading 'scaleX')
at n.getData (cropper.min.js?ver=1.6.1:10:25897)
at HTMLAnchorElement. (um-modal.min.js?ver=2.8.0:1:1641)
at HTMLDocument.dispatch (jquery.min.js?ver=3.7.1:2:40035)
at v.handle (jquery.min.js?ver=3.7.1:2:38006)
```

**To Reproduce**
click on “apply” to save new profile image.

**Support forum issue**
https://wordpress.org/support/topic/js-error-after-update-to-2-8-0/

**Comment by nikitasinelnikov** [comment]
I cannot replicate this bug on my end
https://jam.dev/c/0f7a73ff-d16f-4650-ae8c-5b5f26704f1e

I'll wait until the customer response.

**Comment by nikitasinelnikov** [comment]
The PR above will fix the JS error, but cannot fix the reason (no initiated cropper for UM objects as well)
