### ISSUE TITLE
Need to report some potential issues

### ISSUE THREAD

**Issue by andreasnrb** [ultimatemember/ultimatemember#139]
Tried to reach out via twitter but to no avail. How should I report some potential issues?

**Comment by champsupertramp** [comment]
Hi @andreasnrb, Is it a security issue?

**Comment by andreasnrb** [comment]
Yepp.

2016-06-12 0:38 GMT+02:00 Champ Camba <notifications@github.com>:

**Comment by andreasnrb** [comment]
So where can I send info?

2016-06-12 10:43 GMT+02:00 Andreas Nurbo <andreas.nurbo@gmail.com>:

**Comment by champsupertramp** [comment]
Hi @andreasnrb , can you please outline which part of the plugin has potential issues without specifying the steps ?

**Comment by andreasnrb** [comment]
File uploading functionality.

2016-06-14 12:02 GMT+02:00 Champ Camba <notifications@github.com>:

**Comment by champsupertramp** [comment]
Hi @andreasnrb, thanks for letting us know. We've created a fix for this issue. Please see: https://github.com/ultimatemember/ultimatemember/commit/07b3e71528ff908a2ff422445360194e7bec45ab
