### ISSUE TITLE
Fails to upgrade from 2.6 Database  when trying to run upgrade script for 2.8

### ISSUE THREAD

**Issue by madmacks59** [ultimatemember/ultimatemember#1391]
when trying to upgrade from database 2.6 to 2.8 all I get is "Upgrade Process Started...
Get Upgrades Packages..." and then nothing. I've only got a few dozen users so this isn't a "just wait longer" issue. Is there some know issue this the upgrade?

**Comment by nikitasinelnikov** [comment]
Hi @madmacks59 

Sorry for the delay, could you check the debug.log file?
Ref: https://wordpress.org/documentation/article/debugging-in-wordpress/

Please let me know if you can see the errors inside this file after starting the upgrade process.
Best Regards!

**Comment by rodolfocerezo** [comment]
I'm getting the same error. After enabling the log, I get this message:

```
[20-Dec-2023 01:36:25 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function set_time_limit() in htdocs/wp-content/plugins/ultimate-member/includes/um-short-functions.php:2805
Stack trace:
#0 htdocs/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.8.0/functions.php(9): um_maybe_unset_time_limit()
#1 htdocs/wp-includes/class-wp-hook.php(324): um_upgrade_usermeta_count280()
#2 htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 htdocs/wp-admin/admin-ajax.php(188): do_action()
#5 {main}
  thrown in htdocs/wp-content/plugins/ultimate-member/includes/um-short-functions.php on line 2805
```

PHP: 8.0.30
WordPress: 6.4.2

**Comment by rodolfocerezo** [comment]
After doing some research I found out that the function set_time_out was disabled in php.ini due to security reasons. I removed the function from disable_functions directive, restarted php service and updated successfully.

**Comment by nikitasinelnikov** [comment]
Thanks for letting me know, I'll mark this issue as closed.
Best Regards!
