### ISSUE TITLE
intercepting AJAX calls and adding "um_current_locale

### ISSUE THREAD

**Issue by ashubawork** [ultimatemember/ultimatemember#1399]
The problem was indeed caused by Ultimate Member, they're intercepting AJAX calls and adding "um_current_locale" parameter without even considering the request format. I've applied a patch to the file responsible for this issue "common.min.js", but it will reverted as soon as the plugin is updated the next time. This should be fixed by the plugin developers. If you have an account with them, please send them an email to report the issue, the attached screenshot and this message should give them enough context.

Issue from the helpscout - https://secure.helpscout.net/conversation/2458916486/76899?folderId=2369200

Need investigation

![Screenshot2023-12-19232836](https://github.com/ultimatemember/ultimatemember/assets/43743394/51d8a159-6e71-42cc-bf6b-e78252eb80dd)

**Comment by dmb1987** [comment]
Hello, the only temporary solution I could make was in the common.min.js file:
was to comment on said part and return 0, once this was done I had no problem

jQuery.ajaxSetup({ beforeSend: function (e, t) { 
return ( 
//t.processData 
//  ? "" !== t.data
 //    ? (t.data += "&um_current_locale=" + um_common_variables.locale) 
//  : (t.data = "um_current_locale=" + um_common_variables.locale) 
//: (t.data = jQuery.extend(t.data, { um_current_locale: um_common_variables.locale })),
 //!0
 0 ); }, }),

**Comment by nikitasinelnikov** [comment]
See https://github.com/ultimatemember/ultimatemember/issues/1395
