### ISSUE TITLE
Translation updated but nothing appears to change

### ISSUE THREAD

**Issue by sdaverede** [ultimatemember/ultimatemember#14]
Hi guys! First of all thanks for this amazing plugin, its making my life easier :+1: 

I got the plugin in english, and y got this message:
"Your site language is es_ES. Good news! Ultimate Member is already available in Español language. Download the translation files and start using the plugin in your language now."

And when y press the "Download the translation" button, i get the other message:
"Your translation files have been updated successfully."

The thing is that nothing appears to change, is it a bug or i'm doing something wrong?

Thanks in advance and sorry for my poor english!

**Comment by ultimatemember** [comment]
Support-related question. https://ultimatemember.com/forums/
