### ISSUE TITLE
timestamp in avatar url

### ISSUE THREAD

**Issue by crmb** [ultimatemember/ultimatemember#140]
`$uri = um_user_uploads_uri() . 'profile_photo-'.$attrs.'.jpg?' . current_time( 'timestamp' );`

What is this hardcoded cache buster ? can't we use the profile's last modification date ?

**Comment by champsupertramp** [comment]
Hi @crmb 

I added a new filter hook so you can modify the cache time.

`+ um_filter_avatar_cache_time`
- `integer $cache_time`
- `integer $user_id`

ref: https://github.com/ultimatemember/ultimatemember/commit/6ab415a07c593113a449e989103273aecacc679d

Regards,

**Comment by crmb** [comment]
Thank you that was fast :+1:
