### ISSUE TITLE
Account page : account details not saved if changing default tab

### ISSUE THREAD

**Issue by tameroski** [ultimatemember/ultimatemember#1403]
**Expected behavior**
As a logged in user, when i change my first name, last name or email on my account page, i expect it to be saved on submit.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [X] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
In the account page, if the default tab is changed using the `um_change_default_tab` hook, account informations like first name, last name and email are not saved anymore in the ‘general’ tab.

**To Reproduce**
1. Add this in functions.php : `add_filter( "um_change_default_tab", function(){return "privacy";} );`
2. Click on "my account"
3. Change your first name and submit
4. First name is still the same

**Do you use UM extensions?**
Nope

**WordPress Environment**
I’m using UM 2.8.1, WP 6.4.2 with Divi. Tried with no plugins and default theme too.

PS : also posted [here](https://wordpress.org/support/topic/bug-account-page-account-not-saved-if-changing-default-tab/) as i wasn't aware of the existence of this repo at first.

**Comment by ashubawork** [comment]
Hello @tameroski 

I checked your filter on my local site and I can't reproduce this issue.
Are you sure you don't have a cache on your site?

Regards.

**Comment by tameroski** [comment]
Hi !

This is not a problem with cache.

But i started over with a fresh WP install and can't reproduce too.

So i compared the default settings with the settings on my previous WP Install, and it seams i changed the "user" page for the "account" one : 

```
--- UM Pages Configuration ---

User:						http://localhost/account/
Account:						http://localhost/account/
Members:					http://localhost/members/
Register:						http://localhost/register/
Login:						http://localhost/login/
Logout:						http://localhost/logout/
Password Reset:				http://localhost/password-reset/
```

Did the same on the fresh WP install, and now i have the issue.

I think i can go back to the original page settings without a harm. What is confusing (a lot), is that the User page and the Account one share the same translation in my language (French) : 
 
<img width="784" alt="same-translation" src="https://github.com/ultimatemember/ultimatemember/assets/338432/1311032f-407d-4a60-9044-722dea82e2ea">

Maybe this is something that can be fixed. And on the other side, if you allow pages to be changed, features like default page hook should still work properly (theoretically).

**Comment by ashubawork** [comment]
Hi @ashubawork 

The account page should be saved as the account and the user page as the user.
![b258b725-0283-41b2-8f7a-d6d5895a67d9](https://github.com/ultimatemember/ultimatemember/assets/43743394/0a45bbf5-b875-4b5e-8c4f-7a379fbccbe2)

Otherwise it may cause incorrect behavior.
Could you rename your page (account or user) for correct settings?

Regards.

**Comment by tameroski** [comment]
Already done that, thanks. It fixed my issue.
