### ISSUE TITLE
Default email background color

### ISSUE THREAD

**Issue by cryptexvinci** [ultimatemember/ultimatemember#1405]
**Is your feature request related to a problem? Please describe.**
The default background color of emails is #f2f2f2, which looks odd. 

**Describe the solution you'd like**
Set the default email background to #ffffff

**Describe alternatives you've considered**

**Additional context**
![Screenshot 2024-01-01 094617](https://github.com/ultimatemember/ultimatemember/assets/10268346/ff949931-e835-4625-a41d-3118442beb77)

**Comment by nikitasinelnikov** [comment]
When we have HTML content inside the notification this background is used to make this view for layout.
https://jam.dev/c/6b8ea2e4-9276-4b7e-84bf-c42f2e1f8980

Let's ask @calumallison
