### ISSUE TITLE
HUGE missbehaviour in UM site access since 1.3.60

### ISSUE THREAD

**Issue by MartNytrm** [ultimatemember/ultimatemember#141]
Hi there,

issue tested in 1.3.60 with new database and fresh WP installation and a second used WP installation.
In short: **With "Global site access: Site accessible to logged in users" you can't reach sites with "Content accessible to Everyone" anymore as logged out user since Update 1.3.60!**

What worked before version 1.3.60:
My settings:
- I have a front page and a static page
- Global site access: Site accessible to logged in users
- Custom redirect is to my front page (mydomain.ltd)
- Front page is my login page
- On my front page I have a menu with some public pages, made accessible by switching "Apply custom access settings?" to "Content accessible to Everyone" or Content accessible to Logged Out Users".
Before Update to version 1.3.60 I could reach this sites as logged out user, because they were obviously marked as accessible without login.

Problem with 1.3.60:
With Version 1.3.60 I will be redirected to my front page when logged out and have no chance to get to one of these public sites.
The same occurs with all action sites from other plugins which are explicitly marked with UM as "Content accessible to Everyone" and worked before 1.3.60
The only thing which gave me a fast workaround is to manually add the already public sites to the list "Exclude the following URLs" in UM access settings.
This should not be a normal behavior, because then the site accessible settings of UM would be useless.

Can you confirm this issue?

Thanks

**Comment by champsupertramp** [comment]
Hi,

This options overrides all access settings in the version 1.3.60.
`Global site access: Site accessible to logged in`  

Can you please change `Global Site Access` to Everyone and see if all access settings work.

Regards,

**Comment by MartNytrm** [comment]
I switched to "Site accessible to Everyone" and now i can access the sites of course (logical exceptions: "user" and "account").

Why does "Global site access: Site accessible to logged in" overwrites even the exceptions for single sites? Is this a bug or do I not get the point?

Greets

**Comment by champsupertramp** [comment]
Hi,

Can you please try the pre-released version 1.3.61 in the link?
https://github.com/ultimatemember/ultimatemember/releases

Let me know if this resolves the issue.

Regards,

**Comment by funkolector** [comment]
Thanks for the update.
It seems to work better with 1.3.61.
But I'll be waiting longer before upgrading next time...:(
On a production website this mistake could have made huge troubles regarding to a paying community members.
Personnaly I'm waiting to know more about your plugin before going premium.
This episode DID NOT convince me at all....

**Comment by MartNytrm** [comment]
Tested version pre 1.3.61:
**Global site access: Site accessible to logged in Users**
As logged out:
(+) no access to sites with default settings -> works
(+) no access to sites with "only logged in" -> works (works without explicit redirect URL, too)
(+) access to sites with "only logged out" -> works
(+) access to sites with "to every one" -> works
As logged in:
(+) access to sites with default settings -> works
(+) access to sites with "only logged in" -> works
(x) no access to sites with "only logged out" -> **works partially
It works when you explicitly set a redirect URL for the site, but it does not when none is set, but it should deny the access nevertheless!**
(+) access to sites with "to every one" -> works

**Global Site Access: Site accessible to Everyone:**
As logged out:
(+) access to sites with default settings -> works
(+) no access to sites with "only logged in" -> works (works without explicit redirect URL, too)
(+) access to sites with "only logged out" -> works
(+) access to sites with "to every one" -> works
As logged in:
(+) access to sites with default settings -> works
(+) access to sites with "only logged in" -> works
(x) no access to sites with "only logged out" -> **works partially
It works when you explicitly set a redirect URL for the site, but it does not when none is set, but it should deny the access nevertheless!**
(+) access to sites with "to every one" -> works

Hope you (@champsupertramp) will understand this mess :-).

Greets

**Comment by champsupertramp** [comment]
Hi @MartNytrm Thanks for letting us know.

Can you please try the pre-released version 1.3.62 in the link?
https://github.com/ultimatemember/ultimatemember/releases

Let me know if you're still encountering issues.

Regards,

**Comment by MartNytrm** [comment]
@champsupertramp 
In pre 1.3.62 I can still find the issue with site option "Content accessible to Logged out users" with no Redirect URL set. Sites with this option still stay accessible for logged in users; unattached by the "Global site access" setting. 

Greets

**Comment by champsupertramp** [comment]
Hi @MartNytrm ,

Can you please provide steps to recreate the issue?

Thank you

**Comment by MartNytrm** [comment]
Hello @champsupertramp,

first to make sure that there is no misunderstanding:
I assume: When you create a site "A" and set UM's access settings for site "A" to "Content accessible to logged out users", logged in users shouldn't see it/be able to open it's link, right?

For reproduction:
1) Create a site "A" with UM site access setting "Content accessible to logged out users"
2) Login with an account (best: use a non-admin to ensure the right visibility/acessibility) -> now we have a "logged in" user
**3) Now, call your site "A" -> there is no redirection to your default redirection site/start page, whatever. You can see this site.**
4) If you now add in UM's access settings of site "A" a special redirection url, site "A" is not accessible, because of redirection for logged in users.

**I excpect 3) to work like 4) just fur your global set redirection url or start page.**

Is this a wrong assumtion?
Can you reproduce it?

Greets

**Comment by champsupertramp** [comment]
Hi @MartNytrm,

Thanks for letting me know. Can you try the updated pre-released version with fixes for this issue?
https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.62.2

Regards,

**Comment by MartNytrm** [comment]
Hi @champsupertramp,

In Version 1.3.62.3:
If you are logged in:
+ Register page (for logged out only, with no redirect URL) --> to profile page (good idea!)
+ Password reset page (for logged out only, with no redirect URL) --> to profile page
+ same with every other site (for logged out only, with no redirect URL)
+ if redirect URL is set --> worked (redirected to specific URL)
+ worked for both "Global Site Access" settings

Jop, I would say this issue is fixed, and you can close this thread with the release of 1.3.62, if you agree.

Thanks!

**Comment by champsupertramp** [comment]
Hi @MartNytrm,

Thanks for letting us know. I am closing this thread now.

Regards,
