### ISSUE TITLE
Add a text box to UM Login form and get a PHP notice

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1411]
**Describe the bug**
Notice: Undefined index: metakey in .../plugins/ultimate-member/includes/admin/core/class-admin-metabox.php on line 1497

**To Reproduce**
Add a text box to default Login form

**Comment by ashubawork** [comment]
Hello @MissVeronica 

I can't reproduce this issue. Do you get this error on the login page without submitting a form?

Regards.

**Comment by MissVeronica** [comment]
I get it in the UM Forms Builder
https://imgur.com/a/Swoxwn0

**Comment by ashubawork** [comment]
Hello @MissVeronica 

Can't reproduce this issue. Did you try to reproduce it from the 2.8.x branch -https://github.com/ultimatemember/ultimatemember/tree/development/2.8.x?

Regards.

**Comment by MissVeronica** [comment]
No from UM 2.8.1

**Comment by MissVeronica** [comment]
Yes, I am always using latest UM version 2.8.2
This is a stackdump taken before the line 1497
```
#0 wp-content/plugins/ultimate-member/includes/admin/core/class-admin-builder.php(1026): um\admin\core\Admin_Metabox->field_input()
#1 wp-includes/class-wp-hook.php(324): um\admin\core\Admin_Builder->dynamic_modal_content()
#2 wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 wp-includes/plugin.php(517): WP_Hook->do_action()
#4 wp-admin/admin-ajax.php(188): do_action()
#5 {main}
```
The variable `$field_args` is an empty array when being tested for the `$field_args['metakey']` index in line 1497.

**Comment by ashubawork** [comment]
Hi @MissVeronica 

Thank you, I found this issue. I will check it.

Regards.
