### ISSUE TITLE
Cropper JS error ‘scaleX’ and the Avada theme

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1424]
**Describe the bug**
```
cropper.min.js?ver=1.6.1:10 Uncaught TypeError: Cannot read properties of undefined (reading ‘scaleX’)
at n.getData (cropper.min.js?ver=1.6.1:10:25897)
at HTMLAnchorElement. (um-modal.min.js?ver=2.8.1:1:1666)
at HTMLDocument.dispatch (jquery.min.js?ver=3.7.1:2:40035)
at v.handle (jquery.min.js?ver=3.7.1:2:38006)
```
**Reference**
https://github.com/ultimatemember/ultimatemember/issues/1385

**UM Support Forum Issue**
https://wordpress.org/support/topic/profile-picture-ally-crop-issue-conflict-with-avada/

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

Thanks, it will be fixed for all themes that use the Fusion Image library since 2.8.2 version.
You can check the branch from the attached PR.

Best Regards!

**Comment by MissVeronica** [comment]
> When Avada theme or even just the Avada builder plugin activated the submit button ceases to work which led me to do this conflict test. 

https://wordpress.org/support/topic/profile-picture-ally-crop-issue-conflict-with-avada/#post-17330439

**Comment by nikitasinelnikov** [comment]
It's related to the fusion images library inside the Avada functionality.
