### ISSUE TITLE
Account deletion with reset password not possible

### ISSUE THREAD

**Issue by MartNytrm** [ultimatemember/ultimatemember#143]
Hi there,

if a **user reset his/her password over UM's password-reset page, he is not able to delete his/her account** neither with the new password nor with the old one.
The new password works with the login, though.

Addition: If the password is changed in the account settings, the account deletion with the new password works fine.

Can you confirm this issue?
Issue tested **in 1.3.60** with new database and fresh WP installation and a second used WP installation.

Thanks

**Comment by champsupertramp** [comment]
Hi @MartNytrm,

Can you please try the pre-released version in the link?
https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.65.2

Thank you,

**Comment by MartNytrm** [comment]
Tested on pre-v1.3.65.4:
Account deletion with reset password works. (Old password is not valid any more.)

-> Issue fixed!

**Comment by champsupertramp** [comment]
Thanks for letting us know.
