### ISSUE TITLE
HTML link in wp_editor textarea is getting messed up

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1434]
**Describe the bug**
Set a textarea field to allow HTML and then edit the area with a HTML link many times and the HTML link will be messed up.

**Quick fix**
Change line 2828 in `.../plugins/ultimate-member/includes/core/class-fields.php` to
`$output .= str_replace( array( '<code>', '</code>' ), '', html_entity_decode( ob_get_clean()));`

**Support Forum issue**
https://wordpress.org/support/topic/rte-links-are-modified-on-saving/

**Comment by ashubawork** [comment]
Hello @MissVeronica 

I can't reproduce this issue. Is this a textarea field with an enabled "Does this textarea accept HTML?" option?

Regards.

**Comment by MissVeronica** [comment]
"Does this textarea accept HTML?" option? Yes

> Describe the bug
> Set a textarea field to allow HTML and then edit the area with a HTML link many times and the HTML link will be messed up.

**Comment by ashubawork** [comment]
Hello @MissVeronica 

Unfortunately I can't reproduce this. I tried saving visual tabs and text tabs several times, but everything saved well.

Regards.

**Comment by MissVeronica** [comment]
Steps to reproduce
1. Enter in the text box this HTML link `<a href="https://github.com/ultimatemember/ultimatemember/issues/1434">UM Bug</a>`
2. Save the form
3. View the link in form view mode and the browser reports the link with OK format
4. Edit the form again
5. Save the form without any changes
6. View the link in form view mode and the browser reports the link as `https://github.com/ultimatemember/ultimatemember/issues/1434%E2%80%B3` with a terminating double quote.
7. Edit the form again
8. Now the link for edit is `<a href=”//github.com/ultimatemember/ultimatemember/issues/1434″”>UM Bug</a>`
9. Save the form without updating the bad link
10. View the link now: `https://your.domain.com/user/2/%E2%80%9D//github.com/ultimatemember/ultimatemember/issues/1434%E2%80%B3%E2%80%9D`

**Comment by ashubawork** [comment]
Helo @MissVeronica 

Thank you for these details, I will check.

Regards.

**Comment by MissVeronica** [comment]
This Support Forum issue sounds like this issue

> When i put <i> with source https://(imgurl)/ and i save it, plugin will change the sourceurl to //(imgurl) and then it wouldnt show up in the email.

https://wordpress.org/support/topic/images-not-shown-in-send-email-but-i-can-see-in-email-e/

**Comment by danielmosss** [comment]
Hey, yes that support forum issue is indeed the same problem. 
I made the custom script from this that you can see in the support forum. 
It would be nice if this get fixed.

**Comment by ashubawork** [comment]
Hello @MissVeronica and @danielmosss

I create a new issue https://github.com/ultimatemember/ultimatemember/issues/1448. We will check it.

Thank you.

**Comment by ashubawork** [comment]
> Steps to reproduce
> 
> 1. Enter in the text box this HTML link `<a href="https://github.com/ultimatemember/ultimatemember/issues/1434">UM Bug</a>`
> 2. Save the form
> 3. View the link in form view mode and the browser reports the link with OK format
> 4. Edit the form again
> 5. Save the form without any changes
> 6. View the link in form view mode and the browser reports the link as `https://github.com/ultimatemember/ultimatemember/issues/1434%E2%80%B3` with a terminating double quote.
> 7. Edit the form again
> 8. Now the link for edit is `<a href=”//github.com/ultimatemember/ultimatemember/issues/1434″”>UM Bug</a>`
> 9. Save the form without updating the bad link
> 10. View the link now: `https://your.domain.com/user/2/%E2%80%9D//github.com/ultimatemember/ultimatemember/issues/1434%E2%80%B3%E2%80%9D`

Hello @MissVeronica 

I check this, but I haven't this issue. My textarea works well. Are there any other special features on your site?

**Comment by MissVeronica** [comment]
It's an issue when Elementor is active.
Probably the setting of the TinyMCE editor. 
https://www.tiny.cloud/docs-3x/reference/Configuration3x/

**Comment by MissVeronica** [comment]
UM Support forum issue without Elementor
https://wordpress.org/support/topic/rte-links-are-modified-on-saving/
