### ISSUE TITLE
Documentation Action: um_user_edit_profile

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1439]
**Expected behavior**
Documentation is reliable

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
Action hook `um_user_edit_profile` is not executed for priority 10.

**To Reproduce**
Add this code snippet to your active theme's functions.php
```
function my_user_edit_profile_9( $post, $form_data ) {
    $output  = 'Prio 9';
    file_put_contents( WP_CONTENT_DIR . '/debug.log', $output . chr(13), FILE_APPEND  );
}
function my_user_edit_profile_10( $post, $form_data ) {
    $output  = 'Prio 10';
    file_put_contents( WP_CONTENT_DIR . '/debug.log', $output . chr(13), FILE_APPEND  );
}
add_action( 'um_user_edit_profile', 'my_user_edit_profile_9', 9, 2 );
add_action( 'um_user_edit_profile', 'my_user_edit_profile_10', 10, 2 );
```

Edit a User Profile and save the Prpfile
Look at `debug.log` and only "Prio 9" is found.

**Expected behavior**
Example code in the UM documentation is valid
https://ultimatemember.github.io/ultimatemember/hooks/um_user_edit_profile.html

**UM Support Forum issue**
https://wordpress.org/support/topic/automatically-copy-some-profile-fields-to-another-database-table/

**Comment by nikitasinelnikov** [comment]
Thanks @MissVeronica 

The doc's example has been updated and will be published with the new release.
