### ISSUE TITLE
Bug in 1.3.61; Undefined page_url

### ISSUE THREAD

**Issue by Adynnor** [ultimatemember/ultimatemember#144]
in relation to the new update with WP_DEBUG getting error:
"Notice: Undefined variable: page_url in /wp-content/plugins/ultimate-member/core/um-permalinks.php on line 93"

simple workaround I've added 
`$page_url = '';`
just below line 69
`if ( is_multisite() ) {`

**Comment by champsupertramp** [comment]
Thanks for letting us know. Fixed https://github.com/ultimatemember/ultimatemember/commit/525afac10107f5e366fa91e8bb62941fcd1cfa82

**Comment by champsupertramp** [comment]
https://github.com/ultimatemember/ultimatemember/releases
