### ISSUE TITLE
Member Directory > Search > Exclude user meta

### ISSUE THREAD

**Issue by nikitasinelnikov** [ultimatemember/ultimatemember#1441]
**Is your feature request related to a problem? Please describe.**
Some customers want to exclude user meta fields from the global search feature in member directory queries.

**Describe the solution you'd like**
We need to add the option for the member directory in the search section where customers can specify what fields they want to exclude.

**Comment by MissVeronica** [comment]
The other case is also true when User wants to only include a few meta fields like name fiends ie exclude all but name fields.
See documentation https://docs.ultimatemember.com/article/1681-restrict-the-search-filter-to-only-specific-meta-keys
