### ISSUE TITLE
Major security concern

### ISSUE THREAD

**Issue by sylvain68** [ultimatemember/ultimatemember#145]
Hello,

It appears that anyone can very easily perform some normally unauthorized actions on UM accounts (with "member" as role). Here is the list of actions concerned: deactivate, reenable, put as pending, approve, reject and maybe resend activation too (not tested).

---Removed steps---

**Reason:** I noticed that no capability check is done in um-actions-core.php and um-admin-actions-user.php files !
It is very urgent to add a check if current user can "manage_options" before allowing users to perform these actions…

**Maybe it would be better to block this topic for safety reasons...**
Hope you could quickly fix this security issue.

Regards,
Sylvain

**Comment by champsupertramp** [comment]
We've created a patch for this and will be pushed an update later.

Thank you
