### ISSUE TITLE
Sorry, but this version of Ultimate Member does not work with extension...

### ISSUE THREAD

**Issue by mr-vance** [ultimatemember/ultimatemember#1453]
I don't see the option to update the theme from WordPress. 
Can anyone be so kind to help out with this? I am using the free version.
![Screenshot 2024-02-03 124338](https://github.com/ultimatemember/ultimatemember/assets/85713465/41b8ca8e-0da1-46c3-aa66-814cd1f229fb)
![Screenshot 2024-02-03 124306](https://github.com/ultimatemember/ultimatemember/assets/85713465/00653337-b214-4fea-b720-ba953063551c)

**Comment by mr-vance** [comment]
Tried downloading and installing the theme from the repo releases but got this.

![7a2d9f37-7b07-4c0f-8fcb-42d054f508fd](https://github.com/ultimatemember/ultimatemember/assets/85713465/bc9083dd-a510-4c29-9c48-1a877daea115)

**Comment by mr-vance** [comment]
Oh, I tried to install the plugin as a theme. silly me. 
The real issue is here

![Screenshot 2024-02-04 074529](https://github.com/ultimatemember/ultimatemember/assets/85713465/fde4a2b7-4a6b-4ef9-a164-a9cce89e988b)

**Comment by MissVeronica** [comment]
You can read this guide
https://docs.ultimatemember.com/article/1847-fixing-outdated-ultimate-member-templates

**Comment by mr-vance** [comment]
@MissVeronica thank you so much ❤️ I was able to fix that one.


But now these five plugins are giving me the hard time 💔 .

They seem to have been installed in a different place and i don't know what to do about them.
![Screenshot 2024-02-03 124306](https://github.com/ultimatemember/ultimatemember/assets/85713465/a66b8602-a18f-4858-b915-6cc7449d1c45)

These are located in the `wp-content/plugins` directory instead, and each has its own directory.

![Screenshot 2024-02-04 161903](https://github.com/ultimatemember/ultimatemember/assets/85713465/2fc18c0d-bae8-42d8-84fb-e2514fa3de22)

I am using the UM Theme version 1.29

![Screenshot 2024-02-03 124338](https://github.com/ultimatemember/ultimatemember/assets/85713465/f0021e15-d6d8-4a36-b217-07e2290246d6)

**Comment by nikitasinelnikov** [comment]
Hi @mr-vance 

Please update UM Theme because there is the latest 1.35 version.

Best Regards!
