### ISSUE TITLE
Login error messages overwrite existing errors

### ISSUE THREAD

**Issue by baden03** [ultimatemember/ultimatemember#1455]
The um_wp_form_errors_hook_logincheck function located in includes/core/um-filters-login.php does not first check if an error already exists.  Would it not play better if we first check if an error has already been set for this user by adding the following before  checking for fetching the user from UM and checking it's status?

```
if( is_wp_error( $user ) ){
            return $user;
}
```

**Comment by nikitasinelnikov** [comment]
Thanks @baden03 

The fix will be added in the 2.8.3 version.
