### ISSUE TITLE
Ever since 1.3.62, our site has been having "ERR_TOO_MANY_REDIRECTS" on home page

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#146]
This has taken me 5 days to figure out.

I've switched servers. I moved from apache to nginx. I sweeped all cache. I deleted all transients... I was stumped.

On a hunch, I deleted your plugin and this resolved completely. I reinstalled it and `301_TOO_MANY_REDIRECTS` comes right back.

Here's the specifics:

- This only happens for logged in users.
- This only happens at the root level page.
- If we type oursite.com/wp-admin, we can skip past the redirect.

I'm happy to devote this entire day into helping you resolve this issue. Please let me know what you'd need from me.

**Comment by dsifford** [comment]
I just tried your latest pre-release and it's still happening.

**Comment by dsifford** [comment]
The last version that seems to work fine for us is version 1.3.61

**Comment by mrbm** [comment]
Try this plugin and their debugging mode:

https://wordpress.org/plugins/better-http-redirects/

**Comment by champsupertramp** [comment]
Hi @dsifford,

Can you please provide the following current settings on your site so i can investigate the issue?

1. Is your site in multi-site mode?
2. In `Admin > Ultimate Member > Settings > Access`, what's the current `Global Site Access` ?
3. In `Admin > Settings > Reading`, what's the current `Front page displays` ?
4. If your site has a static frontpage, can you please check if your frontpage has enabled the Ultimate Member access settings in edit screen?


Regards,

**Comment by dsifford** [comment]
Certainly.

1. No.
2. Global.
3. Static.


... and as I get to 4, it appears somebody must have adjusted those access settings. I found the culprit. 

Tag this as invalid. Thanks for the help dialing in to the problem. 👍

**Comment by champsupertramp** [comment]
Thanks for letting us know. I am closing this issue now. 

Regards,
