### ISSUE TITLE
 Auto capitalize form field. 

### ISSUE THREAD

**Issue by idelvert** [ultimatemember/ultimatemember#1463]
Auto capitalize form field. why??? no interest.
Can you tell us where is the correct hook to remove it.

**Comment by nikitasinelnikov** [comment]
Hi @idelvert 

Could you provide more information and screenshots? What is a field and where can you see the auto capitalizing?

Best Regards!

**Comment by nikitasinelnikov** [comment]
This issue has been inactive for a while so we’re going to go ahead and mark it Closed.
Please feel free to re-open this thread if any other questions come up and we’d be happy to help. 🙂
Regards
