### ISSUE TITLE
Email activation link expiration (days)

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1466]
**Expected behavior**
UM Settings -> Users -> Password: "Email activation link expiration (days)" should also process the user setting as days 

**Describe the bug**
.../plugins/ultimate-member/includes/core/class-user.php line 1610

Current PHP code:
`$this->profile['account_secret_hash_expiry'] = time() + $expiry_time;
`

**Expected behavior**
Updated PHP code:
`$this->profile['account_secret_hash_expiry'] = time() + $expiry_time * DAY_IN_SECONDS;`

**UM Support Forum issue**
https://wordpress.org/support/topic/bug-expiration-of-the-email-activation-link-in-days/

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

Thanks, we also detected this issue during the last testing.
We will fix that.

Best Regards!
