### ISSUE TITLE
Outdated Documentation > um_submit_form_errors_hook__registration

### ISSUE THREAD

**Issue by baden03** [ultimatemember/ultimatemember#1470]
The documentation found at:
https://docs.ultimatemember.com/article/1278-umsubmitformerrorshookregistration
is outdated. The filter is passing two vars:

```
function my_submit_form_errors_hook__registration( $submitted_data, $form_data ) {
    // your code here
}
add_action( 'um_submit_form_errors_hook__registration', 'my_submit_form_errors_hook__registration', 10, 2 );
```

2. The link back to the source:
https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/um-actions-form.php#L124
shows the change, but the line is is not accurate, should be L212

**Comment by nikitasinelnikov** [comment]
Hi @baden03 

We have the recent changes here:
https://ultimatemember.github.io/ultimatemember/hooks/um_submit_form_errors_hook__registration.html
This is a new docs related to the hooks.

We have stopped the support of the old hook docs. But there are still some hooks that have the page in old docs but don't have in the new. We are working on migration every release.

Best Regards!
