### ISSUE TITLE
Avada theme and the Cropper function

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1477]
**Describe the bug**
```
um-responsive.min.js?ver=2.8.4:1 Uncaught TypeError: jQuery(…).cropper is not a function
at um-responsive.min.js?ver=2.8.4:1:163
at dispatch (jquery-3.7.1.min.js?ver=3.7.1:2:40035)
at v.handle (jquery-3.7.1.min.js?ver=3.7.1:2:38006)
```

**Support Forum issue**
https://wordpress.org/support/topic/file-upload-uncaught-typeerror-jquery-cropper-is-not-a-function/

**Reference**
https://github.com/ultimatemember/ultimatemember/issues/1424

**Comment by centpede** [comment]
I found a workaround , see here:
https://wordpress.org/support/topic/file-upload-uncaught-typeerror-jquery-cropper-is-not-a-function/#post-17485728

**Comment by ashubawork** [comment]
Hello @MissVeronica and @centpede 

I checked my local site and I can't reproduce this issue with the Avada. Maybe you are using some special theme settings?

Regards.

**Comment by nikitasinelnikov** [comment]
This issue has been inactive for a while so we’re going to go ahead and mark it Closed.
Please feel free to re-open this thread if any other questions come up and we’d be happy to help. 🙂
Regards
