### ISSUE TITLE
Nobody giving support for the Ultimate Member Recaptcha plugin?

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1497]
There are no UM support replies to any of the issues for the last 12 months at
https://wordpress.org/support/plugin/um-recaptcha/active/

**UM Support Forum issue**
https://wordpress.org/support/topic/nobody-giving-support-for-the-ultimate-member-recaptcha-plugin/

**Comment by ashubawork** [comment]
I received a response from the creator of this topic, the problem is not on the side of our plugin.
