### ISSUE TITLE
Undefined variables if Member Directory settings haven't been saved

### ISSUE THREAD

**Issue by robincornett** [ultimatemember/ultimatemember#15]
I set up a local copy of UM to work through setting up custom fields--quick setup, didn't mess with adjusting much in the way of settings or anything at all. Discovered that the site was throwing notices for undefined variables, all coming from the assets/dynamic_css/dynamic_directory.php file. Apparently there are not default values set for these:

* css_profile_card_bg
* css_profile_card_text
* css_card_bordercolor
* css_img_bordercolor

Once I edited the member directory and set values for those, the notices disappeared, even if I cleared the values out and left them empty.

**Comment by ultimatemember** [comment]
patched. fix in next updae
