### ISSUE TITLE
UM 2.8.5 issues with Custom email templates and profile tabs

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1500]
I'm having a lot of issues like this with UM 2.8.5

`Fatal error: Uncaught Error: Cannot access private property um\core\Options::$options ......`

**Comment by MissVeronica** [comment]
The UM documentation about creating and using custom email templates is no longer valid 
when `UM()->options()->options` is private.

https://docs.ultimatemember.com/article/1515-how-to-add-and-use-custom-email-templates

**Comment by Graphnic** [comment]
I too have had a similar issue this evening on a site using custom email templates.  The filter brought the site down with a Critical Error.

The issues appears to be at the point when custom templates are merged into the options array UM()->options()->options.

**Comment by MissVeronica** [comment]
Yes you are right.

This is the critical code where `UM()->options()->options` now is protected by UM

```
	foreach ( $custom_emails as $slug => $custom_email ){
		// Default settings.
		if ( ! array_key_exists( $slug.'_on', UM()->options()->options ) ) {
			UM()->options()->options[ $slug.'_on' ]  = empty( $custom_email['default_active'] ) ? 0 : 1;
			UM()->options()->options[ $slug.'_sub' ] = $custom_email['subject'];
		}
```

I'm rewriting my plugins now with this coding to bypass this nasty UM protection.

**Comment by MissVeronica** [comment]
These code snippets for adding extra Profile tabs are also outdated with UM 2.8.5 and will give a Fatal error

https://docs.ultimatemember.com/article/69-how-do-i-add-my-extra-tabs-to-user-profiles

**Comment by MissVeronica** [comment]
UM Support Forum issue with the integration of "WP User Fronted" plugin

https://wordpress.org/support/topic/fatal-error-after-new-update-4/

**Comment by ashubawork** [comment]
Hello @MissVeronica 

Thank you for your feedback. We will update documentations.
These are gists with fixed code:
1. Custom email "Example 1 - Profile is complete" - [](https://gist.github.com/ashubawork/ec7997fc8c1a7b5d7e181d3a6f7d5338)
2. Custom email "Example 2 - Account is not verified" - [](https://gist.github.com/ashubawork/2d20e5208bb0937dc172e2bc07c4b016)

Regards.

**Comment by garyvoth** [comment]
Hello. This has impacted us as well. Site crashed after upgrading to UM 2.85. 

We rely specifically on the **um-admin-user-profile-update-email** plugin to synchronize user data between our WordPress site and our MS365 business database. 

We were able to roll back UM to 2.84 and all is working again for now. Looking forward to any further news on whether this can be fixed.

Thank you so much for your efforts.

**Comment by MissVeronica** [comment]
@garyvoth
There will be an update of the email plugin today.

**Comment by ashubawork** [comment]
Hello @MissVeronica @Graphnic @garyvoth 

We updated documentation, please change your custom code:
[https://docs.ultimatemember.com/article/1515-how-to-add-and-use-custom-email-templates](https://docs.ultimatemember.com/article/1515-how-to-add-and-use-custom-email-templates)
[https://docs.ultimatemember.com/article/69-how-do-i-add-my-extra-tabs-to-user-profiles](https://docs.ultimatemember.com/article/69-how-do-i-add-my-extra-tabs-to-user-profiles
)
Regards.

**Comment by MissVeronica** [comment]
Version 4.6.0 Updated and tested both for UM 2.8.4 and UM 2.8.5 is ready for download now

**Comment by Graphnic** [comment]
Thanks for the update @ashubawork. 

I'm using a custom email for when a user of a particular role is 'approved'. Without familiarity of the inner workings of UM, I'm struggling to adapt the function based on the new code examples. It seems to fail on the array merge with our old code. Any advice?

`function custom_um_email_notifications_after_user_is_approved( $emails ) {

	/* New email templates */
	$custom_emails = array(
		'parents_approved_email'     => array(
			'key'            => 'parents_approved_email',
			'title'          => __( 'Account Welcome Email, Parents (Role um_parents)', 'ultimate-member' ),
			'subject'        => 'Welcome to {site_name}!',
			'body'           => '',
			'description'    => __( 'Send the user (Parents) an email when their account is approved.', 'ultimate-member' ),
			'recipient'      => 'user',
			'default_active' => true
		),
		'prospective_approved_email' => array(
			'key'            => 'prospective_approved_email',
			'title'          => __( 'Account Welcome Email, Prospective Parents (Role um_prospective-parents)', 'ultimate-member' ),
			'subject'        => 'Welcome to {site_name}!',
			'body'           => '',
			'description'    => __( 'Send the user (Prospective Parents) an email when their account is approved.', 'ultimate-member' ),
			'recipient'      => 'user',
			'default_active' => true
		),
	);

	/* Default settings */
	UM()->options()->options = array_merge( array(
		'parents_approved_email_on'      => 1,
		'parents_approved_email_sub'     => 'Welcome to {site_name}!',
		'prospective_approved_email_on'  => 1,
		'prospective_approved_email_sub' => 'Welcome to {site_name}!',
	), UM()->options()->options );

	return array_merge( $custom_emails, $emails );
}

add_filter( 'um_email_notifications', 'custom_um_email_notifications_after_user_is_approved' );


/**
 * Send custom email templates (depending on UM user role) on UM User approve action.
 *
 * @param int $user_id
 *
 * @return boolean
 */
function custom_um_after_user_is_approved( $user_id = null ) {

	if ( empty( $user_id ) ) {
		$user_id = get_current_user_id();
	}

	$status = get_user_meta( $user_id, 'account_status', true );
	if ( 'approved' !== $status ) {
		return;
	}

	$rolename = UM()->roles()->get_priority_user_role( $user_id );
	$userdata = get_userdata( $user_id );

	switch ( $rolename ) {
		case 'um_parent':
			UM()->mail()->send( $userdata->user_email, 'parents_approved_email' );
			break;
		case 'um_prospective-parent':
			UM()->mail()->send( $userdata->user_email, 'prospective_approved_email' );
			break;
		default:
			break;
	}
}

add_action( 'um_after_user_is_approved', 'custom_um_after_user_is_approved' );`

**Comment by ashubawork** [comment]
Hi @Graphnic 

Try to use this code:
```php
if ( ! function_exists( 'um_email_locate_template' ) ) {
	/**
	 * Locate a template and return the path for inclusion.
	 */
	function um_email_locate_template( $template_name ) {
		$blog_id = is_multisite() ? '/' . get_current_blog_id() : '';

		$template = locate_template(
			array(
				trailingslashit( 'ultimate-member/email' . $blog_id ) . $template_name . '.php',
				trailingslashit( 'ultimate-member/email' ) . $template_name . '.php',
			)
		);

		if ( ! $template ) {
			$template = wp_normalize_path( STYLESHEETPATH . '/ultimate-member/email/' . $template_name . '.php' );
		}

		return apply_filters( 'um_locate_email_template', $template, $template_name );
	}
}

function custom_um_email_notifications_after_user_is_approved( $emails ) {

	// New email templates
	$custom_emails = array(
		'parents_approved_email'     => array(
			'key'            => 'parents_approved_email',
			'title'          => __( 'Account Welcome Email, Parents (Role um_parents)', 'ultimate-member' ),
			'subject'        => 'Welcome to {site_name}!',
			'body'           => '',
			'description'    => __( 'Send the user (Parents) an email when their account is approved.', 'ultimate-member' ),
			'recipient'      => 'user',
			'default_active' => true
		),
		'prospective_approved_email' => array(
			'key'            => 'prospective_approved_email',
			'title'          => __( 'Account Welcome Email, Prospective Parents (Role um_prospective-parents)', 'ultimate-member' ),
			'subject'        => 'Welcome to {site_name}!',
			'body'           => '',
			'description'    => __( 'Send the user (Prospective Parents) an email when their account is approved.', 'ultimate-member' ),
			'recipient'      => 'user',
			'default_active' => true
		),
	);

	foreach ( $custom_emails as $slug => $custom_email ) {
		// Default settings.
		$email_option_on  = UM()->options()->get( $slug . '_on' );
		$email_option_sub = UM()->options()->get( $slug . '_sub' );
		if ( '' === $email_option_on ) {
			$email_on = empty( $custom_email['default_active'] ) ? 0 : 1;
			UM()->options()->update( $slug . '_on', $email_on );
		}
		if ( '' === $email_option_sub ) {
			$email_sub = empty( $custom_email['subject'] ) ? $slug : $custom_email['subject'];
			UM()->options()->update( $slug . '_sub', $email_sub );
		}

		// Template file.
		$located = um_email_locate_template( $slug );
		if ( ! file_exists( $located ) ) {
			wp_mkdir_p( dirname( $located ) );
			file_put_contents( $located, $custom_email['body'] );
		}

		$emails[ $slug ] = $custom_email;
	}

    return $emails;
}

add_filter( 'um_email_notifications', 'custom_um_email_notifications_after_user_is_approved' );

/**
 * Send custom email templates (depending on UM user role) on UM User approve action.
 *
 * @param int $user_id
 *
 * @return boolean
 */
function custom_um_after_user_is_approved( $user_id = null ) {

	if ( empty( $user_id ) ) {
		$user_id = get_current_user_id();
	}

	$status = get_user_meta( $user_id, 'account_status', true );
	if ( 'approved' !== $status ) {
		return;
	}

	$rolename = UM()->roles()->get_priority_user_role( $user_id );
	$userdata = get_userdata( $user_id );

	switch ( $rolename ) {
		case 'um_parent':
			UM()->mail()->send( $userdata->user_email, 'parents_approved_email' );
			break;
		case 'um_prospective-parent':
			UM()->mail()->send( $userdata->user_email, 'prospective_approved_email' );
			break;
		default:
			break;
	}
}

add_action( 'um_after_user_is_approved', 'custom_um_after_user_is_approved' );
``` 
Regards.

**Comment by Graphnic** [comment]
@ashubawork Thank you, I'll try that.  Appreciate your response!

**Comment by MKLU447** [comment]
Same error after upgrading to 2.8.5, here the info :

ne erreur de type E_ERROR a été causée dans la ligne 3263 du fichier /customers/f/12/b/WEBSITE.COM/httpd.www/wp-content/plugins/cm-answers-pro/lib/controllers/AnswerController.php. Message d’erreur : Uncaught Error: Cannot access private property um\core\Options::$options in /customers/f/12/b/WEBSITE.COM/httpd.www/wp-content/plugins/cm-answers-pro/lib/controllers/AnswerController.php:3263
Stack trace: 0 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-hook.php(324): CMA_AnswerController::um_cma_customtab_add_tab(Array) 1 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/plugin.php(2012): WP_Hook->apply_filters(Array, Array) 2 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-content/plugins/ultimate-member/includes/core/class-profile.php(161): apply_filters(‘um_profile_tabs’, Array) 3 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-content/plugins/ultimate-member/includes/class-config.php(607): um\core\Profile->tabs() 4 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-content/plugins/ultimate-member/includes/class-init.php(998): um\Config->__construct() 12 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-content/plugins/ultimate-member/includes/core/class-rewrite.php(83): UM->config() 6 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-hook.php(324): um\core\Rewrite->add_rewrite_rules(Array) 7 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/plugin.php(2012): WP_Hook->apply_filters(Array, Array) 8 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-rewrite.php(1473): apply_filters(‘rewrite_rules_a…’, Array) 9 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-rewrite.php(11209): WP_Rewrite->rewrite_rules() 10 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-rewrite.php(1884): WP_Rewrite->refresh_rewrite_rules() 11 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-hook.php(324): WP_Rewrite->flush_rules(true) 12 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) 13 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-includes/plugin.php(1217): WP_Hook->do_action(Array) 14 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-settings.php(717): do_action(‘wp_loaded’) 112 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-config.php(107): require_once(‘/customers/f/12/…’) 16 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-load.php(120): require_once(‘/customers/f/12/…’) 17 /customers/f/12/b/WEBSITE.COM/httpd.www/wp-admin/admin-ajax.php(22): require_once(‘/customers/f/12/…’) 18 {main}

**Comment by MissVeronica** [comment]
@MKLU447
You must contact the "Cm Answers Pro" plugin developers about this issue.

**Comment by Graphnic** [comment]
> @ashubawork Thank you, I'll try that. Appreciate your response!

FYI this resolves the issue. Thanks for your help. 😎

**Comment by MissVeronica** [comment]
@MKLU447 

No it's not an UM issue and the UM coding will not be changed to fix this issue.
Above you will find coding examples how to fix this issue in other plugins integrating with UM.
