### ISSUE TITLE
Bulk actions checkbox disabled for UM plugin.

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#1522]
**Describe the bug**
The bulk actions checkbox is disabled for the Ultimate Member plugin on the Plugins page.

**Screenshots**

![Screen1](https://github.com/ultimatemember/ultimatemember/assets/28895658/7ee902f5-76ab-4c1a-aedf-88f4feafb3b6)

![Screen2](https://github.com/ultimatemember/ultimatemember/assets/28895658/1021fdc4-87be-4839-9ef7-d98f9d510b6a)

**Comment by nikitasinelnikov** [comment]
Closed based on this article:
https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/
