### ISSUE TITLE
Cropper JS error again

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1539]
**Describe the bug**
`cropper.min.js?ver=1.6.1:10 Uncaught TypeError: Cannot read properties of undefined (reading 'scaleX') at i.getData (cropper.min.js?ver=1.6.1:10:26098) at HTMLAnchorElement.<anonymous> (um-modal.min.js?ver=2.8.6:1:1666) at HTMLDocument.dispatch (jquery.min.js?ver=3.7.1:2:40035) at v.handle (jquery.min.js?ver=3.7.1:2:38006)`

**To Reproduce**
Upload Photo → Crop → Apply. 
However, I am unable to press the “Apply” button after cropping the image.

**Support forum issue**
https://wordpress.org/support/topic/issue-with-image-upload-and-cropping-on-profile-page/

**References**
https://github.com/ultimatemember/ultimatemember/issues/1424
https://github.com/ultimatemember/ultimatemember/issues/1385

**Comment by nikitasinelnikov** [comment]
More details of the issue are there:
https://github.com/ultimatemember/ultimatemember/issues/1539
