### ISSUE TITLE
birth_date field doesn't respect specified label on profile form

### ISSUE THREAD

**Issue by realuser** [ultimatemember/ultimatemember#155]
If you add the pre-existing birth date field it seems to force a label of "Age" regardless of what label you give it in the UI

This appears to be because of this:
https://github.com/ultimatemember/ultimatemember/blob/c84f645fc8bbcfd391d46647a0ba351b4820f44f/core/um-filters-fields.php#L19

I can override the filter in code but it seems like this should just use whatever the user specifies in the field settings for the profile form.

**Comment by champsupertramp** [comment]
Thanks for letting us know. We've removed the overriding label in birth date field type.

The change has been added in the pre-released version in the link:
https://github.com/ultimatemember/ultimatemember/releases

Regards,
