### ISSUE TITLE
Additional parameters to filter um_user_profile_restricted_edit_fields

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1551]
**Is your feature request related to a problem? Please describe.**
The filter is not easy to use for adding restricted edit fields, seems to be designed for removing existing restricted edit fields.

**Describe the solution you'd like**
Additional meta_key and maybe also an array with current form fields

**Describe alternatives you've considered**
This code is executed for each call to the filter and adds unwanted processing foreach meta key in the form.
```
    public function um_user_profile_restricted_edit_fields_custom_privacy( $arr_restricted_fields, $_um_profile_id ) {

        if ( ! current_user_can( 'administrator' )) {

            if ( is_array( UM()->fields()->fields ) && ! empty( UM()->fields()->fields )) {

                foreach( UM()->fields()->fields as $form => $form_fields ) {
                    foreach( $form_fields as $meta_key => $form_field ) {

                        if ( isset( $form_field['public'] ) && $form_field['public'] == $this->code ) {

                            if ( ! in_array( $meta_key, $arr_restricted_fields )) {

                                $arr_restricted_fields[] = $meta_key;
                            }
                        }
                    }
                }
            }
        }

        return $arr_restricted_fields;
    }
```

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica

For getting all form fields please use `UM()->form()->form_data['custom_fields']`.
Also thanks for pointing me, that running of the `get_restricted_fields_for_edit()` function was into the fields loop.

Please check my recent commit to the 2.8.7 version. https://github.com/ultimatemember/ultimatemember/commit/cccce6ebc3e8211ccc1177c3113de5244b7e8bbb

**Comment by nikitasinelnikov** [comment]
@MissVeronica 
Can this issue be closed?

**Comment by MissVeronica** [comment]
Yes

**Comment by MissVeronica** [comment]
There is still an issue with this filter `um_user_profile_restricted_edit_fields` in profile edit mode 
the `function edit_field` is calling the `function get_restricted_fields_for_edit` 
in a loop for all fields on the form.

**Comment by nikitasinelnikov** [comment]
@MissVeronica I have added static variable in the recent commit for your and similar cases

**Comment by MissVeronica** [comment]
Many thanks, it is working perfectly now.
