### ISSUE TITLE
UM 2.8.7 email activation

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1553]
WP All Users column Status and the new dropdown menu:
Sending a second email activation is never sent for accounts with status awaiting email activation
Sending activation email for an approved account will get the URL ...user_id=1 for all Users activation links.

**Comment by nikitasinelnikov** [comment]
@MissVeronica thanks for your report.
Please check this functionality from the latest commit in master branch

**Comment by MissVeronica** [comment]
Tested OK now
