### ISSUE TITLE
Unable to change Membership Status in Users page (after last update)

### ISSUE THREAD

**Issue by jkontosgr** [ultimatemember/ultimatemember#1562]
**Expected behavior**
Must be a button "Apply" to change Membership status (It was existed in previous version)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
In default Wordpress page "Users->All Users" there was (in top row) a button to change DM status on selected users below

**To Reproduce**
1. Go to 'Users'
2. Click on 'All members'
3. Select any user
4. Cannot change Membership e.g. "Membership rejected" there is no button to "Apply" "Εφαρμογή" in Greek, but there is another button "Filter" which had never been there!
5. Also some translations from Membership dropdown box have reverted to English (from previous Greek ones)
6. Please check screenshots below- there is no way to change the statuses
7. Also is there any way to have the ability to rename/change the text of Statuses in Settings ???

**Expected behavior**
Work as usual like version 2.8.6.

**Screenshots**
in version 2.8.6
![image](https://github.com/user-attachments/assets/0e7a2feb-bfdb-477a-a744-9ab7bc1762e4)
![image](https://github.com/user-attachments/assets/44d6e1be-6521-465f-9939-862b90e9e36b)
in version 2.8.7 and 2.8.8
![image](https://github.com/user-attachments/assets/4daa98cf-a7f6-466b-9ac4-9d6367d13aef)
![image](https://github.com/user-attachments/assets/60d15783-8338-43e2-935e-0726f90fe190)

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [x] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>

Copy and paste the install info from ** Ultimate Member > Settings > Install Info ** in WordPress admin.

**Comment by nikitasinelnikov** [comment]
Hi @jkontosgr 

Please read this article. Bulk actions were merged with WordPress native dropdown.

https://docs.ultimatemember.com/article/1943-guide-to-ultimate-member-managing-users-in-wordpress

Translations will be added soon on wp.org by the Translations team. Some strings have different places between versions.

Let me know if you have other questions,
Best Regards!

**Comment by nikitasinelnikov** [comment]
Hi @jkontosgr 

Should I mark this issue as resolved?

Let me know if you still have some issues.
