### ISSUE TITLE
Profile Permalink Based on custom field

### ISSUE THREAD

**Issue by MoBadawy** [ultimatemember/ultimatemember#158]
How can make the Profile Permalink Based on custom field that was made for each user?
Is this possible ?

**Comment by champsupertramp** [comment]
Hi @MoBadawy 

can you provide an example profile permalink?

**Comment by MoBadawy** [comment]
somthing like this http://example.com/user/456456/
and this number "456456" get from custom user  meta value not user id.

also can it be like that http://example.com/456456/  without /user/ ?

**Comment by champsupertramp** [comment]
Hi @MoBadawy 

Sorry for the delay on getting back to you. 

You can check how we generate Profile Slugs and URL in the link:
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-permalinks.php#L237-L436

and this how we check the slug if it belongs to a user or not:
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-user.php#L928-L997

If you want to remove the /user/ as a default UM Profile page, you need to customize it.

Regards,

**Comment by Saad047** [comment]
Hello.
Is there any way to change the **Profile Permalink Base** ? I am struggling to find a proper way for this ? I can make changes in core files but I am looking for something more robust and long lasting ? Any help ?
Thanks

**Comment by champsupertramp** [comment]
Hi @Saad047 

What profile permalink base do you need? 

Regards,
