### ISSUE TITLE
プロフィール画像のアップロードに関する権限不足の問題

### ISSUE THREAD

**Issue by nntokyo** [ultimatemember/ultimatemember#1583]
発生状況:
Ultimate Memberプラグインのバージョン2.8.9ではプロフィール画像の変更が正常に行えましたが、2.9.0にアップデート後、権限不足のため画像のアップロードができない問題が発生しています。この問題は、特定のユーザーアカウントにおいても確認されています。
詳細:

プロフィール編集画面にアクセスし、画像を選択してアップロードを試みると、「権限が不足しています」といったエラーメッセージが表示されます。
アップロード先のフォルダ（wp-content/uploads/ultimatemember）のパーミッションは正しく設定されており、読み取り、書き込み、実行の権限が付与されています。
サーバーの設定やPHPのメモリ制限も確認済みで、特に問題は見当たりません。

再現手順:

会員状態でログイン。
Ultimate Memberのプロフィール編集ページに移動。
プロフィール画像を選択し、アップロードを試みる。
エラーメッセージが表示される。

期待される動作:
ユーザーがプロフィール画像を正常にアップロードできること。
影響を受けるユーザー:
この問題は、特定のユーザーアカウントに限らず、複数のユーザーに影響を及ぼしています。

**Comment by nikitasinelnikov** [comment]
Also, you could try this pre-release version. Maybe it works better on your installation
https://github.com/ultimatemember/ultimatemember/pull/1580

**Comment by nntokyo** [comment]
![download_file](https://github.com/user-attachments/assets/17a5e5ca-2609-44d0-8d53-51335b76464f)

詳細について回答いただきありがとうございます。
自分のプロフィールの画像でも編集できないので、こちらは潜在的なバグになると思われます。
権限についてはAdminを利用しております。

**Comment by nntokyo** [comment]
> Also, you could try this pre-release version. Maybe it works better on your installation #1580

このバージョンを利用しましたが再現します。
自分のプロフィールでも変更できないです。
Wordpressの標準のユーザーでは変更できています。

**Comment by nikitasinelnikov** [comment]
Hi @nntokyo 

Thanks for your report. I have added the fix to this branch
https://github.com/ultimatemember/ultimatemember/tree/development/2.9.x

We will release the 2.9.1 version soon.

Best Regards!

**Comment by nntokyo** [comment]
@nikitasinelnikov 素早い対応をいただき誠にありがとうございます。
