### ISSUE TITLE
UM 2.9.1 and WP 6.7.0 "ultimate-member text domain was triggered too early" Not solved

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1587]
**Describe the bug**
See https://github.com/ultimatemember/ultimatemember/issues/1581

**Comment by MissVeronica** [comment]
The issue is doing translations with UM textdomain in the plugin `function __construct()`
In my case the "User Profile Scrolling" plugin.
I will make an update of the plugin "User Profile Scrolling"

**Comment by MissVeronica** [comment]
"User Profile Scrolling" plugin update ready
https://github.com/MissVeronica/um-user-profile-scrolling

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica
We have checked the 2.9.1 version with enabled not a default language (e.g. Ukrainian) and didn't face the "ultimate-member text domain was triggered too early" issue. All translation functions are moved from `__construct` or hooks earlier than `init` hook. So 2.9.1 core without active extensions has to work as expected for now.

Let me know if you still can see this issue when only UM is active

**Comment by MissVeronica** [comment]
I'm already using 2.3.8.
Local language is working OK
