### ISSUE TITLE
empty needle for include/exclude scripts with empty string in array

### ISSUE THREAD

**Issue by robincornett** [ultimatemember/ultimatemember#16]
I was excluding scripts from running on a page and accidentally clicked the Add New Page button one extra time. Being lazy, I did not remove the blank line. Discovered in my PHP error log a notice about an empty needle. I believe that if you change line 46 in core/um-enqueue.php to be:

```
$exclude = um_get_option( 'js_css_exclude' );
// only filter if it is an array--will error if null
if ( is_array( $exclude ) ) {
	array_filter( $exclude );
}
```

That would filter out any empty strings before the foreach loop is run on the array. I think that you'd want to apply the same change to line 59 for the comparable include.

**Comment by ultimatemember** [comment]
Patched, ready for next update.
