### ISSUE TITLE
upload pre-v1.3.69.10 to Trac

### ISSUE THREAD

**Issue by runofthemill** [ultimatemember/ultimatemember#161]
hey guys - saw you released a pre-release (that makes sense...) here that fixes a number of issues, including a few that I'm affected by. I use composer to manage plugins, so it would be great if you guys could update trunk on Trac to pre-v1.3.69.10 so I can grab it with the `dev-trunk` tag :)

thanks so much in advance for your help!

**Comment by champsupertramp** [comment]
Hi,

Please check the latest version 1.3.71

Regards,
