### ISSUE TITLE
Account Activation Email upon Registration

### ISSUE THREAD

**Issue by Pizza1** [ultimatemember/ultimatemember#1612]
**Expected behavior**
Receive account activation email upon registration

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
'Account activation box is checked, but no account activation email is received, only a welcome email.

**To Reproduce**
As admin:
1. Turn on 'Account Activation Email' in UltimateMemeber->Settings->Emails

As a new user:
1. Go to the UM register page
3. Fill out all the details and register
4. Check email 
5. There's a welcome email, but there is no confirmation account activation email

**Expected behavior**
Receive an account activation confirmation email

**Screenshots**
![image](https://github.com/user-attachments/assets/a8af8fdd-a64d-46cd-b506-973ce5cb94fe)
(Account activation email is checked)

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
```
Copy and paste the install info from ** Ultimate Member > Settings > Install Info ** in WordPress admin.
```
</details>

**Comment by MissVeronica** [comment]
What is your setting at `UM Settings -> General -> Users -> "Registration Default Role "`?

Have you set the  "Registration Default Role " to "Require email Activation" at 
`UM User Roles -> Edit "Registration Default Role " -> "Registration options"`?

**Comment by Pizza1** [comment]
I set the Registration Default Role to "Require email Activation" and it worked, thank you!

**Comment by nikitasinelnikov** [comment]
Thanks @MissVeronica!
