### ISSUE TITLE
Error with avada

### ISSUE THREAD

**Issue by dacopan** [ultimatemember/ultimatemember#162]
When use avada theme, this theme add to menu admin custom flieds, but not saved whe use with UM.

the error is that missing "ID" param in UM um-navmenu-walker.php

**Comment by champsupertramp** [comment]
Hi @dacopan 

Thanks for letting us know.

Fixes has been pushed: https://github.com/ultimatemember/ultimatemember/commit/31192e66e979b86c4bbaa67c0a6718f7d2acee9e

Updated the pre-released version  https://github.com/ultimatemember/ultimatemember/releases

Regards,
