### ISSUE TITLE
Enqueue select2 only on um_options page

### ISSUE THREAD

**Issue by partyka1** [ultimatemember/ultimatemember#163]
Hi,
you dequeue woocommerce select2 plugin from, and enqueue other version. Please add some condition like:
```
if($pagenow == 'admin.php' && $_GET['page']=='um_options') {
	$this->load_selectjs();
}
```
to ensure it is only queued at your settings page. New version of select2 can mess with other WooCommerce plugins. You can do this to all your needed js plugins.
Thanks

**Comment by champsupertramp** [comment]
@partyka1 UM loads select2.js in front-end forms and options. There was a compatibility issue with Woocommerce select2.js because its version is outdated.
