### ISSUE TITLE
 Empty needle in ultimate-member/core/um-enqueue.php on line 55

### ISSUE THREAD

**Issue by MediPaper** [ultimatemember/ultimatemember#164]
Hi, received this error string. Is there a way to fix this? 

Empty needle in ultimate-member/core/um-enqueue.php on line 55

Thanks

**Comment by champsupertramp** [comment]
Hi,

This has been fixed in the latest pre-released version in the link:https://github.com/ultimatemember/ultimatemember/releases

Regards,
