### ISSUE TITLE
Issue with multiple registration forms per page

### ISSUE THREAD

**Issue by mdorchain** [ultimatemember/ultimatemember#166]
Hi,

When several registrations are located in a page (tabs, accordions, etc), all the forms automatically inherit of the query_args message et uid after any of the forms is submitted (um-actions-register.php line 216).
This results with all the forms showing their own um-postmessage no matter if they have been submitted or not.

Perhaps adding the form_id to the query_args would allow the forms to filter properly and show the postmessage only if they have been submitted.

Right now it makes impossible to use multiple registration form in a page with an admin validation.

Thanks

Michael

**Comment by champsupertramp** [comment]
Hi @mdorchain ,

This line https://github.com/ultimatemember/ultimatemember/blob/master/core/um-actions-register.php#L216 ?

Are you using the latest version of UM from WP repository?

Regards,

**Comment by mdorchain** [comment]
Hi @champsupertramp,

Sorry I messed up the line #.

If you check the line 222 (https://github.com/ultimatemember/ultimatemember/blob/master/core/um-actions-register.php#L222), you will see that only the message and the user_id are submitted.
This results with having all the forms to react to the same query string. 

Adding in the form_id in the query_args would allow a better filtering during the postback. This way only the form with form_id would react to the postback and display the postmessage.

The issue is easy to reproduce by just putting 2 registration forms in the page and submitting any of them.

Thank you.

**Comment by champsupertramp** [comment]
Hi @mdorchain ,

I've pushed the changes in the pre-released version:
https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.69.17

Let me know if you're still encountering issues.

Regards,

**Comment by mdorchain** [comment]
There is a significant regression in the way it worked.
The fix now completely ignore the registration options in the roles.

First there is no more notice when "admin review " is set for the role.
Second, it automatically login the new registered user login.

In my scenario, I allow a particular role to register other users on the front end using the registration forms. Now each time they do, they get kicked out and then logged in as the newly registered user.
This makes UM completely unusable for this kind of scenario.

I'm rolling back to the current stable version :)

Thanks

Michael

**Comment by champsupertramp** [comment]
Hi @mdorchain ,

Thanks for letting me know. There was an issue with the pre-released version 1.3.69.17

If you got the chance, can you please try the updated pre-released version:
https://github.com/ultimatemember/ultimatemember/releases

Regards,

**Comment by mdorchain** [comment]
Still the same with 1.3.69.18. :(

The redirect to the user profile and the to automatic login are still happening despite the role registration settings "admin review".

Michael

**Comment by champsupertramp** [comment]
Hi,

I reverted back the changes made in admin review message:
https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.69.21

 `The redirect to the user profile and the to automatic login are still happening despite the role registration settings "admin review".`  Does this happen when using one registration form on a page?

I tested on our test sites and it works fine.

Regards,
