### ISSUE TITLE
forgot password link redirects to /login/

### ISSUE THREAD

**Issue by jasongolod** [ultimatemember/ultimatemember#167]
Hi gang,

I just updated to ...69.19 and that fixed the /register/ page redirecting to /login/.  However, two issues that are related seem to exist:

1) /password-reset/  still redirects to /login/. 
2) Using the register page shortcode in another page redirects to /login/ (not sure if that is by design or not)

Thanks for your help.

**Comment by champsupertramp** [comment]
Hi @jasongolod,

Thanks for letting us know. Can you please check the /password-reset/ page has the UM Access settings enabled?

Regards,

**Comment by jasongolod** [comment]
Thanks for the quick reply. UM custom permissions were disabled. Enabling for logged out users makes everything work as expected

**Comment by champsupertramp** [comment]
Hi @jasongolod,

Thanks for letting us know. Please check pre-released version 1.3.69.20. I've pushed fixes to the custom access settings issue.

https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v1.3.69.20

Regards,

**Comment by jasongolod** [comment]
updated to 1.3.69.20

I need to enable UM custom permissions to keep /password-reset/ page from redirecting to /login/.

**Comment by champsupertramp** [comment]
Hi @jasongolod ,

What's your current Global Site Access? 
Go to UM > Settings > Access > Global Site Access

If it is set to `Site accessible to logged in Users`, you will need to exclude Password Reset page in Access > Exclude the following URLs or enable the access settings of that page.

Regards,

**Comment by jasongolod** [comment]
I was set to 'loggd in users'.  That cleared it up.   Sorry for crying wolf. Thanks

**Comment by champsupertramp** [comment]
Thanks for letting us know. Closing this now.
