### ISSUE TITLE
Issue with latest version of UM - No way to get all users using get_members()

### ISSUE THREAD

**Issue by wpdelighter** [ultimatemember/ultimatemember#169]
Issue with latest version of UM - No way to get all users using `get_members()` . By default, now it returns the number of users set for pagination. 

https://github.com/ultimatemember/ultimatemember/commit/a85a687ba7f78c45af2777535e1e67cbe3dd1104#commitcomment-18973696

**Comment by champsupertramp** [comment]
Hi @wpdelighter,

Please see my reply:
https://github.com/ultimatemember/ultimatemember/commit/a85a687ba7f78c45af2777535e1e67cbe3dd1104#commitcomment-18975995

Regards,

**Comment by wpdelighter** [comment]
Sorry @champsupertramp , I was away and didn't get time to check. 

I will let you once I check it. 

Thanks for quickly looking into the issue and patching !!
