### ISSUE TITLE
Initial test feedback

### ISSUE THREAD

**Issue by paaljoachim** [ultimatemember/ultimatemember#17]
Hey

I have feedback from the point of having installed the plugin to checking out various settings.

Feedback

I noticed the rating at https://wordpress.org/plugins/ultimate-member/
Which is awesome!

Getting Started screen.

Automatically installed pages and Getting started

Add some thumbnails showing what the screens look like. As the user will right away get a visual view of the structure.

What about a section right below that says where to go next.
Hand holding the user to what they need to do.

Go now to…..and do this…..
Guide the user….

I went to the first section mentioned the Dashboard. 
There were two messages:
1. Registration is disabled. Please go to the general settings page in the WordPress admin and select anyone can register. Hide this notice

2. Allow Ultimate Member to track plugin usage? Opt-in to tracking and our newsletter and we will immediately e-mail you a 20% discount which you can use on any of our extensions. No sensitive data is tracked.
Allow tracking Do not allow tracking

Clicked Allow tracking
Clicked the general settings link and turned on Membership checkbox Anyone can register.

Out of fear of losing the getting started section I clicked the back arrow in the browser to go to the next getting started link - Settings - and thankfully it opened in a new tab.

Interesting how you guys have selected on adding tabs to the left of the screen instead of the default on the top using standard WP tabs. Your version looks really nice.

Ultimate Member Settings
Setup

Looks good. Pages were automatically created I remember reading. (I still do not know what they look like.)
Nice to see you also have reset buttons to return to the default.

Users

Default New User Role. 
Member or Admin. My feeling is that there should be other default roles as well.

Profile Permalink Base.
Interesting! Very nice!

User Display Name. 
Nice!

Automatically redirect author page to their profile?
The question that arises where does the NO option lead to? 
Third option based on role type or user would be to redirect user to content they have access to.
(Right now I do not think you guys have content restriction levels yet.)

As in creating content based on different levels of membership, or based on user. Meaning one could have unlimited content levels. Each user has access to specific user content.
One could create a site based on customer content restriction.
An example:
I have a friend who has a company where they fly drones to take high resolution video and images for various clients who need an overview of a building, road etc. Adding the video and images to a customer restricted part of the site would be really good.

Enable Members Directory?
Right now I am not sure what this is. Meaning I will keep it on until I see a screenshot of what it is.
Then I will find out if I need it or not.

Use Gravatars?
Good

Require a strong password?
Just a little adjustment of the wording here:
“Enable or disable a strong password rules on password reset and change procedure”

Enable or disable strong password rules on password reset and change procedure
I removed the “a”, but wording could also be done a little easier here.
Something like..
Force strong password rules on password reset and change procedure

Account

Password Account tab
Not sure what this looks like….
Link to a screenshot would be nice…

Privacy Account tab.
Link to a screenshot would be nice…

Notifications Account tab
Link to a screenshot would be nice…

Delete Account Tab
Link to a screenshot would be nice…

Account Deletion Custom Tex
Good!

Add a First & Last Name fields
Fine

Allow users to change e-mail
Interesting! Good!

Require a strong password?
Fine

Access

Panic Key.
Very good!

Global Site Access
Another option could be: content restricted to individual user

Allow Backend login screen for Guests
Not sure right now what this does….

The rest of the options under this section seem alright. I was pulled away and need to go quicker through the various options….

Emails

Account Welcome Email and Account Activation Email and Pending etc…
What about a TinyMCE content area??

A very detailed section.

Uploads
Looks good!

Appearance

Is about visuality. Here it would be good to have a way to visually see the change as one makes it. 
Improving in on screenshot number 2 here: https://wordpress.org/plugins/popupally/screenshots/

Extensions
Jetpacks way or even better Site Origins widget bundle has a good way to turn on or off widgets.
https://wordpress.org/plugins/so-widgets-bundle/screenshots/

Ultimate Member can be used in so many ways. 

From a simple content restriction having each member login. Adjust their profile and see the content they have. All the way up to seeing other members profiles, messageboards (wall), extended profile and more.

Having a way to go simple/basic turning on or off features will really help alot in extending the use cases of how Ultimate Member is used.

**Comment by champsupertramp** [comment]
Thank you very much for your feedbacks!

Please do check the latest version 1.3.29.
