### ISSUE TITLE
Initiating form error for custom field

### ISSUE THREAD

**Issue by beingak** [ultimatemember/ultimatemember#170]
Hi,

I have added custom fields with um_after_register_fields hook

1) Can error handling be done with plugin hooks for these fields? I found it checks for metakey and it may not be possible. Please confirm.

2) How form error can be initiated for these fields, so that it does not save fields and show custom error text? I will manage the error handling with same hook um_after_register_fields.

Let me know if there is matter way to do this and thank you for this amazing plugin.

Arun

**Comment by champsupertramp** [comment]
Hi,

You can try the following code to append UM errors:
```PHP
global $ultimatemember

add_action("um_before_submit_form_post","um_mycustom_error", 10, 1);
function um_mycustom_error( $submitted ){  // $submitted = $_POST
   if( isset( $submitted["my_field_key_or_name"] ) ){  
    $ultimatemember->form->add_error( $field_key_or_name, $error_description );
  }
}
```
Regards,
