### ISSUE TITLE
Deleting members caused other problems

### ISSUE THREAD

**Issue by i2000s** [ultimatemember/ultimatemember#171]
Dear UM developers,

Thank you for the nice WP plugin, I have been enjoying it so far except for one annoying issue that I have no clue how to solve on the latest Version 1.3.71. The issue is that when I clicked on the Bulk Actions/Delete to some (15) spam members (grouped as preapproved  in my Community Role category who will need my approval), two things happened: 
1. Those deleted members disappeared on my current Users list, but there is still a Red number 15 showing alongside with the Users tab on the dashboard, which means they are still on the list who are waiting for approval. Now I have no place to find them out, as they have disappeared from the Users list.
2. I cannot change any current users' Community Role after deleting those users. If I do try changing one user's Community Role, the interface will immediately jump to the Front page of the website but nothing else happens. I can edit users' profile though, which won't change the user's community role. 

Let me know if you can reproduce this issue on your side and when will you fix this problem. Thanks!

**Comment by champsupertramp** [comment]
We indeed have the issue with new users count in red circle next to the «Users» section it won’t change and disappear even if you delete new users.

However, I couldn’t replicate issue with community role on our test site, you can change community role of new users without any issue.

**Comment by verysiberian** [comment]
The way I have found around this issue is to first reject those members if they are pending. If the unwanted members are active, then deactivate them. Do one of these and then delete them. They will then no longer show up in the red circle next to the Users section.

**Comment by i2000s** [comment]
@champsupertramp On the community role aftermath, the issue is on other users established before those deleted users. I have defined some community roles for them, but after deleting those new users, I cannot change the roles of old users any more. The page just jumps to the front page, and it seems there is a bug stopping me using UM. Did you try that?

@verysiberian Thank you for the workaround. I wish I can go back, but hopefully this can be fixed in the next UM release.

**Comment by champsupertramp** [comment]
Hi,

I created a new pre-released version 1.3.72 which has fixes to issue #1 

#2 - Is this on the front-end? I'm still not able to reproduce this issue. If possible, please provide screenshots?

Regards,

**Comment by i2000s** [comment]
For issue 2, it is in the dash board. It doesn't work when I change the community role on any users. See the screenshot before I click on the "Change" button. It will jump to the front page of the website after the click. 
![umcommunityrolechange](https://cloud.githubusercontent.com/assets/3915003/18523982/c9c670ce-7a73-11e6-8b50-374b40f76c05.png)

**Comment by champsupertramp** [comment]
Hi @i2000s 

After submitting the change `community role`, does it change user roles? 

It does change on our end but it is redirecting back to `/wp-admin/users.php` without the search filter. I'm working on this issue.

Regards,

**Comment by champsupertramp** [comment]
Hi @i2000s,

Please check pre-release version 1.3.72.2
https://github.com/ultimatemember/ultimatemember/releases

Let me know if you're still encountering issues.

Regards,

**Comment by i2000s** [comment]
@champsupertramp I can confirm the following:

1. When I delete a new users, it works as expected -- the user got deleted, and no red circle shown on the dashboard afterwards.

2. Changing the `Community Role` for a user works without the search filter. However,

3. If I search a user first and then change the `Community Role` of the user, it will be directed to the `/wp-admin/users.php` and then the front page. Nothing got changed.

Thank you for working on solving it immediately.

**Comment by champsupertramp** [comment]
Hi @i2000s ,

If you say `front-page`, is it the /wp-admin/ or the www.yoursitedomain.com/ page?

Regards,

**Comment by i2000s** [comment]
cquic.unm.edu website front page.

**Comment by champsupertramp** [comment]
Hi @i2000s,

Are you also changing the current account's community role? 

Can you please provide a link to your register page? I will register and then ask you to allow that account to access wp-admin so i can investigate?

Regards,

**Comment by i2000s** [comment]
@champsupertramp Please register at http://cquic.unm.edu/register/. I will be waiting for your message. Thanks!

**Comment by champsupertramp** [comment]
Hi @i2000s ,

I registered on your site. Username is `umdevv`.

**Comment by i2000s** [comment]
@champsupertramp Approved. 　I will need to go now. Let me know if you find any solution. I will check back tomorrow morning. Thanks.

Regards,
i2000s

**Comment by champsupertramp** [comment]
Hi @i2000s 

I'm not able to login with `umdevv` /  `umdevv@cquic.unm.edu` as username/email.

I registered a new one. Please approve the account with username `umdev_test`.

Regards,

**Comment by champsupertramp** [comment]
Sorry, it was `umdevvv`. I'm able to access now.

**Comment by i2000s** [comment]
Unfortunately, I just deleted `umdevvv`. Please use the other one. Sorry about that.

**Comment by champsupertramp** [comment]
Hi @i2000s,

I tested and it redirects me to the front-page. Can you please do a plugin conflict test?
http://docs.ultimatemember.com/article/96-how-to-do-a-plugin-theme-conflict-test

Regards,

**Comment by i2000s** [comment]
@champsupertramp We haven't got a chance to do the plugin conflict test, and may not find such a chance recently as our website is having a lot of global visitors for a conference in Oct. Since other related issues have been fixed in the UM prerelease and the conflict test may not be useful to find errors in UM, I suggest to close this issue for now. I will report back if the future conflict test results in any bugs related to UM. Thanks!

**Comment by champsupertramp** [comment]
Let me know if you're still encountering this issue in the pre-release version.
