### ISSUE TITLE
Recent updates to registration forms (specifically role) caused a catestrophic meltdown of our site

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#172]
Not sure when this happened, but at some point over the last 2-3 weeks one of the updates you sent out created a meltdown in our registration process..

Here's the details on what's happening:

Our registration form has a `role (dropdown)` which allows the user to select one of two roles: `general-member` or `em-resident`. This has worked well for us.

Recently, we've been getting complaints saying users could not register. After investigating, I found that when I selected `em-resident` as the role, it would trigger the Security Warning `wp_die()` ([defined here](https://github.com/ultimatemember/ultimatemember/blob/37354a5eae2ffe4d9be5ddadc8be04eb462072a8/core/um-form.php#L128)). I thought that was odd, so I looked into it further.

I then found that, for reasons unbeknownst to me, the plugin is now keying the `em-resident` option as `1169-autosave-v1`. 

![image](https://cloud.githubusercontent.com/assets/5240018/18497888/255b6d14-7a00-11e6-8dc0-6d4247be4bce.png)

I imagine that this is the reason for the security warning: `1169-autosave-v1` isn't a defined role on our site. So, naturally, that would trigger the `wp_die()`.

Any suggestions you might have are greatly appreciated. Our site has just over 3500 active users, so if this issue could be elevated, I would also appreciate it.

Thanks so much.

CC: @cgaafary

**Comment by champsupertramp** [comment]
Hi,

Have you tried version 1.3.71?

Regards,

**Comment by dsifford** [comment]
@champsupertramp Is that a beta release? We're using the latest build now.

**Comment by dsifford** [comment]
The site is www.aliemu.com if you'd like to play around with it yourself.

**Comment by champsupertramp** [comment]
Hi @dsifford 

I registered on your site with a username `umdev`. Can you please allow the account to access wp-admin? I'll investigate the issue.

Regards,

**Comment by champsupertramp** [comment]
Hi,

Can you please try pre-released version 1.3.72?
https://github.com/ultimatemember/ultimatemember/releases

Are you able to give me a temporary admin access with the account i created earlier?

Regards,

**Comment by dsifford** [comment]
@champsupertramp Thanks so much. The pre-release does indeed fix the issue.

You're a lifesaver 👍

**Comment by champsupertramp** [comment]
Thanks for letting us know. Fixes will be included on the official release.

I'm closing this issue now.
