### ISSUE TITLE
Add 'password change'/'password reset request'/email changed' notifications

### ISSUE THREAD

**Issue by vovodroid** [ultimatemember/ultimatemember#175]
When user performs 'password change'/'password reset request '/email changed' actions it would be good to send notification to site admin.

Or other option - just to add option like "BCC all user emails to Admin".
Such emails should also contain user IP address.

Regards.

**Comment by ultimatemember** [comment]
We dont have any plans to add this feature to plugin at this time. Best to hire a developer to write this custom functionality for you if you need it now. Thanks.
