### ISSUE TITLE
Predefined Fields "country" and "languages" are not translatable

### ISSUE THREAD

**Issue by pyrog** [ultimatemember/ultimatemember#18]
```php
			case 'countries':
				$array = array (
							'AF' => 'Afghanistan',
							'AX' => 'Åland Islands',
							'AL' => 'Albania',
```
… should be:

```php
			case 'countries':
				$array = array (
							'AF' =>__('Afghanistan','ultimatemember'),
							'AX' => __('Åland Islands','ultimatemember'),
							'AL' =>__('Albania','ultimatemember'),
```
[/core/um-builtin.php#L1109](https://github.com/ultimatemember/ultimatemember/blob/1c4ca1802cb71f169018ffbe60052c7300160133/core/um-builtin.php#L1109)
[/core/um-builtin.php#L1298](https://github.com/ultimatemember/ultimatemember/blob/1c4ca1802cb71f169018ffbe60052c7300160133/core/um-builtin.php#L1298)

Also, you store language name in usermeta `languages`
```php
a:2:{i:0;s:6:"German";i:1;s:6:"French";}
```
Could you, please, store only language code ?
:bulb: Why not storing only LC separated by a simple char: `de;fr`

And a lot of messages are not translatable too: 
```php
	function unique_field_err( $key ){
		global $ultimatemember;
		if ( empty( $key ) ) return 'Please provide a meta key';
		if ( isset( $this->core_fields[ $key ] ) ) return 'Your meta key is a reserved core field and cannot be used';
		if ( isset( $this->predefined_fields[ $key ] ) ) return 'Your meta key is a predefined reserved key and cannot be used';
		if ( isset( $this->saved_fields[ $key ] ) ) return 'Your meta key already exists in your fields list';
		if ( !$ultimatemember->validation->safe_string( $key ) ) return 'Your meta key contains illegal characters. Please correct it.';
		return 0;
	}
```

Please, could you update it ?
Thanks

**Comment by champsupertramp** [comment]
Hi @pyrog 

We are working on the internalization support with WPML. Please see the latest version.

Thank you for your recommendations.
