### ISSUE TITLE
Add Age Filter for Members Directory

### ISSUE THREAD

**Issue by sbskamey** [ultimatemember/ultimatemember#186]
It would be great if you can add an age filter to the members directory. e.g search 18-25 years old.

Age filter is the only filter that is not available,

**Comment by kishoresahoo** [comment]
@sbskamey @champsupertramp Please check this 
https://shop.opentuteplus.com/product/ultimate-member-age-filters/ (free)

**Comment by sbskamey** [comment]
Something like this would be great - has this plugin been trusted and verified by UM?

**Comment by kishoresahoo** [comment]
Hey I am the developer behind it. Well it is free and you can give a try sometimes.

**Comment by sbskamey** [comment]
@kishoresahoo Hi, I have installed the plugin, but unsure how to actually apply it?

**Comment by sbskamey** [comment]
@kishoresahoo @champsupertramp Doesn't work for me I'm afraid. Image attached.

<img width="922" alt="screen shot 2016-10-05 at 12 20 51" src="https://cloud.githubusercontent.com/assets/22370316/19111243/6f63bf22-8af6-11e6-827f-d90eb76ee5ed.png">

**Comment by sbskamey** [comment]
Also unsure how it's actually applied as option does not show up in Search Options. Also only appeared on one search directory, and not the other.

<img width="575" alt="screen shot 2016-10-05 at 12 13 57" src="https://cloud.githubusercontent.com/assets/22370316/19111304/d0b7c516-8af6-11e6-9e39-db6f7d3fbfbe.png">

**Comment by kishoresahoo** [comment]
Have you added age fields to profile and added some ages?

**Comment by sbskamey** [comment]
I have the UM Birth Date fields that I'm using

**Comment by sbskamey** [comment]
@kishoresahoo I am using the UM Birth Date fields - is that correct? See image attached.

<img width="760" alt="screen shot 2016-10-08 at 09 11 47" src="https://cloud.githubusercontent.com/assets/22370316/19211563/52ee5a4e-8d37-11e6-8c05-e980de0db304.png">

**Comment by kishoresahoo** [comment]
ahh, I will give  look on it. Seem like a bug.

**Comment by sbskamey** [comment]
@kishoresahoo Thanks so much.

**Comment by sbskamey** [comment]
Hi @kishoresahoo is this working correctly now? Would love to add this to my site as soon as possible. Thanks!

**Comment by kishoresahoo** [comment]
@sbskamey We are planning to do a total rewrite and will be coming as paid add-on. thanks

**Comment by sbskamey** [comment]
Hi @champsupertramp would be great if UM can look into this feature. I don't see why an age filter should be a paid add on when all the other filters are standard. Thanks

**Comment by zaxpetkov** [comment]
Hi.Az I sewed problem and did not understand how it decided?
