### ISSUE TITLE
Repository is behind WordPress SVN repository

### ISSUE THREAD

**Issue by egifford** [ultimatemember/ultimatemember#19]
Hi, this is a great plugin! We're using it (along with the premium extension bundle) to build an association website.

We've patched a few things related to issue #7 and would like to share the code with a pull request.

We're coding against the latest version of the plugin (1.3.19), but that isn't available here.

Could you push your latest code and tags up to this repository?

Many thanks!

**Comment by ultimatemember** [comment]
Can you post the code on a gist or something so I can check it please?

**Comment by egifford** [comment]
Here is a gist: https://gist.github.com/egifford/12e19ff26821c5c5893d

This is kind of a hack, but it is working for us.  I think a better solution would be to use WordPress's AJAX mechanism like was done in the rest of the plugin, but I'm not sure how to start that.

I left a lot of comments in there.  I would normally cleanup that up for a pull request.  Let me know if you need that.

The basic idea is that um-file-upload.php and um-image-upload.php need to know exactly where WordPress is installed so they can call wp-load.php.  So let's tell them!

I added some code to um-enqueue.php in the wp_enqueue_scripts() function to attach a GET parameter to the URLs of the two upload scripts.  The attached parameter is the location of WordPress.

The two upload scripts then attempt to access that parameter and use it to load wp-load.php.  If the parameter is missing, the upload scripts default to the lookup logic that was already present in the code.

There are probably some security issues here, i.e. loading code based on a GET parameter.

Thanks for this plugin, we're having a good time using it.  We also purchased your add-on package.

**Comment by champsupertramp** [comment]
Updated the repo. Please check the latest version. Thank you

**Comment by egifford** [comment]
Thanks! This is great.
