### ISSUE TITLE
Overriding template defaults in shortcode?

### ISSUE THREAD

**Issue by denised** [ultimatemember/ultimatemember#191]
I'm trying to make sense of these lines from function `load` in um-shortcodes.php:

```
// get data into one global array
$post_data = $ultimatemember->query->post_data($this->form_id);
$args = apply_filters('um_pre_args_setup', $post_data);   // [1]
...
$args = array_merge($post_data, $args); // [2]
```

In line [1], the original `$args` passed to the function `load` is overwritten by the result of filtering `$post_data`, which would seem to make line [2] pretty pointless.

I want to pass an argument to ultimatemember shortcode that would override the default for that form (in this case, I want a custom redirect).   It seems to me that if line [1] were to look like this:

```
$post_data = apply_filters('um_pre_args_setup', $post_data);
```

then the `array_merge` in line [2] would make sense, and I would get exactly what I want.

Does this make sense?   Is it perhaps what was originally intended?

**Comment by champsupertramp** [comment]
Hi @denised 

Have you tried the following action hooks:
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-shortcodes.php#L313-L317

and this filter hook?
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-shortcodes.php#L302

Regards,
