### ISSUE TITLE
Add Profile Picture to Registration Form

### ISSUE THREAD

**Issue by sbskamey** [ultimatemember/ultimatemember#193]
It would be great If you could add a Profile Picture to the Registration Form. This is so that I can make it compulsory for new members to have a profile picture.

**Comment by champsupertramp** [comment]
This is possible in the pre-release version. You just need to use the custom code in the link to allow profile/cover photo upload: 
https://gist.github.com/champsupertramp/6b73195db24eb6650a23b4440b4287c3

Regards,
