### ISSUE TITLE
Bug in Multisite Webseites -> Edit -> Users

### ISSUE THREAD

**Issue by danielhuesken** [ultimatemember/ultimatemember#194]
Hello,

we have found a bug weh you use UM in a Multisite. IF ypu in Network -> Webseits and Edit one site and go to Users Tab. Than You can’t add a user too the side with the Form under the users list.

The Problem is that ther in the hidden id filed stands a post id and noct a site id.

I have found out that the problem is in the UM_Query::get_roles() method. Ther you use a WP_Query with setup_postdata(). The setup_postdata() sets the globel $id to the post id. And the admin site uses the same gilbel $id for site id.

I think a simple bugfix can be the usage of get_posts() for that or usesing the results directly without setup_postdata().

See:
https://wordpress.org/support/topic/bug-in-multisite-webseites-edit-users/

**Comment by champsupertramp** [comment]
Merged. Thank you
