### ISSUE TITLE
WPCLI blocked by Call to a member function get_meta() on nul

### ISSUE THREAD

**Issue by Just-Ghali** [ultimatemember/ultimatemember#198]
Every time we try to run a WPCLI command with the ultimate member plugin installed we get:

`PHP Fatal error:  Call to a member function get_meta() on null in /wp-content/plugins/ultimate-member/core/um-actions-access.php on line 99`

We are running ultimate member Version 1.3.71

**Comment by hcarsten** [comment]
Hi,
just had a similar issue and solved this by adding this : 

global $ultimatemember;
in file um-init.php, line 226, just before the "$ultimatemember = new UM_API();"

**Comment by champsupertramp** [comment]
Hi,
 
Please try the pre-release version in the link:
https://github.com/ultimatemember/ultimatemember/releases

Let us know if this resolves the issue.
