### ISSUE TITLE
Activation account link contains user id

### ISSUE THREAD

**Issue by vovodroid** [ultimatemember/ultimatemember#199]
Currently this link contains Wordpress user ID, that is quite insecure thing.
https://example.com/?act=activate_via_email&hash=KuBNS66c7h0SvK4pqi6ZTnTR1ES2hTl1INySe7NQ&user_id=15

Is there any way to hide it? For instance fetch user id by hash inside [activate_account_via_email_link](https://github.com/ultimatemember/ultimatemember/blob/master/core/um-permalinks.php#L153) function?

Regards.

**Comment by calumallison** [comment]
Hi,

We'll discuss this as a team and see if there is anything that can be done for UM 2.0.

Thanks
