### ISSUE TITLE
No way to clean submitted data

### ISSUE THREAD

**Issue by hcarsten** [ultimatemember/ultimatemember#202]
We had added some extra data to the registration form which needs to be secured. I did not found anything in the registration process where I can filter the registration data. So the sensitive data is showing up in the "submitted" meta_key.

just added a short hack into core/um-user.php, method set_registration_details() : 

+ $submitted = apply_filters('um_before_save_filter_submitted', $submitted);
+ do_action('um_before_save_registration_details', $this->id, $submitted );

best

**Comment by champsupertramp** [comment]
Hi,

Added this in the pre-release version:
https://github.com/ultimatemember/ultimatemember/releases

Thank you,
