### ISSUE TITLE
Function doesn't work with a site URL with port

### ISSUE THREAD

**Issue by hudson6666** [ultimatemember/ultimatemember#204]
The function ` $ultimatemember->permalinks->profile_url()` doesn't work well when I run the wordpress on a host with ports. However, my wordpress global URL settings are correctly set with port and most of the links in my wordpress work ok.

For example, my wordpress runs at 127.0.0.1:8000, and it redirect to some URI at 127.0.0.1 while clicking some links.

I have already found this problem occurred to 
- The profile/posts/comments icon links on profile page
- Update my profile menu link on profile page
- Log out link

**Comment by champsupertramp** [comment]
Hi,

Have you turned on this option "Allow Port forwarding in URL" in Admin > UM > Settings > Advanced?

Regards,

**Comment by hudson6666** [comment]
You're right, I didn't turn on that option. I turned it on and it did work. So sorry to bother you about that.

To be honest, I didn't have thought, or actually, I don't think this should an advanced option. In fact, I think this is a frequently used option. So I wish (if there's no security concern) you could set this option on as default or put it to somewhere conspicuous.

Thank you so much.

**Comment by champsupertramp** [comment]
Thanks for letting us know.
