### ISSUE TITLE
Warn and Ban users.

### ISSUE THREAD

**Issue by Cyberdemon87** [ultimatemember/ultimatemember#205]
Hello.
I’m running into some trouble with banning users with the functionality of UM.

If I want to ban a user and put his email on the “Blocked Email Addresses” in the UM access options, he can still login using his username.
Here are some suggestions which I think will please everyone using UM.

First of all, add a field “Blocked Specific Users/Usernames” so we can add usernames there.
I think this is critical, because the way it is now, it really doesn’t make any sense.
And setting the “Blocked IP Addresses” as an alternative doesn’t save it either, since most people have dynamic IPs so with one reset on their router, they are back. Many people nowadays use proxies/VPN also.

Secondly, have the option to somehow warn users that they will get banned if they continue to behave like that (whatever this may be in each case) before you ban them to give them a chance first.

And last, have 2 kind of bans. A “light” one, that will ban the user for a specific period of time (for example 1 day) and a ban hammer that will ban him permanently.

I think these are good suggestions, if they are possible to achieve, and can help maintaining a healthy community site built with UM, since UM is built for this reason.
You could even have all this as a paid extension if it works.

Please let me know what you think and also if there is anything of the above I can do for now on my site, at UM’s current state.

**Comment by calumallison** [comment]
Thanks for the suggestion. We will discuss this with team. In future best to suggest features directly via our website :)
