### ISSUE TITLE
Reload current page after Logout

### ISSUE THREAD

**Issue by Cyberdemon87** [ultimatemember/ultimatemember#206]
I display the UM login form in a text widget with the UM shortcode and there is the logout link there if you are logged in.

As you know, logout for UM works as a page, for example:
site.com/logout

And when clicked, it’s programmed to logout the user and redirect him to the homepage.
What I wish to achieve, is to stop this redirection to the homepage and just reload the current page the user is at the time when he clicks on logout.

I do not wish to redirect to the homepage or a custom url.

Maybe if you can add the option "Refresh active page" that you have for "Action to be taken after login" to the "Action to be taken after logout", this could work?

![um](https://cloud.githubusercontent.com/assets/20409743/20220839/c2839dd6-a837-11e6-95a3-a6b4a9919b2c.JPG)

Please let me know.
Thanks!

**Comment by calumallison** [comment]
Thanks for the suggestion. We will discuss this with team. In future best to suggest features directly via our website :)
