### ISSUE TITLE
WPML support for select dropdown and multi-select choices

### ISSUE THREAD

**Issue by ultimatemember** [ultimatemember/ultimatemember#212]
Currently UM does not properly localise the choices when switching language. Happens with both normal dropdown and multi-select dopdown.

**Comment by champsupertramp** [comment]
One of our users used WPML strings translation add-on for this scenario.

**Comment by poripa** [comment]
I have applied this fix and solved the problem. See the link below. Credits to @dymitar. 
https://wordpress.org/support/topic/issue-with-wpml-and-translated-strings/

**Comment by champsupertramp** [comment]
Hi @poripa, 

Have you tried the latest version 1.3.82? It has fixes to this issue.

Let me know if you're still encountering issues without changing anything in the core plugin.

Regards,
