### ISSUE TITLE
Compatibility with SSL site certificate

### ISSUE THREAD

**Issue by i2000s** [ultimatemember/ultimatemember#213]
Hi,

I am switching my website from `http` protocol to `https` protocol, but I found the UM plugin and UM-google-recaptcha plugin use some hard-coded `http` links to call style files and so on which makes the site look wired and have mixed content. I am not sure how to fix those hard-coded links. Because even I can replace them by hand, the future updates of the plugins will rewrite those links again, I think. Could anyone provide some workaround or fix this problem on the UM plugin itself? 

Thanks,
Qi

**Comment by champsupertramp** [comment]
Hi @i2000s can you pleaes provide a list of those styles files?

Regards,

**Comment by i2000s** [comment]
NVM, we fixed this issue by using the [SSL Insecure Content Fixer plugin](wordpress.org/plugins/ssl-insecure-content-fixer). I don't remember exactly which links broke the SSL certificate, but I think there were places calling the theme with `http`. Sorry, I cannot go back and check it again. Feel free to close this issue as this has been fixed by using external tools--though not ideal. Thank you!

**Comment by champsupertramp** [comment]
Thanks for letting us know. I am closing this issue now.

**Comment by chriseckman** [comment]
@i2000s Where were you getting the issue? I found that the plugin fixed it, however with the profile images on the notifications, it would break.

**Comment by i2000s** [comment]
@chriseckman I encountered this issue when I turned on SSL on our Wordpress website. As you have also observed, the `http` links were mostly called on profile images and CSS style files. Beside using the plugin I mentioned earlier, I think I had also manually changed some links where `http` was used on the header of templates within my customized theme. I am not sure where do you see the "notification breaks". Double check where the `http` links were called using the `inspect elements` function of Chrome, for example, and try fixing the rest manually. Good luck!

**Comment by chriseckman** [comment]
@i2000s yeah, I just fixed it, ran a search and replace on the notifications table to swap out the http with https profile images.
