### ISSUE TITLE
Datepicker and checkbox fields need focus css

### ISSUE THREAD

**Issue by ultimatemember** [ultimatemember/ultimatemember#214]
When datepicker is highlighted the input itself does not have any focus styling (odd UX) and this also apply to checkbox/radio fields.

**Comment by champsupertramp** [comment]
Pushed fixes to Datepicker highlight/focus issue. 
https://github.com/ultimatemember/ultimatemember/commit/4fd9e852effa43086ded4d746f5f3dd593f33f8f

Checkbox/Radio fields already have the CSS on focus. Please see the attached image below:

![um-form-highlights](https://cloud.githubusercontent.com/assets/12200688/21133148/7484fc0e-c152-11e6-8cb1-aebc1329bfb3.png)

**Comment by sharadkk** [comment]
I am using Ultimate Member profile form on one of my wordpress websites. Strangely the date picker is not working well with my theme. Although when I return to default theme, it works. But when my installed theme is used, the date picker breaks down as attached.

![date-picker](https://user-images.githubusercontent.com/11190884/89638532-9ea71e80-d8c9-11ea-8d6a-5fa2e8f2d30b.png)
