### ISSUE TITLE
show profile tab by userid

### ISSUE THREAD

**Issue by myselfgaurav** [ultimatemember/ultimatemember#218]
i want to make shortcode that will show user details from user id .

something like [showdetail id=5][/showdeatils], will show exact page like http://momreps.com/user/username where username is username from user with id 5. please guide me way to do this

**Comment by champsupertramp** [comment]
@myselfgaurav 

Please check the link. You can add the code in your theme's functions.php
https://gist.github.com/champsupertramp/a1ed201cb05ff68bcecac4c7cd5b004b

example:
`[um_user user_id="1" meta_key="display_name" ]` - prints the display name of a user with ID set to 5

Regards,
