### ISSUE TITLE
NO CONFIRM for “Delete this user” ???

### ISSUE THREAD

**Issue by artmerk** [ultimatemember/ultimatemember#219]
As an Admin level, if I view a user profile, then click on the settings gear icon, there is an option to “Delete this user”.

When you click on the link (/user/some_dude/?um_action=um_delete&uid=7) there is NO confirmation dialog box or screen. This is very dangerous in my opinion! Can you please update or provide some custom fucntion or code here to fix this? thanks!

**Comment by champsupertramp** [comment]
Hi,

Please check the latest version 1.3.79. It has fixes to this issue. Ensure that you've clear site and browser cache before you test it as we've pushed fixes in the `assets/js/um.min.js` and `assets/js/um-account.js` files
