### ISSUE TITLE
Profile photo alpha channel is lost

### ISSUE THREAD

**Issue by pyrog** [ultimatemember/ultimatemember#22]
The uploaded picture is in PNG format with an alpha channel.
![logo accueil paysan](https://cloud.githubusercontent.com/assets/2158081/9601676/91fcb342-50a3-11e5-9251-7ee356f8fb75.png)

The computed picture is saved in JPEG format (without tranparency).

![profile_photo](https://cloud.githubusercontent.com/assets/2158081/9601667/85306bea-50a3-11e5-932c-edbf362d85d0.jpg)

**Comment by champsupertramp** [comment]
Please check the latest version
