### ISSUE TITLE
Loop with multiple mails when creating user

### ISSUE THREAD

**Issue by novalis111** [ultimatemember/ultimatemember#220]
Just tested with a fresh 4.7.1 wordpress + 1.3.79 UM Plugin. When creating user from admin the script ends up calling /wp-admin/user-new.php, sending a mail on each loop as configured in UM. My site fails at ~30 redirects, so user + admin get 30 mails each. Disabling UM solves the issue.

**Comment by champsupertramp** [comment]
Hi @novalis111,

Thanks for letting us know. This has been fixed in the pre-release version 1.3.80
https://github.com/ultimatemember/ultimatemember/releases

We will release another update today. Let us know if this resolves the issue.

Regards,

**Comment by novalis111** [comment]
Yes, that did the trick. Thanks for the fast fix!
