### ISSUE TITLE
Hardcoded redirects prevents plugin extending

### ISSUE THREAD

**Issue by n-for-all** [ultimatemember/ultimatemember#223]
Hi there,

i developed one of the plugins for ultimate member to submit the forms via ajax, frankly it would be nice if you could allow a little more to extend this plugin, for example, removing the hard coded redirects and use a filter there to return the value instead of redirecting, i created the plugin for one of my clients to submit login and register via ajax with some hacks and now he wants the whole ultimate member forms to be in ajax also and it is nearly impossible to make it work without removing each of your form functions action and copying the function code, then removing the hard coded redirects manually one by one.

A better solution would be creating a function with a filter inside to choose whether to redirect or return the value, this will allows plugins to return the value and capture the response and hence ajax can be integrated easily which is currently a essential part of todays web apps.

[Check Plugin](http://www.ajaxy.org/product/ajax-forms-for-ultimate-member)

Thanks.

**Comment by champsupertramp** [comment]
Hi,

Thanks for letting us know. Unfortunately, we are not able to do those major changes. I suggest that you create pull requests with the changes the you want so we can review them.

We'll discuss this as a team.

Regards,
