### ISSUE TITLE
Enable excluding specific users from directory view

### ISSUE THREAD

**Issue by erpol** [ultimatemember/ultimatemember#225]
It would be really useful for the admin to be able to exclude specific users from showing in a member directory, either for maintenance or testing purposes, to hide admin (which is not necessarily a member), to hide deactivated users, etc.

The logical place UI-wise would be in the member directory's settings page, just under "Only show specific users", a text area "Exclude specific users" - that would be neat and relevant. 

Thanks for your consideration,

RP

**Comment by calumallison** [comment]
Hi,

This is something we are considering adding in the future.

Thanks
