### ISSUE TITLE
Translation doesnt work

### ISSUE THREAD

**Issue by Patresko** [ultimatemember/ultimatemember#226]
Hello,

Multiselect and dropdown buttons in user profile doesnt use translated text from .PO files. These buttons are still in English even they are translated in to different language.

While I'm editing this fields I can see my desired language but after i saved all changes in profiles these fields are in english language only in user profile page.

**Comment by champsupertramp** [comment]
Hi @Patresko,

do you have a translation plugin installed on your site?

Regards,

**Comment by Patresko** [comment]
Yes I have. I'm using WPML but I guess that these two buttons using .PO files isnt it?

**Comment by champsupertramp** [comment]
Can you please provide screenshots?

**Comment by champsupertramp** [comment]
Can you please provide steps to recreate the issue, and if possible include screenshots?

**Comment by Patresko** [comment]
In this picture you can see user profile (preview mode not editing) that these two field are in English language
[url=https://postimg.org/image/h5nsp5hin/][img]https://s27.postimg.org/h5nsp5hin/Sn_mka.jpg[/img][/url]

In the second picture while I'm in edit mode I can see my translated language (Slovak)
[url=https://postimg.org/image/qrhd5g8of/][img]https://s27.postimg.org/qrhd5g8of/Sn_mka1.jpg[/img][/url]

**Comment by champsupertramp** [comment]
Hi @Patresko  can you please send me an email of temporary FTP and WP Admin access of your site?
here's the email address: support@ultimatemember.com

**Comment by Patresko** [comment]
Already sent

**Comment by champsupertramp** [comment]
Hi,

This has been fixed in https://github.com/ultimatemember/ultimatemember/releases/tag/pre-v.1.3.82.9

Regards,
