### ISSUE TITLE
can't search members with name containing '

### ISSUE THREAD

**Issue by pyrog** [ultimatemember/ultimatemember#23]
Search **médi'âne** but UM say that no members match **médi\'âne**

Similar as #21

**Comment by pyrog** [comment]
Also, when I edit the member name from UM form, it store `Médi&#039;âne`
The **single quote** shouldn't be encoded inside the DB ?

**Comment by champsupertramp** [comment]
We've pushed fixes to this issues. see the latest release.

ref: https://github.com/ultimatemember/ultimatemember/pull/26
