### ISSUE TITLE
No ALT on UM Avatar

### ISSUE THREAD

**Issue by amiremami** [ultimatemember/ultimatemember#230]
Hi 🙂
This link reports that there is no alt tag on the default UM image avatar. This is something I should add or you can fix it in next update?
http://www.contentforest.com/seo-tools/image-alt-checker

Thanks

**Comment by champsupertramp** [comment]
Hi @amiremami ,

Please try the pre-release version in the link:
https://github.com/ultimatemember/ultimatemember/releases

It has fixes to this issue.

Regards,

**Comment by tigredanky** [comment]
works

**Comment by champsupertramp** [comment]
Thanks for letting us know.

**Comment by amiremami** [comment]
Sorry for late reply champ, thank you so much for fixing this :)
