### ISSUE TITLE
UM-Messages JS and CSS Loading for Guest Visitors

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#231]
I've ran some page speed tests on GTMetrix and WepPageTest.org and see:

https://[siteurl]/wp-content/plugins/um-messaging/assets/css/um-messaging.css?ver=4.7.2
https://[siteurl]/wp-content/plugins/um-messaging/assets/js/um-messaging.js?ver=4.7.2

being loaded. can you please set these to only load for logged-in users as it needlessly bloats guest visitor experience? thanks.

**Comment by champsupertramp** [comment]
Hi @tigredanky,

This is for the Ultimate Member plugin only. Can you please submit a ticket to our paid support form? https://ultimatemember.com/paid-support/

Thank you,
