### ISSUE TITLE
Wall Posts Text Entry Field Small

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#232]
Comments for wall are super shrunk and minimized.

![screen shot 2017-02-05 at 4 41 48 pm](https://cloud.githubusercontent.com/assets/460065/22711282/6c9a8ed2-ed35-11e6-9bd2-d2271133e2b2.png)
![screen shot 2017-02-05 at 4 41 37 pm](https://cloud.githubusercontent.com/assets/460065/22711285/6f9be798-ed35-11e6-8c42-f6bbcfaa35ba.png)

**Comment by champsupertramp** [comment]
Hi @tigredanky ,

Please submit this issue on the Paid Support page: https://ultimatemember.com/support/

We only provide support for Ultimate Member core plugin in this repository.

Regards,
