### ISSUE TITLE
Admin Cannot Edit Fields

### ISSUE THREAD

**Issue by artmerk** [ultimatemember/ultimatemember#234]
Just updated to Version 1.3.82

Now, if a field is set to "Can user edit this field?" = No, the field is non-editable for both the user AND the Admin.

The Admin should be able to edit these fields still, correct???

See attached screenshot for example
![screen shot 2017-02-14 at 2 54 42 pm](https://cloud.githubusercontent.com/assets/22449748/22953322/8ca647c6-f2c5-11e6-85a3-ea615dc846f4.png)

**Comment by champsupertramp** [comment]
Hi @artmerk, 

Have you tried the latest pre-release version pre-v1.3.83.12?

Regards,

**Comment by artmerk** [comment]
Yes, this commit in pre-v1.3.83.12 fixes the issue:
https://github.com/ultimatemember/ultimatemember/commit/9cd3a6102b8103ee4193d997275bf089826c9f1b

thank you!
