### ISSUE TITLE
Message Pop Up Not Centered to Window's Dimensions

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#236]
When clicking the message button on a user's profile, the popup message box is not sitting in the center of the window.

![screen shot 2017-02-15 at 12 40 22 pm](https://cloud.githubusercontent.com/assets/460065/22994515/0d93ff52-f37c-11e6-9e8c-9af8a6ca5d30.png)
![screen shot 2017-02-15 at 12 40 02 pm](https://cloud.githubusercontent.com/assets/460065/22994514/0d923f00-f37c-11e6-92ea-dd00efb5e619.png)

**Comment by champsupertramp** [comment]
Hi @tigredanky,

Unfortunately, we cannot provide support for UM premium extensions. This repository is for the UM core plugin only. You can submit this issue in the link: https://ultimatemember.com/paid-support/

Regards,
