### ISSUE TITLE
Translation bugs

### ISSUE THREAD

**Issue by melbayad** [ultimatemember/ultimatemember#237]
Hello "Ultimate Member" community,
First of all, I would like to congratulate you for this amazing plugin.
I'm using UM version 1.3.82 and would like to use the same forms for each language (French and English), This is how I proceed  : 
1. I installed UM plugin, update settings and form fields (Login, Registration, Profile)
2. I activated Polylang plugin
3. I duplicated (Account, User, Members, Reset password, ...) pages for FR version
4. I donwloaded the ultimatemember-fr_FR .po and .mo files and placed them in the /wp-content/languages/plugins folder.

But I'm currently facing some translation bugs  : 
1. When I access to "User" page in FR, it works but when I switch to EN version I have this error : "_mywebsiteurl_ redirected you too many times."
2. In "Account" page, All links pointed to EN version instead of FR.
3. All form fields are populated in EN version, but in FR they are blank.
4. When I click on the crog button, I don't have 'Logout', 'My account' links.

I examined all the forum discussion about this matter with no luck. Can you please tell me what I am doing wrong ? Thanks in advance.

**Comment by Milehano** [comment]
I have the same problem It's really annoying 🤕

**Comment by calumallison** [comment]
Hi, can you please create a support topic on wp.org forum for this. We provide support via email (paying customers) and the wp.org forum (free users). Thanks! :)

**Comment by Milehano** [comment]
Hi, they told me to make a ticket here... :(

**Comment by missmatsuko** [comment]
@melbayad Did you ever find a solution for this? I am having the exact same problem. I saw a relevant support post [here](https://wordpress.org/support/topic/forgot-password-page-only-works-for-one-language/), but there's not solution there either...
