### ISSUE TITLE
Shortcodes Not Working in Post Content

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#240]
We've tried:  {first_name} {nickname} {display_name} in the page editor and it doesn't grab the logged-in user's data.

The menu is displaying it for the user profile using {display_name}, but not in the lower content.

We're using Elegant Theme's Divi builder, FYI.

![screen shot of rendered page](https://cloud.githubusercontent.com/assets/460065/23232355/c93e59a4-f8ff-11e6-9b3b-f0f859c32e1f.png)

**Comment by champsupertramp** [comment]
Hi @tigredanky,

Those are UM meta shortcodes. You can try this code to enable the shortcode function:
https://gist.github.com/champsupertramp/a1ed201cb05ff68bcecac4c7cd5b004b

Regards,
