### ISSUE TITLE
Suggestion: Allow for photos to be added to wall comments

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#241]
Allowing to upload a photo as a comment or in addition to a wall post comment would be sweet. Thanks.

**Comment by champsupertramp** [comment]
Hi @tigredanky 

We cannot provide support for UM extensions here.  You can submit this feature request in the link:
https://trello.com/b/30quaczv/ultimate-member-development-roadmap

Regards,
