### ISSUE TITLE
Change Placeholder Text for Password Re-entry Field

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#242]
Please have the confirmation password field placeholder say "Confirm [Label or Placeholder Text Value]"

![Second Password Field should say something different](https://cloud.githubusercontent.com/assets/460065/23385571/854f136e-fd05-11e6-8f1a-4445ada34077.png)

**Comment by calumallison** [comment]
Thanks for suggestion. Will discuss as team. In future best to suggest features via our website and not here. Thanks :)
