### ISSUE TITLE
Content Block on Profile Edit Screen Not Loading

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#243]
WYSIWIG Content Editor loads, but GIF animation of bouncing squares shows behind... 

This is on Admin Profile edit Form screen

![screen shot 2017-02-27 at 5 16 06 pm](https://cloud.githubusercontent.com/assets/460065/23387316/9ff78a6a-fd10-11e6-9e54-4d7fd5f7f979.png)

**Comment by denisbaranov** [comment]
@champsupertramp this ticket is fixed.

**Comment by jhthompson** [comment]
Currently having this same issue, what was the previous fix?
