### ISSUE TITLE
Issue Updating Account Information Custom Fields

### ISSUE THREAD

**Issue by elitzer2** [ultimatemember/ultimatemember#244]
I have added the custom fields I request on the registration form to the account page so users can update the details when they go to their account. However, I am having an issue where it says everything was successful yet nothing changed. I am adding the extra profile fields via a hook: [https://gist.github.com/champsupertramp/c1f6d83406e9e0425e9e98aaa36fed7d](https://gist.github.com/champsupertramp/c1f6d83406e9e0425e9e98aaa36fed7d)

If I take out `&& in_array( $k, $arr_fields )` in the below code from um-actions-account.php, then my custom fields are updated properly…

```$changes = array();
foreach( $_POST as $k => $v ) {
    if ( !strstr( $k, 'password' ) && !strstr( $k, 'um_account' ) && in_array(
        $k, $arr_fields ) ) {
        $changes[ $k ] = $v;
    }
}
```

I also noticed that the `$changes` variable in the `um_account_pre_update_profile` hook does not show anything changed unless I remove the above check. I have tried re-creating the custom fields after several UM plugin updates. I’ve deactivated/reactivated the plugin, I’ve cleared the cache, and have tried creating several users. I thought I had got this working by adding the following lines. However, it seems the issue has come up again.

Any ideas? I don’t want to alter the source code because it doesn’t persist through updates, or otherwise I wouldn’t mind keeping it this way. Thanks!

**Comment by calumallison** [comment]
Hi, can you please submit a ticket via our website (if paying customer) or create a topic on support forum (if free user). We only provide support via those two places.

Thanks!

**Comment by elitzer2** [comment]
I was told to open a ticket on GitHub on the forums.....

https://wordpress.org/support/topic/issue-updating-account-information-custom-fields/#post-8864840
