### ISSUE TITLE
invalid argument supplied for foreach() in core\um-admin-builder.php on line 132 + 53

### ISSUE THREAD

**Issue by bananakbb** [ultimatemember/ultimatemember#245]
Hello.
Installed UM, have newest version of PHP,WP,UM.
Want to change forms, have problem like that:
WARNING: invalid argument supplied for foreach() in C:\xampp\htdocs\wp-content-plugins ……………………….. core\um-admin-builder.php on line 132 + 53
If I fill everything from a new field, it is not stored. I also get no error message or anything i deleted UM, still the same. How can i get this to work?

**Comment by champsupertramp** [comment]
Hi,

Can you please try the pre-release version 1.3.84 in the link?
https://github.com/ultimatemember/ultimatemember/releases

Regards,

**Comment by davidpesce** [comment]
I'm getting the same error on v1.3.84

**Comment by champsupertramp** [comment]
Hi @davidpesce, 

Have you tried the pre-release version in the link?
https://github.com/ultimatemember/ultimatemember/releases

Can you please provide the following details?

- PHP version
- Is there a cache plugin/module installed on your site?
- List of all active plugins

This will help me investigate the issue further.

Regards,
