### ISSUE TITLE
"This is a translation of UM profile page" missed in Ultimate Member section

### ISSUE THREAD

**Issue by melbayad** [ultimatemember/ultimatemember#246]
Hello Ultimate Member team,

I'm translating my wordpress website in 2 languages (English and French) following this [tutorial](http://docs.ultimatemember.com/article/193-wpml-integration). I duplicated all pages (User, Account, Login, etc) but I didn't find "This is a translation of UM profile page" option to map these duplicated pages with UM ones.

Do you have any idea about this matter ? (Note that I'm using UM plugin free version)
Thanks all.

**Comment by champsupertramp** [comment]
Hi @melbayad ,

Do you have the WPML Multilingual CMS plugin?
https://wpml.org/version/

Regards,

**Comment by melbayad** [comment]
Hi @champsupertramp ,

No. I'm using [Polylang](https://polylang.wordpress.com/) plugin version 2.1.2.

**Comment by tomaszkoc** [comment]
Any possibility to get it working with Polylang?

**Comment by gautamgdeft** [comment]
yes i have wpml plugin

**Comment by denisbaranov** [comment]
Hi,
Options "This is a translation of UM profile page?" and "This is a translation of UM account page?" are placed into the "UM Content Restriction" metabox. You need to select "page" in the "Restricted Access to Posts" option to see it.
You don't need "This is a translation of UM profile page?" and "This is a translation of UM account page?" options if you don't restrict access to the pages.
