### ISSUE TITLE
Remove query strings from static resources

### ISSUE THREAD

**Issue by amiremami** [ultimatemember/ultimatemember#248]
Hi :)
I have this warning in gtmetrix for these images, in despite of I use a plugin for removing query strings. But still these avatars have query string. How to fix this?

https://www.ajibtarin.com/wp-content/uploads/ultimatemember/1/profile_photo-190.jpg?1489715945
https://www.ajibtarin.com/wp-content/uploads/ultimatemember/1/profile_photo-80.jpg?1489715945

Thanks

**Comment by champsupertramp** [comment]
Hi @amiremami,

You can use this filter hook to remove extra random number:
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-short-functions.php#L1385

Regards,

**Comment by amiremami** [comment]
Thanks a lot Champ. During optimization I had another issue:
https://wordpress.org/support/topic/7000-links-reported-404-in-google/

Not important, because I noindex and disallow all of them, just wanted to inform you.

Thanks again :)

**Comment by amiremami** [comment]
Hi again @champsupertramp 
My developer tried to use this function. He removed numbers and it changed like this:
https://dev.ajibtarin.com/wp-content/uploads/ultimatemember/1/profile_photo-190.jpg?1

I asked him to remove also ?1 , but he told me:

No, because for apply_filter function need minimum two arguments, if I remove user_id argument, in logs too much error messages

PHP message: PHP Warning:  Missing argument 2 for apply_filters(), called in /var/www/dev.ajibtarin.com/htdocs/wp-content/plugins/ultimate-member/core/um-short-functions.php on line 1385 and defined in /var/www/dev.ajibtarin.com/htdocs/wp-includes/plugin.php on line 176

Is this something you need to fix in the plugin or something is not working on my website?

Thanks

**Comment by champsupertramp** [comment]
Hi @amiremami, why not return an empty string?

**Comment by amiremami** [comment]
Ok, my developer changed it to "profile_photo-190.jpg?" But he couldn't remove the ? . 

Do you have any solution?

**Comment by champsupertramp** [comment]
Hi @amiremami,

Please try the updated pre-release version. We've fixed it:
https://github.com/ultimatemember/ultimatemember/releases

ref:
https://github.com/ultimatemember/ultimatemember/commit/0b996ecc2149e3332abf96c008013ccb5519cc66#diff-6b1bba33e40c8aeb3ee3cfd31f785065R1387
