### ISSUE TITLE
Warning - This plugin is not properly prepared for localization on https://translate.wordpress.org

### ISSUE THREAD

**Issue by Jimmi08** [ultimatemember/ultimatemember#249]
Hi, 
I've got this warning when I tried to find localization in my language.

https://translate.wordpress.org/locale/sk/default/wp-plugins/ultimate-member

![image](https://cloud.githubusercontent.com/assets/5429548/24139639/279c37fa-0e1d-11e7-85d8-526a660e4b4b.png)

By the way, where can I find other language files?

Thanks

**Comment by calumallison** [comment]
Hi, we will be making UM available for translation on wp.org soon. Thanks :)
