### ISSUE TITLE
i can't find Language File

### ISSUE THREAD

**Issue by nakamuraagatha** [ultimatemember/ultimatemember#25]
I'm not founded ultimatemember-en_US.mo on my plugin. and this repo not show that. can you add .po file?

**Comment by champsupertramp** [comment]
Hi, 

We are currently working on it and make it 100% functional with WPML.

I suggest to use the following codes in your theme functions.php and use the textdomain `ultimatemember` to make the plugin translatable:

```PHP
add_action( 'plugins_loaded', 'um_i18n_load_textdomain' );
/**
 * Load plugin textdomain.
 *
 * @since 1.0.0
 */
function um_i18n_load_textdomain() {
  load_plugin_textdomain( 'ultimatemember', false, get_template_directory(). '/languages' ); 
}

```

**Comment by nakamuraagatha** [comment]
thanks
