### ISSUE TITLE
Use WP_Http instead of curl

### ISSUE THREAD

**Issue by LaszloHont** [ultimatemember/ultimatemember#250]
Could ultimatemember use the WP_Http class intead of curl, then it will work with proxies?

http://planetozh.com/blog/2009/08/how-to-make-http-requests-with-wordpress/

**Comment by champsupertramp** [comment]
@LaszloHont can you please provide which code line in the plugin?

**Comment by LaszloHont** [comment]
It's used a few times in different places in the ReduxFramework directory

**Comment by LaszloHont** [comment]
and heavily in lib/u-mailchimp-api.php and lib/um-mailchimp-api-v3.php

**Comment by champsupertramp** [comment]
Hi @LaszloHont 

Unfortunately, we cannot modify those third-party librabries as we update them frequently from their respected respositories.

Regards,

**Comment by LaszloHont** [comment]
um-mailchimp is from you though

**Comment by champsupertramp** [comment]
Hi @LaszloHont, We are using a third-party library to handle the MailChimp API requests.
