### ISSUE TITLE
Automatically scroll down to profile

### ISSUE THREAD

**Issue by Cyberdemon87** [ultimatemember/ultimatemember#253]
Hello!

A simple (I think), but great functionality that is missing in Ultimate Member is to automatically scroll down to the profile section of About/Posts/Comments etc. each time the user visits the profile page and to not have to scroll down manually.

Do you think that is something that can be added in a future update?

And another irreleavent request. Any chance to have a favorites tab for posts or comments the user mark as favorites?

Please let me know.
Thanks!

**Comment by calumallison** [comment]
Hi,

Thanks for the suggestion. This will be discussed as a team.

Thanks
