### ISSUE TITLE
Two Column Registration Form Doesn't Work

### ISSUE THREAD

**Issue by tigredanky** [ultimatemember/ultimatemember#259]
I had a registration form that I duplicated from a working one column form and converted to a two column form, but when I would fill out the form and hit register, I'd get taken to the home page. One client was getting a nonce error. FYI
![screen shot 2017-04-04 at 7 55 16 am](https://cloud.githubusercontent.com/assets/460065/24663209/11f351dc-190c-11e7-8ed1-a67465567602.png)

**Comment by champsupertramp** [comment]
Hi,

Did you test it with a default WP theme?

Regards,

**Comment by tigredanky** [comment]
no, not yet. but can try.

**Comment by tigredanky** [comment]
Just tested it with WP 2017 and I was able to create an account using the two column registration page. Thanks!
