### ISSUE TITLE
Notification account tab turned ON, not displayed

### ISSUE THREAD

**Issue by lincle** [ultimatemember/ultimatemember#263]
https://wordpress.org/support/topic/notification-account-tab-turned-on-not-displayed/#post-9025834

Ultimate Member > Settings > account > Notifications Account Tab
Notification account tab turned ON, not displayed.

Password Account Tab, Privacy Account Tab, Delete Account Tab can be switched.
Disable all plugins except Ultimate Member.
Activate Twenty Fifteen theme.

I turned on Notifications Account Tab.
/account/general/

There is no Notifications Account Tab.

Update to latest version 1.3.84
Clear cache
Notification account tab is not displayed yet.

**Comment by champsupertramp** [comment]
Hi @lincle,

It only shows when you have UM extensions. If you have UM extensions, please submit this issue on our paid support page:  https://ultimatemember.com/paid-support/ 

Regards,
