### ISSUE TITLE
Filter in strong_pass validator

### ISSUE THREAD

**Issue by toszcze** [ultimatemember/ultimatemember#267]
I think the 'strong_pass' method of UM_Validation class should be refactored to have a filter to change the default validation conditions. I'm thinking about something like this after checking all the conditions:

`return apply_filters( 'um_validation_strong_pass', $result, $candidate );`

For example, I would like to force users to use one special character. I would also like to add minimum and maximum password length checks to this validator to avoid double validation error messages (first one when the password is too short, second one when the password doesn't meet the validation criteria).

I can create a pull request if you like.

**Comment by champsupertramp** [comment]
Hi @toszcze,

Thanks for letting us know. You can create a pull request and we'll check them out.

Regards,
