### ISSUE TITLE
Fixed version of pt_br translation

### ISSUE THREAD

**Issue by FabioZumbi12** [ultimatemember/ultimatemember#268]
Hi,

I have translated UM from em_us to pr_BR (with google tool) but i have fixed all bad words and wrong translations (as i know) and i want to share (and yes, i discarded the actual translation).

If yes, how can i send the pom files?

**Comment by champsupertramp** [comment]
Hi,

You can send a pull request so we can test and review.

**Comment by FabioZumbi12** [comment]
Oh, sorry.
I forgot to respond here. I didnt found the translations file, only english po file. Where i can create a file or change the string for my language?
