### ISSUE TITLE
Email templates did not translated

### ISSUE THREAD

**Issue by masimies** [ultimatemember/ultimatemember#270]
Translated email settings messages, but they have not translated to real email to new members.
Meanwhile i updated templates directly, and if someone else need these files, they are in attachment.
[emailtemplates.zip](https://github.com/ultimatemember/ultimatemember/files/992189/emailtemplates.zip)

In ZIP-file are included PO&MO language files also, witch are 46% of translated to fi language. Mostly those words what are visible to members.

**Comment by champsupertramp** [comment]
Hi,

You should use the HTML email templates so you can translate them.

Please read: http://docs.ultimatemember.com/article/121-using-html-in-e-mail-templates

Regards,

**Comment by masimies** [comment]
Ok,
So can not use html templates with multi-language purposes.

**Comment by sadiqodunsi** [comment]
Hi Matti, thank you for the email templates you posted here, it made my life easier as I don't understand Finnish yet and I'm building a website in Finnish with the help of a friend. 

I am having one problem though and I was wondering if you could help me out. I am not able to view a user profile when my site is in Finnish. It works fine in the default language which is English but when I switch to Finnish it doesn't work. Please help me.

**Comment by masimies** [comment]
Hi,
I think that your problem could be come from forms. Do not translate any meta-keys or use Finnish-values in options, like with groups. Keep your group names as default member and admin. Finnish-people knows what Member means :-)
By the way. I did my sites for languages as own subsite for every language. I'm having multisite environment. It's simplier for me, and there is no problems with database table values as well.

br,

-matti

**Comment by sadiqodunsi** [comment]
Thank you for your reply. I tried all your suggestions but it still doesn't work. However, when I changed the permalink settings on wordpress to plain (/?p=123), it worked. Although, I will like to use post name because plain permalink is not good for SEO. Do you maybe have any other suggestion for me?

**Comment by masimies** [comment]
Well, hard to say without seeing.
My permalink is /%postname%/ but how this could be make this effect.
In common settings. Site language. You have language as Finnish?
