### ISSUE TITLE
Sort members by multiple criterias

### ISSUE THREAD

**Issue by i2000s** [ultimatemember/ultimatemember#271]
Hi there,

I thought it would be nice to allow multiple sorting customized variables to order members shown on a member directory page. Currently, it seems only to allow one custom meta key to be used in sorting and then sorting members with the same meta key by their first names. In my specific case, I would like to sort members using at least one meta key and then their last names, and it seems impossible, currently. 

Did I miss anything or you can generalize this sorting mechanism to allow multiple meta keys? I am happy to test.

Thanks!

**Comment by calumallison** [comment]
Hi,

This is not currently possible with UM but will add to our user suggestion list for potential update to plugin.

Thanks
