### ISSUE TITLE
UM member visibility in multisite environment

### ISSUE THREAD

**Issue by masimies** [ultimatemember/ultimatemember#281]
Hi,
Noticed issue with WP-user account in multisite environment. Even that user is not member of any groups, the profile is visible in online-users widget when logged in. If there is many sub-sites with UM activated, online users are visible thru network, not only as current site users only.
Bad thing was that if the user is with admin-role rights (can edit other users profile) can open and edit any visible user profile thru online-users widget. Even that the user is super-admin.
Online-users widget is now unusable with multisite-installation due of this effect.

br,

-matti

**Comment by masimies** [comment]
Hi,
I can confirm that this was fixed now with new release.

br,

-matti

**Comment by champsupertramp** [comment]
Thanks for letting us know.
