### ISSUE TITLE
Commit version tags to repository

### ISSUE THREAD

**Issue by egifford** [ultimatemember/ultimatemember#29]
Related to issue #19:  Thanks for updating the repository with the latest code!

Any chance the version tags could also be committed?

Thanks!

**Comment by champsupertramp** [comment]
Hi @egifford , may i know what version tags?

**Comment by egifford** [comment]
I'm referring to the version numbers for Ultimate Member:
https://wordpress.org/plugins/ultimate-member/developers/

Most WordPress plugins on GitHub have git tags that match their versioned releases.

As an example, take a look at the GitHub project for Yoast SEO:
https://github.com/Yoast/wordpress-seo/tags

The Ultimate Member GitHub project actually did have these tags up until the recent refresh.  But I think the got removed by accident.

Having these versioning tags helps when someone is forking the project when we need to tweak the plugin in some way.  It allows us to explicitly "checkout" a particular version of the plugin.

Thanks for considering this.

**Comment by champsupertramp** [comment]
Hi, i've added the a version tag but i'm not sure how can i restore the previous tags as i was just added  a few weeks ago and unable to see the version tag history.
