### ISSUE TITLE
After new user registration, HTTP 500 error

### ISSUE THREAD

**Issue by NerdOfLinux** [ultimatemember/ultimatemember#292]
Whenever I test the register page on my website(Ultimate Member 1.3.87), I get redirected to a page that says my server is unable to handle the request HTTP error 500.

**Comment by champsupertramp** [comment]
Hi,

Can you please check for any PHP error logs?

Regards,

**Comment by NerdOfLinux** [comment]
The issue was a missing package on my Ubuntu server.

**Comment by champsupertramp** [comment]
Thanks for letting us know.
