### ISSUE TITLE
Updated version of pt-br

### ISSUE THREAD

**Issue by FabioZumbi12** [ultimatemember/ultimatemember#295]
Hi,
I didnt found other language files to update, then, i uploading here to you check and test.

[translationpt-br.zip](https://github.com/ultimatemember/ultimatemember/files/1127646/translationpt-br.zip)

**Comment by champsupertramp** [comment]
Hi Fabio,

You can now help us translate the plugin on the wp.org repository:
https://translate.wordpress.org/projects/wp-plugins/ultimate-member

Regards,

**Comment by FabioZumbi12** [comment]
I translated 99% of the plugin strings on this files. On that page i need to put string by string '-' Why not accept this file or only check and update/upload to that page using this file?

**Comment by Thiagoslds** [comment]
Olá! 
Agradeço a tradução, está me ajudando.
Mas no campo de Login, não está aparecendo o texto "Entrar", pode me ajudar? 

![Captura de tela de 2019-05-09 12-01-28 2](https://user-images.githubusercontent.com/50455727/57463921-22e79d80-7252-11e9-9143-ba6f756ebaa9.jpg)
