### ISSUE TITLE
Mail is not going

### ISSUE THREAD

**Issue by kmalviya-systango** [ultimatemember/ultimatemember#296]
I have installed ultimatemember in my project. On localhost with the help of wp-mail-smtp mails were going, when user register or when forgot password. But after deploying on godady host the mails stopped going. I have tried everything but mails are not going.

User are now registering on my website but they are not able to receive any mail.

Please help me, its very urgent as bussiness is affecting.

Thanks

**Comment by akshaygoyal88** [comment]
Getting same issue
ultimatemember version 1.3.84 and WP version 4.8

**Comment by champsupertramp** [comment]
@kmalviya-systango - what's the UM version installed on your site? Also, does your site have any SMTP plugin?

**Comment by champsupertramp** [comment]
@akshaygoyal88 - Can you please try the latest version 1.3.87?

**Comment by kmalviya-systango** [comment]
The issue is resolved after installing SendGrid plugin, https://wordpress.org/plugins/sendgrid-email-delivery-simplified/
