### ISSUE TITLE
logging in with email address does not work

### ISSUE THREAD

**Issue by sedrubal** [ultimatemember/ultimatemember#297]
When trying to log in using E-Mail address I always receive the error message

>Sorry, we can't find an account with that username

But signing in with username works as expected.

**Comment by sedrubal** [comment]
Ah I think the issue is that the label of the login field is called "Username or E-Mail" as you can create wordpress accounts using a user name or an email address. For my account I used a user name and not an email address but I also configured an email address. The ultimate member login form does not search for a user with this user name or with this email address but it does only search for a user where the filed "username or email address" contains the entered data.

Do you want to change the behavior?

**Comment by champsupertramp** [comment]
Hi,

Unfortunately, if you want to change the behavior, this requires customisation on your end as this is by design.

Regards,
