### ISSUE TITLE
Profile images are guessable

### ISSUE THREAD

**Issue by sedrubal** [ultimatemember/ultimatemember#298]
It was very useful if you don't want to publish the members / profile pages for unauthenticated users if the profile image urls were not guessable.

Currently the profile image url for a user is `/wp-content/uploads/ultimatemember/<user id>/profile_photo.jpg`

It would be better if it was something like `/wp-content/uploads/ultimatemember/<user id>/<some random characters>/profile_photo.jpg`

You even don't have to store the random characters as you could just search for the only existing directory under `wp-content/uploads/ultimatemember/<user id>/` in the PHP code.

**Comment by champsupertramp** [comment]
Thanks for letting us know. I've added this in the feature request list. 

Regards,

**Comment by cod3monk** [comment]
I am also highly interested in this feature. Depending on the implementation it would not even require an additional database column: by concatinating the user id with a secret string and then hashing it should be sufficient to make file locations unguessable.

**Comment by sedrubal** [comment]
For us it was also ok to use one random / configurable string for all images like: `/wp-content/uploads/ultimatemember/<some random characters>/<user id>/profile_photo.(jpg|png)`

**Comment by sedrubal** [comment]
I found the hooks `um_upload_basedir_filter` and `um_upload_baseurl_filter` here: https://github.com/ultimatemember/ultimatemember/blob/c4b648443843e51bb4d1f8c0c0ef8ff5c2ffd985/includes/core/class-files.php#L158-L159 and I could implement the latter suggestion by using this code:

```php
 /**
 * obfuscate the profile image url.
 * docs: not found
 * instructions: define `PROFILE_IMAGE_UPLOAD_DIR_SECRET` in wp-config.php
 */
add_action('um_upload_basedir_filter', 'custom_profile_image_upload_dir', 999, 1);
add_action('um_upload_baseurl_filter', 'custom_profile_image_upload_dir', 999, 1);
function custom_profile_image_upload_dir( $url ) {
       return $url . PROFILE_IMAGE_UPLOAD_DIR_SECRET . '/';
}
```

But then I couldn't upload any new profile image and ultimatemembers created many directories named like the value of the variable `PROFILE_IMAGE_UPLOAD_DIR_SECRET` on many locations it shouldn't write to at all.

**Comment by ForauDNB** [comment]
Apologies for commenting on old issue but does this effectively prevent anybody from browsing to/crawling for pictures in uploads/ultimatemember/ID ? (assuming you have disabled indexing).

Please confirm as i have doubts about the security of uploaded items. 

What permissions would you recommend setting on the upload, ultimatemember and UserID folders (and the images inside them)? You seem to have to keep global otherwise it breaks the upload process...
