### ISSUE TITLE
Consider using default scripts by WordPress

### ISSUE THREAD

**Issue by passatgt** [ultimatemember/ultimatemember#3]
Hi!

I think um-jquery-form.js and um-masonry.js could be loaded from the WordPress core, since these are already included:

wp_enqueue_script( 'jquery-form' );
wp_enqueue_script( 'jquery-masonry' );

**Comment by ultimatemember** [comment]
These scripts are minfied and included in um.min.js (when minify is turned on) to reduce calls to extra js files.

**Comment by passatgt** [comment]
Make sense! But might cause compatibility issues if loaded twice? (by other plugin for example)

**Comment by ultimatemember** [comment]
I have not tested this particular case. Did you? (I can understand what you mean) but have to test with another plugin that loads these scripts.
