### ISSUE TITLE
Duplicate method 'convert_tags'

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#30]
Hi @ultimatemember,

Found a duplicate `convert_tags()` method in https://github.com/ultimatemember/ultimatemember/blob/master/core/um-mail.php#L112
and https://github.com/ultimatemember/ultimatemember/blob/master/core/um-short-functions.php#L41

is there a purpose why we have duplicated this method in `um-mail.php` ?

Thanks,

**Comment by ultimatemember** [comment]
You are right we can remove the duplicate in um-mail.php and use the function instead of class method everywhere.

**Comment by ultimatemember** [comment]
So we can replace $this->um_convert_tags with the function instead in the plugin core files.

**Comment by champsupertramp** [comment]
ref: https://github.com/ultimatemember/ultimatemember/commit/956fd728bae1677e12f60aa17eb74800464e7315
