### ISSUE TITLE
conditional logic with user role

### ISSUE THREAD

**Issue by jzwyssig** [ultimatemember/ultimatemember#307]
Conditional logic based on user role does not work (dropdown AND radio). Tried it several times with different conditions and user roles (with "Member" as well). Using e.g. a self created drop down does not show this issue!
Can anyone confirm this bug? Thanks!

**Comment by SkynetCom** [comment]
Same issue here... by the way, no conditional options it's working

**Comment by jzwyssig** [comment]
Okay it works! One has to use lowercase letters and ingore special characters. I used for example "Studierende/r" as members. In the conditional logic field I selected _show if equals to_ studierender.
