### ISSUE TITLE
UM user reviews Cannot activate

### ISSUE THREAD

**Issue by lal101** [ultimatemember/ultimatemember#308]
![image](https://user-images.githubusercontent.com/29221608/29653859-bcc45c8c-88dd-11e7-96a5-e1968635ae4a.png)
![image](https://user-images.githubusercontent.com/29221608/29653901-e1683676-88dd-11e7-803a-77561bdfd8f6.png)

**Comment by champsupertramp** [comment]
Hi,

Unfortunately, we don't provide support for paid extensions in this github repo.

I suggest that you create a ticket for paid extensions issues in the link: https://ultimatemember.com/support/

Regards,
