### ISSUE TITLE
Multiple Roles for users.

### ISSUE THREAD

**Issue by BetaStacks** [ultimatemember/ultimatemember#310]
How can I add a 2nd role to a user? I need the users to be able to be part of "1st headed and "parent.

Cheers!

**Comment by champsupertramp** [comment]
Hi @BetaStacks, Are you refering to UM 1.3.38?

**Comment by BetaStacks** [comment]
It looks like I'm on 1.3.88

**Comment by nikitasinelnikov** [comment]
Hi @BetaStacks 

Please try to upgrade UM to 2.0 version. You can download it in release/2.0 branch. There was many changes in roles logic between 1.3.88 and 2.0. There are some abilities to set 2 roles to 1 user (WP Default role + UM custom role).

Thanks!

**Comment by jonbarratt** [comment]
Just noticed that in v2.0, if you edit/save a user profile from the backend admin area (e.g. you wanted to update the WP default role or other details), the WP default role and any other roles get deleted/replaced by the UM role. This destroys the multiple role capability.

**Comment by stefahn** [comment]
I need this feature too.

@nikitasinelnikov: At https://wordpress.org/support/topic/assign-multiple-roles-to-single-users/#post-9454422 you wrote that this feature will be covered by a plugin named "Groups". Now it will become part of the core?

**Comment by Garconis** [comment]
Hoping for this soon!

**Comment by nikitasinelnikov** [comment]
Hi there guys,

We plan to make UM2.0.2 official release as soon as possible. Currently UM2.0.2 provide an ability to add multiple roles for WP User. https://www.screencast.com/t/phGdw2dT46pC Until UM2.0 UM role was user meta, but since UM2.0 this is fully user role ad you can use WP functions like:

current_user_can( 'um-role-key-here' );

More documentation about 2.0 changes will be added soon to ultimatemember.com

Thanks!

**Comment by BetaStacks** [comment]
Awesome!! Thanks for the update, you all rock!

**Comment by Garconis** [comment]
So does this now allow for multiple roles too? Previously in 2.0, all roles were getting wiped out when a role was changed by your plugin. It's ideal that the roles stay in tact when adding a new role (or at least having the option to KEEP previous/existing roles in addition to the new one).
