### ISSUE TITLE
add css to filed  [improuvment]

### ISSUE THREAD

**Issue by 6clicks** [ultimatemember/ultimatemember#311]
hello Is it possible to add a specific css class to the form filed that would help a lot when we have to style the form ...

**Comment by himanshuahuja96** [comment]
that would be nice

**Comment by nikitasinelnikov** [comment]
Hi there guys,

You can use filter "um_extend_field_classes" at your child theme functions.php for change field's classes. More details about hook here at beta hooks docs https://ultimate.g-photo.com.ua/wp-content/plugins/um-hook-docs-generator/docs/?hook=um_extend_field_classes

Thanks!

**Comment by haydnjames** [comment]
I don't understand how this new function fixes the issue? Adding a new class is only useful if it carries some weight, but as .um-form-field is styled using !important - any additional classes are immediately overruled. Can this function be used to remove the .um-form-field class entirely? And can it be used to target other form elements like buttons, and select menus?
