### ISSUE TITLE
Profile Permalink Base as encoded one(Improvement)

### ISSUE THREAD

**Issue by himanshuahuja96** [ultimatemember/ultimatemember#313]
It would be good if we don't share any type of information like **site.com/user/username** -> **site.com/user/encrypeduser** is used default for Profile Permalink Base but we can simply use some encoded value and It should also change the **site.com/author/encryptedusername** for all posts and pages too.

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
