### ISSUE TITLE
When change user role name, users are desassigned to him

### ISSUE THREAD

**Issue by alfredo49** [ultimatemember/ultimatemember#314]
Hi:

When you change the name of user role, all the users assigned to him are desassigned and you have to assign it again.

i have the last version of UM.

i did the test with all the plugin deactivated and default wordpress theme.

Attach a video where you can see the issue

[http://www.tqmdesarrollo.com/issue-ultimate-member.wmv](url)

Thxs

Regards

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
