### ISSUE TITLE
Role field in profile edition are not protected against html injection

### ISSUE THREAD

**Issue by fnbf21** [ultimatemember/ultimatemember#315]
Hi everyone,

I recently realized that if you add a role field in member profile with only two option, the user can inject another role in the form through the navigator development tools.

For exemple : 

My subscribers can become invisible. Thus, I added a radio button for them to chose between being visible or invisible (different from the private mode in account page). However by using the development tool of firefox I can replace invisible by administrator and submit the form.

Could it be possible to implement the verification of the value ? Thus, check if the value is available in the form ?

Currently I modify the um-actions-profile file to add a check for the specific role I don't want them to gain. 

Thanks

**Comment by denisbaranov** [comment]
Hi,
Can you please write in more detail what you are doing to reproduce the injection.
Regards,

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
