### ISSUE TITLE
Updating Account Information  First Name and last name not working 

### ISSUE THREAD

**Issue by abdallahmaali** [ultimatemember/ultimatemember#316]
i have problem in account page  when user edit first name and last name its didn't save new value 
i'm using the default register form

**Comment by Tebbott** [comment]
I'm also having this issue.  I've tested by using the 2017 theme and deactivating all plugins, but the information still isnt edited when clicking update on the account page.

**Comment by denisbaranov** [comment]
Hi guys, are you currently talking about version 1.3.88? In version 2.0, this bug has already been fixed.

**Comment by Tebbott** [comment]
Where is version 2?

**Comment by denisbaranov** [comment]
Currently, the version in the Ultimate Member 2.0-beta repository and you can download from the master branch

**Comment by Tebbott** [comment]
I've just downloaded and installed the v2 beta.  I've deactivated v1, and activated v2.  I've then switched to the twentyseveteen theme and deactivated all other plugins.  I navigate to the front end, log in to a test user, edit my first name within the account section and click save - I get the "Your account was updated successfully." message, but the updated information still isnt being saved.

Am I doing something wrong?  Any advice you can give to help with this issue?  I

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,

**Comment by garabavlad** [comment]
Seems like one of their hook is broken.
I fixed this with updating once again the submited data.
The code is below.  Just throw these lines in your **functions.php** file
`function change_user_name(  $changes  )
{

    $submit = $changes['um_account_submit'];
    $user_id = get_current_user_id();


    if($submit == 'Update Account')
    {
        update_user_meta($user_id,'first_name',$changes['first_name']);
        update_user_meta($user_id,'last_name',$changes['last_name']);
    }

}
add_action( 'um_submit_account_errors_hook', 'change_user_name', 10, 1 );`

Check it out and tell me if it works now.

**Comment by miguelh09** [comment]
@garabavlad thanks dude, you save my life and my job.
