### ISSUE TITLE
Problem with permalinks structure

### ISSUE THREAD

**Issue by satnapar** [ultimatemember/ultimatemember#317]
When I change the permalink structure to plain format (eg. /?p=123) everything works great. When I change it back to Post Name format (eg. /sample-post/) I got myself an error Page not found)
using Ultimate Member Version 1.3.88

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
