### ISSUE TITLE
Restricted Access Message field under Settings > Access adding additional characters to HTML

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#318]
Backslashes and other characters are added to html: <a href=\"/membership/\">

This is for the Restricted Access Message text box under Settings > Access.

**Comment by champsupertramp** [comment]
Hi @joshuakern, Are you using UM 1.3.x or UM 2.0?

**Comment by joshuakern** [comment]
Hi @champsupertramp, I'm using 2.0

**Comment by nikitasinelnikov** [comment]
Hi,

We tried to fix this issue in previous commits. Please check how it works now with the latest version from "master" branch. 

Thanks!

**Comment by joshuakern** [comment]
It's better but still not working properly. The html is being added to the Visual editor after hitting  save.
<img width="848" alt="screen shot 2017-10-12 at 12 06 26 pm" src="https://user-images.githubusercontent.com/18587286/31506665-12f59880-af46-11e7-8e94-91146d78eb65.png">

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern 

Please update UM to the latest version, I have added fix for wp_editor field. Please check how it works for you now.

Thanks!

**Comment by joshuakern** [comment]
@nikitasinelnikov 

Works perfectly. Thanks!
