### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by joshuaseymour** [ultimatemember/ultimatemember#319]
This an error message for the main site of a new multisite install:

Fatal error: Uncaught Error: Call to undefined function um\core\um_get_option() in /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/core/class-permalinks.php:97 Stack trace: #0 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/core/class-permalinks.php(14): um\core\Permalinks->get_current_url() #1 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/class-init.php(894): um\core\Permalinks->__construct() #2 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/class-init.php(310): UM->permalinks() #3 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/class-init.php(185): UM->includes() #4 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/class-init.php(72): UM->__construct() #5 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/class-init.php(1064): UM::instance() #6 /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-ma in /nas/content/live/avolveguru/wp-content/plugins/ultimatemember-master/includes/core/class-permalinks.php on line 97

**Comment by nikitasinelnikov** [comment]
Hello, Joshua

Thanks for reporting the issue. I have added fix in the latest commit, please download latest vesion, and check how it works for you. Also please rename "ultimatemember-master" plugin folder to "ultimate-member"

Thanks!
