### ISSUE TITLE
Remove stream photos from upload directory clean up.

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#32]
Hi,

We have reported issues about stream photos getting broken images after updating user profiles.

I found the bug in https://github.com/ultimatemember/ultimatemember/blob/master/core/um-actions-user.php#L20

Related with my proposal here: https://github.com/ultimatemember/ultimatemember/issues/31

We need to add the `stream_photo` in the validation to fix the issue. see example below:
```PHP
if ( !strstr( $str, 'profile_photo') && !strstr( $str, 'cover_photo') && !strstr( $str, 'stream_photo' ) && !preg_grep('/' . $str . '/', $array ) )
```

Do you think the above changes may cause issues to all existing sites?

**Comment by ultimatemember** [comment]
This seems to be fine to add. You can commit the code changes.

**Comment by champsupertramp** [comment]
ref: https://github.com/ultimatemember/ultimatemember/pull/27

**Comment by ultimatemember** [comment]
It does not seem pushed yet in that commit. Can you please check it?
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-actions-user.php#L34

**Comment by champsupertramp** [comment]
pushed. https://github.com/ultimatemember/ultimatemember/blob/master/core/um-actions-user.php#L34
