### ISSUE TITLE
Getting this error when I try to install 2.0

### ISSUE THREAD

**Issue by bluepaintman** [ultimatemember/ultimatemember#321]
Fatal error: Can't use method return value in write context in /home/content/17/10311217/html/servicehuddle/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php on line 147

**Comment by nikitasinelnikov** [comment]
Hi

Please update your installed version to the latest version from repository and check how it works now. If you still have the issue please provide error log.

Thanks!

**Comment by borjamerino-v** [comment]
I have the same problem wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php on line 147

**Comment by nikitasinelnikov** [comment]
Hi @borjamerino-v @bluepaintman please try to install the latest version from release/2.0 branch. This issue was fixed here. I will wait your feedback.

Thanks!
