### ISSUE TITLE
Wordpress profile has misleading link to gravatar

### ISSUE THREAD

**Issue by mgmax** [ultimatemember/ultimatemember#323]
With UM 1.3 the wordpress profile page /wp-admin/profile.php (for users with backend access) has wrong information about the profile picture: It shows the photo and then a text "You can change your photo on gravatar", which is wrong if you have uploaded a photo via ultimatemember. This text should rather be "Edit" and link to the ultimatemember profile /user/ .

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,

**Comment by mgmax** [comment]
Reopened as #338.
By the way, it would be cool if you took a look at the current pull requests.
