### ISSUE TITLE
Nicknames appear before username on Users page in admin

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#325]
Nicknames appear before usernames when no gravatar under the Users page in admin - see screenshot.. This is for 2.0.

<img width="611" alt="screen shot 2017-09-25 at 9 51 06 pm" src="https://user-images.githubusercontent.com/18587286/30838792-b43eeea2-a23b-11e7-8546-8add17842f7a.png">

**Comment by denisbaranov** [comment]
Hi,

Please upgrade your local repo. We have added the latest changes 2 days ago.

Thanks!
