### ISSUE TITLE
Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#329]
Notice: Trying to get property of non-object in /wp-content/plugins/ultimate-member/includes/core/class-access.php on line 358

I see this error when not logged in - http://dev.thefranklininn.com/membership/.

I have 2.0 installed. Not sure if it started after updating or not.

**Comment by nikitasinelnikov** [comment]
Hi Joshua,

this issue was fixed at last commit. Please check how it works now.

Thanks!

**Comment by joshuakern** [comment]
I don't see the notice now. Thanks!

**Comment by nikitasinelnikov** [comment]
Great! I close this issue
