### ISSUE TITLE
Member Page using "dev/members_directory_list" branch keeps reloading (BUG)

### ISSUE THREAD

**Issue by himanshuahuja96** [ultimatemember/ultimatemember#331]
When We try to view the page the page keeps reloading, 
Tested on-
Twenty * themes, Astra etc
Plugins Installed-
Ultimate member dev/members_directory_list

Screenshot
![Alt text](https://i.imgur.com/DVksz1Q.png "Optional title")

**Comment by nikitasinelnikov** [comment]
Hi,

Please upgrade your local repo. I have added the latest changes today. This branch currently in development.

Thanks!
