### ISSUE TITLE
Search widget description incorrect ?

### ISSUE THREAD

**Issue by ajoah** [ultimatemember/ultimatemember#332]
Hi,

I think the description of the search widget is not correct :

![image](https://user-images.githubusercontent.com/10757301/31600583-4e888704-b257-11e7-8c4b-3d87b4a678b0.png)

https://github.com/ultimatemember/ultimatemember/blob/master/includes/widgets/class-um-search-widget.php

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
