### ISSUE TITLE
'Activation link expired' error is inaccurate

### ISSUE THREAD

**Issue by tylertadej** [ultimatemember/ultimatemember#334]
> This activation link is expired or have already been used.

According to the Ultimate Member docs and support forums, the activation link does NOT expire. Also, the error should read 'has' instead of 'have'

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
