### ISSUE TITLE
Notice: Undefined index: _um_access_roles

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#335]
I see the following error in my footer when logged in as an Editor. This never appears when logged in as an Admin

Notice: Undefined index: _um_access_roles in /wp-content/plugins/ultimate-member/includes/core/class-access.php on line 471

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,
