### ISSUE TITLE
Multiselect and Checkbox bugs

### ISSUE THREAD

**Issue by ibiza69** [ultimatemember/ultimatemember#337]
Hi, today we found a bug at **MULTISELECT** Field at registration form and profile form.

We listed “job sectors” in the multiselect.
Then we went to the members directory and included in the search fields.

Lawyers
Administrators
ecc....

Then we searched at members directory for members job sector and the result was none, when there are members in those sectors, the field is not working properly.

We have tested same thing with **CHECKBOX** (job sectors) and the result was the same, no results.

Once we activate any of those **MULTISELECT** or **CHECK BOX**, "all other search fields stop working" and don´t give either any result. When we deleted them, other fields start working again.

Hopefully someone gives a solution…….. as a jobs seekers members website without job sectors is totally unusefull....

**Comment by champsupertramp** [comment]
Hi,

Can you please try creating a new ticket and follow the template for submitting issues?
https://github.com/ultimatemember/ultimatemember/issues/new

Regards,

**Comment by ibiza69** [comment]
Hi there! Calum solved the situation thru email. Thanks a lot for the help ;) You can close this.
