### ISSUE TITLE
Bug. When change user role name, users are desassigned to him

### ISSUE THREAD

**Issue by alfredo49** [ultimatemember/ultimatemember#339]
### Ultimate Member Version
1.3.88 (withouth extensions)

### Subject of the issue
When change user role name, users are desassigned to him

### Expected behavior
Changing the user role name non affects users assign to him

### Actual behavior
Users are dessagigned when you change the user role name

### Steps to reproduce the behavior
Just change the user role name in Ultimate Member => User Roles

**Comment by nikitasinelnikov** [comment]
Hi @alfredo49 

There was manually released 2.0 version. Can you try to upgrade to 2.0 version and check how it works? There was many changes in UM Roles logic in 2.0 version. I'm wait your feedback about this.

Thanks!
