### ISSUE TITLE
User tags form field doesn't allow help text

### ISSUE THREAD

**Issue by nutsandbolts** [ultimatemember/ultimatemember#341]
The "user tags" form field doesn't allow any sort of description or help text to explain to users what they're selecting, how many they can choose, etc. I guess this is a feature request but I'm really surprised this isn't available by default. All possible form fields should allow help text as well as a description below the label.

**Comment by nikitasinelnikov** [comment]
Hi,

I have added help text field to "add/edit field" modal window. Currently we work with 2.0 version release. This fix will be added in 2.0 version, which will be released as soon as possible in few weeks.

Thanks!
