### ISSUE TITLE
Problem when displaying user profiles in different languages

### ISSUE THREAD

**Issue by sadiqodunsi** [ultimatemember/ultimatemember#342]
I am having a problem with the user profile when I switch my site to another language (Finnish). I am not able to view a user profile when my site is switched to Finnish language. It works fine in the default language which is English but when I switch to Finnish language it doesn't work. This is the response I get "Oops! That page can’t be found. It looks like nothing was found at this location. Maybe try a search?" 

Am I supposed to use a different shortcode for the Finnish page? Also I have clicked yes on the place where it asked if "This is a translation of UM profile page?"

Also, how can I enable a different member search page for each language? I want the member search page on the Finnish language to display Finnish texts and the member search page of the English page to display English texts.

**Update regarding user profile:** When I changed the permalink settings to plain on wordpress, it worked fine. But the problem with that is, it is not good for SEO. I would like to continue using the post name permalink instead if plain. 

Please help

**Comment by nikitasinelnikov** [comment]
Hi @sadiqodunsi 

Please provide information about plugin what do you use for multilanguage feature at your site? Is this WPML?

Thanks!

**Comment by sadiqodunsi** [comment]
Hi @nikitasinelnikov 

Thank you for getting back to me. I am using Polylang for the multi-language feature.

Regards,
Sadiq

**Comment by nikitasinelnikov** [comment]
Hi Sadiq,

Sorry but currently Ultimate Member works compatible only with WPML. Maybe compatibility with Polylang will be added in future versions.

Thanks!

**Comment by MvdO** [comment]
I really love UM, but on a automatic translated multilingual website the plugin is not usable right now.
Polylang is relatively expensive for the average UM customer, **high monthly costs**.   

To globalize your website content nowadays is very important.

Is there any possibility to speed up compatibility with Transposh? It's a **free service** for automatic machine based translation, would be awesome ass a selling point for UM against other membership plugins.

Is it possible to get an indication of costs for customized code for compatibility with Transposh?
