### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'um\lib\mobiledetect\Mobile_Detect'

### ISSUE THREAD

**Issue by krishaamer** [ultimatemember/ultimatemember#343]
### Ultimate Member Version
UM 2.0

### Subject of the issue
When trying to enabled plugin system fails with 

`Fatal error: Uncaught Error: Class 'um\lib\mobiledetect\Mobile_Detect' not found in /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php:996 Stack trace: #0 /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php(318): UM->mobile() #1 /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php(187): UM->includes() #2 /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php(74): UM->__construct() #3 /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php(1068): UM::instance() #4 /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php(1072): UM() #5 /nas/content/live/esl2/wp-content/plugins/ultimate-member/ultimate-member.php(26): require_once('/nas/content/li...') #6 /nas/content/live/esl2/wp-admin/includes/plugin.php(1882): include('/nas/content/li...') #7 /nas/content/live/esl2/wp-admin/plugins.php(164): plugin_sandbox_scrape('ultimate-member...') #8 {main} thrown in /nas/content/live/esl2/wp-content/plugins/ultimate-member/includes/class-init.php on line 996`

**Comment by Cyberdemon87** [comment]
I have the same problem, please try to fix it. Plugin cannot be enabled.

**Comment by nikitasinelnikov** [comment]
Hi guys @Cyberdemon87 @krishaamer maybe it's connected with "Mobile_Detect" classes conflicts. Please try to install this zip instead current 2.0 version
[ultimate-member-mobile-fix.zip](https://github.com/ultimatemember/ultimatemember/files/1470339/ultimate-member-mobile-fix.zip)

Please let me know if the issue resolved, I will push this changes to repo.


Thanks!

**Comment by krishaamer** [comment]
Yes, this one seems to be working. Thanks!
