### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function language_url() on null

### ISSUE THREAD

**Issue by krishaamer** [ultimatemember/ultimatemember#344]
### Ultimate Member Version
2.0

### Subject of the issue
`Fatal error: Uncaught Error: Call to a member function language_url() on null in /nas/content/staging/esl2/wp-content/plugins/ultimate-member/includes/um-short-functions.php:600 Stack trace: #0 /nas/content/staging/esl2/wp-content/plugins/ultimate-member/includes/um-short-functions.php(663): um_get_url_for_language('', false) #1 /nas/content/staging/esl2/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php(219): um_get_core_page('user') #2 [internal function]: um\admin\core\Admin_Settings->init_variables('') #3 /nas/content/staging/esl2/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #4 /nas/content/staging/esl2/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #5 /nas/content/staging/esl2/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /nas/content/staging/esl2/wp-admin/admin.php(154): do_action('admin_init') #7 /nas/content/staging/esl2/wp-admin/index.php(10): require_once('/nas/content/st...') #8 {main} thrown in /nas/content/staging/esl2/wp-content/plugins/ultimate-member/includes/um-short-functions.php on line 600`

**Comment by nikitasinelnikov** [comment]
I have added the fix, please check how it works now.

Thanks!

**Comment by yavane** [comment]
WordPress 4.9.1 and this still exist

**Comment by mwenell** [comment]
I get also following error:

2018/01/08 12:34:30 [error] 1670#1670: *10958 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function language_url() on null in /var/www/html/wp-content/plugins/ultimate-member/core/um-short-functions.php:636
Stack trace:
#0 /var/www/html/wp-content/plugins/ultimate-member/core/um-short-functions.php(698): um_get_url_for_language(NULL, false)
#1 /var/www/html/wp-content/plugins/ultimate-member/um-config.php(114): um_get_core_page('user')
#2 /var/www/html/wp-content/plugins/ultimate-member/admin/core/um-admin-redux.php(47): include_once('/var/www/html/w...')
#3 /var/www/html/wp-content/plugins/ultimate-member/admin/core/um-admin-redux.php(36): UM_Redux_Framework_Config->setSections()
#4 /var/www/html/wp-includes/class-wp-hook.php(286): UM_Redux_Framework_Config->initSettings('')
#5 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /var/www/html/wp-settings.php(471): do_action('wp_loaded')
#8 /var/www/html/wp-config.php(88): r" while reading response header from upstream, client: 81.175.243.110, server: g2.mydatabankapp.com, request: "GET /wp-admin/plugins.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "g2.mydatabankapp.com", referrer: "https://g2.mydatabankapp.com/wp-admin/post-new.php?post_type=page"

This happened when i had selected new page into the account page. I have removed this page from wp and also tried to remove this option in wp_options but still i get this error. Looks like i cannot anymore use Ultimate Member or i have to reset my database.

**Comment by joselulepe** [comment]
Yes, the problem is Polylang. I have the same problem.

**Comment by nikitasinelnikov** [comment]
Hi guys @krishaamer @yavane @mwenell 

Please check how it works now with the latest 2.0 commited version. Does the issue still persist?

Thanks!

**Comment by mwenell** [comment]
Unfortunately i have forgotten which feature gave this error. I have been able to avoid the error somehow => Cannot repeat it right now. Do anybody remember what made this error? Was it some shortcode or something else?

**Comment by lewstef** [comment]
the issue is still there, just took the latest version and it crashed my website

**Comment by nikitasinelnikov** [comment]
hi guys,

let's try this version https://github.com/ultimatemember/ultimatemember/archive/master.zip. I have tried to run language_url only for WPML plugin.

thanks!

**Comment by engelys** [comment]
thx, that archive version is not crash my website

**Comment by antoineBusted** [comment]
Hi I just downloaded version 2.0.18 alpha and the problem is still here. It is impossible to display the profile form unfortunately...
