### ISSUE TITLE
Weird HTML-encoded apostrophe issue (&#039;) in Biography field in member directories

### ISSUE THREAD

**Issue by Indigo744** [ultimatemember/ultimatemember#346]
### Ultimate Member Version
UM Version 1.3.88
WordPress version 4.8.3
Locale is in French

### Subject of the issue
In the Biography field of a user, I put a sentence with an apostrophe (`'`) in it. 

### Expected behavior
The apostrophe should look like an apostrophe

### Actual behavior
In a member directory, it is displayed as `&#039;`
There is no issue when viewing the user's profile page.

In WordPress user configuration tab:

> ![image](https://user-images.githubusercontent.com/7137528/32899186-90b1cba8-caea-11e7-9afa-2d4083210f20.png)

The issue when seeing in a member list:

> ![image](https://user-images.githubusercontent.com/7137528/32899245-bb009ce0-caea-11e7-863d-68807ec7f6cd.png)

When looking at the user profile page, the user is not seen:

> ![image](https://user-images.githubusercontent.com/7137528/32899257-c10e23d2-caea-11e7-83f3-b94c599ffce8.png)

### Steps to reproduce the behavior

1. Set a user with an apostrophe in the Biography field (maybe the issue concerns other fields as well?).
2. Build a member directory with this user, set the Biography field to be displayed.
3. Add shortcode to a page, go to the page.

I've only found #23 kinda related to this... But it's old and should be fixed...

**Comment by nikitasinelnikov** [comment]
Hi @Indigo744 

I have added fix for Biography field, please upgrade UM to 2.0 version form "master" branch and check how this works for you.

Thanks!

**Comment by Indigo744** [comment]
Thanks @nikitasinelnikov !

However, is there any gotcha when upgrading to 2.0? Will I receive updates from WP or GH?
The site is almost done...

**Comment by nikitasinelnikov** [comment]
Hi @Indigo744 

If you have almost done site I recommend temporary to change code in the UM's file. "ultimatemember/core/um-filters-fields.php" and remove this lines:

1) add_filter('um_profile_field_filter_hook__description', 'um_profile_field_filter_hook__description', 99, 2);
2) "um_profile_field_filter_hook__description" function

But in future for getting new features you need to upgrade UM to 2.0 or higher, because we plan new features and optimization.

Thanks!

**Comment by Indigo744** [comment]
Indeed, UM version 2.0 seems really nice :)

When UM version 2.0 will be officially released on WP?
Or can I use "GitHub updater" plugin to get update from GH directly?

**Comment by nikitasinelnikov** [comment]
If you have almost done site please try to upgrade UM2.0 at dev site firstly or create full backup of your site. More information you can read here http://docs.ultimatemember.com/article/262-manually-updating-to-2-0

UM2.0, when be almost stable  for active installs, will be officially released on WP as soon as possible.

Thanks!
