### ISSUE TITLE
More visible Ultimate member specific pages

### ISSUE THREAD

**Issue by paaljoachim** [ultimatemember/ultimatemember#353]
Hi

I am doing a small test of Ultimate Member
From the initial look I really like what I see.
The following is the Pages screen:

![screen shot 2017-11-30 at 15 36 47](https://user-images.githubusercontent.com/5323259/33436085-557caecc-d5e4-11e7-8850-2d77d313ea15.png)

Notice how WooCommerce adds the words: - Cart Page, Checkout Page etc.

For all Ultimate Member pages it would be good to have something like:
Members - UM etc. As it would show which pages that belong to Ultimate Member.

Thanks.

**Comment by nikitasinelnikov** [comment]
Hi @paaljoachim 

This feature was added to the latest 2.0 release at "release/2.0" branch

Thanks!
