### ISSUE TITLE
Case study

### ISSUE THREAD

**Issue by paaljoachim** [ultimatemember/ultimatemember#355]
I began testing Ultimate Member because I have seen that is has a nice UI on the frontend, and by going through the backend I also thought it looked nice and tight and straight to the point.

My case study:
I am working on a nonprofit WooCommerce site that needs a membership plugin to where a new user can signup and pay the yearly fee to then gain access to the products. I just found out that Ultimate Member does not have a payment module.

As various features should like lego pieces/modules. Payment should be one of them included in the core of the plugin. Think the older version of Jetpack how it creates modules like a tapestry of squares where one would activate and deactivate modules. It would be great to have something like this in UM. As some activations would require purchase while others would not.

**Comment by nikitasinelnikov** [comment]
Hi @paaljoachim 

There is paid extension for UM and WooCommerce integrations. More info you can find there https://ultimatemember.com/

Thanks!

**Comment by paaljoachim** [comment]
Hey Nikita

I had to do some digging and found out through the docs that there is a plugin at themeforest: 
https://codecanyon.net/item/umswitcher-sell-subscriptions-for-ultimate-member-powered-by-woocommerce/19080706?s_rank=1
