### ISSUE TITLE
Mycred add-on makes Members page "no matched"

### ISSUE THREAD

**Issue by sachiotomita** [ultimatemember/ultimatemember#357]
### Ultimate Member Version
Tell us what UM core version you use. Do you use UM extensions? Tell us which UM extensions and what are their versions.
1.3.88

### Subject of the issue
Describe your issue here.
After making Mycred add-on activated, Members page (list of members of certain role)
shows 'no matched',
with message of "We are sorry. We cannot find any users who match your search criteria."

Here is sql query:
SELECT DISTINCT SQL_CALC_FOUND_ROWS wp_users.ID
FROM wp_users
LEFT JOIN wp_usermeta
ON ( wp_users.ID = wp_usermeta.user_id ) 
LEFT JOIN wp_usermeta AS mt1
ON ( wp_users.ID = mt1.user_id ) 
LEFT JOIN wp_usermeta AS mt2
ON (wp_users.ID = mt2.user_id
AND mt2.meta_key = 'hide_in_members' ) 
LEFT JOIN wp_usermeta AS mt3
ON ( wp_users.ID = mt3.user_id )
WHERE 1=1
AND ( wp_usermeta.meta_key = 'mycred_default' 
AND ( ( mt1.meta_key = 'role'
AND mt1.meta_value IN ('teacher') ) 
AND ( mt2.user_id IS NULL 
OR ( mt3.meta_key = 'hide_in_members'
AND mt3.meta_value NOT LIKE '%Yes%' ) ) ) )
ORDER BY wp_usermeta.meta_value+0 DESC
LIMIT 0, 12

This part is different:
AND ( wp_usermeta.meta_key = 'mycred_default' 
AND ( ( mt1.meta_key = 'role'
AND mt1.meta_value IN ('teacher') ) 
AND ( mt2.user_id IS NULL 
OR ( mt3.meta_key = 'hide_in_members'
AND mt3.meta_value NOT LIKE '%Yes%' ) ) ) )

### Expected behavior
Tell us what should happen
It should be shown as I set on Member Directories, admin page

### Actual behavior
Tell us what happens instead
"We are sorry. We cannot find any users who match your search criteria."

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 
Turn on Mycred add-on
and open 'Members' page

**Comment by nikitasinelnikov** [comment]
Hi @sachiotomita 

Did you tried to use the latest UM2.0 and UM:myCRED 2.0 extension? Please try to upgrade and let me know if the issue still persists.

Thanks!

**Comment by himanshuahuja96** [comment]
I have tested with Mycreed and same issue. And also with Really Simple SSL plugin too.
[https://wordpress.org/plugins/really-simple-ssl/](Really Simple SSL)
