### ISSUE TITLE
User cache crashes database after a period of time

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#358]
### Ultimate Member Version
Latest

### Subject of the issue
We've been having issues recently over the past several months where our site (hosted on digitalocean) would be good for a while, and then suddenly and without warning, the memory usage would skyrocket and the site would crash.

After changing around some of the configurations to the innodb buffer cache, I was able to slowly reproduce this without exhausting the memory fully. 

When we got to near-max memory usage, I deleted the user cache and that _fully_ fixed this issue.

**TL;DR:** Your innodb usage or setting is causing databases to crash. Confirmed. 100% certain.

Here's a screenshot of our memory usage showing the moment I cleared the user cache....

![image](https://user-images.githubusercontent.com/5240018/33534002-c4c63042-d872-11e7-81ad-1365c3d0aada.png)

### Expected behavior
Database should not crash ever.

### Actual behavior
Database crashes consistently after the user cache builds up due to an exhaustion of the memory.

### Steps to reproduce the behavior
See above.

Happy to answer any other questions you might have.

**Comment by champsupertramp** [comment]
Hi @dsifford,

This has been fixed in the version UM 2.0. The issue was with autoload user profile caches on every page load.

Regards,

**Comment by dsifford** [comment]
When is 2 planned to release? Latest in the WP repository at the time of writing is `1.3.88`.

If not planned for a while, perhaps maybe push a fix for this? This is a pretty huge issue, IMHO.

**Comment by dsifford** [comment]
Also, @champsupertramp here's a screenshot showing just how quickly this issue affects users...

![image](https://user-images.githubusercontent.com/5240018/33569911-2df0f404-d8f9-11e7-89b6-f2f9ea7f231e.png)

There is almost zero time to react once the memory leak happens. Apache jumps from ~33% total memory usage to 95+% memory in a matter of minutes.

So, again, this is a gigantic issue. Please consider pushing a fix to current version.

**Comment by champsupertramp** [comment]
Hi @dsifford,

Can you please apply this fixes to your copy of UM?
https://github.com/ultimatemember/ultimatemember/commit/28826d10972ed874b1a459aa5a5e1563dc3e9608

Once you've updated the file, please clear all user profile cache in UM dashboard.

Let me know if this made any significant changes in the performance.

Regards,

**Comment by champsupertramp** [comment]
In UM 1.3.88, this can be found in /ultimate-member/core/um-user.php https://github.com/ultimatemember/ultimatemember/blob/1.3.x/core/um-user.php#L146

**Comment by dsifford** [comment]
@champsupertramp I can't really afford to be the test dummy here for this and there's no way that I'm aware of to make this memory leak happen on demand, so I'm just gonna update to 2.0. 

I looked at the site and noticed that it _is_ released now, just not to the WP repository.

**Comment by michellealiem** [comment]
Hey @champsupertramp - thanks for your quick responses. We’re dealing with a relative high-stakes leaning management system and community, training physicians and other health professionals. So we’re always a bit nervous for potentially bandaid fixes. Cross fingers that the manual UM 2.0 works. Thanks again for your time.

**Comment by dsifford** [comment]
@champsupertramp Can you guys push out a patch for this to wp.org? Are you all not supporting version 1 anymore? If that's the case, any idea when 2 will land?
