### ISSUE TITLE
UM conflicts with Post/Page password protected.

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#36]
Hi @ultimatemember ,

There's an issue in UM admin hook where it redirects the form back to homepage instead of the current page/post when submitting 'Password protected page'.

Here's a fix:
https://github.com/ultimatemember/ultimatemember/commit/1ec02e11a92a347a8bacb8ff26f6bb77c9ebbafd

**Comment by ultimatemember** [comment]
Merged
https://github.com/ultimatemember/ultimatemember/pull/35

**Comment by champsupertramp** [comment]
Thank you
