### ISSUE TITLE
Menu item conflict with advanced custom fields plugin

### ISSUE THREAD

**Issue by MikeKoval** [ultimatemember/ultimatemember#360]
Hi!

Ultimate member adds custom fields for every menu item and user can set to what roles we need to show this menu item.
But when I added extra custom fields for every menu item and have ultimate member plugin activated, these extra custom fields are now shown

**Comment by nikitasinelnikov** [comment]
Hi @MikeKoval 

Please check the lates commit https://github.com/ultimatemember/ultimatemember/commit/03082943af8fe4116c0d326a66551a2938d5eeed

I have added some fixes for this issue.

Thanks!

**Comment by MikeKoval** [comment]
Hi, @nikitasinelnikov
Great to know there is interest in this.

Unfortunately it didn't help:
- I checked "WP Menu Item Custom Fields Workaround" 
- Firstly I have permissions error at UM_Menu_Item_Custom_Fields_Walker::get_fields and missing param $depth, some ACF_* class was trying to call it.
- When I tried to replace "protected" to "public" of UM_Menu_Item_Custom_Fields_Walker::get_fields and add default value 0 for $depth, I saw that each menu item have 2 Ultimate Member sections with list of checkboxes, my custom field still was not present amount Menu Item params if UM plugin is switched on
- Then I accidentally removed and pasted ultimate-member plugin folder via IDE (files without my changes), and after this I haven't seen errors anymore, but also it seems "WP Menu Item Custom Fields Workaround"  is not working anymore, and my custom field still is not present amount Menu Item params if UM plugin is switched on.

Thank you!

**Comment by nikitasinelnikov** [comment]
Hi @MikeKoval 

My email is nsinelnikov.work@gmail.com Can you provide *.zip with your plugin or theme which add another custom fields to Menu Items? I will take a look into this issue and try to fix as soon as possible. Just there is a rather narrow place in WP Menu items hooks/integrations and many plugins/themes have the conflicts there.

Thanks!

**Comment by nikitasinelnikov** [comment]
Hi @MikeKoval 

Please download the latest version from "master" branch or this link https://ultimatemember.com/wp-content/uploads/2017/11/ultimate-member.zip There was added fix for compatibility with many plugins and menu items.

Thanks!

**Comment by MikeKoval** [comment]
@nikitasinelnikov Thank you!
