### ISSUE TITLE
Disable wp-admin/

### ISSUE THREAD

**Issue by katsar0v** [ultimatemember/ultimatemember#361]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Disabling / cloaking the admin panel for unregistered and non-admin users. 

### Expected behavior
Disable wp-admin for all non-admin logged in users, as well for all not logged in users. Only admins should be able to reach /wp-admin/

### Actual behavior
In 1.3.88 there was a setting about disabling the wordpress login for not logged users, as well the possibility for admins to use the front-end login. This is gone in the beta version.

### Steps to reproduce the behavior
Use beta version (release/2.0 branch)

### Do you use UM extensions? 
- [x] None
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @katsar0v 

Sorry, but this feature is deprecated since 2.0 version. You can use "Wordfence" or some another plugins, which have this features to make wp-admin and wp-login.php secure.

Thanks!
