### ISSUE TITLE
User Roles reset after deactivation and reactivation

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#363]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
User Roles reset every time the plugin is deactivated and reactivated.

### Expected behavior
The settings should remain.

### Actual behavior
The User Roles settings reset.

### Steps to reproduce the behavior
Deactivate and then reactivate the plugin.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern 

I have test this issue at my test site and see that User Roles and their meta data remain the same after deactivate/activate UM2.0 version. I see properly Roles data on Edit user role screen after UM reactivation. 

When UM is inactive user, which had UM roles - stop to have this roles, but if you re-activate UM - UM roles are back to this users.

Please provide more details of the issue if you still have it after upgrade to the latest 2.0 version.

Thanks!
