### ISSUE TITLE
Fatal error: Access level to UM_Menu_Item_Custom_Fields_Walker::get_fields() must be public (as in class ACF_Walker_Nav_Menu_Edit)

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#365]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Actual behavior
When I click on Menus, I see the following error:

Fatal error: Access level to UM_Menu_Item_Custom_Fields_Walker::get_fields() must be public (as in class ACF_Walker_Nav_Menu_Edit) in /public_html/dev/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php on line 9

### Steps to reproduce the behavior
I couldn't tell you how to reproduce. This just randomly started. I haven't been doing anything other than editing pages.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern 

I have added the fix to the latest 2.0 version. Please upgrade the plugin at your site.

Thanks!

**Comment by joshuakern** [comment]
I just uploaded the master branch. I now see the following errors when clicking on Menus.

Warning: Declaration of UM_Menu_Item_Custom_Fields_Walker::get_fields($item, $depth, $args = Array, $id = 0) should be compatible with ACF_Walker_Nav_Menu_Edit::get_fields($item) in /public_html/dev/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php on line 9

Fatal error: Uncaught ArgumentCountError: Too few arguments to function UM_Menu_Item_Custom_Fields_Walker::get_fields(), 1 passed in /public_html/dev/wp-content/plugins/advanced-custom-fields-pro/includes/walkers/class-acf-walker-nav-menu-edit.php on line 59 and at least 2 expected in /public_html/dev/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php:24 Stack trace: #0 /public_html/dev/wp-content/plugins/advanced-custom-fields-pro/includes/walkers/class-acf-walker-nav-menu-edit.php(59): UM_Menu_Item_Custom_Fields_Walker->get_fields(Object(WP_Post)) #1 /public_html/dev/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php(13): ACF_Walker_Nav_Menu_Edit->start_el('', Object(WP_Post), 0, Object(stdClass), 0) #2 /public_html/dev/wp-includes/class-wp-walker.php(145): UM_Menu_Item_Custom_Fields_Walker->start_el('', Object(WP_Post), 0, Object(stdClass)) #3 /public_html/dev/w in /public_html/dev/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php on line 24

**Comment by kylecarlson** [comment]
I'm getting the same exact error with latest ACF/UM installed.

**Comment by ben104** [comment]
I get a similar issue ACF 5.6.7 & UM 2.0

Warning: Declaration of UM_Menu_Item_Custom_Fields_Walker::get_fields($item, $depth, $args = Array, $id = 0) should be compatible with ACF_Walker_Nav_Menu_Edit::get_fields($item) in /nas/content/live/getnorth2018/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php on line 9

Warning: Missing argument 2 for UM_Menu_Item_Custom_Fields_Walker::get_fields(), called in /nas/content/live/getnorth2018/wp-content/plugins/advanced-custom-fields-pro/includes/walkers/class-acf-walker-nav-menu-edit.php on line 59 and defined in /nas/content/live/getnorth2018/wp-content/plugins/ultimate-member/includes/core/um-navmenu-walker.php on line 24

**Comment by codebloo** [comment]
I just updated and get the same error on multiple sites all running ACF pro, UM2, Woocommerce UM extension 2 -- and one also using the UM Instagram extension.

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern @ben104 @kylecarlson @codebloo 

Please download the latest version from "master" branch or from this link https://ultimatemember.com/wp-content/uploads/2017/11/ultimate-member.zip

Thanks!
