### ISSUE TITLE
Error messages when saving Register page

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#366]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Expected behavior
No error messages.

### Actual behavior

Undefined index: um_role in /public_html/wp-content/plugins/ultimate-member/includes/core/um-filters-arguments.php on line 34

Notice: Undefined index: status in /public_html/wp-content/plugins/ultimate-member/includes/core/um-filters-arguments.php on line 36

Notice: Undefined index: _message in /public_html/wp-content/plugins/ultimate-member/includes/core/um-filters-arguments.php on line 37

Also, the UM Content Restriction settings do not work on my Register page. It's not redirecting logged in users.

### Steps to reproduce the behavior
I save the Register page. The error messages don't appear when saving other pages.

<img width="1276" alt="screen shot 2017-12-22 at 10 15 23 am" src="https://user-images.githubusercontent.com/18587286/34302904-0f4fa778-e701-11e7-836b-27a88285708e.png">

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern 

Please upgrade your UM2.0, I have added the fix in the latest commit.

Thanks!
