### ISSUE TITLE
Edit custom fields after registration?

### ISSUE THREAD

**Issue by stefahn** [ultimatemember/ultimatemember#368]
Using UM 1.3.88. On our site we need to be able to change the data in custom fields **after** a user has registered.

As stated in https://wordpress.org/support/topic/where-does-the-data-go-2/ the data is not accessible in the WordPress backend when the user is being edited. 

The data is stored in the user meta table and I could edit it via phpMyAdmin, but that is very cumbersome and not feasible for my client.

Is there a way to edit the data of custom fields in the WordPress backend?
If not, I would like to suggest this as a feature. I think it would be very helpful to many users.

Regards,
Stefan

**Comment by champsupertramp** [comment]
Hi,

Thanks for letting us know. Unfortunately, it is not possible to modify the user data from UM custom field in WP backend. I've added this in the feature request list.

Regards,

**Comment by stefahn** [comment]
Yeah, it would be great if you added this feature. Also read to pay for this. 
Can you estimate when / whether you will implement this? 
Thanks!
