### ISSUE TITLE
Choices Callback setting throwing error

### ISSUE THREAD

**Issue by treechime** [ultimatemember/ultimatemember#369]
### Ultimate Member Version
2.0 (beta)

### Subject of the issue
`Notice: Undefined index: parent_dropdown_relationship in [...]\wp-content\plugins\ultimate-member\includes\core\class-fields.php on line 680`

### Expected behavior
Adding a function to "Choices Callback" for a multi-select field should populate choices with choices from callback function.

### Actual behavior
Choices are populated as expected, however also throws above error.

Checking if the index exists on line 680 fixes error. e.g. `$arr_options = call_user_func( $data['custom_dropdown_options_source'], ( isset($data['parent_dropdown_relationship']) ? $data['parent_dropdown_relationship'] : '' ) );`

### Steps to reproduce the behavior
1. Create custom multi-select field with a callback function that returns an array of key value pairs and add it to the Profile field.
2. View profile to see error

**Secondary question:** Can choices callback also be added to checklist field types?

**Comment by nikitasinelnikov** [comment]
Hi @treechime 

Thanks for your feedback, I have added the fix to the latest commit. Please provide more clear description about "Can choices callback also be added to checklist field types?", maybe some screenshots what do you mean.

Thanks!

**Comment by treechime** [comment]
Creating a multi-select field with Choices Callback option

![image](https://user-images.githubusercontent.com/8661599/35596748-e7709f84-0666-11e8-8302-11ff51f2338d.png)

Creating a checkbox/radio button field, does not have a Choices Callback option

![image](https://user-images.githubusercontent.com/8661599/35596771-ff14813c-0666-11e8-8339-c2b7ef0b0d37.png)

I imagine it would be relatively the same logic between the different fields, so not difficult to implement?
