### ISSUE TITLE
Fixes for multiple redirection in category restrictions

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#37]
Here's a fix for multiple login redirection issue:
https://github.com/ultimatemember/ultimatemember/commit/f6ef053dda7e940f0fa00a2aa610fc5482df70ef

**Comment by ultimatemember** [comment]
Is this patched?

**Comment by champsupertramp** [comment]
@ultimatemember yes, but pushed in /dev/ branch.

**Comment by ultimatemember** [comment]
Thanks
