### ISSUE TITLE
Account page empty after update to 2.0

### ISSUE THREAD

**Issue by scrobbleme** [ultimatemember/ultimatemember#371]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0 ( beta )

### Subject of the issue
The account page is empty. 

![image](https://user-images.githubusercontent.com/504835/34671134-95b1aa0c-f479-11e7-9bc1-85baa0cf2c69.png)

### Expected behavior
Account related settings

### Actual behavior
Nothing is shown, at least a log:

`AH01071: Got error 'PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/XYZ/wp-content/plugins/ultimate-member/templates/account.php on line 25\n', referer: https://XYZ/wp-admin/post.php?post=18&action=edit`

### Steps to reproduce the behavior

update to 2.0

### Do you use UM extensions? 

none

**Comment by nikitasinelnikov** [comment]
Hi @scrobbleme 

Please try to install the latest version from there https://github.com/ultimatemember/ultimatemember master branch. If the issue still exists you can write me directly to email nsinelnikov.work@gmail.com or write to UM HelpScout support system. I cannot investigate this issue at my test site, so I need you wp-admin/FTP credentials.

Thanks!

**Comment by scrobbleme** [comment]
@nikitasinelnikov Thank you. Latest master is working again.
