### ISSUE TITLE
UM 2.0 copies email templates into theme directory.

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#372]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
It appears that UM 2.0 is creating a directory within the theme or child theme of the site that is running it called `ultimate-member` with the subdirectory `emails` that contains all the email templates. 

Can you not do that? Ideally, the plugin would not pollute the file directory of other plugins/themes. 

We are deploying and developing the site on a docker cluster and it is imperative that we have a deterministic file structure.

### Expected behavior
UM should not create directories outside of its own filesystem.

### Actual behavior
UM is creating directories outside of its own filesystem.

### Steps to reproduce the behavior
Install and activate the plugin.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users

**Comment by dsifford** [comment]
Example:

```
.
└── aliemu
    ├── assets
    │   ├── air-logo.svg
    │   ├── air-pro-logo.svg
    │   ├── aliemu-logo-horizontal.svg
    │   ├── aliemu-logo-u.svg
    │   ├── capsules-logo-pill.svg
    │   ├── capsules-logo.svg
    │   ├── completed.svg
    │   ├── notcompleted.svg
    │   └── team
    │       ├── adam-spaulding.png
    │       ├── allie-min.png
    │       ├── anand-swaminathan.png
    │       ├── andy-grock.png
    │       ├── brent-thoma.png
    │       ├── bryan-hayes.png
    │       ├── chris-edwards.png
    │       ├── chris-gaafary.png
    │       ├── craig-coccio.png
    │       ├── david-juurlink.png
    │       ├── derek-sifford.png
    │       ├── eric-morley.png
    │       ├── fareen-zaver.png
    │       ├── felix-ankel.png
    │       ├── george-hughes.png
    │       ├── glenn-oettinger.png
    │       ├── jay-khadpe.png
    │       ├── jeff-riddell.png
    │       ├── jeremy-branzetti.png
    │       ├── jill-logan.png
    │       ├── jonathan-bronner.png
    │       ├── jonathan-giordano.png
    │       ├── kasey-mekonnen.png
    │       ├── lalena-yarris.png
    │       ├── lewis-nelson.png
    │       ├── lynn-roppollo.png
    │       ├── mark-culver.png
    │       ├── meghan-groth.png
    │       ├── meg-pusateri.png
    │       ├── michael-craddick.png
    │       ├── michael-winters.png
    │       ├── michelle-hines.png
    │       ├── michelle-lin.png
    │       ├── nadia-awad.png
    │       ├── nana-sefa.png
    │       ├── nikita-joshi.png
    │       ├── paul-takamoto.png
    │       ├── rob-bryant.png
    │       ├── rob-cooney.png
    │       ├── robert-pugliese.png
    │       ├── salim-rezaie.png
    │       ├── scott-weiters.png
    │       ├── sean-mcgann.png
    │       ├── seth-trueger.png
    │       ├── taku-taira.png
    │       ├── team-placeholder.svg
    │       ├── teresa-chan.png
    │       ├── travis-manasco.png
    │       └── zlatan-coralic.png
    ├── editor.css
    ├── editor.css.map
    ├── footer.php
    ├── functions.php
    ├── header.php
    ├── js
    │   ├── educator-dashboard.js
    │   ├── educator-dashboard.js.map
    │   ├── nav-helper.js
    │   ├── nav-helper.js.map
    │   └── particles.js
    ├── learndash
    │   ├── course_content_shortcode.php
    │   ├── course_list_template.php
    │   ├── course.php
    │   └── lesson.php
    ├── lib
    │   ├── learndash.php
    │   ├── misc.php
    │   ├── script-loader
    │   │   ├── index.php
    │   │   └── localizers
    │   │       └── educator-dashboard.php
    │   ├── shortcodes.php
    │   ├── slack.php
    │   └── ultimate-member.php
    ├── page-about.php
    ├── page-air.php
    ├── page-air-pro.php
    ├── page-aliemu-team.php
    ├── page-capsules.php
    ├── page-faculty-start.php
    ├── page-feedback.php
    ├── page-home.php
    ├── page-login.php
    ├── page-user-agreement.php
    ├── page-user.php
    ├── style.css
    ├── style.css.map
    └── ultimate-member
        └── email
            ├── approved_email.php
    │       ├── changedpw_email.php
    │       ├── checkmail_email.php
    │       ├── deletion_email.php
    │       ├── inactive_email.php
    │       ├── notification_deletion.php
    │       ├── notification_new_user.php
    │       ├── notification_review.php
    │       ├── pending_email.php
    │       ├── rejected_email.php
    │       ├── resetpw_email.php
    │       └── welcome_email.php
    └── vendor
```

**Comment by dsifford** [comment]
Example:

```
.
└── my-site
    ├── functions.php
    ├── header.php
    └── ultimate-member
        └── email
            ├── approved_email.php
            ├── changedpw_email.php
            ├── checkmail_email.php
            ├── deletion_email.php
            ├── inactive_email.php
            ├── notification_deletion.php
            ├── notification_new_user.php
            ├── notification_review.php
            ├── pending_email.php
            ├── rejected_email.php
            ├── resetpw_email.php
            └── welcome_email.php
```

**Comment by treechime** [comment]
+1 this is so against WordPress best practices.

**Comment by nikitasinelnikov** [comment]
Hi @dsifford and @treechime 

This is a fairly popular practice for editing templates. By default when you install Ultimate Member plugin there are not any folders at yout theme/child theme. If you start to edit any templates (pages or email notification) when we create at your theme/child theme file with edited template.

Please look into Woocommerce product, they have the same logic - if you need to edit template, you need to place it in your theme/child theme. 

The best practice for this - is creating child theme, where will be stored all custom files and you will be able upgrade any plugins/theme at any time without the fear of losing these modified files.

Thanks!

**Comment by dsifford** [comment]
@nikitasinelnikov Why not use the uploads directory?

**Comment by treechime** [comment]
@nikitasinelnikov yes, that's standard if I had customised something, but it automatically puts the folder there automatically with no customisations. That folder should only be there as overrides.

**Comment by momofone** [comment]
I have WooCommerce and The Events Calendar templates in my child theme folder - I thought that was pretty standard to override existing templates.

**Comment by dsifford** [comment]
But these are not overrides. @treechime and I both made zero modifications to the templates and yet the default ones were still automatically copied to the theme directory.

**Comment by nikitasinelnikov** [comment]
Hi @dsifford 

Did you installed 2.0 like clear install, or did you have 1.3.88 previously installed at your site?

Thanks!

**Comment by dsifford** [comment]
@nikitasinelnikov It was an update from 1.3.88.

**Comment by nikitasinelnikov** [comment]
Hi @dsifford and other guys!

Sorry for delay, we currently work with 2.0 official release. @dsifford there are some upgrades scripts, which run on upgrade (1.3.88->2.0 in this case). Because some customers maybe changed their email templates we decide to copy this templates in any case (template was changed or not) to theme templates directory for applying new email templates logic.

There are not any email templates at theme templates folder if fresh install is running. So in your case if it's really important and you didn't change email templates previously, you may delete this email templates from your theme and email notifiations will get this templates from plugin's folder.

Thanks!
