### ISSUE TITLE
Ability to bypass required fields by removing them from the DOM

### ISSUE THREAD

**Issue by matt-sanders** [ultimatemember/ultimatemember#376]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
When building a form, regardless of the mode, if a field is removed from the DOM before the form is submitted ( resulting in it's data not being present in the `$_POST` object ), the form validation will skip it's required check. This could potentially allow malicious users to bypass required checks.

### Expected behavior
All required fields should be checked for a value regardless of their value being set in the `$_POST` request. 

### Actual behavior
You can bypass required fields for successfull form validation.

### Steps to reproduce the behavior
Create a form, or take one of the defaults ( let's use the registration form for example ). the username field is required, but if you delete it from the DOM and then submit the form, no validation is thrown. The issue lies in two files:
```
// core/um-form.php line 102
$this->post_form = apply_filters('um_submit_post_form', $_POST);
```
This takes the `$_POST` request and sets it as the `post_form`. This is then sent from the hook `um_submit_form_errors_hook` to another function which eventually calls `um_submit_form_errors_hook_()` ( um-actions-form.php ) for validation. The issue occurs here:

```
// core/um-actions-form.php line 218
// $args in this case is the post_form object
if ( isset($args[$key]) ) {
   if ( isset( $array['required'] ) && $array['required'] == 1 ) {
     // ... do the rest of the validation
   }
}
```

This allows a savvy user to remove the required field from the sent `$_POST` object and completely bypass the validation. What I recommend is something like:
```
// core/um-form.php line 102

$this->form_data = $ultimatemember->query->post_data( $this->form_id ); // move this line up from below
if ( isset($this->form_data['custom_fields']) ){
   $custom_fields = unserialize( $this->form_data['custom_fields'] );
   $defaults = array();
   foreach ( $custom_fields as $key => $value ){
      $defaults[$key] = '';
   }
}

$this->post_form = apply_filters('um_submit_post_form', array_merge( $defaults, $_POST ));
```
There's possibly a better way to go about that, but just off the top of my head, the above would ensure that all the fields were at least set in the post_form object, and then overwritten with the correct values from the `$_POST` object later on if needed.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by matt-sanders** [comment]
@champsupertramp can I ask why this is closed please? I just tried this again with the latest version of ultimate member and the same behaviour exists. These are the steps I took:

1. Create a fresh install of WordPress
2. Install Ultimate Member
3. Add the default registration form shortcode to a page
4. Visit that page in an incognito window
5. Using Dev tools, delete the username field
6. Fill out all other fields and submit
7. User is erroneously created without specified username

To make sure that it wasn't just the username field, I created a new field, made that one required and followed the same steps. Again the form failed to check my required field and passed validation.

Guys, this is form validation 101, you don't rely on the front-end alone to verify the validity of your data. If you mark a field as required, it should be required. If a user is able to circumvent this in any way the logic is incorrect.

**Comment by champsupertramp** [comment]
Hi,

I apologize for the sudden closing of this issue as we are making the repo active. 

I confirmed this issue still occurs. I'm re-opening this ticket and provide you an update.


Regards,

**Comment by nikitasinelnikov** [comment]
Hi @matt-sanders ,

Could you check the latest version from the "master" branch. This issue could be fixed. Please let me know.

Thanks!

**Comment by matt-sanders** [comment]
Awesome guys, looks like it's fixed!
