### ISSUE TITLE
um-conditional.js breaks when jQuery.browser is not defined

### ISSUE THREAD

**Issue by leolabs** [ultimatemember/ultimatemember#377]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
um-conditional.js breaks when jQuery.browser is not defined, crashing the rest of the page JS

### Expected behavior
It should not throw an error but just ignore the check

### Actual behavior
`Uncaught TypeError: Cannot read property 'msie' of undefined`

### Steps to reproduce the behavior
Use jQuery 1.12.4

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by leolabs** [comment]
Fix: https://github.com/ultimatemember/ultimatemember/pull/378

**Comment by nikitasinelnikov** [comment]
Hi @leolabs 

This issue was fixed, thanks for your pull request. Minified scripts will be pushed soon.

Thanks!
