### ISSUE TITLE
Fixes for category/post restriction and redirection issue

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#38]
There's an issue with category restriction settings. It doesn't work when adding restriction in category and posts under categories.

Here's a fix:
https://github.com/ultimatemember/ultimatemember/commit/727e45f58d38264b0f1e2559fb384fd4630b5658

**Comment by ultimatemember** [comment]
This is in https://github.com/ultimatemember/ultimatemember/pull/35 right?

**Comment by champsupertramp** [comment]
@ultimatemember yes
