### ISSUE TITLE
The social login extension does not respect assigned roles. It always defaults to "member" role

### ISSUE THREAD

**Issue by sadiqodunsi** [ultimatemember/ultimatemember#382]
I have 2 registration forms that I assigned the role "Experts" and "customers" to.  

When a user registers using the normal registration forms, the roles are assigned accordingly. However, when a user registers using social login, they are always assigned to the default "member" role (which is in the ultimate member settings for "Default New User Role")

I followed the steps in this social login guide carefully but the behavior did not change.
http://docs.ultimatemember.com/article/223-social-login-assigning-roles

I use Ultimate Member Version 1.3.88

I use the following UM extensions
- [ ] Private Messages
- [ ] Social Login
- [ ] User Reviews
- [ ] Verified Users
- [ ] Online Users

Please help me asap. It is very urgent

**Comment by nikitasinelnikov** [comment]
Hi @sadiqodunsi 

This issue will be fixed in the next commit of UM2.0 and UM:Social Login. So I recommend to make your live site's backup or make it's dev copy and upgrade to 2.0 version. 

Thanks!

**Comment by sadiqodunsi** [comment]
Hi thanks for the response, I just updated to UM 2.0 but the issue persists and not only that my private messaging also stopped working after the upgrade.

**Comment by nikitasinelnikov** [comment]
Hi @sadiqodunsi 

We test/prepare commit with fix for social login now, so it will be released today later. Please provide more details about the issues with private messaging.

Thanks!

**Comment by sadiqodunsi** [comment]
Hi, 

I just realized that the user review extension is blocking the private messaging from working. Whenever I deactivate the user review extension the message extension works properly. I also noticed that when the user review extension is activated, it does not show the 5 star icon. 

Everything was working fine before I upgraded to UM 2.O. The problem I was having with the social login extension made me upgrade to 2.0 but it seems the upgrade is causing a lot of different issue. 

Please what can I do about the review extension as it is very important for my business.

P.s. I have deactivated all other plugins and switched to default twenty-fifteen theme but the problem persists. Thus, the UM review extension is the problem. 

 Also, let me know when you release the fixed version of social login.

Thanks

**Comment by sadiqodunsi** [comment]
Hi, 

There is also a problem with my terms and conditions extension. Whenever I click show terms on the registration form, it opens another registration page on the same form instead of showing the terms and conditions page.

And whenever it is activated, the registration page always refreshes after clicking submit.

Thanks
Sadiq Odunsi

**Comment by nikitasinelnikov** [comment]
Hi @sadiqodunsi 

Please try to download the latest versions (core + extensions) from ultimatemember.com The fix for social login is already released. There more info about how download the latest versions http://docs.ultimatemember.com/article/262-manually-updating-to-2-0 

If the issue still persists, please create ticket in our support system for we can help you and do some debug steps at your site. https://ultimatemember.com/support/ticket/

Thanks!
