### ISSUE TITLE
Profile access per roles is not honored

### ISSUE THREAD

**Issue by amr3li** [ultimatemember/ultimatemember#384]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( latest )
- [x ] 2.0 ( beta )

### Subject of the issue
User Role Setting > Profile Access, not honoring (Can view these user roles only)

### Expected behavior
User is meant to view only selected roles

### Actual behavior
User can view all roles profile even if its not allowed in assigned role settings

### Steps to reproduce the behavior
Create a user directory with multiply roles to display, check a user profile of those roles viewer is not allowed to view and the viewer will be allowed to view the profile page and profile card in the directory.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users

**Comment by jonbarratt** [comment]
Not sure if this is related. However, um_user( 'role' ) appears to be picking up the WordPress role rather than the UM role. This is most clearly evident in the class addition to profiles and directories where a simple browser inspection reveals the um-role-xxxxxx class as added to the member's profile element. The xxxxxx is the WordPress role, not the UM role.

**Comment by nikitasinelnikov** [comment]
hi @amr3li 

There was added fixes for this issue, please check how it works at the latest UM2.0
You can download it from "master" branch

Thanks!

**Comment by amr3li** [comment]
Hello @nikitasinelnikov

Alright will check and share the results.

Many thanks
