### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function wpml_object_id_filter()

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#385]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Fatal error: Uncaught Error: Call to undefined function wpml_object_id_filter()

### Actual behavior
I see the following error when I log in to my site from the frontend.

Fatal error: Uncaught Error: Call to undefined function wpml_object_id_filter() in /public_html/wp-content/plugins/ultimate-member/includes/um-short-functions.php:678 Stack trace: #0 /public_html/wp-content/plugins/ultimate-member/includes/core/class-rewrite.php(186): um_is_core_page('user') #1 /public_html/wp-includes/class-wp-hook.php(286): um\core\Rewrite->locate_user_profile('') #2 /public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /public_html/wp-includes/template-loader.php(12): do_action('template_redire...') #5 /public_html/wp-blog-header.php(19): require_once('/home/thefrankl...') #6 /public_html/index.php(17): require('/home/thefrankl...') #7 {main} thrown in /public_html/wp-content/plugins/ultimate-member/includes/um-short-functions.php on line 678

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern 

This issue was already fixed today, please re-download UM2.0 and check

Let me know,
Thanks!
