### ISSUE TITLE
Default to Privacy ON

### ISSUE THREAD

**Issue by ahinerfeld** [ultimatemember/ultimatemember#386]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
I would like for all new users to have Privacy set to on by default.  Then the user can choose to tun it off if they would like.

### Expected behavior
I would like all new users to default to Privacy ON

### Actual behavior
New users have to turn Privacy ON

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @ahinerfeld,

Please use some of UM hooks after user registration ( 'um_user_register' or 'um_registration_complete' )

And add action to this hook with this code:
update_user_meta( $user_id, 'profile_privacy', __('Only me','ultimate-member') );

Thanks!
