### ISSUE TITLE
Content restriction not working as it should

### ISSUE THREAD

**Issue by codepanov** [ultimatemember/ultimatemember#387]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
Content restricted page is not so restricted

### Expected behavior
After selecting a page from the menu link for the second time, logged out user should stay on a login page.

### Actual behavior
The page has a custom access setting set to Content accessible to Logged In Users. A logged out user after clicking on a menu is diverted to login page, which is fine, but when clicked again, from that login page, the user now finds him self on that content restricted page.

### Steps to reproduce the behavior
Make two pages. One accessible to everyone, and another set to Content accessible to Logged In Users.
Make a menu with link to both pages. Go to the page that is accessible to everyone. Stay logged out. On the menu, select the page with restricted content, when you find your self on a login page, click again on a menu, selecting again a content restricted page.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @codepanov 

Please upgrade UM to the latest version at "master" branch (2.0.1). There was added many fixes for content restriction functionallity.

Thanks!

**Comment by codepanov** [comment]
Thank you.
