### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by frisgaard** [ultimatemember/ultimatemember#389]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
Danish translation

### Expected behavior
Showing danish strings instead of english

### Actual behavior
Showing non-translated strings in frontend forms and i'm 100% sure the strings is translated in the downloaded language files.

### Steps to reproduce the behavior
I've downloaded the danish language files for Ultimate Member but still frontend forms has non-translated strings which i'm 100% sure is translated in the downloaded language files.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @frisgaard 

Did you tried to use the latest UM2.0.2 version? Please also provide screenshots where do you see not translated strings.

Thanks!

**Comment by frisgaard** [comment]
Hi @nikitasinelnikov,

When tried to activated the UM2.0.2 plugin I get this error: "Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /wp-content/plugins/ultimate-member/includes/class-init.php on line 134"...

But I have now solved the problem myself:

When downloading files from the Wordpress translating-site, I get a file named as ultimatemember-da_DK.(mo and po), but it should be named ultimate-member-da_DK.(mo and po)... - Now it works as expected...

Regards
Asger Frisgård

**Comment by nikitasinelnikov** [comment]
Hi @frisgaard,

What PHP version do you use? UM2.0 works properly since PHP5.6

Please let me know
Thanks!

**Comment by frisgaard** [comment]
I'm sorry, i've forgot to check the php-version and when i do, I found out it was much older than I think - I'll immediately contact my hosting provider to get it upgraded....
