### ISSUE TITLE
Transferring To Redesign

### ISSUE THREAD

**Issue by BetaStacks** [ultimatemember/ultimatemember#392]
Quick Question: 
Is there documentation on how to migrate my current Ultimate Member users from my current site to a fresh new WordPress install?

**Comment by nikitasinelnikov** [comment]
Hi @BetaStacks 

For me the best plugin to migrate sites is "All in one WP Migration". Do you need to transfer only users? 

Thanks!

**Comment by BetaStacks** [comment]
Thanks for the reply!
I'll check it that tool out.

All of the content is going to be redone so I just need the users.
