### ISSUE TITLE
Image Upload on General account tab not working properly

### ISSUE THREAD

**Issue by gRoberts84** [ultimatemember/ultimatemember#394]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
On both 1.3.88 and 2.0.2, when uploading an image via the account general page, the image is not moved to the users upload folder and the temporary upload URL is stored instead of the image filename.

### Expected behavior
The uploaded image should be moved to the users upload folder and the filename should be stored in the users meta data as it is when registering.

### Actual behavior
The uploaded image remains in the temporary upload folder and the temporary upload URL is stored instead of the image filename.

### Steps to reproduce the behavior
Add an image upload field to the default form.

Configure the account generate tab to render the additional fields:

```
add_action('um_after_account_general', 'show_extra_fields', 100);
function show_extra_fields() {

  global $ultimatemember;
  $id = um_user('ID');
  $output = '';

  $names = [ 'upload_image' ];

  $fields = [];
  foreach( $names as $name )
    $fields[ $name ] = UM()->builtin()->get_specific_field( $name );

  $fields = apply_filters( 'um_account_secure_fields', $fields, $id );

  foreach( $fields as $key => $data )
    $output .= UM()->fields()->edit_field( $key, $data );

  echo $output;
}
```

Upload an image and click update.
Note upon reload, that a 404 error occurs and the image no longer shows.
Also note, that the hidden field containing the current value contains the temporary URL:

    <input type="hidden" name="upload_image" id="upload_image" value="http://www.domain.co.uk/wp-content/uploads/ultimatemember/temp/6TnisCw9AhJ2RqtiUca2MDzIK0EHsuRNs7WwDzay/stream_photo_88ff0fb9a13aefe92a291e6c5b45c355_5aa82da4aed5b.jpg">

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by jaystream** [comment]
We are having this issue. Is there any workaround?

**Comment by champsupertramp** [comment]
Unfortunately, The upload image field in the account form is not yet supported. This requires customisation on your end.

Regards,

**Comment by jaystream** [comment]
> Unfortunately, The upload image field in the account form is not yet supported. This requires customisation on your end.
> 
> Regards,

Yeah.. Thanks.. I got it working.. :)

**Comment by Jeopardy11** [comment]
thanks for the code..but where should i paste it..i don't have any coding skills...please assist...my profile/cover photo stucks on processing screen after i finish cropping the image..

**Comment by jaystream** [comment]
These are the code I've made it to work:
Created a video (https://www.youtube.com/watch?v=XhPndve0BAM) for explanation. Sorry for my english.

`add_filter( 'um_account_tab_general_fields', 'showAccountExtraFields', 10, 2 );
function showAccountExtraFields($args, $shortcode_args) {
    $args .= ',company_logo';
    return $args;
}

/**
 * Add fields to created account tab
 *
 * @return [type] [description]
 */
function xwb_predefined_fields_hook($fields){


    $post_data = UM()->query()->post_data( 5 );

    $customFields = maybe_unserialize($post_data['custom_fields']);

    $fields['company_logo'] = $customFields['company_logo'];


    return $fields;
}
add_filter( 'um_predefined_fields_hook', 'xwb_predefined_fields_hook' );


add_action('template_redirect', 'xwb_download_routing',11);
/**
 * Download link customization
 *
 * @return [type] [description]
 */
function xwb_download_routing() {
    if ( 'download' !== get_query_var( 'um_action' ) ) {
        return false;
    }

    $query_form = get_query_var( 'um_form' );
    if ( empty( $query_form ) ) {
        return false;
    }

    $form_id = get_query_var( 'um_form' );
    $query_field = get_query_var( 'um_field' );
    if ( empty( $query_field ) ) {
        return false;
    }
    $field_key = urldecode( get_query_var( 'um_field' ) );
    $query_user = get_query_var( 'um_user' );
    if ( empty( $query_user ) ) {
        return false;
    }

    $user_id = get_query_var( 'um_user' );
    $user = get_userdata( $user_id );

    if ( empty( $user ) || is_wp_error( $user ) ) {
        return false;
    }
    $query_verify = get_query_var( 'um_verify' );
    if ( empty( $query_verify ) ||
        ! wp_verify_nonce( $query_verify, $user_id . $form_id . 'um-download-nonce' ) ) {
        return false;
    }

    um_fetch_user( $user_id );
    $field_data = get_post_meta( $form_id, '_um_custom_fields', true );

    if ( empty( $field_data[ $field_key ] ) ) {
        //return false;
    }

    if ( ! um_can_view_field( $field_data[ $field_key ] ) ) {
        return false;
    }

    $field_value = UM()->fields()->field_value( $field_key );
    if ( empty( $field_value ) ) {
        return false;
    }

    $download_type = $field_data[ $field_key ]['type'];
    if ( $download_type === 'file' ) {
        UM()->files()->file_download( $user_id, $field_key, $field_value );
    } else {
        UM()->files()->image_download( $user_id, $field_key, $field_value );
    }

    return false;
}




add_filter('um_after_user_account_updated','xwb_after_user_account_updated',10,2);
/**
 * Hook when updating an account
 *
 * @param  [type] $user_id [description]
 * @param  [type] $changes [description]
 * @return [type]          [description]
 */
function xwb_after_user_account_updated($user_id, $changes){
    $args['submitted'] = $changes;
    $post_data = UM()->query()->post_data( 5 );
    $fields = maybe_unserialize($post_data['custom_fields']);

    // loop through fields
    if ( ! empty( $fields ) ) {

        foreach ( $fields as $key => $array ) {

            if ( ! isset( $array['type'] ) ) {
                continue;
            }

            if ( isset( $array['edit_forbidden'] ) ) {
                continue;
            }

            // required option? 'required_opt' - it's field attribute predefined in the field data in code
            if ( isset( $array['required_opt'] ) ) {
                $opt = $array['required_opt'];
                if ( UM()->options()->get( $opt[0] ) != $opt[1] ) {
                    continue;
                }
            }

            // fields that need to be disabled in edit mode (profile) (email, username, etc.)
            $arr_restricted_fields = UM()->fields()->get_restricted_fields_for_edit( $user_id );
            if ( in_array( $key, $arr_restricted_fields ) ) {
                continue;
            }

            if ( ! um_can_edit_field( $array ) || ! um_can_view_field( $array ) ) {
                continue;
            }

            //the same code in class-validation.php validate_fields_values for registration form
            //rating field validation
            if ( $array['type'] == 'rating' && isset( $args['submitted'][ $key ] ) ) {
                if ( ! is_numeric( $args['submitted'][ $key ] ) ) {
                    continue;
                } else {
                    if ( $array['number'] == 5 ) {
                        if ( ! in_array( $args['submitted'][ $key ], range( 1, 5 ) ) ) {
                            continue;
                        }
                    } elseif ( $array['number'] == 10 ) {
                        if ( ! in_array( $args['submitted'][ $key ], range( 1, 10 ) ) ) {
                            continue;
                        }
                    }
                }
            }


            /**
             * Returns dropdown/multi-select options keys from a callback function
             * @since 2019-05-30
             */
            $has_custom_source = apply_filters( "um_has_dropdown_options_source__{$key}", false );
            if ( isset( $array['options'] ) && in_array( $array['type'], array( 'select', 'multiselect' ) ) ) {

                $options = array();
                if ( ! empty( $array['custom_dropdown_options_source'] ) && function_exists( $array['custom_dropdown_options_source'] ) && ! $has_custom_source  ) {
                    $callback_result = call_user_func( $array['custom_dropdown_options_source'], $array['options'] );
                    if ( is_array( $callback_result ) ) {
                        $options = array_keys( $callback_result );
                    }
                }

                $array['options'] = apply_filters( "um_custom_dropdown_options__{$key}", $options );

            }


            //validation of correct values from options in wp-admin
            $stripslashes = '';
            if ( isset( $args['submitted'][ $key ] ) && is_string( $args['submitted'][ $key ] ) ) {
                $stripslashes = stripslashes( $args['submitted'][ $key ] );
            }

            if ( in_array( $array['type'], array( 'select' ) ) ) {
                if ( ! empty( $array['options'] ) && ! empty( $stripslashes ) && ! in_array( $stripslashes, array_map( 'trim', $array['options'] ) ) && ! $has_custom_source  ) {
                    continue;
                }

                //update empty user meta
                if ( ! isset( $args['submitted'][ $key ] ) || $args['submitted'][ $key ] == '' ) {
                    update_user_meta( $user_id, $key, '' );
                }
            }

            //validation of correct values from options in wp-admin
            //the user cannot set invalid value in the hidden input at the page
            if ( in_array( $array['type'], array( 'multiselect', 'checkbox', 'radio' ) ) ) {
                if ( ! empty( $args['submitted'][ $key ] ) && ! empty( $array['options'] ) ) {
                    $args['submitted'][ $key ] = array_map( 'stripslashes', array_map( 'trim', $args['submitted'][ $key ] ) );
                    $args['submitted'][ $key ] = array_intersect( $args['submitted'][ $key ], array_map( 'trim', $array['options'] ) );
                }

                // update empty user meta
                if ( ! isset( $args['submitted'][ $key ] ) || $args['submitted'][ $key ] == '' ) {
                    update_user_meta( $user_id, $key, array() );
                }
            }

            if ( isset( $args['submitted'][ $key ] ) ) {

                if ( isset( $array['type'] ) && in_array( $array['type'], array( 'image', 'file' ) ) ) {

                    if ( um_is_temp_file( $args['submitted'][ $key ] ) || $args['submitted'][ $key ] == 'empty_file' ) {
                        $files[ $key ] = $args['submitted'][ $key ];
                    } elseif( um_is_file_owner( UM()->uploader()->get_upload_base_url() . $user_id . '/' . $args['submitted'][ $key ], $user_id ) ) {

                    } else {
                        $files[ $key ] = 'empty_file';
                    }

                } else {
                    if ( $array['type'] == 'password' ) {
                        $to_update[ $key ] = wp_hash_password( $args['submitted'][ $key ] );
                        $args['submitted'][ $key ] = sprintf( __( 'Your choosed %s', 'ultimate-member' ), $array['title'] );
                    } else {
                        if ( isset( $userinfo[ $key ] ) && $args['submitted'][ $key ] != $userinfo[ $key ] ) {
                            $to_update[ $key ] = $args['submitted'][ $key ];
                        } elseif ( $args['submitted'][ $key ] != '' ) {
                            $to_update[ $key ] = $args['submitted'][ $key ];
                        }
                    }

                }

            }
        }
    }



    if ( ! empty( $files ) && is_array( $files ) ) {
        UM()->uploader()->replace_upload_dir = true;
        UM()->uploader()->move_temporary_files( $user_id, $files, true );
        UM()->uploader()->replace_upload_dir = false;
    }
}`
