### ISSUE TITLE
Content restriction does not work when using a third-party visual editor (Goodlayers Page builder, Visual Composer)

### ISSUE THREAD

**Issue by netunia** [ultimatemember/ultimatemember#398]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Content restriction does not work when using a third-party visual editor (Goodlayers Page builder, Visual Composer) on pages and posts

### Expected behavior
Content restriction does not work when using a third-party visual editor (Goodlayers Page builder, Visual Composer) on pages and posts.

In the version of the plugin UM 2.0.2 from March 12, 2018 content restriction (on pages and posts) does not work if the content on them was created through a third-party visual editor (for example: Goodlayers Page builder, VC).

When editing and creating content through the standard visual editor WordPress, content restriction works correctly.

What were the settings?
Global access to the site is open.

In the "UM Content Restriction" settings area for a particular page or post, "Show access restricted message" and a restriction for editors and members are specified.

In version 1.3.88, there is no problem with restricting content when creating pages using a third-party visual editor.

### Do you use UM extensions? 
No.

**Comment by nikitasinelnikov** [comment]
Hi @netunia 

I have checked this issue at my test install with visual composer plugin and seems this works properly https://www.screencast.com/t/YQ8rmlmbxKN

If it still not works for you please provide the more clear description with screenshots.
Also will be nice if you send zip archives with page builder plugins where you see the problem.

Thanks!
