### ISSUE TITLE
Unable to complete an upload for profile/cover photo

### ISSUE THREAD

**Issue by CpopPhoto** [ultimatemember/ultimatemember#4]
After initalizing the app, everything seems to work well except when I go to try to upload a profile photo or cover photo. It comes up but it appears below the window with no ability to scroll down to it. How can this be resolved so members may upload photos?
![image](https://cloud.githubusercontent.com/assets/11262752/6434024/e0c559d0-c04c-11e4-8620-e52456b8a993.png)

**Comment by ultimatemember** [comment]
As this is not a general issue with the plugin, and is probably a conflict. Please post this issue on the forums so we can have private details to our tests. Post it here please https://ultimatemember.com/forums/
