### ISSUE TITLE
Main menu disappears for logged in users under role specific accessible settings for one menu entry

### ISSUE THREAD

**Issue by MartNytrm** [ultimatemember/ultimatemember#400]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0.2 ( beta )

### Subject of the issue
There seem to be a (main) menu appearance issue, when using some role specific Ultimate Member visibility settings for menu entries.

### Expected behavior
If you want a menu entry to be visible for only some user roles when logged in, only this menu entry should disappear for logged out users and the wanted logged in roles. 
The menu should not disappear completely for logged in users, no matter if they should see the one entry or not.

### Actual behavior
Main menu completely disappears for logged in admin-user (and potentially for all logged in users), when one menu entry is set to be only visible for some logged in user roles.
These settings seem to work for logged out users correctly though.

### Steps to reproduce the behavior

1. The Wordpress roles are standard and here everything is done by "Admin".

2. Set Ultimate Member's "Global Site Access " to "Site accessible to Everyone".

3. Create one test page "testpage" and add it to your main menu (-> "testpage" is shown in menu for logged out and logged in users).

4. Now, change the "Ultimate Member Menu Settings" of your "testpage" to "Logged In Users" and choose for example "admin" and "editor" (others work, too).

5. After this, the issue occurres and the main menu is not displayed at all for the logged in user "Admin" (maybe others, too). Whereas when you log out, the menu reappears and, like wanted, the "testpage" menu entry is hidden.

### Do you use UM extensions? 
- [x] Google reCAPTCHA

### (in addition) Reproducible for:
Ultimate Member Version: 2.0.2 (manually upgraded from 1.3.88)
Ultimate Member Addons: none
Further Wordpress Addons: none

**and** 

Ultimate Member Version: 2.0.2 (fresh install)
Ultimate Member Addons: 
    - Google reCAPTCHA
Further Wordpress Addons: 
    - All In One WP Security
    - BackUpWordPress
    - Cooked
    - Enable Media Replace
    - Knowledge Base for Documents and FAQs
    - My Calendar
    - Recent Posts Widget With Thumbnails
    - WP Mail SMTP

**and**

tested with diffrent Wordpress themes.

Thanks,

Nytrm

**Comment by KloppProductions** [comment]
Having the same issues with my websites since the UM 2.0 update. Only the Core UM plugin is activated (all other plugins deactivated, and also with default Wordpress theme) get a Top Menu ID error.

**Comment by KloppProductions** [comment]
Was able to resolve the issue by editing the user roles of UM Members and built new menus. All issues seemed to be gone. Probably not resolved for future users who update to UM Core 2.0.4. This still needs to be reviewed by UM support.

**Comment by MartNytrm** [comment]
@KloppProductions 

> by editing the user roles

What exactly did you edit there?

The thing is, I'll get this issue with a complete new installation as well, if I follow the mentioned reproduction steps, although it was with version 2.0.2 (beta). 
If I have time today, I will retry my reproduction steps with a complete new installation under 2.0.4.

**Comment by masimies** [comment]
Noticed this same after new release. Menus are working only with "logged in users". If you use any roles under it, menus are disappearing. I have used "Nav menu roles" plugin what handle this with selected roles, so UM is not needed for this functionality, until fixed somehow.

**Comment by MartNytrm** [comment]
**To fix the disappearing menu manually:**
(Successfully tested under version 2.0.4.)

1. Set a "_Role Priority_" for your _Administrator_ role. I choose the value "_10_", some other users took the "_1_", it seems, it does not matter. Click "_Update Role_".
(Settings can be found here: Ultimate Member -> User Roles -> Administrator > Priority Role)

2. Menu should reappear for logged in admin.

3. (OPTIONAL) You can revert your set administrator "_Priority Role_" back to _nothing_ and the menu would still work and is shown.

Because I did this under version 2.0.4, I can't tell, if the **update 2.0.5/2.0.6** (from April 12, 2018) fix this issue by itself without user intervention, but the changelog did mention a fix for it:
2.0.6: April 12, 2018

    Bugfixes:
        Fixed nav-menu content restriction issues for Administrator role

2.0.5: April 12, 2018

    Bugfixes:
        Fixed old pre2.0 extensions notices
        Fixed nav-menu content restriction issues
        Fixed lost password URL in UM Login Form
        Fixed restriction message on taxonomy page, which is restricted

Because of the manual fix that worked for many users
(https://wordpress.org/support/topic/um-2-0-4-primary-menu-not-visible-when-logged-in-as-admin/
https://wordpress.org/support/topic/update-broke-my-menu-2/
https://wordpress.org/support/topic/update-broke-my-menu/
https://wordpress.org/support/topic/um-2-0-4-menus-disappear/)
and the hope that especially version 2.0.6 will fix this issue, i will close this issue.

@masimies If you could try to update to version 2.0.6 or do the manual fix, and tell me if it worked for you, we can be completely safe about this.
If it won't work, we can open the issue again.

**Comment by masimies** [comment]
It's working now with 2.0.7 version! Didn't test with previous at all.

**Comment by MartNytrm** [comment]
> It's working now with 2.0.7 version!

Sounds good!
