### ISSUE TITLE
Create a new tab in version 2.0

### ISSUE THREAD

**Issue by katsar0v** [ultimatemember/ultimatemember#401]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x ] 2.0 ( beta )

### Subject of the issue
Create new account tab 

### Expected behavior
I expect to create a new tab
### Actual behavior
Nothing happens

### Steps to reproduce the behavior
Use hook from last stable 1.x version

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

Also is there going to be any API Documentation for version `2.0` ? Thanks!

**Comment by nikitasinelnikov** [comment]
Hi @katsar0v 

There is the latest version's "Hooks List". Separated by (Actions|Filters) https://docs.ultimatemember.com/article/1324-hooks-list

You can use "um_account_page_default_tabs_hook" hook for add account tabs.

Thanks

**Comment by katsar0v** [comment]
Thank you, that's what I needed, could not find it working for the `2.0` beta version. The issue is resolved, are there any guides I can follow (patterns, example) so that my extension can also look visually integration? Thanks!

**Comment by nikitasinelnikov** [comment]
Hi @katsar0v 

Great! Please provide what do you mean "visually integration"? UM team is under 2.0 version official release preparing. So, other docs will be ready for official release or as soon as possible after release.

Thanks!
