### ISSUE TITLE
Wrong URL of buttons on profile page in WP Multisite

### ISSUE THREAD

**Issue by shozibabbas** [ultimatemember/ultimatemember#404]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
UM redirects to URL "https://www.myurl.com/xp/xp/?profiletab=posts" on clicking profile tab button. Rest of the buttons are in the same way. I am on multisite wordpress.

### Expected behavior
UM should redirect to URL "https://www.myurl.com/xp/?profiletab=posts" on clicking profile tab button and all others.

### Actual behavior
UM redirects to URL "https://www.myurl.com/xp/xp/?profiletab=posts"

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @shozibabbas 

Did you try to use the latest UM2.0.2. Can you create dev site and run 1.3.88->2.0.2 upgrade and check how it works after the upgrade.

Please let me know,
Thanks!

**Comment by masimies** [comment]
Here was another issue opened of this same problem in #426

**Comment by shozibabbas** [comment]
The issue was because of a broken plugin. I don't remember the plugin name yet. But it got resolved when I disabled a broken plugin.
