### ISSUE TITLE
Redirections after login not working

### ISSUE THREAD

**Issue by Deardevils** [ultimatemember/ultimatemember#406]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
I am developing a website and there are some user groups. Each group’s user login via the login page form, should link to different pages.

For example, group A users login, and redirect to Landing page A.
group B users login, and redirect to Landing page B.

I can see there are settings available in each user role page, however, when I set the redirection url up, it doesn’t work. Always redirect to /account page.

Note: I have tested all the plugins and no conflicts at all. No cache plugins. UM version 1.3.88, WP version 4.9.4.

### Expected behavior
I didn't use login page redirection to override, so the redirection after logging in at user role page, should work, but actually it is not working.

### Actual behavior
Redirection not working at all, and it not redirect to profile page as well, it only can go to account page.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @Deardevils 

Please try to use the latest UM2.0 version from the repository "master" branch.

Thanks!

**Comment by PGWr** [comment]
I am having a similar problem. I setup a new role in UM. When I log in with a userid associated with that role it should go to a profile page. It goes to some type of altered form with just links to Account and Logout. I have 3 other roles set up from a few weeks ago and they all work fine.

For the one that does not work I get an odd URL: 
https://www.myresapp.com/login/?redirect_to=https%3A%2F%2Fwww.myresapp.com%2Fuser%2Fpaulemp%2F

Any help appreciated.
