### ISSUE TITLE
Remove !important classes from CSS

### ISSUE THREAD

**Issue by haydnjames** [ultimatemember/ultimatemember#407]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
CSS continues to include excessive overuse of !important making it incredibly difficult to style even the simplest of form elements, fields, buttons etc.

This issue was acknowledged previously here but was closed with no resolution?
https://github.com/ultimatemember/ultimatemember/issues/136

Either remove !important from core CSS or make it easier for developers to override it in other ways. For example, allowing the setting of classes for fields in the form builder the same as you can for rows and overall forms would be a good start.

### Expected behavior
CSS should only include !important when absolutely required to do so.

### Actual behavior
CSS includes !important in almost every element and declaration (over 500 instances across the included stylesheets).

### Steps to reproduce the behavior
Installation. 

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by albi** [comment]
I had the same problem and solved it with the following code that I've added to my functions.php:

`if(!is_admin() && $GLOBALS['pagenow'] != 'wp-login.php'){
	function unload_um_styles(){

		// Deregister & dequeue styles
		wp_dequeue_style(array(
			'um_fonticons_ii',
			'um_fonticons_fa',
			'select2',
			'um_modal',
			'um_styles',
			'um_members',
			'um_profile',
			'um_account',
			'um_misc',
			'um_fileupload',
			'um_datetime',
			'um_datetime_date',
			'um_datetime_time',
			'um_raty',
			'um_scrollbar',
			'um_crop',
			'um_tipsy',
			'um_responsive',
			'um_default_css',
		));

		wp_deregister_style(array(
			'um_fonticons_ii',
			'um_fonticons_fa',
			'select2',
			'um_modal',
			'um_styles',
			'um_members',
			'um_profile',
			'um_account',
			'um_misc',
			'um_fileupload',
			'um_datetime',
			'um_datetime_date',
			'um_datetime_time',
			'um_raty',
			'um_scrollbar',
			'um_crop',
			'um_tipsy',
			'um_responsive',
			'um_default_css',
		));

	};
	add_action('wp_print_styles','unload_um_styles');
};`

But be careful as this removes all styles that are delivered by UM. But for my project this was no problem at all as I covered all form styles on my own.

**Comment by haydnjames** [comment]
Genius. Thank you! :)

**Comment by carasmo** [comment]
See: https://github.com/ultimatemember/ultimatemember/issues/522

**Comment by terryhauptza** [comment]
Hello, I've tried this but doesn't seem to change anything. I'd like to remove the !important css from the social activity plugin (assets/css/um-activity.min.css), can anyone point me in the right direction?

I'm using WP Astra Pro theme and Elementor (Pro).

**Comment by mharif010** [comment]
``p`jjhjj`

**Comment by nchaccal** [comment]
Hi, 

Sorry for reopen this thread again. 

I want to know if there an easy way to remove the modal for upload files. 

I remove all the styles -with this code- and then try to rebuild the file upload function with a nice and simple button, but cant achieve it

Thanks in advance!
