### ISSUE TITLE
Optimise CSS and JS in final release of 2.0

### ISSUE THREAD

**Issue by haydnjames** [ultimatemember/ultimatemember#409]
Ultimate Member v2.0.2 loads over 40 different CSS and JS files individually. None of them minified.

These should be combined into single CSS and JS files and condensed where possible. 

Reducing file requests, reducing file sizes and improving page loads.

**Comment by RyanNutt** [comment]
Any update on this? I'm using 2.0.25 and it's loading a ton of JS and CSS files.

**Comment by haydnjames** [comment]
@champsupertramp Why did you close this? The CSS continues to be bloated.
