### ISSUE TITLE
Multi-language URLs

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#41]
hi @ultimatemember 

There's an issue with the Form links when Multi-language support is enabled. 

If a page url is www.example.com/fr/login/ (French), register button and forgot password links are still set as  www.example.com/en/login/ (English)

I found the issue in https://github.com/ultimatemember/ultimatemember/blob/master/core/um-short-functions.php#L427

It only filters URLs in 'account' screens. Login, Register and Forgot password slugs should be in the condition to apply the filter that swaps the URLs.

**Comment by champsupertramp** [comment]
I pushed a patch on dev branch: 
https://github.com/ultimatemember/ultimatemember/commit/2874e9227029bb720c99b770f36684e338c4304a

**Comment by ultimatemember** [comment]
Comitted to master. https://github.com/ultimatemember/ultimatemember/pull/45
