### ISSUE TITLE
¿wp-admin / wp-login screen? 2.0.4

### ISSUE THREAD

**Issue by bitcuantico** [ultimatemember/ultimatemember#412]
Hi!

Before I upload the lastest version of ultimatemember, I can access in the login page that UM create, and that was perfect, because I can't access via wp-admin or wp-login, but now that I upload I can't fin or restore that feature.

Can anybody help me please?

### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0.4 ( latest )

### Subject of the issue
Describe your issue here.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by masimies** [comment]
For ensure this i created a own page for redirect wp-admin and add it's link to menu. For administrators only.
`$backbuttonurl = "./wp-admin";
wp_redirect( $backbuttonurl );
exit;`

Then you do not need admin-bar either in FrontPage. And it's only better security if backend login is not available. Add google recaptcha-extension also to login-page.

**Comment by bitcuantico** [comment]
Yeah thanks, but I need that redirect to the custom login of ultimatemember. Can u help me?
