### ISSUE TITLE
Settings Page not Working

### ISSUE THREAD

**Issue by gitblair** [ultimatemember/ultimatemember#417]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue

Clicking Settings takes admin to front page.

I’ve disabled all other plugins and testing with Twenty Seventeen wordpress theme.
I’ve also tried uninstalling and reinstalling.

### Expected behavior
Should take you to settings.

### Actual behavior
Redirects to front page of website

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
can you provide screencast or video with this issue. seems we cannot investigate it at our test site
