### ISSUE TITLE
Integration broken with AffiliateWP add-on Signup Referals

### ISSUE THREAD

**Issue by gspice** [ultimatemember/ultimatemember#421]
### Ultimate Member Version
`2.0.9` recently released

### Subject of the issue
Reported by our user -- Integration with **AffiliateWP - Signup Referrals** is broken.  It no longer shows **Ultimate Member** as an option to create referrals from new UM registrations.   

### Expected behavior
In your previous released version `1.3.88` this is how the settings appeared:

![um-1 3 88](https://user-images.githubusercontent.com/3018245/38837860-81846d10-4188-11e8-93fc-fa3e718c5f5b.png)

### Actual behavior
The Signup Referrals settings in `2.0.9`, now the Ultimate Member options are not available to select so a referral is not generated when a new user registers through the UM register page.

![version-2 0 9](https://user-images.githubusercontent.com/3018245/38837667-ae1b3490-4187-11e8-988b-4f93a8d1de1f.png)

### Steps to reproduce the behavior
* Install and activate Ultimate Member `2.0.9`
* Install and activate AffiliateWP and Affiliate add-on Signup Referrals
* Go to Affiliates > Settings > Integrations - Signup Referrals

**Comment by champsupertramp** [comment]
Hi @gspice,

Unfortunately, we cannot provide support for third-party plugins. Please contact the plugin developer and ask them to update their plugin with the new changes in UM 2.0

https://affiliatewp.com/add-ons/pro/signup-referrals/?utm_campaign=documentation&utm_source=helpscout&utm_medium=doc&utm_term=1211-signup-referrals-ultimate-member-registration-referral-type


Regards,
