### ISSUE TITLE
Custom profile layout?

### ISSUE THREAD

**Issue by HeartMath** [ultimatemember/ultimatemember#424]
I would like to have the user profile content in custom locations like in this pen (https://codepen.io/HeartMath/pen/aYrMQy)

How can I pull in specific fields?

**Comment by RiFi2k** [comment]
I would start right around here, this will get you everything, then go from there.
[https://github.com/ultimatemember/ultimatemember/blob/48bf1ac0d4edac7c4e45d308d78853890dc0460e/includes/core/class-builtin.php#L1228](https://github.com/ultimatemember/ultimatemember/blob/48bf1ac0d4edac7c4e45d308d78853890dc0460e/includes/core/class-builtin.php#L1228)
