### ISSUE TITLE
JSON error when uploading profile photos and cover photos

### ISSUE THREAD

**Issue by yannc2021** [ultimatemember/ultimatemember#425]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
Describe your issue here.

When I upload a photo on the profile page, the upload box does not change to the resize box when the progress bar ends. I get this error message

```
SyntaxError: Unexpected token W in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.n.parseJSON (jquery.js?ver=1.12.4:4)
    at Function.a.parseJSON (jquery-migrate.min.js?ver=1.4.1:2)
    at Object.onSuccess (um-functions.min.js?ver=4.9.5:1)
    at Object.success (um-fileupload.min.js?ver=4.9.5:1)
    at Object.t.success (um-jquery-form.min.js?ver=4.9.5:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4) "Wrong nonce"
```

This error does not happen every time. Sometimes I am able to upload the photo successfully, maybe 1 out of 5 attempts it uploaded. 

How can I fix this or display an error message to the user when this error happens? 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

1. Upload a profile photo OR
1. Upload a profile photo, when it goes to the resize box, close the box, and click upload photo again. 

This errors happens when the user closes the resize box, and uploads another photo again. 

## PHP version
- [ ] 7.1 above
- [x] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by yannc2021** [comment]
Fixed the problem. It was a nonce validation issue with changing ip address.

**Comment by Internapse** [comment]
With Ultimate Member version 2.0.17, I'm now seeing this same issue.

I also found another thread with the same issue on the WordPress forums. https://wordpress.org/support/topic/wrong-nonce-error/

Both solutions seem to solve their issue by changing the IP address to match, but I don't even have a CDN setup or any dynamic IP addressing that I can see.

Is this still an ongoing issue for anybody?

**Comment by yannc2021** [comment]
I solved it by removing the ip address part from nonce creation and nonce checking. Works perfectly for me now.

**Comment by nelz16** [comment]
hey @yannc2021, could you explain how to remove the ip address part from both nonce creation and nonce checking please...having the same problem here with uploading a profile picture with the error label coming up. this is whats showing on the 404 error page

The requested URL /um-api/route/um!core!Files/ajax_image_upload/bd9e44ac01 was not found on this server.
