### ISSUE TITLE
User profile tab links using internal routing address when SERVER_NAME has been set to a local URL

### ISSUE THREAD

**Issue by RiFi2k** [ultimatemember/ultimatemember#427]
### Ultimate Member Version
Tell us what UM core version you use. 
2.0.11

### Subject of the issue
On the user page the profile tab links are using the internal routing address when you are running in a pretty standard container environment. So for example in my case the environmental variable for SERVER_NAME is set as the internal url of the container behind the VPN so it can be connected too, and another NGINX container acts as the frontend proxy to the outside world.

I did some digging and rooted this all out for this particular case, I haven't run into any other links being incorrect along my travels.

[https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/um-actions-profile.php#L1336](https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/um-actions-profile.php#L1336)

Which traces to

[https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-permalinks.php#L132](https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-permalinks.php#L132)

In that function everything falls back to the SERVER_NAME which used to mostly only be mis-managed if someone had a messed up server config but now with the rise of containers and environments like mine I don't think you can just safely assume SERVER_NAME === HTTP_HOST anymore.

First it would probably be good to check if they do match, then procceed as normal if they do, but in the case like mine or even possibly a site running with a .com and a .org you may end up sending someone to a non resolvable URL or the wrong URL which would kill their session anyways and log them out.

Pantheon has a post about it on their website as well, just to show that this wouldn't just be a one off [https://pantheon.io/docs/server_name-and-server_port/](https://pantheon.io/docs/server_name-and-server_port/)

What I ended up doing was just scrapping all that and grabbing the $wp_query.

At that point the query has already been handled to get you onto the correct profile page so you can just use $query['page_id'] and $query['um_user'] and just build the needed URL from the permalink and the username string pulled out of the original query. Also it keeps you from having to rely right on HTTP_HOST to set those URLs.

I would have just thrown up a pull request but I wasn't sure how you all would want to handle it, because odviously you know the codebase better than me and may have methods or functions you can just direct swap out.

### Steps to reproduce the behavior
If you want to be able to reproduce this, the easiest way would be to just spin up a site with [Lando](https://docs.devwithlando.io/tutorials/wordpress.html) and install UM, navigate to your profile page and all those links should read https://appserver/user/username?profiletab=main etc, etc if you follow the boilerplate directions for WP.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

Side note, love this plugin and it's the goto anytime anyone wants to do a social community in WP. Happy to do a pull if you agree with my assesment.

**Comment by himanshuahuja96** [comment]
Yes, I am also facing this issue on pantheon. Before there was an option to set HTTP_HOST / SERVER_NAME but now there is no option. If there could be any option or a filter to do that.

Thanks

**Comment by RiFi2k** [comment]
If you want a quick and dirty hack, just paste this on the top of your functions.php file for your theme.
`$_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];`

**Comment by RiFi2k** [comment]
`add_filter('um_profile_tabs', 'custom_profile_tabs', 1000 );`
This may get you where you want to be, I can't remember. Try var dumping $tabs in your function

**Comment by dsifford** [comment]
`$_SERVER['HTTP_HOST']` is not set when running on localhost. Just an FYI. 

Currently fighting with `class-permalinks.php` because of that very issue.
