### ISSUE TITLE
Reflected Cross-Site Scripting on 'profiletab' parameter

### ISSUE THREAD

**Issue by bosichua** [ultimatemember/ultimatemember#428]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] Version 2.0.11 ( latest )

### Subject of the issue
The parameter profiletab is vulnerable to reflected xss. This payload will invoke a alert prompt:
https://XXXX/user/YYYY/?profiletab=main**'><script>alert(0)</script>**&um_action=edit

### Expected behavior
A JavaScript alert box showing "0"

### Actual behavior
The value should be html encoded to corresponding values such as &lt;, &gt; and &quot;

### Steps to reproduce the behavior
1) Use a Burp Proxy or Fiddler, intercept the HTTP Request:
https://XXXX.io/user/YYYY/?profiletab=main&um_action=edit

2) Edit the HTTP Request to:
https://XXXX.io/user/YYYY/?profiletab=main'><script>alert(0)</script>&um_action=edit

3) Send

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

**Comment by dsifford** [comment]
@bosichua I'm not able to reproduce this.

**Comment by bosichua** [comment]
Hi @dsifford 
I think you have to edit the parameter through Burp Proxy and not typing into the URL directly.

![image](https://user-images.githubusercontent.com/30226632/39751861-2b08b69c-52ec-11e8-876d-12e524c12e4b.png)

![image](https://user-images.githubusercontent.com/30226632/39751942-7a399ce0-52ec-11e8-8e07-321a5a637d61.png)
