### ISSUE TITLE
Fix manage users in WP 4.4

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#43]
Hi @ultimatemember,

There's an issue with the manage users after updating the WP core to 4.4

It doesn't update the roles, status and filters. 

Here's a fix: 
https://github.com/ultimatemember/ultimatemember/commit/1151000c1136228d2ef0cf05f9502d0bbbb821c5

**Comment by ultimatemember** [comment]
https://github.com/ultimatemember/ultimatemember/pull/45
