### ISSUE TITLE
Allow editors to view, verify and delete members

### ISSUE THREAD

**Issue by stefahn** [ultimatemember/ultimatemember#430]
By default all _admins_ can see, verify and delete members. In our case editors should do that job. I edited the editor role (via UM) so that editors can edit, delete and view our member role "Mitglieder". See this screenshot: https://screenshots.firefox.com/5jocFL0CG55k3rth/www.vzap2018.de

However, if I log in as an editor I can't access /wp-admin/users.php or /wp-admin/users.php?role=um_mitglieder. 
Also if I get the verification mail as an editor, I can't access http://domain.de/user/xy/ to verify the user "xy".
How is an editor supposed to view, verify or edit a member?

Using UM 2.0.11.

**Comment by inetnet** [comment]
It is very likely that you forgot to add visibility for this role.
See this screenshot: http://prntscr.com/mazkd5
