### ISSUE TITLE
Avoid /user/ in member page

### ISSUE THREAD

**Issue by dotMastaz** [ultimatemember/ultimatemember#433]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0.13 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
Before 2.0.xx upate, url member page was : http://www.domain.com/name-user
Now it's http://www.domain.com/user/name-user

How to retrieve url http://www.domain.com/name-user and avoid this /user/ ?

Thank you !

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by champsupertramp** [comment]
Hi,

UM user page was not designed to handle the www.example/user-name/ as it causes site-wide slug conflicts with posts/pages/categories.

Regards,

**Comment by dotMastaz** [comment]
Before is like that no ?
