### ISSUE TITLE
roles()->set_role potential update meta for wrong user

### ISSUE THREAD

**Issue by rdanamcd** [ultimatemember/ultimatemember#434]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0.13

### Subject of the issue
From what I see in the code, there's a potential problem in class-roles-capabilities.php in set_role( $user_id, $new_role = '' ) on line 192: UM()->user()->update_usermeta_info( 'role' );

This line assumes I've already um_fetch_user( $user_id ), what if I haven't and I'm updating the role for another user_id? The usermeta is then updated for the wrong user in the database.

I may be missing something though.

To be safe, I'm calling um_fetch_user( ... ) before UM()->roles()->set_role(...) and then um_reset_user() afterwards.

## PHP version
- [x] 7.0 above

Thanks
Dana

**Comment by yannc2021** [comment]
I'm also having issues with changing a user to admin role from the wordpress users admin page. The user does not have admin capabilities after changing to admin role. This happened since the last update.
