### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS since v2.0.13

### ISSUE THREAD

**Issue by Typel** [ultimatemember/ultimatemember#436]
### Ultimate Member Version 2.0.13
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
After upgrading from Ultimate Member version 2.0.11 to 2.0.13 and without changing any plugin settings at all, the home page now tries to load for several minutes before finally producing a redirect loop error in the browser (in Chrome, it looks like ERR_TOO_MANY_REDIRECTS). Internal pages are still accessible if you visit the URL directly.

### Expected behavior
The home page should load like normal.

### Actual behavior
The home page gets stuck in a redirect loop. Only disabling Ultimate Member seems to fix it.

### Steps to reproduce the behavior
Upgrade from version 2.0.11 to version 2.0.13. Try to load the website's homepage (not logged in).

## PHP version
- [ ] 7.1 above
- [x] 7.0.10
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by hirenshah** [comment]
@Typel 

How did you fix this?  I have the same issue :(

**Comment by Typel** [comment]
@hirenshah Sorry, I don't recall - this was 2 years ago and I no longer use the plugin. I'm thinking it was most likely a conflict with another plugin since I closed this shortly after opening. If facing the same issue today, I would try temporarily disabling or removing any plugins that facilitate 301-type redirection to see where the conflicts are.

**Comment by hirenshah** [comment]
@Typel

I managed to figure it out... I had placed a UM widget inside the OceanWP Side Panel, which needed the user to be logged in.  As soon as I removed that widget, there were no issues :D
