### ISSUE TITLE
Many Problems with checkbox and conditionals and required

### ISSUE THREAD

**Issue by omicronn** [ultimatemember/ultimatemember#438]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Many Problems with checkbox and conditionals and required too !

I have :
– Checkbox 1 : yes / no (required)
– Checkbox 2 : red / blue (required)
-> show if Checkbox 1 contains yes
– textbox 1 (required)
-> show if Checkbox 2 contains contains red
– textbox 2 (required)
-> show if Checkbox 1 contains contains no

Issues :
– textbox 1 and 2 are not required, no error message after posting
– if Checkbox 1 is yes and Checkbox 2 is red, textbox 1 is not displayed after posting
– Warning: strstr() expects parameter 1 to be string, array given in …./wp-content/plugins/ultimate-member/includes/core/um-actions-form.php on line 380

I think there are several issues with checkbox and conditionals.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
Thank you for your feedback. This bug will be fixed in the next Ultimate Member release.

**Comment by omicronn** [comment]
Ok I've seen the modification in 2.0.17.
But I'm not sure, that the checkbox case is fixed.
For me the checkbox is an array like the radio !
$cond_value = ( $fields[ $parent_key ]['type'] == 'radio' ) ? $args[ $parent_key ][0] : $args[ $parent_key ];
