### ISSUE TITLE
Admins can't access page with restricted content after 2.0 update

### ISSUE THREAD

**Issue by ITSjwags** [ultimatemember/ultimatemember#439]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
I have content restriction on a page to logged in users only (still shown in the navigation to everyone). So the flow is when you try to access this page you first will be redirected to a login page, then after successful login, you're redirected back to this page.

### Expected behavior
As an admin, you should be able to be redirected to the restricted page and also you should be able to view that restricted page.

### Actual behavior
If you're an admin (after updating to 2.0.13) when you login you get this message "This action has been prevented for security measures." Then if I stay logged in and just try to access that page, it will redirect back to the home page. So basically any admin right now can't access the page at all.

### Steps to reproduce the behavior
_FLOW 1_
- Click page in navigation
- Get redirected to login page
- Try to login with an existing admin account
- Notice error message

_FLOW 2_
- Log in with existing admin account
- Try to view content restricted page while being logged in
- Notice redirection back to homepage

## PHP version
- [ ] 7.1 above
- [x] 5.6.35
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users

### Screenshots of Wordpress setup
Settings on page
![image](https://user-images.githubusercontent.com/4692878/39716683-dd6ae66e-51e5-11e8-88d3-e4110df1bd9b.png)

Error message after logging in, while trying to redirect to the restricted content page
![image](https://user-images.githubusercontent.com/4692878/39844679-32694266-53a6-11e8-8da6-30884b50507f.png)

**Comment by denisbaranov** [comment]
Hi. Please update your Ultimate Member. I use version 2.0.15 and can not reproduce behavior, that you described. All works well.
