### ISSUE TITLE
Can't upload Cover Photo to profiles on multisite installs with "sites" in the URL

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#44]
Hi @ultimatemember 

A client sent this:

If you have a multisite network with the word "sites" in the URL, cover photo uploading won't work because um-filters-files.php splits the directory path using the word "sites" as follows:

`$split = explode('sites',$dir);`

This can be fixed by doing this instead (add slash):

`$split = explode('sites/',$dir);`

I've pushed the fixes to the dev branch:
https://github.com/ultimatemember/ultimatemember/commit/3b2f95b538adc50e3bf63a2aca5e48836ac097f8

Thanks to @brianshim

**Comment by ultimatemember** [comment]
Comitted to master.
