### ISSUE TITLE
Debug information shown on screen.

### ISSUE THREAD

**Issue by MarkTierney1975** [ultimatemember/ultimatemember#441]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
wp_die() debug array shown on screen.

### Expected behavior
Error should be added to the form

### Actual behavior
wp_die var dump shown on screen

### Steps to reproduce the behavior
Registering using an email already in use.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [x] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

in ultimate-member/includes/core/um-actions-save-profile.php line 52

if( is_wp_error( $return ) ) {
	wp_die(  '<pre>' . var_export( array( 'message' => $return->get_error_message(), 'dump' => $arr_user, 'changes' => $changes ), true ) . '</pre>'  );
}

This basically dumps out the user input on screen instead of adding an error to the form.

**Comment by denisbaranov** [comment]
Hi, Mark. This is developers debug message. If site works well user would never see it.
