### ISSUE TITLE
Spam registrations bypassing ultimate member registration form

### ISSUE THREAD

**Issue by fyoda** [ultimatemember/ultimatemember#444]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x ] 2.0.13 ( )

### Subject of the issue
In my website I have ultimate member installed to manage user registrations. By default, all users get Subscriber role and a verification link is sent by email to check users' mail.
However, to allow users to register on my website through the ultimate member form, I had to enable the "Anyone can register" flag in the WordPress settings.
By doing so I discovered that malicious users can reach the default wordpress registration form and spam users by typing: https://yoursite.com/wp-login.php?action=register.
I think the plugin should redirect all people trying to access that default page to the ultimate member registration form. 
I got some spam in the last day discovering this issue. I solved the problem by redirecting manually all users trying to access the default to the ultimate member registration form.
Is this an issue?

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.0.3
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
In my opinion this is not issue, because usual users doesn`t know default WordPress registration url. 
Also admin should set "Anyone can register" in the WordPress settings. If not, default registration would be disabled.
But I think this is a good idea to make build-in redirect from default registration to UM registration page.

**Comment by FlyThePlanet** [comment]
I don't really understand that...

> However, to allow users to register on my website through the ultimate member
> form, I had to enable the "Anyone can register" flag in the WordPress settings.

I also have UM installed, "Anyone can register" flag is disable and the users can still register via the UM form. It's even advised by UM to disable this flag to prevent users from using the default form...
https://docs.ultimatemember.com/article/269-how-to-stop-users-registering-via-wp-login-page

So I must have missed something or you have a very specific issue when you disable "Anyone can register".

That said, add build-in...
- redirect from the default registration page to the UM registration page,
- redirect from the default login to the UM login,
- and redirect after a default logout (via the admin bar) to the page set in UM after a logout (and not the default WP login page)
...would be a VERY good thing! It would make the result of using UM much more clean as at the moment it's very easy to use or end up by mistake on the default WP pages, and apart from the "Anyone can register" flag solution we have nothing to fix the use of the default login and make a clean redirect after a logout.

**Comment by fyoda** [comment]
I think the problem got solved by disabling the "Anyone can register" flag.

Thanks.

**Comment by FlyThePlanet** [comment]
> I think the problem got solved by disabling the "Anyone can register" flag.

Regarding the title of this ticket, yes, disabling the "Anyone can register" flag should normally fix the problem.
That's why I said just above "So I must have missed something or you have a very specific issue when you disable "Anyone can register".".

But still, it's very surprising and not clean to leave the access to the default (not customized) login page and let WP keep redirecting to it after a logout from the admin bar.
Adding those redirections would give a much nicer finish to UM.

**Comment by SilverMarc** [comment]
I have removed the checkmark from the "Anyone can register" box in the WP Settings but I still receive spam registrations on my website. I get about 2 to 3 spam registrations each week.

There must be some way that these unwanted registrations are bypassing the WP "Anyone can register" setting. The unwanted registrations are coming in from the Ultimate Member Default Registration form as they are identified with that Form ID.

Just FYI, in case others are trying to solve this as well.

**Comment by hugme** [comment]
I am getting the same issue. The "anyone can register" box is not checked however I still receive 2-5 junk email registrations per day I have to go in and delete. Luckily they are put into the 'pending' folder.

I've gone in and disabled the regisration page which was built by ultimate member as well and this still does not stop it.

How do we stop junk registrations if the "anyone can register" box does not work?

**Comment by fethomm** [comment]
Is there a solution to this by now? Google reCaptcha under German regulations is not the solution. I get up to 50 spam mails per day and this is very annoying.

**Comment by pije76** [comment]
Still no solution for this issue till now?

**Comment by hugme** [comment]
I uninstalled ultimate Member. I couldn't get this issue resolved.

**Comment by Maverick87Shaka** [comment]
I'm also noticing an increasing number of spammer that can register with the UM form, without any issue wither using reCAPTCHA V3 or V2.
Default wordpress registration method is disable. 
Is getting really annoying ☠️
