### ISSUE TITLE
Get All Author Information

### ISSUE THREAD

**Issue by squiggie** [ultimatemember/ultimatemember#445]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Previously, I had some custom function that would allow me to pull author information and put it in the wordpress rest api for my app. 

```
function my_rest_author_prepare_post( $data, $post, $request ) {
    $_data = $data->data;
    $user_id = get_the_author_meta( 'ID' );

    // Call ultimatemember global variable
    //global $ultimatemember;

    // Set user ID
    $ultimatemember->user->set( $user_id );

    //Set author data
    $profile_photo = um_get_avatar( um_profile('profile_photo'), 400 );
    $cover_photo = um_get_avatar( um_profile('cover_photo'), 32 );
    $umuser = array(
        'description' => $ultimatemember->user->profile['description'],
        'displayname' => $ultimatemember->user->profile['display_name'],
	'profession' => $ultimatemember->user->profile['profession'],
        'profile_photo' => $profile_photo,
        'cover_photo' => $cover_photo,        
        'facebook' => $ultimatemember->user->profile['facebook'],
        'twitter' => $ultimatemember->user->profile['twitter'],
        'googleplus' => $ultimatemember->user->profile['googleplus'],
        'linkedin' => $ultimatemember->user->profile['linkedin'],
        'instagram' => $ultimatemember->user->profile['instagram'],
        'websiteurl' => $ultimatemember->user->profile['user_url'],
    );

    $_data['um_author'] = $umuser;
    $data->data = $_data;
    return $data;

}

add_filter( 'rest_prepare_post', 'my_rest_author_prepare_post', 10, 3 );
```

After the Ultimate Member 2 upgrade, now this function breaks the wp-json rest api /post call with the following error;

`Unexpected '<'`

### Expected behavior
I would like to find out how to replace this code and achieve the same results adding all the author information back into the rest api. Is this possible?

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
Advice - To debug rest api request you can call it manually. Example:
http://your_site/wp-json/wp/v2/posts

Try to use this code:

function my_rest_author_prepare_post( $data, $post, $request ) {
    
    um_fetch_user( $post->post_author );    
    
    $data->data['um_author'] = array();
    
    $fields = array(
        'description' => null,
        'displayname' => null,
        'profession' => null,      
        'facebook' => null,
        'twitter' => null,
        'googleplus' => null,
        'linkedin' => null,
        'instagram' => null,
        'websiteurl' => null,
        'cover_photo' => 32,
        'profile_photo' => 400
    );
    
    foreach ( $fields as $key => $value ) {
        $data->data['um_author'][$key] = preg_replace('/\s{2,}/', ' ', um_user($key, $value));
    }
    
    return $data;
}

add_filter( 'rest_prepare_post', 'my_rest_author_prepare_post', 10, 3 );

**Comment by squiggie** [comment]
I get this error.

> Call to undefined function um_fetch_user()

**Comment by squiggie** [comment]
Thanks, @denisbaranov  this worked!

For anyone else that might need it, I added a little extra filter. 

The cover photo and profile photo return some html and all I needed were the urls. So I altered the function as follows. 

```
function my_rest_author_prepare_post( $data, $post, $request ) {

	um_fetch_user( $post->post_author );    

	$data->data['um_author'] = array();

	$fields = array(
	    'description' => null,
	    'displayname' => null,
	    'profession' => null,      
	    'facebook' => null,
	    'twitter' => null,
	    'googleplus' => null,
	    'linkedin' => null,
	    'instagram' => null,
	    'websiteurl' => null,
	    'cover_photo' => 32,
	    'profile_photo' => 400
	);
	
	foreach ( $fields as $key => $value ) {
	    if ( $key == 'cover_photo' || $key == 'profile_photo'){
	    	preg_match_all('#\bhttps?://[^,\s()<>]+(?:\([\w\d]+\)|([^,[:punct:]\s]|/))#', um_user($key, $value), $match);
	        $data->data['um_author'][$key] = $match[0][0];
	    } else {
	        $data->data['um_author'][$key] = preg_replace('/\s{2,}/', ' ', um_user($key, $value));
	    }
	}
	
	return $data;
}
```

**Comment by Sp3eex** [comment]
If I use that as an API, how would I pass Uri args to the method
