### ISSUE TITLE
First Field in Search Options on Member Directory Not Appearing

### ISSUE THREAD

**Issue by gitblair** [ultimatemember/ultimatemember#446]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x ] 2.0 ( beta )

### Subject of the issue
Whatever field I choose as first search option on a searchable member directory does not appear to members. All fields appear fine to admin.

### Expected behavior
I have three search fields indicated for search on my member directory. Everyone should see all three fields of search choice.

### Actual behavior
Members only see the last two fields on the member search.

### Steps to reproduce the behavior
I've deleted the member directory and recreated it. I've tried different search fields and whatever is in the first choice in the member directory editor refuses to display for members (admin see fine). I've scoured the roles but cannot see anything that would stop a member role from not seeing the first search field. To be sure I've also cleared all cache but the issue persists. Is anyone else having this issue?

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ x] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ x] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x ] Google reCAPTCHA 
- [ x] Online Users

**Comment by denisbaranov** [comment]
What version of the plugin have you use? I use version 2.0.15 and have not this problem. Can you give your site url?

**Comment by denisbaranov** [comment]
It's strange. Maybe you have some custom filter at 'um_shortcode_args_filter' hook that change 'search_fields' field of the $args array? Also you can search array_shift function usage in your code.

**Comment by gitblair** [comment]
Well I've narrowed it down to one Addon: User Reviews.

When I disable User Reviews, my problem goes away.
