### ISSUE TITLE
Feature Request: Message Button on Following List

### ISSUE THREAD

**Issue by gitblair** [ultimatemember/ultimatemember#448]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Just a suggestion for a feature to Followers addon to add the Message Button on the list of people you are following. To left or to right of the Following/Unfollow button.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
You can add this buttons manually:

1. Open wp-content/plugins/um-followers/templates/followers.php
2. Find string `echo UM()->Followers_API()->api()->follow_button( $user_id2, get_current_user_id() );`
3. Add code
`if ( defined('um_messaging_requires') ) {
                    echo ' ', UM()->Messaging_API()->shortcode()->ultimatemember_message_button( array( 'user_id' => $user_id2 ) );                    
                }`

1. Open wp-content/plugins/um-followers/templates/following.php
2. Find string `echo UM()->Followers_API()->api()->follow_button( $user_id1, get_current_user_id() );`
3. Add code
`if ( defined('um_messaging_requires') ) {
                    echo ' ', UM()->Messaging_API()->shortcode()->ultimatemember_message_button( array( 'user_id' => $user_id1 ) );                    
                }`
