### ISSUE TITLE
Dropdown with Choices Callback set not visible in view mode on Default Profile form

### ISSUE THREAD

**Issue by FlyThePlanet** [ultimatemember/ultimatemember#450]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0.16 ( latest )

### Subject of the issue
If we set a function in the Choices Callback field of a custom Dropdown field, everything works fine, the values are populated according to the Parent Option field value.

But... the field for which we have set this Choices Callback function becomes not visible on the Default Profile form in view mode! (in edit mode the field is visible and on the Default Registration form it's also visible)
If we remove the function in Choices Callback, the field immediately becomes visible again in view mode.

This behaviour is easy to reproduce.

Of course I have Visibility set to "View everywhere".

### Expected behavior
Dropdown with “Choices Callback” set should be visible in view mode on Default Profile form

### Actual behavior
Dropdown with “Choices Callback” set is not visible in view mode on Default Profile form

### Steps to reproduce the behavior
- Default Profile form > Add a custom Dropdown field
- Set a function in the Choices Callback field and choose a Parent Option
- Leave Visibility set to "View everywhere" and Save/Update
- Display the user profile

## PHP version
- [ ] 7.1 above
- [x] 5.4
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users

**Comment by m-abuodeh** [comment]
Hello
I have the same issue here, Also I want to add another issue that in "Member directory", Drop down list for City is empty and showing no options. options only populated in profile form " Edit view".

**Comment by artmerk** [comment]
Same Issue for me.  The field for which we have set this Choices Callback function is not visible on the Default Profile form in view mode.

**Comment by AyZeeEe** [comment]
Any update on this issue? I'm also having the same problem, when being dependant on the `Parent Option`. 

`Choices Callback` works fine, if there's no dependancy on the Parent Option; but once we populate it dynamically, it no longer shows in "view" mode.

**Comment by FlyThePlanet** [comment]
Hi, @champsupertramp 

Why is this ticket closed?
The issue is not fixed. Even with the last version (2.0.56).
Can you please re-open it.

Thanks!

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet , I apologize that i had to skipped and forgot to leave a comment to this issue as we are improving this repo and get issues fixed.

Thanks for letting us know that you are still having this issues in the latest version.

Could you please provide the custom code for callback function of select/multi-select field here so we can reivew?

Regards,

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet, if possible, please provde a screenshot of the multi-select/select field options in UM form builder.

Regards,

**Comment by FlyThePlanet** [comment]
Hi,

Custom code...
```
function getFloors() {
	//Get the value from the 'parent' field, sent via the AJAX post.
	$choice = $_POST['parent_option'];

	//Depending on the value of $choice, return a different array.
	switch($choice) {
		case "18 rue Henry Bordeaux":
		case "20 rue Henry Bordeaux":
			$floors = [
				"RDC" =>"RDC",
				"1er" => "1er",
				"2nd" => "2nd",
				"3ème" => "3ème",
				"4ème" => "4ème",
				"5ème" => "5ème",
				"6ème" => "6ème"
			];
			break;
		case "22 rue Henry Bordeaux":
		case "24 rue Henry Bordeaux":
			$floors = [
				"RDC" =>"RDC",
				"1er" => "1er",
				"2nd" => "2nd",
				"3ème" => "3ème",
				"4ème" => "4ème",
				"5ème" => "5ème",
				"6ème" => "6ème",
				"7ème" => "7ème",
				"8ème" => "8ème"
			];
			break;
		case "44 avenue Gambetta":
			$floors = [
				"RDC" =>"RDC",
				"1er" => "1er",
				"2nd" => "2nd",
				"3ème" => "3ème",
				"4ème" => "4ème",
				"5ème" => "5ème",
				"6ème" => "6ème",
				"7ème" => "7ème",
				"8ème" => "8ème",
				"9ème" => "9ème",
				"10ème" => "10ème"
			];
			break;
		default:
		//code to do something if other options are not selected (throw an error, or set $floors to a default array)
		$floors = ["Sélectionnez une adresse"];

	}
	return $floors;

}
```

Profile form in edit mode...
https://ibb.co/sytcqrn

It's in French but the fields are:
[First name] [Last name]
[Address] [Floor]
[Question]

The "Floor" field is populated according to the address selected (cf. function above).

Profile form in view mode... (the "Floor" field is not displayed)
https://ibb.co/KmRK7R7

Profile form in form builder... 
https://ibb.co/HXYSwg8

Thanks.

**Comment by champsupertramp** [comment]
Hi,

Could you please try adding this code snippet?

```
add_filter("um_has_dropdown_options_source__floor","__return_true");
add_filter("um_get_field__floor","um_get_field__floor", 10,1  );
function um_get_field__floor( $array ){
     
        //Get the value from the 'parent' field, sent via the AJAX post.
	$choice = $_POST['parent_option'];

	//Depending on the value of $choice, return a different array.
	switch($choice) {
		case "18 rue Henry Bordeaux":
		case "20 rue Henry Bordeaux":
			$floors = [
				"RDC" =>"RDC",
				"1er" => "1er",
				"2nd" => "2nd",
				"3ème" => "3ème",
				"4ème" => "4ème",
				"5ème" => "5ème",
				"6ème" => "6ème"
			];
			break;
		case "22 rue Henry Bordeaux":
		case "24 rue Henry Bordeaux":
			$floors = [
				"RDC" =>"RDC",
				"1er" => "1er",
				"2nd" => "2nd",
				"3ème" => "3ème",
				"4ème" => "4ème",
				"5ème" => "5ème",
				"6ème" => "6ème",
				"7ème" => "7ème",
				"8ème" => "8ème"
			];
			break;
		case "44 avenue Gambetta":
			$floors = [
				"RDC" =>"RDC",
				"1er" => "1er",
				"2nd" => "2nd",
				"3ème" => "3ème",
				"4ème" => "4ème",
				"5ème" => "5ème",
				"6ème" => "6ème",
				"7ème" => "7ème",
				"8ème" => "8ème",
				"9ème" => "9ème",
				"10ème" => "10ème"
			];
			break;
		default:
		//code to do something if other options are not selected (throw an error, or set $floors to a default array)
		$floors = ["" => "Sélectionnez une adresse"];

	}

     $array['custom_dropdown_options_source'] = true;
     $array['options'] = $floors;

 return $array; 

}
```

Let me know if this still has issues.

Regards,

**Comment by FlyThePlanet** [comment]
Well...
- On one hand it indeed allows to see the "Etage" field (Choices Callback field) in view mode,
- BUT... in edit mode, this "Etage" field is empty and its list is also empty.

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet, Did you also add a callback function to the parent fields to populate the options?

Regards,

**Comment by FlyThePlanet** [comment]
Of course. And as soon as I revert to my function, I go back to the previous behaviour:
- "Etage" field (Choices Callback field) NOT visible in view mode,
- but "Etage" field and list properly populated in edit mode.

But your version is interesting as it unlocks the visibility in View mode.
So the solution is probably a combination of our 2 codes.

**Comment by FlyThePlanet** [comment]
Sorry, it's worst. I use your code and update the function name (it has not been done in the 1st test), nothing's working.
- field not visible in view mode
- field & list not populated in edit mode

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet ,

Could you please add a test select field in a Profile Form? 

Add this function in the callback field settings: `um_my_custom_field_callback`

And then add the following code to your functions.php

```
function um_my_custom_field_callback( $array ){
         $array['custom_dropdown_options_source'] = true;
         $array['options'] = array(
             "a" => "Apple",
            "b" => "Banana",
            "c" => "Carrot"
        );

        return $array; 

}
```

Please test if this works in Edit and View.

Regards,

**Comment by FlyThePlanet** [comment]
> add a test select field

Dropdown field or Multi-select field?

Anyway, I've tested both but the behaviour is the same with both.
It doesn't work at all:
- In view mode, the field is not displayed
- In edit mode, the whole page is not displayed properly...
https://ibb.co/bHFHYtm
Instead of...
https://ibb.co/VDCmvTk

**Comment by FlyThePlanet** [comment]
Looks like you're in the Phils. I was in Cebu 1 month ago ;-)
Currently I'm in Europe (-6h) but do you want to do a TeamViewer? It may go faster to do some tests.

**Comment by FlyThePlanet** [comment]
Hi @champsupertramp 
Looks like you're in the Phils. I was in Cebu 1 month ago ;-)
Currently I'm in Europe (-6h) but do you want to do a TeamViewer? It may go faster to do some tests.

**Comment by artmerk** [comment]
Hi @FlyThePlanet and @champsupertramp,

I appreciate all the work you are doing to fix this.  However, I cannot easily test any new functions because I am running 2.043.  I “froze” our version as this is the last version that works for me with callbacks.

I am VERY eager to see this fixed.  The “Choices Callback” is one of the most powerful features of Ultimate Member, allowing unlimited field types with custom functions.

I am happy to setup a test environment on the latest version and test.  But I am surprised / confused that Champ cannot replicate the same problems that we are seeing??





On Aug 23, 2019, at 11:48 PM, Champ Camba <notifications@github.com> wrote:

Hi @FlyThePlanet <https://github.com/FlyThePlanet> ,

Could you please add a test select field in a Profile Form?

Add this function in the callback field settings: um_my_custom_field_callback

And then add the following code to your functions.php

function um_my_custom_field_callback( $array ){
         $array['custom_dropdown_options_source'] = true;
         $array['options'] = array(
             "a" => "Apple",
            "b" => "Banana",
            "c" => "Carrot"
        );

        return $array; 

}
Please test if this works in Edit and View.

Regards,

**Comment by champsupertramp** [comment]
Hi @artmerk, We have made some changes on how to populate select/multi-select fields with filter hooks and callback function in the latest version. I'm writing a doc as a guide. I'll post it here when it is ready.

@FlyThePlanet  - Yes, I live in Quezon. 4 hours drive from Manila City.  Could you please tell confirm if you're using the latest version?

Regards,

**Comment by FlyThePlanet** [comment]
>  Could you please confirm if you're using the latest version?
Yes.
- WordPress: 5.2.2
- Theme > OceanWP: 1.7.1
- UltimateMember: 2.0.56
- UltimateMember reCAPTCHA: 2.1.1
- PHP: 7.1

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet ,

Could you please try this code snippet to your test form?  This is how we implement the callbacks for Parent and Child dropdown fields. It works on our end with the latest master version in the repo

```

/**
 * Parent dropdown callback
 * @return array
 */
function um_my_parent_dropdown_options_callback(){
	$array  = array(
		"a" => "A",
		"b" => "B",
		"c" => "C",
	);

	return $array;
}
```

```
/**
 * Child dropdown callback
 * @param  boolean $has_parent 
 * @return array         
 */
function um_my_child_dropdown_options_callback( $has_parent = false ){

	$parent_option = $_POST['parent_option'];

	$all_options = array(
		"a" => array(
			"apple" => "Apple",
			"acre" 	=> "Acre",
			"amber" => "Amber",
		),
		"b" => array(
			"d" => "D",
			"e" => "E",
			"f" => "F",
		),

	);

	$arr_options = array();
		

	if( isset( $all_options[ $parent_option ] ) ){
		$arr_options = $all_options[ $parent_option ];
	}elseif( ! isset( $_POST['parent_option'] ) ) {

		foreach( $all_options as $k => $opts ){
			$arr_options = array_merge( $opts, $arr_options );
		}

	}

	return $arr_options;

}

```

Regards,

**Comment by FlyThePlanet** [comment]
Yes I can make a test but few questions:

> It works on our end with the latest master version in the repo

Do you mean the one in production (2.0.56) or the one you're currently working on?

> This is how we implement the callbacks for Parent and Child dropdown fields.

There are 2 functions, including one for the parent?
You don't use the GUI for the parent any more?

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet,  

1. I'm using the master repo: https://github.com/ultimatemember/ultimatemember/commits/master

2. Yes, you have to add these functions in the field settings( see screenshots below ):
<img width="726" alt="Screen Shot 2019-08-25 at 11 30 43 PM" src="https://user-images.githubusercontent.com/12200688/63652235-975a3400-c790-11e9-8b6d-a6f167c7ffb8.png">
<img width="726" alt="Screen Shot 2019-08-25 at 11 30 35 PM" src="https://user-images.githubusercontent.com/12200688/63652236-975a3400-c790-11e9-886c-574f253076a5.png">


Regards,

**Comment by FlyThePlanet** [comment]
> I'm using the master repo

Ok. However awaiting your answer I've already done a test on the 2.0.56.

> Yes, you have to add these functions in the field settings( see screenshots below )

I understood what I had to do but my question was more, is it now THE way to do to make it work now? Do we have NOT to use the GUI for the parent field any more?

Ok, now the result of the tests... and... IT WORKS!
Even with the 2.0.56, indeed it works this way. The fields are properly populated, the data saved and displayed when we edit the form and the fields are displayed either in view or edit mode.

However I still have other additional tests to run to see if it works in every cases, including on the registration form and when the form is reloaded. As, you did not (yet?) re-opened this ticket...
https://github.com/ultimatemember/ultimatemember/issues/580
...but I discovered that with the last version(s?) of UM, I now have even more problems: when we edit a profile, values are not kept even when the form is reloaded and modified values (for the callback fields)  are not saved. After submitting the form the profile sticks to the old values.

Ok, but let's go back to this ticket. Just to say that it indeed seems to work well now, but I still have some few tests to run... ;-)

**Comment by FlyThePlanet** [comment]
Ok finished.

Your code and method fixe everything for the Profile form!
- Parent & Child fields are now visible in view & edit modes
- Parent & Child lists are properly populated in edit mode
- Parent & Child values are now properly saved in edit mode
- Parent & Child values are now kept if the form is reloaded in edit mode (error after submit)
- Parent & Child values are now visible in view & edit modes

Great! For me the issue of this ticket is fixed!

However, this new code and method does not fix the issue of this other ticket on the Registration form which still needs to be reopen...
https://github.com/ultimatemember/ultimatemember/issues/580

Thanks for your efforts @champsupertramp ! :+1:

**Comment by FlyThePlanet** [comment]
> I understood what I had to do but my question was more, is it now THE way to do to make it work? Do we have NOT to use the GUI for the parent field any more?

I've tried removing the function for the parent field and just use the GUI.
It still works. It looks like we can keep using the GUI. All the fix is in the code of the last UM version(s?) and this new function for the child field.

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet  i was able to register with the same codes to populate parent and child dropdown fields with same callback function settings.

Have you tried the pre-release version?

Regards,

**Comment by FlyThePlanet** [comment]
> i was able to register with the same codes to populate parent
> and child dropdown fields with same callback function settings.

Be careful, the issue is not that we can't populate the field on the Register form.

It's that when you populate them, submit the form, if the form needs to be reloaded because there was an error on one field, the child field value is not kept like the value of all the other fields (except the password & reCaptcha of course).

Look at the **Steps to reproduce the behavior**
https://github.com/ultimatemember/ultimatemember/issues/580#issue-461452269

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet  could you please try the recent commits?

I have fixed the issue in Register form submission: https://github.com/ultimatemember/ultimatemember/commit/7a469ee53a8eeb4b82d0ca2a0a8d3ad7cbcba8eb

Let me know if you're still encountering any issues.

Regards,

**Comment by FlyThePlanet** [comment]
Hi @champsupertramp 

I'm not at home this WE so I can't test the whole pre-release version to control that there's no regression.
But I just tested the submission you pointed out and... YES, it fixes the ticket #580!

So on my side, I don't have any more issues on the choice callback and child fields!
Thanks very much for fixing all this. You did a great job!

**Comment by champsupertramp** [comment]
Hi @FlyThePlanet  Thanks for letting us know. I've also fixed the issue with the checkbox on login form submission: https://github.com/ultimatemember/ultimatemember/commit/f2e1e9955af280a6b14be3eef8e1fa2cd553a9e5

Thanks a lot for reporting issues.

I am closing this ticket now. 

Regards,

**Comment by FlyThePlanet** [comment]
Hi @champsupertramp 

> Thanks for letting us know. I've also fixed the issue with the checkbox on login form submission: f2e1e99

I confirm, it's also fixed.
Thanks!
