### ISSUE TITLE
How to permanently disable user caching. 

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#451]
We have a large site using UM and the user cache is crippling our wp_options query time. How does one disable this completely?

This no longer appears to be valid: https://wordpress.org/support/topic/auto-loaded-user-data/#post-8335825

I'd prefer to disable, rather than schedule a cron to clear.

**Comment by champsupertramp** [comment]
Hi @dsifford,

You can turn it off with the following code( add it in your theme functions.php ):

```
add_filter("um_get_option_filter__um_profile_object_cache_stop","__return_true");
```

Regards,
