### ISSUE TITLE
Menu Weirdness - Nav vs. Page Access

### ISSUE THREAD

**Issue by dcmcshan** [ultimatemember/ultimatemember#463]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x ] 2.0 ( beta )

### Subject of the issue
Menus were not showing up despite being available to "Everyone"

### Expected behavior
Menus should show up.

### Actual behavior
Menus were missing, out of order

### Steps to reproduce the behavior
Have a page with "Restrict access to this content checked", set "Who can access this content" to Everyone, and have the menu item listed as "Everyone"

Unrestricting access to content clears up the problem.  But it's entirely non obvious, and required PHP debugging to see where restrictions were set.  Site was in place before upgrade...

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by champsupertramp** [comment]
Hi,

Does your site have any caching plugin or server module? If so, can you please try deactivating the cache and see if this issue still occur?

**Comment by dcmcshan** [comment]
Turns out your page access filter for menus is broken.  If there are restrictions, accessible to Everyone, the menu wont show.

Removing the restriction on the page solves it for me, but I think it’s a bug in the menu filter
