### ISSUE TITLE
WPML integration

### ISSUE THREAD

**Issue by LuigiPulcini** [ultimatemember/ultimatemember#464]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( latest )
- [x] 2.0.17 ( latest )

### Subject of the issue
I am trying to add Polylang integration to UM, which should be pretty easy, considering that Polylang is compatible with WPML and most of the functions in the External_Integrations class can be adapted to make UM simultaneously compatible with both WPML and Polylang.

The problem I am facing is that, according to the current UM code, the "_um_wpml_user" and "_um_wpml_account" options are saved into a serialized array contained in the "um_content_restriction" post meta. But the functions in the `External_Integrations` class try to retrieve them as separate post meta, obviously failing.
This is the first line where the `get_post_meta()` function is called directly on the "_um_wmpl_user" option.
https://github.com/ultimatemember/ultimatemember/blob/3eca951d0752901eff309709300d01388e87d8f7/includes/core/class-external-integrations.php#L57
But the same problem appears on line 191 and 194 as well.

After saving a page with one of the two options checked, I went to the database and confirmed that there is no "_um_wpml_user" or "_um_wpml_account" post meta, but only the "um_content_restriction" post meta, containing a serialized array that includes the correct value for the two options.

I believe the retrieval of those options should be accomplished as follows:
`
$um_content_restriction = get_post_meta( get_the_ID(), 'um_content_restriction', true );
if ( get_the_ID() > 0 && $um_content_restriction['_um_wpml_user'] == 1 ) {
	$profile_url = get_permalink( get_the_ID() );
}
`

A similar approach should be used for lines 191 and 194 as well.

I might be missing something, but according to my findings, I believe something is not right in the code.

**Comment by denisbaranov** [comment]
Thank you.
We will modify file class-external-integrations.php
[fix/github#464_WPML_integration](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23464_WPML_integration)
