### ISSUE TITLE
Changing account password via Account > Change Password tab accepts empty field value.

### ISSUE THREAD

**Issue by angelBhim** [ultimatemember/ultimatemember#466]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x ] 2.0 ( beta )

### Subject of the issue
Changing account password via **Account > Change Password** tab accepts empty field value.

### Expected behavior
When empty field submitted it should show field validation

### Actual behavior
Upon Update password button click, it shows a success message

### Steps to reproduce the behavior
Go to Account > Change Password click update password button with empty field values

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
You can set in settings -> general -> users option "Require a strong password" - and it will be request password with lower letter, uppercase letter, numerical and long in 8 letters
