### ISSUE TITLE
auto approve user based on whitelist

### ISSUE THREAD

**Issue by mafar** [ultimatemember/ultimatemember#471]
**Objective:**

1. I want to define an auto approve white list.
2. If user from that domain registers, he should get automatically approved and get email
3. All others must get email_pending
4. I have already set option to admin Verification required as default option

**Code:**

I expect following code to work, but I always get email_pending for gmail
```php
function action_um_after_new_user_register($user_id, $args)
    {

    $auto_approve_domains = array(
        'gmail.com',
        'webmail.com'
    );

    $user = get_user_by('id', $user_id);
    $domain = substr(strrchr($user->data->user_email, "@") , 1);
    if (in_array($domain, $auto_approve_domains ))
        {
        global $ultimatemember;
        um_fetch_user($user_id);
        $ultimatemember->user->approve();
        }
};
add_action('um_after_new_user_register', 'action_um_after_new_user_register', 10, 2);
```

**Comment by champsupertramp** [comment]
Hi @mafar,

Try changing the priority frin 10 to 1 and see if this works.
```
add_action('um_after_new_user_register', 'action_um_after_new_user_register', 1, 2);
```
Regards,

**Comment by mafar** [comment]
No use, I tried  prio 1 and prio 100
They both both dont work

**Comment by champsupertramp** [comment]
Hi,

Have you tried the new method in 2.0+ ?
```
$ultimatemember->user->approve();
```

to 

```
UM()->user()->approve();
```

Regards,

**Comment by mafar** [comment]
@champsupertramp c
```
UM()->user()->approve();
```
This also does not work.
is ```UM()``` global variable ? I just replaced line ```$ultimatemember->user->approve();``` and and i still dont get auto approved for gmail accounts

Plz advise

**Comment by champsupertramp** [comment]
Hi @mafar,

Could you please check if the action hook works?

```
add_action('um_after_new_user_register', 'action_um_after_new_user_register', 10, 2);
function action_um_after_new_user_register($user_id, $args){
    wp_die("Check: {$user_id}");
}

```

**Comment by mafar** [comment]
@champsupertramp 
i cant find ```um_after_new_user_register``` in source code of 2.x 

Best closest things from 2.x source i can think of are
```um_user_register```
and 
```um_registration_complete```

But i am not sure which one is best.
I hope their documentation can explain workflow and order of hooks so one can know which hook is after what

**Comment by mafar** [comment]
I tired with both ```um_user_register``` and ```um_registration_complete```   but nothing happens

```
// 1.x uses um_after_new_user_register  and um_user_register
// for 2.x um_registration_complete  um_user_register 
add_action('um_user_register', 'action_um_user_register', 2, 2);
function action_um_user_register($user_id, $args){
    $auto_approve_domains = array(
        'gmail.com',
        'webmail.com'
    );  
    $user = get_user_by('id', $user_id);
    $user_email = $user->user_email;
    $domain = substr(strrchr($user_email, "@") , 1);
    if (in_array($domain, $auto_approve_domains ))
     {
      // 1.x syntax
         //global $ultimatemember;
        // um_fetch_user($user_id);
        // $ultimatemember->user->approve();
      //
      // 2.x syntax  
      //
       um_fetch_user($user_id);
       UM()->user()->approve();
     }
}
```

**Comment by mafar** [comment]
um_post_registration_pending_hook  seems to work. Others dont. thats strange
