### ISSUE TITLE
The SEO Framework compatibility

### ISSUE THREAD

**Issue by sybrew** [ultimatemember/ultimatemember#472]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( old )
- [x] 2.0.21 ( latest )

### Subject of the issue
I've implemented Ultimate Member compatibility for The SEO Framework v3.1.
I aim to ship it in August or September 2018.

With this, you may plan on removing the compatibility in your plugin for The SEO Framework without fearing users complaining. But, whatever's implemented now won't conflict in the future.

Keep an eye out for the [compatibility file](https://github.com/sybrew/the-seo-framework/blob/master/inc/compat/plugin-ultimatemember.php) in The SEO Framework, might you find mistakes or future compatibility issues.

P.S. You should update the UM versions in the issue template 😉

**Comment by champsupertramp** [comment]
Hi @sybrew  Thanks for letting us know!
