### ISSUE TITLE
Registration on the site with a not valid email

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#475]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
Registration on the site with a not valid email
F.E. [email.txt](https://github.com/ultimatemember/ultimatemember/files/2209136/email.txt)

### Expected behavior
Displaying the error message "This is not a valid email" below line "E-mail Address"

### Actual behavior
Accepts a not valid email and visits the site

### Steps to reproduce the behavior
1) Go to http://v.g-photo.com.ua/register/
2) In the "Email" field enter a not valid email (f.e."$@11.1")
3) Fill in the remaining required fields
4) Click button "Register"

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
Field check only if email unique. You can add validate for this field and throw back error via this hook
do_action( 'um_add_error_on_form_submit_validation', $array, $key, $args );
