### ISSUE TITLE
Password reset brings to same request form following the same link

### ISSUE THREAD

**Issue by elkwaet** [ultimatemember/ultimatemember#477]
### Ultimate Member Version
- [x] 2.0 ( beta )

### Subject of the issue
Hi,
On my site, it is not possible to users to reset their password from the form. When they type email in the password reset form, they receive mail with the link but when open this one they got again the same form. I think i'll disable the Reset option for the moment.
Can someone help me to fix this issue please?
Thanks

### PHP version
- [x] 7.1 above

### Do you use UM extensions? 
- [x] Google reCAPTCHA

**Comment by denisbaranov** [comment]
I check this issue on my site and all works fine. Can you show screenshots of the steps?
