### ISSUE TITLE
The function "Edit Editor roles only" in the Administrative Permissions doesn't work correctly

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#480]
### Ultimate Member Version
- [ ] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
When this feature is enabled, it is possible to edit all the roles, not only the Editor

### Expected behavior
Only Editor roles can be edited

### Actual behavior
All roles can be edited

### Steps to reproduce the behavior
1) Go to http://v.g-photo.com.ua/wp-admin/admin.php?page=um_roles as an administrator
2) Click "Edit" on any role (f.e. Subscriber)
3) Put a tick in the "Can edit other member accounts?"
4) In the "Can edit these user roles only" section, select the Editor
5) Click "Update Role" button
6) Go to "http://v.g-photo.com.ua/members/" as a user with the role that you changed(f.e. Subscriber)
7) Click the "Edit profile" button on the user with any role

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by denisbaranov** [comment]
Hi Vladislav,

Thanks for helping make UM better. This issue will be fixed in next updates.

Regards.
