### ISSUE TITLE
Fatal error in MailChimp plugin

### ISSUE THREAD

**Issue by czachor** [ultimatemember/ultimatemember#489]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 1.3.88 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
PHP fatal error occures when invalid API key is submitted

### Expected behavior
Form should be submitted and page reloaded

### Actual behavior
Fatal error occurs after submit:
> Fatal error: Uncaught Error: Call to undefined method WP_Error::get() in /wp-content/plugins/um-mailchimp/includes/core/filters/um-mailchimp-settings.php:97 Stack trace: #0 /wp-includes/class-wp-hook.php(286): um_mailchimp_render_field_type_mailchimp_api_key('<input type="te...', Array, Array, Object(um\admin\core\Admin_Forms_Settings)) #1 /wp-includes/plugin.php(203): WP_Hook->apply_filters('', Array) #2 /wp-content/plugins/ultimate-member/includes/admin/core/class-admin-forms.php(288): apply_filters('um_render_field...', '', Array, Array, Object(um\admin\core\Admin_Forms_Settings)) #3 /wp-content/plugins/ultimate-member/includes/admin/core/class-admin-forms.php(231): um\admin\core\Admin_Forms->render_field_by_hook(Array) #4 /wp-content/plugins/ultimate-member/includes/admin/core in /wp-content/plugins/um-mailchimp/includes/core/filters/um-mailchimp-settings.php on line 97

Now it's impossible to change any settings on the `Extensions` page because of the error.

### Steps to reproduce the behavior
Open `Settings > Extensions`, enter `45675867896789678test` (invalid key) in `MailChip API Key` field. Save and the error message is visible.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [x] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by champsupertramp** [comment]
Hi @vladislavkitchenko, 

We cannot provide fixes for Ultimate Member extensions in this public repository.  Please use the support ticket page to submit the issues with the extensions: http://ultimatemember.com/support/

Regards,
