### ISSUE TITLE
Profile picture crop not working ajax_resize_image & ajax_delete_profile_photo not found (404)

### ISSUE THREAD

**Issue by lexzz** [ultimatemember/ultimatemember#492]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
Just installed the latest version.
The upload problem seems to be fixed. But after uploading the window to crop the picture hangs. The crop function doesn't work properly

When I check my console I see the following error
https://www.******.com/um-api/route/um!core!Files/ajax_resize_image/e4b9341143 not found (404)

Same when I try to delete a profile picture:
https://www.******.com/um-api/route/um!core!Profile/ajax_delete_profile_photo/0b91fd3067 not found (404)

The uploading seems to work, when I close the upload window and refresh the page, the uncropped picture is visible.

### Expected behavior
The image should crop, and close the window

### Actual behavior
The uploading seems to work, when I close the upload window and refresh the page, the uncropped picture is visible.

### Steps to reproduce the behavior
Upload a new profilepicture, crop it and it hangs on "processing...."

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [x] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by lexzz** [comment]
![umerror](https://user-images.githubusercontent.com/13751516/43965968-ee372dce-9cc0-11e8-831d-54e71669504e.png)

**Comment by lexzz** [comment]
Just found the problem! 
The problem seemed to be the permalink of the WordPress installation
The way it was configured didn't work with ultimatemember

**Comment by nikitasinelnikov** [comment]
hi @lexzz 

We fixed this issue at 2.0.24 version. Please check.

Thanks!

**Comment by BeZoOo** [comment]
I am facing this issue now and I am using the latest version, you fixed nothing

**Comment by lexzz** [comment]
Hey @BeZoOo 
Did you try my solution? 

Changing the permalinkstructue fixed my problem.
