### ISSUE TITLE
Issue in layout

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#495]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.21

### Extensions Version
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2

### Subject of the issue
On the login page, if you don't pass the "reCAPTCHA" check and click "Login", the error message appear on the "Keep me signed in" field
Look at the screenshot: http://www.screencast.com/t/l3zYH7vUiYE

### Expected behavior
The error message don't appear on the "Keep me signed in" field

### Actual behavior
The error message appear on the "Keep me signed in" field

### Steps to reproduce the behavior
1) Go to "Login" page
2) Enter the correct login and password
3) Click "Login" button

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Fixed to branch fix/github#495
