### ISSUE TITLE
Issue in the layout in private chat

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#496]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.21

### Extensions Version
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
On the private chat, when you mouse over "remove", the icon overrides the text of the message
Look at the screenshot: http://www.screencast.com/t/C8jCMQB4

### Expected behavior
The icon is not overrides the text of the message

### Actual behavior
The icon overrides the text of the message

### Steps to reproduce the behavior
1) Go to "User" page> Messages
2) Mouse over to any message you send

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by champsupertramp** [comment]
Hi @vladislavkitchenko, 

We cannot provide fixes for Ultimate Member extensions in this public repository.  Please use the support ticket page to submit the issues with the extensions: http://ultimatemember.com/support/

Regards,
