### ISSUE TITLE
Issue: checkbox toggle is not shown. css classes are not removed properly 

### ISSUE THREAD

**Issue by mariolukas** [ultimatemember/ultimatemember#497]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
Checkboxes in Formulars do not work. 

### Expected behavior
When a checkbox in a Form is clicked it should
show that the state changed.

### Actual behavior
The state changes but the correct css class is 
not added to the <i> element. 

### Steps to reproduce the behavior
I don't know exactly. It seems to be an issue 
which is related to jquery ui. 

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

It seems that something breaks the `removeClass()` somehow. There was a similar [Bug ](https://stackoverflow.com/questions/14532327/odd-issue-with-jquery-removeclass-not-doing-anything) in jQuery Ui several years ago. But i am using a fixed version of jQuery UI.

However, I changed `removeClass()` to `removeAttr('class')` for removing all classes on an Element
in [um-scripts.js](https://github.com/ultimatemember/ultimatemember/blob/master/assets/js/um-scripts.js#L55). That seems to work. 

```
    jQuery(document).on('change', '.um-field-area input[type=checkbox]', function(){
        var field = jQuery(this).parents('.um-field-area');
        var this_field = jQuery(this).parents('label');
        if ( this_field.hasClass('active') ) {
            this_field.removeClass('active');
            this_field.find('i').removeAttr('class').addClass('um-icon-android-checkbox-outline-blank');
        } else {
            this_field.addClass('active');
            this_field.find('i').removeAttr('class').addClass('um-icon-android-checkbox-outline');
        }
    });
```

**Comment by denisbaranov** [comment]
Fixed to branch fix/github#497
