### ISSUE TITLE
Edit comments with hashtags

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#498]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.23

### Extensions Version
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
When you edit a comment that has a hashtag, HTML code is displayed in the edit field
Watch the video: http://www.screencast.com/t/FVp1eOpF

### Expected behavior
The text of the comment is displayed in the edit field
### Actual behavior
HTML code is displayed in the edit field

### Steps to reproduce the behavior
1) Go to "User" page > Activity
2) Edit your comment with the hashtag

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by champsupertramp** [comment]
Hi @vladislavkitchenko, 

We cannot provide fixes for Ultimate Member extensions in this public repository.  Please use the support ticket page to submit the issues with the extensions: http://ultimatemember.com/support/

Regards,
