### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by ahmadawais** [ultimatemember/ultimatemember#5]
Installed latest version and on welcome page I saw this
```
Warning: Invalid argument supplied for foreach() in /home/wp/public_html/wp-content/plugins/ultimate-member/admin/templates/welcome/about_footer.php on line 9
```

**Comment by ultimatemember** [comment]
I've just tried to uninstall and re-install UM on my installation, and I see the welcome page without any php warnings (debug mode on). please post a screenshot of the issue.

**Comment by ultimatemember** [comment]
We've just tried to install the plugin (a fresh install) and not gotten the error. Can we kindly ask you to disable other plugins and test for conflicts?

**Comment by ahmadawais** [comment]
Actually it is a fresh install, and there is nothing in the plugins except the default ones.

Is it Calum Allison? 
I'd like to suggest a few things, I am Ahmad Awais, I featured Ultimate Member at WPMetaList if you remember.

- Strong Pass is OFF but it is still asking me to enter one capital and small letter with number. I hate this option on sites, I think, users must be allowed to use their regular passwords, otherwise they stop logging in. 

- There should be a limit on how big file a user can upload while adding Cover image and display picture. People sometime can add 10Mb files and I don't wana pay for SSD :)

**Comment by ultimatemember** [comment]
I just tested the strong password on register form with the password "password" and it registered me fine (I turned off strong password on password field on register form).

The images are resized down after upload so they have a smaller image/file size. The problem is that many users profile photos are likely to be uploaded straight from their mobile phone. And with the megabytes available on phones these days the photos are large in size. So if you impose a file limit size then users wont be able to upload photos from their phone.

Is this on a local site install or an online site?

Thanks

**Comment by ahmadawais** [comment]
It is an online site. 
But you can give a choice to the admins to restrict the upload. It's compulsory since, anyone against my site will explore this as a vulnerability and will start uploading 500MB or data in GBs what then?
I'd like to restrict user from uploading anything bigger than 500KB.

And thanks for the password thing, I was doing it wrong, I found the solution.

**Comment by ultimatemember** [comment]
Well your server will most likely come with a max file upload size but we will add options in so you can limit the file sizes how you like :) . Just be aware that it may stop the average user from uploading a profile photo if they use mobile. But if you are using UM on a site like WP Meta your target user base will know how to reduce an image. If you create temporary admin details for your site we will login and have a look at what may be causing that error to show on your install if you want us to. But it might not be tonight as it's getting late here.

Thanks!

**Comment by ahmadawais** [comment]
Well, I will look into the error again. But I am going to strongly
appreciate the addition of max upload size feature since it should be
there. Almost all of the custom avatar WordPress plugins have it. I am
planning to shift WPMeta on UM ;)

**Comment by ultimatemember** [comment]
Yes we will add that in one of the next few updates. Good to hear that you are using UM for WPMeta. You will need to let us know once it's ready so we can check it out. Ok let us know what you find and we are happy to have a look at it if you want us to.

**Comment by ahmadawais** [comment]
Great, I'm also going to use it in a premium product, which willbe kind of
extension of UM.
