### ISSUE TITLE
After disabling the "Allow users to set their activity wall privacy through account page?" option, privacy settings are saved

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#500]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.23

### Extensions Version
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
If the option "Allow users to set their activity wall privacy through account page?" has been enabled and the user has set some privacy settings for himself, then after deactivating this option all user privacy settings will be saved
Watch the video: http://www.screencast.com/t/gZD8G9PssdOW

### Expected behavior
Privacy settings should be public after turning off this option

### Actual behavior
All user privacy settings are saved after this option is turned off

### Steps to reproduce the behavior
1) Go to wp-admin>Ultimate Member>Settings>Extensions>Social Activity
2) In the "Allow users to set their activity wall privacy through account page?" field сlear the check mark
3) Go to "User" page>Activity

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by champsupertramp** [comment]
Hi @vladislavkitchenko, 

We cannot provide fixes for Ultimate Member extensions in this public repository.  Please use the support ticket page to submit the issues with the extensions: http://ultimatemember.com/support/

Regards,
