### ISSUE TITLE
The "Download History" button redirects to the main page

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#503]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.23

### Extensions Version
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
If you delete all messages in the chat and click on the "Download History" button, you are redirected to the home page
Watch the video: http://www.screencast.com/t/sy3B4TOhhG

### Expected behavior
Buttons "Download History" should not be, if the chat is empty

### Actual behavior
Redirects to the home page

### Steps to reproduce the behavior
1) Go to "User" page>Messages
2) Delete all messages in a chat with someone
3) Click "Download History" button

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by champsupertramp** [comment]
Hi @vladislavkitchenko, 

We cannot provide fixes for Ultimate Member extensions in this public repository.  Please use the support ticket page to submit the issues with the extensions: http://ultimatemember.com/support/

Regards,
