### ISSUE TITLE
Issue in change the size of the text area

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#505]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.25

### Extensions Version
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
On the "User" page, the user can change the size of the text area and go beyond
Watch the video: http://www.screencast.com/t/ilPE7UZIagt

### Expected behavior
The text area can't go beyond

### Actual behavior
The text area can go beyond

### Steps to reproduce the behavior
1) Go to "User" page>Edit Profile
2) Change the size of the text area

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Fixed to branch fix/github#505
