### ISSUE TITLE
Doesn't verify a user account when he completes his profile

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#507]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.1.0

### Extensions Version
Profile Completeness - 2.0.4
bbPress - 2.0.4
User Tags - 2.0.3
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
When the user has completed their account, the account has not been verified
Watch the video: http://www.screencast.com/t/o8wnBfDF9

### Expected behavior
Account verified

### Actual behavior
Account not verified

### Steps to reproduce the behavior
1) Go to wp-admin>Ultimate Member>User Roles>Edit(eg Subscriber)>Profile Completeness
2) In the "Verify user account" field, select yes
3) Go to the "User" page as a user with this role, which you edited>Edit Profile
4) Complete your account
5) Go to "User" page

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [x] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [x] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [ ] Notices
- [x] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
fixed to branch fix/github#507
