### ISSUE TITLE
str_word_count on biography

### ISSUE THREAD

**Issue by xclam** [ultimatemember/ultimatemember#508]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
In french str_word_count don't concidere accent as a word.
I set word limitation to 40
I have this sentence :
Coach certifiée passionnée par le développement personnel, les neurosciences et l'éducation positive, je me ferai un plaisir de vous accompagner vers la détermination et la réalisation de vos objectifs, qu'ils soient d'ordre privé, familial ou professionnel.

### Expected behavior
Count 36 word and let save the profile

### Actual behavior
Count 45 word and throw error

### Steps to reproduce the behavior
Set up the word limit to 40 and copy/paste this sentence on a profile.

--> I fixe it adding accents in str_word_count
line 440 in includes/core/um-actions-form.php
`if ( str_word_count( $args[$key], 0, "éèàôù" ) > $array['max_words'] ) {`

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Thank you.
We will add this changes in the next release.
Branch: [fix/github#508__str_word_count__behavior](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23508__str_word_count__behavior)
