### ISSUE TITLE
In the wp-admin page does not display the saved values

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#509]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.1.0

### Extensions Version
Notices - 2.0.2
Profile Completeness - 2.0.4
bbPress - 2.0.4
User Tags - 2.0.3
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
In the wp-admin>Ultimate Member>Notices does not display the saved values
Watch the video: http://www.screencast.com/t/1d7Qg6OUnCf

### Expected behavior
Displays the saved values

### Actual behavior
Does not display saved values

### Steps to reproduce the behavior
1) Go to wp-admin>Ultimate Member>Notices>Edit Notice
2) Edit the fields
3) Update notice

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [x] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [x] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [x] Notices
- [x] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by inetnet** [comment]
In the current version this problem is not detected.
If you experience this problem please reopen the ticket
