### ISSUE TITLE
Notice is not displayed only to certain user, chosen by ID

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#510]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.0.1

### Extensions Version
Notices - 2.0.2
Profile Completeness - 2.0.4
bbPress - 2.0.4
User Tags - 2.0.3
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
When you select a specific user by the ID, the notice is not displayed
http://www.screencast.com/t/1OVEJamJeiH

### Expected behavior
Notice is displayed

### Actual behavior
Notice is not displayed

### Steps to reproduce the behavior
1) Go to wp-admin>Ultimate Member>Notices>Edit Notice
2) In "Show only to certain user(s)" field enter value
3) Click the Update button
4) Go to your site

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [x] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [x] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [x] Notices
- [x] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Thanks. It will be fixed in the next "Ultimate Member - Notices" extension release.
