### ISSUE TITLE
WooCommerce Checkout Payment section won't load when UM is enabled.

### ISSUE THREAD

**Issue by andresmrg** [ultimatemember/ultimatemember#513]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
WooCommerce Checkout Payment section won't load when UM is enabled. Screenshot related http://prntscr.com/kpw6o6

### Expected behavior
WooCommerce checkout payment section should load as usual and the user should be able to pay.

### Actual behavior
WooCommerce checkout payment section gets stuck loading the payment section. Image related: http://prntscr.com/kpw6o6

### Steps to reproduce the behavior
Login to the wordpress site as a customer > select a product to purchase > go to the checkout page, see the payment section gets stuck loading.

## PHP version
- [x] 7.0 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by inetnet** [comment]
This problem was not found on the current version (2.0.39), if you still have this problem, please open the ticket again.
