### ISSUE TITLE
Ajax load more post issue on Profile page

### ISSUE THREAD

**Issue by nash4ever** [ultimatemember/ultimatemember#514]
### Ultimate Member Version
- [x] 2.x ( latest )

### Subject of the issue
Posts don't load on the `?profiletab=posts` page if you click on the load more button (load more posts with ajax) 

### Expected behavior
It should load more posts of the user (it worked fine on 1.x versions, after I updated my Ultimate member plugin to the latest version it stopped working)

### Actual behavior
If the visitor isn't logged the `/wp-admin/admin-ajax.php` returns 400 error, response: 0
If the visitor is logged the `/wp-admin/admin-ajax.php` returns 200 error, and empty response

Request pamareters:

```
action | um_ajax_paginate
args | post,10,10,26
hook | um_load_posts

```

### Do you use UM extensions? 
No.

**Comment by nash4ever** [comment]
Any update? Or only we have this issue?

**Comment by TomasZmek** [comment]
any news? I have meny authors on my site, who have more 10 post. But users can not listen, becouse this button not work.

**Comment by fidoboy** [comment]
I'm also having this problem. Please update with any news or solution

**Comment by TomasZmek** [comment]
after last update ultimatemember problem was fixed

**Comment by fidoboy** [comment]
> after last update ultimatemember problem was fixed

I've updates installed to latest version available, and the problem, for not logged users, still exists. It works fine however for logged in users

**Comment by fidoboy** [comment]
There is any news about this issue? Not logged users can't load using ajax because the AJAX answer is always empty

**Comment by inetnet** [comment]
This problem was not found on the current version (2.0.39), if you still have this problem, please open the ticket again.
