### ISSUE TITLE
In the wp-admin>Forms page doesn't display the saved values

### ISSUE THREAD

**Issue by vladislavkitchenko** [ultimatemember/ultimatemember#517]
### Ultimate Member Version
- [ ] 1.3.x
- [x] 2.1.0

### Extensions Version
Instagram - 2.0.2
Real-time Notifications - 2.0.3
Notices - 2.0.2
Profile Completeness - 2.0.4
bbPress - 2.0.4
User Tags - 2.0.3
Social Activity - 2.0.7
Private Messages - 2.0.8
Online Users - 2.0.4
Friends - 2.0.2
Followers - 2.0.4
Google reCAPTCHA - 2.0.2
Verified Users - 2.0.3

### Subject of the issue
In the wp-admin>Ultimate Member>Forms page doesn't display the saved values
After the form is updated, the default values are displayed
Watch the video: http://www.screencast.com/t/g10J5TBL

### Expected behavior
Displays the saved values

### Actual behavior
The default values are displayed

### Steps to reproduce the behavior
1) Go to wp-admin>Ultimate Member>Forms>Edit Form
2) Edit the fields
3) Update form

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [x] Instagram
- [x] User Tags 
- [x] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [x] Followers
- [x] Real-time Notifications
- [ ] Social Login
- [x] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [x] Verified Users
- [ ] myCRED
- [x] Notices
- [x] Profile Completeness 
- [x] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [x] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Can't reproduce this issue in the "Ultimate Member" version 2.0.39
Note: Don't forget to click "Update" form after editing the form fields.
