### ISSUE TITLE
Someone else's name on account page after change in URL

### ISSUE THREAD

**Issue by Imbatido** [ultimatemember/ultimatemember#520]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue

Hello,

I think I found a kind of bug in your plugin. I want a user system on my website but only for login. So people can't see other users, there's no communication and users don't know of their existing. So there is no members list, and I closed the user page, there's only the possibility to change their own account things like name and password.

So account page of user xxxx is:
../wordpress/account/xxxx/

But when I change xxxx in the URL into yyyy (a user that also exists) then the name of yyyy shows up above the page, with the data of the logged in user (xxxx) underneath. And in the title bar is also yyyy named.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Hi.
There is no bug. You can deny to view other profiles using UM setting "Can view other member profiles?"
see http://joxi.net/Vm6oEqliD8EMN2
