### ISSUE TITLE
Allow removal of CSS and JS on non UM pages

### ISSUE THREAD

**Issue by carasmo** [ultimatemember/ultimatemember#522]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
There are 21 CSS files and 21 JS files loaded site wide.

### Expected behavior
Just load the CSS and JS on only UM pages or have conditionals like WooCommerce (which also does this but they have a lot of widgets, you only have the search widget). 

such as `is_ultimate_member();`

### Actual behavior
21 CSS files and 21 JS files load site wide.

### Steps to reproduce the behavior
Install the plugin.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
N/A

**Current solution.**

For those who want to remove the CSS and JS on all other pages, here you go. The UM search form in the widget will need to be styled by you. I used JS to remove UM classes and added crap. My theme search form looked awesome and UM messed it up.

**This php is added to a core functionality plugin. There is a starter on Github.** 

The array is the page ids, change them to yours. 

This is related to [issue 407](https://github.com/ultimatemember/ultimatemember/issues/407)

```
add_action( 'wp_enqueue_scripts',  'core_functionality_dequeue_UM_styles', 1000 );
/** 
 * Remove all 21 CSS files (horrible) for UM on non UM pages
 * Remove all 21 JS files (disgusting) for UM on non UM pages
 * 
*/
function core_functionality_dequeue_UM_styles(){

	// if is a UM page, then load, otherwise don't
	// this is a list of page ids using UM, can't find is_um() conditional or equiv 
	if ( is_page( array( '13', '16', '15', '18', '14', '12', '17' ) ) ) return;
		
	// UM CSS Array	
	$um_css = array( 
		'um_default_css',
		'um_responsive',
		'um_styles',
		'select2',
		'um_profile',
		'um_account',
		'um_members',
		'um_tipsy',
		'um_datetime_time',
		'um_datetime_date',
		'um_datetime',
		'um_scrollbar',
		'um_fileupload',
		'um_fonticons_fa',
		'um_fonticons_ii',
		'um_raty',
		'um_crop',
		'um_modal',
		'um_misc',
		'um_old_default_css',
		'um_old_css',
	); 
	
	foreach ( $um_css as $css ) :
		wp_dequeue_style( $css );
	endforeach;
	
	// UM JS Array
	$um_js = array(
		'um_datetime_locale',
		'um_gchart',
		'select2',
		'um_jquery_form',
		'um_fileupload',
		'um_functions',
		'um-gdpr',
		'um_conditional',
		'um_scripts',
		'um_members',
		'um_profile',
		'um_account',
		'um_datetime',
		'um_datetime_date',
		'um_datetime_time',
		'um_datetime_legacy',
		'um_scrollbar',
		'um_raty',
		'um_crop',
		'um_tipsy',
		'um_modal',
		'um_responsive',
	); 	
	
	foreach ( $um_js as $js ) :
		wp_dequeue_script( $js );
	endforeach;	
		
}

```

**Comment by carasmo** [comment]
Yes, they need to remove all !important, and hook earlier so that themes can put their styles last.

**Comment by Beee4life** [comment]
the css sucks indeed... i hook a custom css file with priority 999 after the css so mine gets used and I can override them (unfortunately you have to use some !importants again).

**Comment by tylertadej** [comment]
Thanks for posting this @carasmo - UM 2.0 needs a lot of work but this helps!

Try replacing the static page IDs with this:
`if ( is_ultimatemember() ) return;`

It is working for me using the latest version of UM

**Comment by Beee4life** [comment]
I have dropped the use of Ultimate Member all together. I noticed I was better of writing my own instead of creating workarounds.

**Comment by denisbaranov** [comment]
You may use temporary solution to disable UM scripts and styles on the pages where there is no any UM blocks: pages, shortcodes, widgets. This solution is written like simple plugin "Ultimate Member - Maybe load assets", you may copy it to the "/wp-content/plugins/" directory and activate on the admin "Plugins" page. If you use custom pages or URLs, you may add it to the $um_posts or $um_urls arrays.
I hope it would be useful.

[um-maybe-load-assets v.1.0.2.zip](https://github.com/ultimatemember/ultimatemember/files/2937176/um-maybe-load-assets.v.1.0.2.zip)

**Comment by Beee4life** [comment]
Maybe the next user will benefit from it. I'm not touching UM anymore with a 10 foot pole :)

To even step it up, I built [my own plugin](https://github.com/Beee4life/b3-onboarding) and I plan to extend it a shit load more... because everything that I thought was wrong with your plugin, I'm fixing (or have fixed) in mine.

**Comment by tripflex** [comment]
Why would you not just add the handling to only load these files on the pages it requires, instead of every single page which is just bloat ... don't really see why this issue was closed as it's def still an issue

**Comment by thedigitalcircle** [comment]
Hi @tripflex 
Thanks for addressing the issues. We are also facing same issue.
Shuvashish

**Comment by tripflex** [comment]
https://docs.ultimatemember.com/article/1490-how-to-remove-css-and-js-on-non-um-pages

**Comment by haydnjames** [comment]
@tripflex It's good that there is now a recognised solution for remove the JS/CSS in places it's not needed. Hopefully they'll tackle the fact CSS/JS is also split across 20-30+ individual files next!

**Comment by tripflex** [comment]
@haydnjames yeah this should be default, css/js should ONLY be loaded on pages in which it's required, loading on every page is just sloppy dev practices (and don't get me wrong i've done it before myself as well when I just didn't even know, but experienced WordPress developers should know this already)

**Comment by robtucker168** [comment]
I have just installed UM had a play, felt good about the settings.... and then ran a GTM... WOW!!!! WT#! So much crap added site wide. To then find out that this has been a problem for 2 years! Yes I found the PhP workaround. tried to apply that using Code Snippets plugin but it didn't work. 

My next step is to deactivate and delete UM. And move on to another plugin. I feel sorry for the 200k installs and I bet half have no clue every single one of their site pages has a huge UM dump on it. what a shame. 

And let's be honest even if this gets fixed (Finally) Any one that jumped ship is not going to change their members plugin back to UM.

**Comment by tripflex** [comment]
@robtucker168 couldn't agree more ... the income from the paid addons should be enough to support fixing these issues it shouldn't land on the shoulders of other developers to do.  This is specifically the reason I do not use UM anymore, even though it's a GREAT plugin .. so sad :(

**Comment by thedigitalcircle** [comment]
Hi @tripflex 
Can you suggest some alternative plugin to use with WPJM. I am also using the plugin only for handling multiple signin and registration process.
