### ISSUE TITLE
Category post protect restriction should not apply in home/front-page.

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#53]
hi @ultimatemember 

If you change the category content availability to 'Content accessible to Logged In Users' and view an archive page or a post with that category, it forces a user to login but it should not apply in homepage.

Here's a patch:
https://github.com/ultimatemember/ultimatemember/commit/1e813076af54ee395951ab4b0477feef442e1f6e

**Comment by ultimatemember** [comment]
Merged to master https://github.com/ultimatemember/ultimatemember/pull/54
