### ISSUE TITLE
"um_after_changing_user_password" running before password has changed

### ISSUE THREAD

**Issue by davidlima88** [ultimatemember/ultimatemember#532]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
"um_after_changing_user_password" running before password has changed when using the reset password process, interrupting the password update.

### Expected behavior
The hook should run after the reset password process has stored the new password in the DB.

### Actual behavior
"um_after_changing_user_password" running before password has changed when using the reset password process, interrupting the password update.

### Steps to reproduce the behavior
Add this to functions.php
```php
add_action( 'um_after_changing_user_password', 'auto_login_after_password_reset' );
function auto_login_after_password_reset($user_id){
    if (!is_user_logged_in()) {
        wp_set_current_user($user_id, $user_login);
        wp_set_auth_cookie($user_id);
        do_action('wp_login', $user_login);
        wp_redirect( get_permalink( get_page_by_path( 'welcome-cybersecurity-training-101' ) ) );
    }
    exit;
}
```
Then use the password reset process normally. The function would log me in, but if I log out, I have to use the old password to log in again. The new password won't be stored.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Thanks. It will be changed in the next release.
Branch [fix/github#532_move_hook_um_after_changing_user_password](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23532_move_hook_um_after_changing_user_password)
