### ISSUE TITLE
Redirect not functioning after registration.

### ISSUE THREAD

**Issue by nicxcin** [ultimatemember/ultimatemember#537]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0.31 ( latest )

### Subject of the issue
A redirect is setup so that after a new user is created the user should be redirect to an account pending page.

(A separate redirect after login is functioning) 

### Expected behavior
Redirect to 'Account Pending' Page

### Actual behavior
Registration Page is reloaded

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.1 above

### Do you use UM extensions? 
None

**Comment by denisbaranov** [comment]
You may configure UM behavior after registration using user role options.
Set option "Action to be taken after registration" to "Redirect to URL".
Set you 'Account Pending' page URL to the "Set Custom Redirect URL" option.

![um roles action to taken after registration](https://user-images.githubusercontent.com/28895658/53903915-8f290380-404d-11e9-9991-db8f134b2b9f.png)
