### ISSUE TITLE
Security issue: ability to retrieve all usernames from each UM password reset page

### ISSUE THREAD

**Issue by fedeandri** [ultimatemember/ultimatemember#541]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
By reading the response headers from the browser console it's possible to retrieve all usernames just by calling the password reset URL several times with incremental user IDs

### Steps to reproduce the behavior
1) create a password reset URL like this one
https://anyUMenabledWebsite.com/password-reset/?act=reset_password&hash=ARBITRARY-RESET-KEY&user_id=1
2) open the browser console and read the first response header which sets a cookie containing the username of the user with ID=1 (usually the admin)
3) repeat steps 1 and 2 while incrementing by 1 the value for user_id and you can retrieve all usernames of that particular website

The problem is in /ultimatemember/includes/core/class-password.php in "form_init()" line 274
https://github.com/ultimatemember/ultimatemember/blob/5e7b250a9e13bd962fb30bd6db4368ab63496e45/includes/core/class-password.php#L274

The cookie that makes it possibile to retrieve the username is the one set at line 290
https://github.com/ultimatemember/ultimatemember/blob/5e7b250a9e13bd962fb30bd6db4368ab63496e45/includes/core/class-password.php#L290

I suggest that you go back to how WordPress handles each password reset request and you set the username (and not the user ID) on your query string. Something like this:
https://anyUMenabledWebsite.com/password-reset/?act=reset_password&hash=RESET-KEY&login=username

So it won't be possible to retrieve all the usernames just by enumerating all user IDs

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by tylertadej** [comment]
@ultimatemember any plans to fix this?

**Comment by champsupertramp** [comment]
Hi @tylertadej  / @fedeandri,

We have added additional password reset hash validation to prevent this issue.

Ref https://github.com/ultimatemember/ultimatemember/commit/00ea16d24f596ba94f4d91a085e85cc477d34c02

cc: @nikitasinelnikov 

Regards,
