### ISSUE TITLE
Registration unable with conditional logic

### ISSUE THREAD

**Issue by Johnny99211** [ultimatemember/ultimatemember#542]
### Ultimate Member Version
Tell us what UM core version you use. 
- 2.0.38

### Subject of the issue
When I add an registration form and add a role dropdown there with 2 roles like "customer" and "subscriber" and add for example a field phone number for only the customer (he needs to fill it out, not the subscriber) with this conditional logic:

`show **if** phone_number **equals to** um_customer`

and continue the registration with the subscriber selected, I can't continue with the registration because the phone number is still required even it's not seen when the subscriber is selected in the dropdown.

I've manually added `$array['required'] = 0;` in the `um_get_custom_field_array` function outside the if/else to prove if there is a problem and it is because after this the registration worked.

So this is not a plugin issue.

Here you can download a video of the problem: https://drive.google.com/open?id=1p6VdVbnmKCCh_XvBxfz9n4J1C1cDAfdz

### Expected behavior
The registration must be possible for the subscriber without the phone number

### Actual behavior
The registration can't be proceeded for the subscriber because the phone number don't is set to not required because of the visibility.

### Steps to reproduce the behavior
Create a registration form with a role select and some fields depending on each role.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [x] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [x] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by Johnny99211** [comment]
As I can see you don't use/check the `$parent_key` in this list here:

`list( $visibility, $parent_key, $op, $parent_value ) = $value;`

So my conditional logic can't even work. In the view it does because I see different fields for each roles but the registration fails. This is not cool in my eyes mate. I'll try to fix this by my own and try to commit it so you can review it.

**Comment by Johnny99211** [comment]
I've found out that `$_POST[ $condition_metakey ]` is always undefined. Have you implemented it correctly here? Because you define a variable named `$condition_metakey` before?

**Comment by masimies** [comment]
Just put something for default value like 999999. People add their correct number if they want anyway. Then you get some time to move on until this is solved.

**Comment by Johnny99211** [comment]
Thats not a good solution because in this case I can make every field not required and all is messed up. I'll make a video of the problem so you can understand it.

**Comment by masimies** [comment]
Yes. In my own stuff, i have added role selection before (this affects all fields what are needed afterwards). Depending of role, these fields are required or not. If role is customer, phone number is required and so on.

**Comment by Johnny99211** [comment]
I do the exact same and does it work on your side?

**Comment by masimies** [comment]
In my case, i have another table where to i collect customer data. Out of "Meta". Due the information what it includes. I put it in more secure place. Common registration is just the first step. This other information is collected after this.

**Comment by Johnny99211** [comment]
Oh okay. So we can't be sure if only I have this problem? Or what do you want to say with this?

**Comment by Johnny99211** [comment]
Is there a UM developer?

**Comment by chriseckman** [comment]
This is an issue. I just needed to update my forms. I also submitted a support ticket, however adding default values "fixed" it in the meantime.

**Comment by Johnny99211** [comment]
My code above also fixed it. I'm running good on this without any issues since I've fixed it my way.
