### ISSUE TITLE
Setting Not Saving 

### ISSUE THREAD

**Issue by shamiul72** [ultimatemember/ultimatemember#543]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.x ( latest )

### Subject of the issue
Setting Not Saving 

### Expected behavior
At the email tab when try to email activation and after configuration when i press save setting button on the top, it redirect me to a page like that "http://site.com/wp-admin/admin.php?page=um_options&tab=email&email=checkmail_email" with a 404 page error without saving the setting. I think there maybe an issue with url/path of post values. Could you please help me and assist me what should i do to fix this issue. Thanks

### Actual behavior
It maybe save and reload the page the same setting page without any 404 error.

## PHP version
- [x] 7.1 above

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Can't reproduce this issue. Saving works well in the "Ultimate Member" Version 2.0.39
