### ISSUE TITLE
Documentation doesn't link properly

### ISSUE THREAD

**Issue by Beee4life** [ultimatemember/ultimatemember#546]
### Subject of the issue
All filters links on the Hooks page link to the current page with a hook $_GET variable, but it just redirects to the current page. No info is shown.

This is the link `https://docs.ultimatemember.com/article/1324-hooks-list?hook=um_core_pages`

### Expected behavior
Redirect to the proper page.

### Actual behavior
Redirects to the current page.

### Steps to reproduce the behavior
* Go to https://docs.ultimatemember.com/article/1324-hooks-list?hook=um_core_pages.
* Scroll to the filters list.
* Click a link.

Also mentioned on the [Wordpress Forums](https://wordpress.org/support/topic/bug-in-documentation/).

**Comment by Beee4life** [comment]
Even though i dropped the plugin all together for being a mess, the fact the documentation links still aren't updated is testament to the rest...

**Comment by champsupertramp** [comment]
Hi @Beee4life , i apologize for the sudden closing of this issue. 

We are making the repo active. I confirmed that this issue occurs. 

I'm re-opening this issue.


Regards,

**Comment by Beee4life** [comment]
Don't on my account :) I am not using the plugin at all anymore. I'll unsubscribe of this topic as well..

**Comment by Beee4life** [comment]
Closing because I stopped using this plugin due to all the chaotic code/documentation.
