### ISSUE TITLE
CSS is riddled with !important

### ISSUE THREAD

**Issue by Beee4life** [ultimatemember/ultimatemember#548]
I've been using your plugin for about 2 days now and the css is giving me headaches. I found 100+ instances of !important in the plugin.

`The !important rule also makes it hard for the user to apply their own styles for better readability or accessibility while viewing your website. Not only that but also the more !important rules you use, the more difficult your CSS code will become to read and maintain. For these reasons, it should be used only where it is absolutely necessary (in very few occasions) and when there is no other option. In most cases, it is possible to get rid of the need for using !important rules by simply changing the HTML tags on your page or assigning new CSS selectors to them.`

Please fix your CSS. A lot of users will appreciate it, even though they don't realise it now...

**Comment by freelancesam** [comment]
Why do these threads keep getting closed? Please fix the !important tags as it's getting difficult to blend UM in with wordpress themes

**Comment by jameshahn2** [comment]
Seriously, fix this problem! It's ruining everything. It's a simple ask!
