### ISSUE TITLE
Google Recaptcha css enqueued in wrong place

### ISSUE THREAD

**Issue by Beee4life** [ultimatemember/ultimatemember#552]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
The css for the recaptcha plugin is loaded in the footer. Since most people load their css in the header it's harder to override it (not impossible, but harder).

### Expected behavior
I expected the css to be loaded in the header.

### Actual behavior
It gets loaded in the footer.

### Steps to reproduce the behavior
Default behavior.

### Proposed solution
Enqueue it in the header and not with a high priority so it gets loaded at the end after most stylesheets.

**Comment by denisbaranov** [comment]
It's not a bug.  reCAPTCHA styles and scripts are loaded only on that pages where it is used. It have been done on purpose to increase page load speed. 
Use CSS specificity to override default CSS rules. See articles:
- [Calculating a selector’s specificity](https://www.w3.org/TR/selectors/#specificity)
- [How is specificity calculated?](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

**Comment by Beee4life** [comment]
It might not be a bug, but it is (in my opinion) poorly coded.
But since I have dropped the plugin completely all together already (because of too many flaws/incorrect definitions/css), I don't really care anymore...
