### ISSUE TITLE
get_email_template called incorrectly

### ISSUE THREAD

**Issue by Beee4life** [ultimatemember/ultimatemember#553]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.x ( latest )

### Subject of the issue
Notice: get_email_template called incorrectly.

### Expected behavior
I went to the settings screen for emails.
My default language is Dutch. 
I have no emails translated.
I then switched to English through the WPML language switcher in the admin bar.
If you then click the email title it throws a notice.

`Notice: get_email_template werd verkeerd aangeroepen. /Users/Beee/HTML/domain/webapp/content/plugins/ultimate-member/templates/email/en_US/checkmail_email.php does not exist in /Users/Beee/HTML/domain/webapp/cms/wp-includes/functions.php on line 4231`

### Actual behavior
A notice is thrown.

### Steps to reproduce the behavior
Explained above.

## PHP version
- [x] 7.1 above

### Do you use UM extensions? 
- [X] Google reCAPTCHA

**Comment by denisbaranov** [comment]
Fixed, see branch [fix/github#553_get_email_template_translation](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23553_get_email_template_translation)
Wait for release.

**Comment by Beee4life** [comment]
Good for the people using it. I have dropped the plugin completely in the meanwhile.
