### ISSUE TITLE
jQuery 3 support

### ISSUE THREAD

**Issue by iholka** [ultimatemember/ultimatemember#556]
### Ultimate Member Version
Tell us what UM core version you use. 
- 2.0.39

### Subject of the issue
Im using jQuery 3 on my website and your plugin is not compatible with this library. I made basic changes to support jQuery 3. But on every plugin update the changes are gone.

Could you please get these changes to your code? In jQuery 3 are few commands removed from library. So, for basic functionality of your free version you need to do changes in these 4 files:

- ultimate-member\assets\js\um-responsive.js
- ultimate-member\assets\js\um-responsive.min.js
- ultimate-member\assets\js\um-scrollbar.js
- ultimate-member\assets\js\um-scrollbar.js

1. Open file
2. Find string **.load(**
3. Replace with **.on('load',**
4. Do this change on each file named below,
5. Save files

Please, make these changes to your code. It really helps to work this plugin with jQuery 3 and will be no JS errors on console.

### Expected behavior
No JS errors in webtools console - user JS not stopped on this JS error

### Actual behavior
Not supported .load function stops JS on site and functionality breaks on site

### Steps to reproduce the behavior
- Include jquery 3 on your site
- Install and activate Ultimate member plugin

## PHP version
- 7.1 above

### Do you use UM extensions? 
no

**Comment by denisbaranov** [comment]
Changed. Changes will be included to the next release.
Branch [fix/github#556_jQuery_3_support](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23556_jQuery_3_support)
