### ISSUE TITLE
Notification with sound

### ISSUE THREAD

**Issue by gencher** [ultimatemember/ultimatemember#557]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
How can I make the Real-time Notifications extension to play a "beep" sound when there is a notification?

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [x ] Private Messages
- [ ] Followers
- [x] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Hi,
Try to use attached code snippet. Add it to the functions.php file. Don't forget to change sound file URL.

[github#557_Notification_with_sound.zip](https://github.com/ultimatemember/ultimatemember/files/2991927/github.557_Notification_with_sound.zip)

**Comment by Rickymase** [comment]
@denisbaranov The change works, there is only one problem, you hear the audio every time I load a page, even when I have 0 notifications. How can I solve it?
