### ISSUE TITLE
Reset Password should send no-cache headers

### ISSUE THREAD

**Issue by sciolist** [ultimatemember/ultimatemember#559]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
Common wordpress caches lead to users resetting other users password instead of their own.

### Expected behavior
Resetting my password should reset my own password, no one elses.

### Actual behavior
When you click on a reset password link in an email, you are sent to a page with a user_id and hash header that is written to a cookie.. you are then redirected to.. /password-reset?act=reset_password (or something similar.)

But on this page the value of the cookie is printed from php into the html. The templates for these pages send no cache instructions to the client, so caches (or browsers, proxies) are free to cache the results.

The result of this is that when I reset my password, the next user who attempts to reset their password will instead reset my password.

To prevent these sorts of issues, wordpress supplies a `nocache_headers()` function that sends the appropriate cache headers. You can see how this works in wp-login.php, which interacts properly with a well implemented cache library / server.

### Steps to reproduce the behavior
- Create a site with ultimate members running behind Varnish (for example.)
- Create two users, 'user a' and 'user b'
- Use the reset password function as 'user a', set the password to 'user a'
- Verify that you can log in with the new password
- Use the reset password function as 'user b', set the password to 'user b'
- Verify that you can now log in as 'user a' with password 'user b', but you cannot login as 'user b' with this password.

## PHP version
- [x] 7.1 above
- [x] 5.4 
- [x] 5.3 below

**Comment by denisbaranov** [comment]
Thanks for getting in touch.  We will add this in the next release.
