### ISSUE TITLE
array_unique in class-members.php fails:  Object of class WP_User could not be converted to string

### ISSUE THREAD

**Issue by sgatterer** [ultimatemember/ultimatemember#560]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.0.43 (WordPress 5.1.1)

### Subject of the issue
The member list is always empty. The error in the logfile says:
PHP Catchable fatal error: Object of class WP_User could not be converted to string in .../wp-content/plugins/ultimate-member/includes/core/class-members.php on line 459

### Actual behavior
This is caused by calling "array_unique" on an array that contains objects that cannot be converted to a string. The result of the "WP_User_Query" is an array that contains WP_User objects, with that array the "array_unique" fails:
array_unique( $users->results )
This is because of the default $sort_flags of "array_unique" being "SORT_STRING":
https://www.php.net/array_unique
array_unique ( array $array [, int $sort_flags = SORT_STRING ] )

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

**Comment by denisbaranov** [comment]
Thanks for getting in touch. We will add "SORT_REGULAR" flag in the next release.
Branch: [fix/github#560_add_sort_flags_to_array_unique](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23560_add_sort_flags_to_array_unique)
