### ISSUE TITLE
members-grid.php: method "um_fetch_user" expects userId, but gets called with WP_User object

### ISSUE THREAD

**Issue by sgatterer** [ultimatemember/ultimatemember#561]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.0.43 (WordPress 5.1.1)

### Subject of the issue
In templates/members-grid.php the method "um_fetch_user" gets called with an WP_User object as parameter "um_fetch_user( $member );", instead the parameter should be "um_fetch_user( $member->ID );"

See https://docs.ultimatemember.com/article/153-umfetchuser

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

**Comment by denisbaranov** [comment]
Hi. In templates/members-grid.php variable $member should be numeric. Look for the beginning of the file.
`foreach( um_members('users_per_page') as $member)`
Function `um_members('users_per_page')` should return an array of member's "user_id"

![gitgub#561](https://user-images.githubusercontent.com/28895658/55885440-98f4d800-5bb2-11e9-8b86-4fb59bc979e8.png)

**Comment by sgatterer** [comment]
Ok, we got an issue with the WP_User_Query parameters, so we got WP_User_Object objects in the results array instead of user ids. We fixed that and now it is working as you have shown. Thx!
