### ISSUE TITLE
Error with AJAX load for not logged users and page cache

### ISSUE THREAD

**Issue by fidoboy** [ultimatemember/ultimatemember#562]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
"Load more" fails on user's posts in front end with W3 Total Cache for not logged users

### Expected behavior
The "load more" button should work as expected without problems

### Actual behavior
It returns error and there is no data returned into the AJAX response

### Steps to reproduce the behavior
Activate a page cache in Wordpress, like W3 Total Cache, and try to load more items on a public user profile. It happens only when you aren't logged in.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ X] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ X] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [X ] MailChimp
- [ ] User Reviews
- [ X] Verified Users
- [ ] myCRED
- [ X] Notices
- [X ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [X ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by fidoboy** [comment]
To solve this the nonce should be removed as required when the user profile is public and the visitor is not logged in. That way it should work without problem

**Comment by denisbaranov** [comment]
Sorry, nonce field can not be removed by security reasons, please read article [WordPress Nonces](https://codex.wordpress.org/WordPress_Nonces)
I recommend you to add this page to cache ignore list. If you use "W3 Total Cache" plugin you may use options "Never cache the following pages" and/or "Never cache pages that use these custom fields".

![gitgub#562](https://user-images.githubusercontent.com/28895658/55890179-ea08ca00-5bba-11e9-9626-563bf2d48b18.png)
![gitgub#562_](https://user-images.githubusercontent.com/28895658/55890182-ec6b2400-5bba-11e9-88d9-16b8ce3170ba.png)
