### ISSUE TITLE
Undefined PHP notice when WP is ran trough CLI

### ISSUE THREAD

**Issue by ajoah** [ultimatemember/ultimatemember#563]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
When WP is ran trough cli (for exemple `wp cron event run --due-now`) Ultimate member causes a PHP notice: `Undefined index: HTTP_HOST in/wp-content/plugins/ultimate-member/includes/core/class-permalinks.php on line 136`

Indeed at this [line](https://github.com/ultimatemember/ultimatemember/blob/8cc4be56d6243f0c0a11abc611897043ef4902a6/includes/core/class-permalinks.php#L136), the plugin uses global variable `$_SERVER['HTTP_HOST']` which is empty when PHP is ran through CLI.

### Expected behavior
No error

### Actual behavior
PHP notice error

### Steps to reproduce the behavior
Run WP through PHP CLI. `wp cron event run --due-now` for exemple

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by denisbaranov** [comment]
Thanks. We will use 'localhost' if $_SERVER['HTTP_HOST'] is empty. 
Branch: [fix/github#563_http_host_for_cli](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23563_http_host_for_cli)
