### ISSUE TITLE
After upgrading core higher than 2.0.4.1: mCustomScrollbar is not a function

### ISSUE THREAD

**Issue by JeusuDigital** [ultimatemember/ultimatemember#567]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
After upgrading core higher than 2.0.4.1 Um Messaging button shortcode breaks

### Expected behavior
Display shortcode without jQuery error

### Actual behavior
After upgrading core higher than 2.0.4.1 when using short code: [ultimatemember_message_button user_id=”123” ]

A jQuery error is thrown on page load and the shortcode button does not work:
mCustomScrollbar is not a function
um-messaging.js line 38 to 40

### Steps to reproduce the behavior
Use core version later than 2.0.4.1, install messaging plugin, use shortcode: [ultimatemember_message_button user_id=”123” ]

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [x] Private Messages
- [ ] Followers
- [x] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by davidwolfpaw** [comment]
Confirming that I am having the same issue with Private Messages on core v2.0.45, WP v5.2, and PHP v7.2

**Comment by JeusuDigital** [comment]
I think maybe the mCustomScrollbar functions have been replaced but have not been updated in the messaging plugin JS, see the commit below:

https://github.com/ultimatemember/ultimatemember/commit/887d4b5293e6f261b16c60cc7538fa276a6a5422

**Comment by nikitasinelnikov** [comment]
Hi there guys,

Please upgrade UM:Private messages plugin to the latest version. You will see upgrade message in your plugins list or at your UM website account page.

Let me know if it works,
Thanks and feel free to ask!
