### ISSUE TITLE
Only administrators can edit their profile

### ISSUE THREAD

**Issue by gregsullivan** [ultimatemember/ultimatemember#568]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
Following the plugin changes due to the security issues, our users are unable to edit their profiles. Instead, they receive the "You are not allowed to edit this user" message.

### Expected behavior
Users should be able to edit their own profiles.

### Actual behavior
They receive the "You are not allowed to edit this user" message.

### Steps to reproduce the behavior
Attempt to edit one's profile while not logged in as an administrator.

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

**Comment by gregsullivan** [comment]
We traced the issue to these lines in `um-actions-profile.php`:

```
	$user_id = null;
	if ( isset( $args['user_id'] ) ) {
		$user_id = $args['user_id'];
	} elseif ( isset( $args['_user_id'] ) ) {
		$user_id = $args['_user_id'];
	}

	if ( UM()->roles()->um_current_user_can( 'edit', $user_id ) ) {
		UM()->user()->set( $user_id );
	} else {
		wp_die( __( 'You are not allowed to edit this user.', 'ultimate-member' ) );
	}
```

Our solution was to set `$user_id` to the current logged in user assuming the user is logged in:

```
	$user_id = null;
	if ( isset( $args['user_id'] ) ) {
		$user_id = $args['user_id'];
	} elseif ( isset( $args['_user_id'] ) ) {
		$user_id = $args['_user_id'];
	} elseif ( is_user_logged_in() ) {
		$user_id = get_current_user_id();
	}

	if ( UM()->roles()->um_current_user_can( 'edit', $user_id ) ) {
		UM()->user()->set( $user_id );
	} else {
		wp_die( __( 'You are not allowed to edit this user.', 'ultimate-member' ) );
	}
```

**Comment by nikitasinelnikov** [comment]
Hi @gregsullivan 

Could you provide where the Profile Form is situated and why there isn't the hidden field "user_id", we include it here https://www.screencast.com/t/ny7B7h8ed

Let me know,
Thanks!

**Comment by gregsullivan** [comment]
The profile form is being loaded via a shortcode on a page. The URL looks like this for the edit form:

`/page-name/?profiletab=main&um_action=edit`

The hidden field definitely isn't loading. What causes the mode to be set to `profile`?

**Comment by nikitasinelnikov** [comment]
hi @gregsullivan 

Thank you for your feedback,
So you have found that UM()->fields()->set_mode !== 'profile', what is value of this variable at your installUM()->fields()->set_mode ?

We set mode on loading all profile fields. https://www.screencast.com/t/89SCmqrT3i

Please let me know,
Best Regards!

**Comment by gregsullivan** [comment]
Sorry—having just stepped through the code, the issue is that in this line:

https://github.com/ultimatemember/ultimatemember/blob/1e960e1089283e0beafdaf6c23dd32596f08d80d/includes/core/um-actions-profile.php#L510

`UM()->user()->target_id` is `NULL` so the hidden field isn't added.

**Comment by nikitasinelnikov** [comment]
Hi @gregsullivan

Could you try the version from this commit https://github.com/ultimatemember/ultimatemember/commit/b248def2757b30b44fac7f2ece7f450f71736e73

I have added the code lines for set target ID for not pre-set User Profile page.

Let me know if this works,
Thanks!

**Comment by gregsullivan** [comment]
This works on my client's site—thanks very much!
