### ISSUE TITLE
Send notification in  Real-time Notifications Extension when a user submits a Contact Form 7 form.

### ISSUE THREAD

**Issue by Rickymase** [ultimatemember/ultimatemember#572]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
Describe your issue here.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [x ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

I have modified a function to send a notification when sending a contact form, but it does not work. 

Do you have any tips on the action or hooks to use? Thanks.

I installed Contact Form 7 and the Ultimate Member plugin with the Real Notification extension.

This is the code entered in my function.php file.

```
/*

	This code sample shows you how to use the API to create
	and add custom notifications (for real-time notifications)
	plugin.

	**STEP 1**: You need to extend the filter: um_notifications_core_log_types with your
	new notification type as follows for example

	*/

add_filter('um_notifications_core_log_types', 'add_custom_notification_type_2', 200 );
	function add_custom_notification_type_2( $array ) {
			
		$array['new_action_2'] = array(
			'title' => 'Cv recive', // title for reference in backend settings
			'template' => '<strong>{member}</strong> has just did some action.', // the template, {member} is a tag, this is how the notification will appear in your notifications
			'account_desc' => 'Account Description', // title for account page (notification settings)
		);
			
		return $array;
	}

	/*

	**STEP 2**: Add an icon and color to this new notification type

	*/

	add_filter('um_notifications_get_icon', 'add_custom_notification_icon_2', 10, 2 );
	function add_custom_notification_icon_2( $output, $type ) {
		
		if ( $type == 'new_action_2' ) { // note that our new action id is "new_action" from previous filter
			$output = '<i class="um-faicon-paper-plane" style="color: #336699"></i>';
		}
		
		return $output;
	}

	/*

	**STEP 3**: Send notification after CF7 mail sent. The action used is the Contact Form 7 plugin that allows you to run the php code when the form has been sent.

	*/

add_action('wpcf7_mail_sent', 'trigger_new_notification_2’, 100);

	function trigger_new_notification_2( $args ) {
				
		$vars['photo'] = um_get_avatar_url( get_avatar( get_current_user_id(), 40 ) ); 
			$vars['member'] = um_user('display_name');
            $vars['notification_uri'] = "https://www.mysite.com/";
             
			UM()->Notifications_API()->api()->store_notification( get_current_user_id(), 'new_action_2', $vars );
			
		}
```
The first 2 steps work perfectly, but it does not send the notification (step 3) to the current user, when he sent a form via Contact Form 7.  ** If I use any UM function, for example, add_action ('um_before_profile_fields', 'trigger_new_notification_2', 100); the notification is sent.

**Comment by ashubawork** [comment]
Hi,

As I see your code is working. I tested it. You just need to enable your notifications in the admin area. Go to "Ultimate member" -> Settings -> Extensions -> Notifications -> and enable "Cv recive".
