### ISSUE TITLE
WebAuthn FIDO2 fingerprint or usb security key login

### ISSUE THREAD

**Issue by Johnny99211** [ultimatemember/ultimatemember#573]
Hello to all,

I've successfully implemented the login via a fingerprint or an usb security key within UltimateMember. If anyone is interested how I did this, let me know it and I'll try to find some time to publish it in a fork.

By the way this means that a user needs to activate it via a settings page and can choose this method now at the login page via a dropdown. Now he just needs to enter his email, the email get's verified and the authentication is done via WebAuthn. If this is successful, I log the user in.

All the best
Johnny

**Comment by Johnny99211** [comment]
Seems like no one is interested in so I'll close this "issue".

**Comment by jordan26** [comment]
@Johnny99211 - Interested.

Not everyone knows to look for your posts here, so many like me may be interested without having to explicitly state so. Always worth sharing tips/knowledge without first getting people to say "Yes".

**Comment by Wuemeli** [comment]
Iam also interested
