### ISSUE TITLE
Input fields of non-administrator accounts are not sanitized

### ISSUE THREAD

**Issue by katsar0v** [ultimatemember/ultimatemember#578]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.x ( latest )

### Subject of the issue
I could put `<img src=a onerror=alert(1)>` near my name on the profile page. I had to create custom role for this

### Expected behavior
Input should be sanitized

### Actual behavior
XSS Attack

### Steps to reproduce the behavior
1. Create custom role, e.g. student
2. Create "profile" page
3. Put `<img src=a onerror=alert(1)>` near first name

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users
- [ ] Groups
- [ ] Gallery

I patched it so:
```
add_filter('um_account_pre_updating_profile_array', function($data) {
          foreach($data as $key => $value) {
              $data[$key] = esc_html(strip_tags($value));
          }
          return $data;
      });
```

**Comment by katsar0v** [comment]
Any update on this? Is crucial to security I think

**Comment by nikitasinelnikov** [comment]
Hi @katsar0v 

The fix will be added soon in the new UM version.

Thanks for your feedback,
Best Regards!
