### ISSUE TITLE
Bulk actions for large sites

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#58]
A client sent the following improvements:

`When I add new user name, by name I mean role like member, admin. Then for that new role I need to edit every single post, instructor, event, page, I mean every single page that is close to the public and manually click on the box next to that user role. By default it is uncheck. It is pain in the back specially with larger sites.`

**Comment by ultimatemember** [comment]
@champsupertramp I do not understand clearly, sorry. What does that mean?

**Comment by champsupertramp** [comment]
This has been resolved. Closing this issue now.
