### ISSUE TITLE
If the user tries to got to the log in page after the login, redirect him

### ISSUE THREAD

**Issue by Glumac7** [ultimatemember/ultimatemember#583]
Hello

I can't seem to figure out how to disable a page after a user has logged in.
What I am trying to do is straight forward. After a user has logged in, redirect him to the Homepage (this works) and if he tries to go to the log in page, redirect him to the Homepage again (disable the Log In page and add a redirection once he has logged in).
I have tried using the UM Content Restriction on the Log In page, but with no luck.
I am open for all suggestions.

Many Thanks

**Comment by ashubawork** [comment]
Hi,

You could try to use this hook in your child theme functions.php (where your_login_page_id - ID of login page):

add_action( 'template_redirect', function() {
	if( is_page( your_login_page_id ) && is_user_logged_in() ) {
		wp_redirect( site_url(), 301 );
		exit();
	}
});

Thank you.
