### ISSUE TITLE
Phrase "Chose display form"

### ISSUE THREAD

**Issue by ralden15** [ultimatemember/ultimatemember#584]
### Ultimate Member Version
- 2.0.52

### Subject of the issue
I'm translating the Ultimate Member plugin to Portuguese. I saw the phrase "Chose display form" that I believe should be "Choose display form". Not?

**Comment by champsupertramp** [comment]
Hi, Thanks for letting us know. We have pushed fixes for this issue. 

ref: https://github.com/ultimatemember/ultimatemember/commit/e9aa014d314631eef50ca24fc139367d3ca05ff3
