### ISSUE TITLE
Please update pickadate to v3.6.4

### ISSUE THREAD

**Issue by shaunco** [ultimatemember/ultimatemember#588]
### Ultimate Member Version
Tell us what UM core version you use. 
- [ ] 1.3.x
- [x] 2.0.55 ( latest )

### Subject of the issue
The current pickadate library v3.5.6 is from 2015.

### Expected behavior
Should be using v3.6.4 from this year, which has significant fixes for various browsers.

**Comment by champsupertramp** [comment]
Hi @shaunco We have updated Pickadate.js to the stable version 3.6.2: https://amsul.ca/pickadate.js/

We need to wait for their official release before we can update again.

Regads
