### ISSUE TITLE
Reset Password Link – Does not work in email templates

### ISSUE THREAD

**Issue by Viborasnake** [ultimatemember/ultimatemember#591]
Hello, 

I've a site with ultimate member and is configurated to send an email every time i create a new account. The ultimate memeber plugin must send and HTML Email with an `<a href="{password_reset_link}">Reset password</a>` but every time the email has come with the link broken, empty.

I've no clue about this issue, any help wil bew appreciated.

**Comment by champsupertramp** [comment]
This issue has been closed for not following the bug reporting format.
