### ISSUE TITLE
Registration submission returns 502 bad gateway

### ISSUE THREAD

**Issue by markorapaic** [ultimatemember/ultimatemember#592]
Hi there!

When clicking "register" the registration form returns a 502 bad gateway error. This happens even if you haven't filled anything out. Where you'd normally expect the error notifications for the empty fields to appear, the page just returns a 502 bad gateway error.

I've tested this with our client's theme, and also the Twenty Nineteen theme, and the same thing happens. I've also deactivated all other plugins except for the Ultimate Member plugin, and can confirm that this bug occurs only when the Ultimate Member plugin is activated.

When I deactivate the latest plugin, and replace it with an older version (2.0.49 in my case), the registration form works as you would expect.

To reproduce, just create a normal registration page with the latest plugin version. We haven't done anything special.

We're not using any additional extensions on this site, and the site itself is running on WP Engine.

**WordPress Environment**
<details>
--- Site Info ---

Multisite:					No

--- Hosting Provider ---

Host:						WP Engine

--- User Browser ---

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          76.0.3809.132 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_14_6) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/76
                          .0.3809.132 Safari/537.36
                          
---- Current User Details --

Role: administrator

--- WordPress Configurations ---

Version:						5.2.2
Language:					en_US
Permalink Structure:			/%postname%/
Active Theme:				Twenty Nineteen 1.4
Page On Front:				Home (#2)
Page For Posts:				 (#0)
ABSPATH:					/nas/content/live/wpengineinstall/
All Posts/Pages:				452
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Disabled
WP Table Prefix:          			Length: 3, Status: Acceptable
Memory Limit:   				40MB

--- UM Configurations ---

Version:						2.0.49
Upgraded From:            		None
Current URL Method:			
Cache User Profile:			Yes
Generate Slugs on Directories:	Yes
Rewrite Rules: 				Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			No
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No

--- UM Pages Configuration ---

User:						https://wpengineinstall.wpengine.com/user/
Account:						https://wpengineinstall.wpengine.com/account/
Members:					https://wpengineinstall.wpengine.com/members/
Register:						https://wpengineinstall.wpengine.com/register/
Login:						https://wpengineinstall.wpengine.com/login/
Logout:						https://wpengineinstall.wpengine.com/logout/
Password Reset:				https://wpengineinstall.wpengine.com/password-reset/

--- UM Users Configuration ---

Default New User Role: 		0
Profile Permalink Base:		user_login
User Display Name:			full_name
Force Name to Uppercase:		No
Redirect author to profile: 		No
Enable Members Directory:	No
Use Gravatars: 				No
Require a strong password: 	Off

--- UM Access Configuration ---

Panic Key: 								
Global Site Access:						Site accessible to Everyone
Backend Login Screen for Guests:			No
Redirect to alternative login page:			
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		No
Enable the Reset Password Limit:			Yes
Reset Password Limit: 3Disable Reset Password Limit for Admins: No
Blacklist Words: 							5

--- UM Email Configurations ---

Mail appears from:  			From name
Mail appears from address:  	from@email.com.au
Use HTML for E-mails:   		Yes
Account Welcome Email:  		Yes
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	Yes
Account Deleted Email:  		Yes
Password Reset Email:   		Yes
Password Changed Email: 		Yes

--- UM Total Users ---

                All Users(3132)
administrator(10)
editor(2)
subscriber(3119)
none(1)

--- UM Roles ---

                Administrator (administrator)
Editor (editor)
Author (author)
Contributor (contributor)
Subscriber (subscriber)

--- UM Custom Templates ---

                N/A

--- UM Email HTML Templates ---

                N/A

--- Web Server Configurations ---

PHP Version:              			7.3.7-2+ubuntu18.04.1+deb.sury.org+1
MySQL Version:            			5.7.26
Web Server Info:          			Apache

--- PHP Configurations ---

PHP Memory Limit:         			512M
PHP Upload Max Size:      			50M
PHP Post Max Size:        			100M
PHP Upload Max Filesize:  			50M
PHP Time Limit:           			3600
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			Yes

--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			N/A
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function exist on your web server.
Exif:				          PHP Exif library is installed on your web server.

--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			/var/lib/php/sessions
Use Cookies:              			On
Use Only Cookies:         			On

--- WordPress Active Plugins ---

                Ultimate Member: 2.0.56
</details>

**Comment by champsupertramp** [comment]
This issue has been closed for not following the bug reporting format.

**Comment by markorapaic** [comment]
**Expected behavior**
When clicking on register, i expect the form to either proceed with registering a user, OR, notifying them of any errors in their submission.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
When clicking "register" the registration form returns a 502 bad gateway error. This happens even if you haven't filled anything out, or if you've filled everything out correctly.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'a page with a registration form that has been generated by the latest version of Ultimate Member'
2. Click on 'register'
4. See error

**Expected behavior**
When clicking on register, I expect the form to either proceed with registering a user, OR, notifying them of any errors in their submission.

**Screenshots**
None

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce


**WordPress Environment**
<details>
```
--- Site Info ---

Multisite:					No

--- Hosting Provider ---

Host:						WP Engine

--- User Browser ---

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          76.0.3809.132 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_14_6) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/76
                          .0.3809.132 Safari/537.36
                          
---- Current User Details --

Role: administrator


--- WordPress Configurations ---

Version:						5.2.2
Language:					en_US
Permalink Structure:			/%postname%/
Active Theme:				Twenty Nineteen 1.4
Page On Front:				Home (#2)
Page For Posts:				 (#0)
ABSPATH:					/nas/content/live/wpengineinstall/
All Posts/Pages:				452
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Disabled
WP Table Prefix:          			Length: 3, Status: Acceptable
Memory Limit:   				40MB


--- UM Configurations ---

Version:						2.0.49
Upgraded From:            		None
Current URL Method:			
Cache User Profile:			Yes
Generate Slugs on Directories:	Yes
Rewrite Rules: 				Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			No
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No


--- UM Pages Configuration ---

User:						https://wpengineinstall.wpengine.com/user/
Account:						https://wpengineinstall.wpengine.com/account/
Members:					https://wpengineinstall.wpengine.com/members/
Register:						https://wpengineinstall.wpengine.com/register/
Login:						https://wpengineinstall.wpengine.com/login/
Logout:						https://wpengineinstall.wpengine.com/logout/
Password Reset:				https://wpengineinstall.wpengine.com/password-reset/


--- UM Users Configuration ---

Default New User Role: 		0
Profile Permalink Base:		user_login
User Display Name:			full_name
Force Name to Uppercase:		No
Redirect author to profile: 		No
Enable Members Directory:	No
Use Gravatars: 				No
Require a strong password: 	Off


--- UM Access Configuration ---

Panic Key: 								
Global Site Access:						Site accessible to Everyone
Backend Login Screen for Guests:			No
Redirect to alternative login page:			
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		No
Enable the Reset Password Limit:			Yes
Reset Password Limit: 3Disable Reset Password Limit for Admins: No
Blacklist Words: 							5


--- UM Email Configurations ---

Mail appears from:  			From name
Mail appears from address:  	from@email.com.au
Use HTML for E-mails:   		Yes
Account Welcome Email:  		Yes
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	Yes
Account Deleted Email:  		Yes
Password Reset Email:   		Yes
Password Changed Email: 		Yes


--- UM Total Users ---

                All Users(3132)
administrator(10)
editor(2)
subscriber(3119)
none(1)


--- UM Roles ---

                Administrator (administrator)
Editor (editor)
Author (author)
Contributor (contributor)
Subscriber (subscriber)


--- UM Custom Templates ---

                N/A


--- UM Email HTML Templates ---

                N/A


--- Web Server Configurations ---

PHP Version:              			7.3.7-2+ubuntu18.04.1+deb.sury.org+1
MySQL Version:            			5.7.26
Web Server Info:          			Apache


--- PHP Configurations ---

PHP Memory Limit:         			512M
PHP Upload Max Size:      			50M
PHP Post Max Size:        			100M
PHP Upload Max Filesize:  			50M
PHP Time Limit:           			3600
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			Yes


--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			N/A
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function exist on your web server.
Exif:				          PHP Exif library is installed on your web server.


--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			/var/lib/php/sessions
Use Cookies:              			On
Use Only Cookies:         			On


--- WordPress Active Plugins ---

                Ultimate Member: 2.0.56
```
</details>

**Comment by champsupertramp** [comment]
Hi @markorapaic ,

We are not able to reproduce the issue on our testing sites with your steps. Do you have Cloudflare installed in your  server?

502 error is likely a server related issue. Therefore, ask your host why this error is occurring.

Your error_log file may also explain it. So please check the error logs on your server. If you need help locating them, ask your hosting provider to help you with that.



Regards,

**Comment by markorapaic** [comment]
Hi @champsupertramp - that site, in particular, isn't running through Cloudflare. Having said that, I have asked the host, and they've pointed me back in the direction of the plugin. They mentioned that it was a segmentation fault. When I reverted to an older version of the plugin, the registration form worked. This makes me think the host/server isn't the cause of the error. Are there any specs on my host that might conflict with that version in particular? Cheers

**Comment by champsupertramp** [comment]
Hi @markorapaic 

Could you please contact me via http://ultimatemember.com/feedback/ ?

I would like to check the issue on your site so we can provide solutions. 

Regards

**Comment by champsupertramp** [comment]
Closing this ticket due to inactivity.

If you need any further assistance with this then please feel free to reopen this ticket and post an update on your current status.
