### ISSUE TITLE
Members directory, add sort by "Last name, then First name", "Nickname" & "Other (Custom Field)"

### ISSUE THREAD

**Issue by FlyThePlanet** [ultimatemember/ultimatemember#597]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with the Ultimate Member's Members directory page, weather it's the grid or list design.
What's the purpose of a directory? List members, people.
And how do you sort a list of persons everywhere? By their...
- Last/Family names then First names, when real names are public
- Nickname or Username, when members are anonymous

But with Ultimate Member...
- you have no option to sort by "Last names then First names"
- and you have no standard option to sort by Nickname either. You can do it using "Other (Custom Field)" but still, you'll not be able to enable Nickname for custom sorting.

But when you build a website with a lot of members or a family website, you necessarily end up with a lot of members with the same family name (sometimes 5, 10, 20, 100). So you NEED to sort them via Last name then First name. There's no other option. You can't only sort them by Last name and leave dozens of members with the same Last name randomly sorted on several pages for the First name :-1: 

It really looks like a very basic feature for a “Directory” page. Every directory is sorted this way, Last name then First name, OR Nickname/Username.

**Describe the solution you'd like**

1/ In Ultimate Member > Member Directories > edit Members > "Default sort users by" & "Choose field(s) to enable in sorting" > for both fields add the 2 options: "Last name, then First name" & "Nickname"

**Adding "Last name, then First name" being the most important!**

2/ In Ultimate Member > Member Directories > edit Members > ...
- Below the "Meta key" field, add the "Meta key field name" text field
- In "Choose field(s) to enable in sorting", add the "Other (Custom Field)" option

This will complete the "Other (Custom Field)" functionality by allowing to add this field in the custom sorting list displaying the "Other (Custom Field)" and using the "Meta key".

Thanks!

**Describe alternatives you've considered**
Nothing

**Additional context**

**Comment by FlyThePlanet** [comment]
Now that the version 2.1.0 has been released with the new Member directory, I hope this improvement will get some attention as it's really needed for a fully functional directory.
Thanks!

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

What "Display Name" do you use at your website? Is it "Last name, then First name" or can it be changed to this view?

Nickname sorting is added in the latest commit in "master" branch

Let me know,
Thanks!

**Comment by FlyThePlanet** [comment]
Nope, it's "First name Last name". "Robert Smith" for example, while on a directory it's always "Last name First name"...
- Smith John
- Smith Paul
- Smith Robert
- Smith Vladimir
- Etc.

**Comment by nikitasinelnikov** [comment]
@FlyThePlanet 

Could you check how this code snippet works?

https://gist.github.com/nikitasinelnikov/2fb1b30fcee35ded4935eb3d240331cb

Let me know about the results,
Thanks!

**Comment by FlyThePlanet** [comment]
To add where? In the theme functions.php or the UM file functions.php

**Comment by nikitasinelnikov** [comment]
To your theme functions.php
Sorry, I have changed the functions' names...there were duplicates.

**Comment by FlyThePlanet** [comment]
Ok. It's not not creating any error but...
1/ can I try it on UM 2.1.1 or only the 2.1.2 RC1?
2/ what am I supposed to see? I can't find any change on UM 2.1.1 where I have many users.
Am I supposed to find a new option in the settings?

I can try it on UM 2.1.2 RC1 but I have to create fake users.

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet ,

Yes, you need to find the new sorting option, added via custom code in the snippet above.

The code is compatible with 2.1.1 and 2.1.2-RC1 both.

Let me know,
Thanks!

**Comment by FlyThePlanet** [comment]
If I'm supposed to find the new option in  "Default sort users by" then it's not working. There's nothing new.

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

Sorry for the delay, there is the initialization of member directories variables on 'plugins_loaded'  hook, so adding code snippet in theme's functions.php file is late. Do you have some customization plugin on your website? If yes, just insert this code snippet to your customization plugin.

There are my screenshots:
https://www.screencast.com/t/fDg2tJGCad5
https://www.screencast.com/t/CWWwhBv9

Let me know if this works for you,
Thanks!

**Comment by FlyThePlanet** [comment]
> there is the initialization of member directories variables on 'plugins_loaded' hook, so adding code snippet in theme's functions.php file is late. Do you have some customization plugin on your website? If yes, just insert this code snippet to your customization plugin.

I'm not 100% sure about what you call a 
Nope. I don't think I have "customization plugin" but I don't think I have one.

Can I add this code somewhere in the UM code , just for testing?
Do you plan to add this enhancement in the next version of UM? Maybe I can just test a RC2?
Sorting by Last name then First name is a basic of any directory.

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

I meant by "customization plugin" the next. Often a good practice for site's customizations is the creation of 1 plugin with all customized handlers (callback functions, assets, etc.) instead of the using of functions.php. 

Sure you could try to add this code directly to the end of wp-content/plugins/ultimate-member/ultimate-member.php file.

Btw. there is a released 2.1.2 version at wp.org.

This functionality can duplicate the sorting via "Display name" if the site's admin set default filling the display name value as "Last name" + "First Name". So we decided don't add this option yet to make the sorting settings more clear. But you could use the snippet above in your case.

Thanks!

**Comment by FlyThePlanet** [comment]
> Often a good practice for site's customizations is the creation of 1 plugin with all customized handlers (callback functions, assets, etc.) instead of the using of functions.php.

Ok. I didn't know some people would do that. I've never seen this recommendation. They always ask for a child theme and to use functions.php.

> This functionality can duplicate the sorting via "Display name" if the site's admin set default filling the display name value as "Last name" + "First Name". So we decided don't add this option yet to make the sorting settings more clear.

That doesn't make any sense to me.
And I'll explain you why in detail... (please don't take it for yourself, when I say "you" it's "the team", "the team's decision")

1. In the WP "Display name" field, you can choose the:
- Nickname
- Username
- First name
- Last name

But you also offer those 4 choices as sorting option in UM. Why?
You should also consider those 4 choices as duplicate of Display name if I follow your reasoning?

2. You offer in the core, options we can already easily get via the "Other (Custom Field)" functionality. On the other hand, you refuse options we can't get without code modification! It makes no sense. It's a kind of 2nd level of duplicate.
Offering those 4 options was not the priority as they are single field criteria. UM is already offering the possibility to get them by using the "Other (Custom Field)"!
But on the other hand you refuse to add options that are multi fields criteria, the ones that are impossible to setup via the UM GUI. It's really not logical.

3. You offer useless options and refuse useful options!
- Nickname
It a very valid sorting criteria. BUT... if an admin chose to display sort his site members by Nicknames, then you have 99.99% chances (if not 100% chances) that the Display name is the Nickname; so you can sort by Display name!
Indeed, you can't sort by Nickname if your members are known under their real name, First or Last name. It makes no sense.
- Username
This option should be removed! For security reasons, you can't decently encourage admins to display and sort their members via their username! And if they insist, they can still use the "Other (Custom Field)" functionality, but at least, you can't be blamed for encouraging revealing members' username.
- First name
This option makes no sense. You can't **only** sort on First names. You'll end-up with tons of duplicates with the same First name, randomly displayed as not sorted by their last name.
- Last name
This option also makes very very little sense as it's also close to impossible to sort **only** by Last names. You'll end-up with dozens of duplicates with the same Last name, randomly displayed as not sorted by their first name.
- Random
Also makes very very little sense for a Directory as you can't find anyone. What's the point?
- Display name
Makes sense, especially if Nickname or "Last name First name" is set in WP. **BUT... can't be used if "First name Last name" is set in WP. In this case, you still need "Last name First name" as sorting option and you offer no solution to fix this most common case!**
- New user first, Last user first, Last login
Makes sense.

4. You completely ignore the fact that "Display name" can be chosen by each user!
In this case, it messes up all your point.
You just can't rely on Display name as you will end up sorting all together "Last name" with "Nickname", Username", First name Last name", etc..

Conclusion, you're not consistent if your logic of duplicates with Display name, you offer by default options already easy to get and refuse options with no solution, you offer several completely pointless options, but still, you refuse to add by default the most widely used basic option of every directly which is to sort first by the Family name (Last name) and then by the First name.

Sorry, but all this (the team decision) makes no sense to me.

**Comment by FlyThePlanet** [comment]
BTW, I confirm your code works in wp-content/plugins/ultimate-member/ultimate-member.php but it will be removed as soon as I update UM :-/

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

You could get the latest 2.1.3-beta1 version from "master" branch. There is possible to sort by "Last & First name". This ability will be added to the official 2.1.3 version also.

Let me know how it works for you,
Thanks!

**Comment by FlyThePlanet** [comment]
> You could get the latest 2.1.3-beta1 version from "master" branch.

Ok. Thanks. I'll test it as soon as the RC is available in the releases page...
https://github.com/ultimatemember/ultimatemember/releases

**Comment by FlyThePlanet** [comment]
Ok I've looked at the commits and finally tested it via applying the modification on " includes/core/class-member-directory.php"...
https://github.com/ultimatemember/ultimatemember/commit/cceb22e9c344c07a155abae257d6e82416b641ab

And I can confirm it works fine, thanks! 👍 
So for me, the 1st part of this enhancement request is completed.

Is left, the 2nd part...

> 2/ In Ultimate Member > Member Directories > edit Members > ...
> - Below the "Meta key" field, add the "Meta key field name" text field
> - In "Choose field(s) to enable in sorting", add the "Other (Custom Field)" option

It's not critical, but IMO this will complete the "Other (Custom Field)" functionality which currently looks started but not really finished.
This would allow to add this custom field in the custom sorting list, properly displaying the "Meta key field name" in the directory page and using the "Meta key" for the SQL query.

**Comment by FlyThePlanet** [comment]
> (BTW, there a problem with the French translation of the Nickname field. It's not aligned on the WP field name but I don't know how to report this type of issue. WP Nickname field is called "Pseudonyme" in the French version of WP. But in the UM translation it's not aligned, it's called "Surnom" which is very confusing)

Ok, I've requested the update...
https://translate.wordpress.org/projects/wp-plugins/ultimate-member/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4705152&filters%5Btranslation_id%5D=67950579

**Comment by FlyThePlanet** [comment]
> nikitasinelnikov closed this 5 minutes ago

Oooops. I guess I can consider this as the answer to the 2nd part.

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

Sorry, I didn't pay attention to your 2nd paragraph. 

> It's not critical, but IMO this will complete the "Other (Custom Field)" functionality which currently looks started but not really finished.
This would allow to add the "Other (Custom Field)" option in the custom sorting list, properly displaying the "Meta key field name" in the directory page and using the "Meta key" for the SQL query.

Do you mean to add all wp_user_meta meta keys here?

https://www.screencast.com/t/yE3Zk0SyFYCT

Let me know,
Thanks!

**Comment by FlyThePlanet** [comment]
> Do you mean to add all wp_user_meta meta keys here?

No. Wait, I design something for you...

**Comment by FlyThePlanet** [comment]
Ok so...

The point is when you want to set a default sort order, you can chose in between 10 fields/criteria selected by the UM team + you've added the possibility to select "Other (Custom Field)" (cf. #1 on the screen copy).

If we select this "Other (Custom Field)" option, then the "Meta key" field is displayed below to set the Meta key we want to use as criteria to sort the members.

BUT... it's only available for the sorting **by default**.
This option can't be used below in the Custom sorting feature.

So I suggest to:
1/ add this "Other (Custom Field)" option in the "Choose field(s) to enable in sorting" list to complete this feature of "Other (Custom Field)" that otherwise looks not finished (cf. #3 on the screen shot)
2/ add a "Meta key name" field just below the "Meta key" field to allow setting a name, a description, to the "Meta key" criteria (cf. #2 on the screen shot). Indeed, by adding this "Other (Custom Field)" option in the Custom sorting list, you will have to display this Meta key criteria in the sorting options on the Directory form. So you will need a name to display for this criteria, not only a technical "Meta key".

![image](https://user-images.githubusercontent.com/39710808/70567645-a4136400-1b96-11ea-87dd-fc258dbe3ae9.png)

That's it. Hope it's clearer now :-)

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

There is the latest release candidate of 2.1.3 version in the "master" branch with the features for Custom Field sorting meta-keys and labels settings in the member directory.

Could you check how it works for you?

Let me know,
Thanks!

**Comment by FlyThePlanet** [comment]
There's no 2.1.3 RC? Where is it supposed to be?
https://github.com/ultimatemember/ultimatemember/releases

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

It's here https://github.com/ultimatemember/ultimatemember/releases/tag/2.1.3-rc.1

Let me know how it works,
Thanks!

**Comment by FlyThePlanet** [comment]
For me it works fine 👍 
- No issue on the Member Directory setting form.
- No issue on the Member Directory in view mode.
- You've even been a bit further than my suggestion by allowing to add multiple Custom fields to the "Sort by" list of criteria.

Well done @nikitasinelnikov , thanks!

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

Thanks for your suggestions!

Regards
