### ISSUE TITLE
um_after_user_account_updated & um_account_pre_update_profile consistency

### ISSUE THREAD

**Issue by MCKLtech** [ultimatemember/ultimatemember#602]
**Is your feature request related to a problem? Please describe.**

These hooks should be consistent in the data order and what they pass.

do_action( 'um_account_pre_update_profile', $changes, um_user( 'ID' ) );

do_action( 'um_after_user_account_updated', get_current_user_id(), $changes )

**Describe the solution you'd like**

Both hooks should be updated to reflect the order of the other. Furthermore, get_current_user_id() assumes a front end user and will fail if the hook is being called elsewhere. It should be replaced with um_user( 'ID' ) or a guarantee of the user ID
 
**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by champsupertramp** [comment]
Hi @MCKLtech 

I have pushed updates in master branch:
https://github.com/ultimatemember/ultimatemember/commit/8aff6c6acf1adbd84dcd7faabaaedc3e76b2ffc0

Regards,
