### ISSUE TITLE
uppercase flag do not work

### ISSUE THREAD

**Issue by dinastyoffreedom** [ultimatemember/ultimatemember#604]
**Expected behavior**
Flag Uppercase is off but it work like it should be ON
this is part of install info., like yuo can see User member configuration
**Force Name to Uppercase:		No**
but  it work like it is always set YES

How can be solve that. I Installed this RC1 hoping the problem was solved.
With Uppercase Enabled Users cannot login since password is always wrong

I do not know if depend by theme used. Can I have a suggestion how it can be solved
thanks
franco

see installation log

## Please include this information when posting support requests ##
--- Site Info ---

Site URL:					http://osservatoriodirittiumani.info
Home URL:					http://osservatoriodirittiumani.info
Multisite:					No

--- Hosting Provider ---

Host:						DBH: db771253650.hosting-data.io, SRV: osservatoriodirittiumani.info

--- User Browser ---

Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          77.0.3865.120 
User Agent String:        Mozilla/5.0 (Windows NT 10.0; Wi 
			  n64; x64) AppleWebKit/537.36 (KH
                          TML, like Gecko) Chrome/77.0.386
                          5.120 Safari/537.36
                          
---- Current User Details --

Role: administrator

--- WordPress Configurations ---
Version:						5.2.4
Language:					it_IT
Permalink Structure:			/%year%/%monthnum%/%day%/%postname%/
Active Theme:				Vienasbel Child 1.0.1
Page On Front:				Front Page (#8)
Page For Posts:				Blog (#10)
ABSPATH:					/homepages/39/d770964398/htdocs/clickandbuilds/OsservatorioDirittiUmani/
All Posts/Pages:				2
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Disabled
WP Table Prefix:          			Length: 8, Status: Acceptable
Memory Limit:   				40MB

--- UM Configurations ---
Version:						2.1.0-rc.1
Upgraded From:            		2.1.0-beta1
Current URL Method:			
Cache User Profile:			Yes
Generate Slugs on Directories:	Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			No
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No
 
 --- UM Users Configuration ---
Default New User Role: 		subscriber
Profile Permalink Base:		user_login
User Display Name:			full_name
**Force Name to Uppercase:		No**
Redirect author to profile: 		No
Enable Members Directory:	Yes
Use Gravatars: 				Yes
Gravatar builtin image:		default
    UM Avatar as blank Gravatar: 	Yes
Require a strong password: 	Off

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [ ] I can reproduce this bug consistently using the steps above.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
```
Copy and paste the install info from ** Ultimate Member > Settings > Install Info ** in WordPress admin.
```
</details>

**Comment by ashubawork** [comment]
Hello,

I check your registration form. You have CSS code for input fields:
`
input[type="text"], input[type="email"], input[type="url"], input[type="password"], input[type="search"], input[type="tel"], input[type="number"], textarea, select, .form-control {
    max-width: 100%;
    height: 50px;
    background-color: #f2f2f2;
    border: none;
    padding: 9px 25px;
    border-radius: 4px;
    font-family: "Muli", sans-serif;
    font-weight: 400;
    font-size: 0.9em;
    text-transform: uppercase;
}
`
Code `text-transform: uppercase;` make letters uppercase. You need to ovveride it with `text-transform: none;`.

Thank you.
