### ISSUE TITLE
um_after_user_status_is_changed_hook needs User ID or similar

### ISSUE THREAD

**Issue by MCKLtech** [ultimatemember/ultimatemember#605]
**Is your feature request related to a problem? Please describe.**

do_action( 'um_when_status_is_set', um_user( 'ID' ) );

Passes the User ID but this is before the status is actually set.

do_action( 'um_after_user_status_is_changed_hook' );
do_action( 'um_after_user_status_is_changed', $status );

Do not pass any user information so it is not possible to hook a user when their status is changed.

**Describe the solution you'd like**

Update do_action( 'um_after_user_status_is_changed_hook' ); to include the User ID 

e.g.
do_action( 'um_after_user_status_is_changed_hook', um_user( 'ID' ) );

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by champsupertramp** [comment]
Hi @MCKLtech  - `User ID` has been added to the action hooks. Please see: https://github.com/ultimatemember/ultimatemember/commit/5d997645233745f068e83ad463486f8f4a200b95

Regards,
