### ISSUE TITLE
Member List Random Sorting

### ISSUE THREAD

**Issue by hirenshah** [ultimatemember/ultimatemember#606]
I have the latest version of UM and have set the members listing to be sorted randomly.

I only have 45 users at the moment and so they are spread over 3 pages (when accessed via a mobile phone). 

Due to the random sorting, switching pages results in the users being reordered. I spent a minute or so switching pages and wasn't able to find a few users because each time they were on a different page.

**Comment by nikitasinelnikov** [comment]
This issue is already fixed here https://github.com/ultimatemember/ultimatemember/releases/tag/2.1.2-rc.1

The official 2.1.2 version will be released in a few days. You could check RC version that the fix is there.
