### ISSUE TITLE
"Enable reveal section transition by default" not working properly or makes no sense

### ISSUE THREAD

**Issue by FlyThePlanet** [ultimatemember/ultimatemember#608]
**Describe the bug**
In the Member Directory form > Profile Card settings, there's a problem with the "Enable reveal section transition by default" field.

If an admin enable the "Show extra user information below tagline?" and set some fields in "Choose field(s) to display in reveal section", it means, by default or not, this admin wants those fields to be visible on the Profile Card.

The "Enable reveal section transition by default" field should then allow to decide if we want those extra information to be displayed by default or not. But it's not the case:
- if we enable this setting, the extra user information are hidden by default, but we are be able to reveal them user by user
- but if we disable the setting, the extra user information are also not displayed by default and this time we have no option to reveal them, which contradicts the previous setting asking to "Show extra user information below tagline?"! It has the effect of disabling this "Show extra user information below tagline?" setting.

**Expected behavior**
"Enable reveal section transition by default" should be renamed "Enable display extra information by default" and...
- if enabled, reveal the extra information by default and hide the button to show/hide them
- if disabled, hide the extra information by default and show the button to show/hide them (which is the current behaviour when the option is enabled)

**To Reproduce**
1. Go to WP admin > Ultimate Member > Member Directories > Members record > Edit
2. Enable "Show extra user information below tagline?"
3. Add some few fields in "Choose field(s) to display in reveal section"
4. Disable "Enable reveal section transition by default"
5. Save/Update the Member Directory
6. Go to the Member Directory page
Even though the admin set to show some extra information below the tagline, you'll have no option to display them, like if those settings have been disabled by "Enable reveal section transition by default"
7. Edit the Member Directory again
8. Enable "Enable reveal section transition by default"
9. Save/Update the Member Directory
10. Go to the Member Directory page
This time you'll see that the extra information are not revealed by default.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [x] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
WP 5.3
PHP 7.2
UM 2.1.1 
</details>

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

Could you check how it works with the latest version in master branch? There is 2.1.2-rc.1 version.

Thanks!

**Comment by FlyThePlanet** [comment]
Yes, but where can I grab the version, it's not here...
https://github.com/ultimatemember/ultimatemember/releases

**Comment by nikitasinelnikov** [comment]
https://github.com/ultimatemember/ultimatemember/releases/tag/2.1.2-rc.1

**Comment by FlyThePlanet** [comment]
I found no difference. No fix in the 2.1.2 RC1.

**Comment by FlyThePlanet** [comment]
Still not difference for this issue, even with the last version of the 2.1.2 RC1.
Still can't get what you display on this dev site...
https://ultimate.g-photo.com.ua/members/

Also to answer your question on the other ticket, no I' don't have any custom template on my test site. Like I said it's really only WP + UM, nothing else and no customization.

**Comment by nikitasinelnikov** [comment]
The labels were changed in wp-admin member directory settings:

https://www.screencast.com/t/WMFHpWCr0

**Comment by FlyThePlanet** [comment]
Ok, so if I understand well...
- "Show extra user information below tagline?" should display the extra information as soon as ticked
- and "Hide extra user information to reveal section" should hide them inside a section that we can open + display the arrow to open the section.

Correct?

Then in this case:
- "Show extra user information below tagline?" ticked + "Hide extra user information to reveal section" unticked is not working. The extra information are simply not displayed.
- "Show extra user information below tagline?" ticked + "Hide extra user information to reveal section" ticked is working fine. Only the arrow is displayed and when we click on it it does reveal the extra information.

**Comment by nikitasinelnikov** [comment]
Hi @FlyThePlanet 

Yes, you are right and there is screenshot how it works for me with the latest version in "master" branch here

https://www.screencast.com/t/GnQk63E5

Thanks!

**Comment by FlyThePlanet** [comment]
Ok. Perfect.
Then I would love to have this issue fixed. I would like those extra information to be displayed by default.
> "Show extra user information below tagline?" ticked + "Hide extra user information to reveal section" unticked is not working. The extra information are simply not displayed.

**Comment by FlyThePlanet** [comment]
Ooops little precisions:
- it does work in grid mode. But it doesn't in list mode! And that's the mode I'm looking for.
- also, the arrow is hidden, it's only the fields that are not displayed.

**Comment by nikitasinelnikov** [comment]
There is the latest commit with the fix for the list view.
Thanks for your feedback!

**Comment by FlyThePlanet** [comment]
Confirmed, fixed!
Great. Thanks very much for your efforts 👍
