### ISSUE TITLE
Fatal error: Call to a member function get_roles() on a non-object

### ISSUE THREAD

**Issue by JpakMedia** [ultimatemember/ultimatemember#61]
Hi @ultimatemember,

I just noticed this error when trying to use WP-CLI after activating the plugin:

```
"Fatal error: Call to  a member function get_roles() on a non-object in ... core/um-builtin.php on line 526"
```

I'm running WP 4.4 with Ultimate Member 1.3.35. Please let me know if there's any other information I can provide!

**Comment by ultimatemember** [comment]
This function is called only if the class was loaded, see code:

		if ( class_exists('UM_Query') ) {
			$um_roles = $ultimatemember->query->get_roles( false, array('admin') );
		} else {
			$um_roles = array();
		}

**Comment by ultimatemember** [comment]
@JpakMedia Please see updated master https://github.com/ultimatemember/ultimatemember/archive/master.zip It should fix the WP-CLI conflicts. Please give us feedback, thanks!
