### ISSUE TITLE
Three Column Registration Form conflict with uimob340

### ISSUE THREAD

**Issue by wpplumber** [ultimatemember/ultimatemember#612]
**Expected behavior**
The expected result is to to have a 3 cols as mentioned in the screenshot after I removed the class uimob340 and tested [the suggested solution](https://docs.ultimatemember.com/article/122-how-to-get-registration-login-form-to-show-in-2-3-columns) which didn't work.
![github um](https://user-images.githubusercontent.com/52907282/70224415-89cc2700-174d-11ea-9412-80c860287be6.png)

**Describe the bug**
The issue seems for me in adding the class uimob340 to the form.
![cssclassissue um](https://user-images.githubusercontent.com/52907282/70224732-137bf480-174e-11ea-8d87-cfb7f61932d4.png)

**WordPress Environment**
<details>
WP: 5.3
</details>

**Comment by ashubawork** [comment]
Checked WP 6.4.1 and UM 2.7.0 - the problem is not reproducible
