### ISSUE TITLE
[WP 4.9] Ultimate Member plugin stuck in 2.0.x version

### ISSUE THREAD

**Issue by Indigo744** [ultimatemember/ultimatemember#615]
**Describe the bug**
My Ultimate Member plugin version is stuck in 2.0.43 and Wordpress doesn't offer any update.

Even though the 2.0.43 version was released March 29, 2019 and quite some version are available after that.

**Expected behavior**
Being able to update to latest plugin version.

**Screenshots**
![image](https://user-images.githubusercontent.com/7137528/70389615-38789d80-19c2-11ea-9bb1-47f16f376710.png)

**Do you use UM extensions?**
None

**WordPress Environment**

<details>

```
--- Site Info ---

Site URL:					[REDACTED]
Home URL:					[REDACTED]
Multisite:					No

--- Hosting Provider ---

Host:						[REDACTED]

--- User Browser ---

Platform:                 Windows 
Browser Name:             Firefox  
Browser Version:          71.0 
User Agent String:        [REDACTED]
                          
---- Current User Details --

Role: administrator, bbp_keymaster, um_administrateur


--- WordPress Configurations ---

Version:						4.9.12
Language:					fr_FR
Permalink Structure:			/%postname%/
Active Theme:				Divi Theme
Page On Front:				Accueil (#2)
Page For Posts:				 (#0)
ABSPATH:					[REDACTED]
All Posts/Pages:				0
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Disabled
WP Table Prefix:          			Length: 10, Status: Acceptable
Memory Limit:   				640MB


--- UM Configurations ---

Version:						2.0.43
Upgraded From:            		None
Current URL Method:			SERVER_NAME
Cache User Profile:			No
Generate Slugs on Directories:	Yes
Rewrite Rules: 				No
Force UTF-8 Encoding: 		Yes
JS/CSS Compression: 			No
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No


--- UM Pages Configuration ---

User:						[REDACTED]/profil/
Account:						[REDACTED]/mon-compte/
Members:					[REDACTED]/espace-membres/liste-des-membres/
Register:						[REDACTED]/inscription/
Login:						[REDACTED]/connexion/
Logout:						[REDACTED]/deconnexion/
Password Reset:				[REDACTED]/reinitialiser-mot-de-passe/


--- UM Users Configuration ---

Default New User Role: 		0
Profile Permalink Base:		user_id
User Display Name:			full_name
Force Name to Uppercase:		Yes
Redirect author to profile: 		Yes
Enable Members Directory:	Yes
Use Gravatars: 				No
Require a strong password: 	Off


--- UM Access Configuration ---

Panic Key: 								[REDACTED]
Global Site Access:						Site accessible to Logged In Users
Custom Redirect URL:						
Exclude the following URLs:				
Backend Login Screen for Guests:			Yes
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		Yes
Enable the Reset Password Limit:			No
Blacklist Words: 							10


--- UM Email Configurations ---

Mail appears from:  			[REDACTED]
Mail appears from address:  	[REDACTED]
Use HTML for E-mails:   		Yes
Account Welcome Email:  		No
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	No
Account Deleted Email:  		No
Password Reset Email:   		Yes
Password Changed Email: 		Yes


--- UM Total Users ---

                All Users(43)
administrator(1)
member(38)
bbp_keymaster(1)
um_administrateur(1)
none(0)


--- UM Roles ---

                Administrator (administrator)
Membre (member)
Keymaster (bbp_keymaster)
Moderator (bbp_moderator)
Participant (bbp_participant)
Spectator (bbp_spectator)
Blocked (bbp_blocked)
Administration BackWPup (backwpup_admin)
Vérification des opérations BackWPup (backwpup_check)
Aide sur les opérations BackWPup (backwpup_helper)
Administrateur (um_administrateur)


--- UM Custom Templates ---

                File: [REDACTED]/ultimate-member/templates/members-grid-old.php
File: [REDACTED]/ultimate-member/templates/members-grid.php


--- UM Email HTML Templates ---

                N/A


--- Web Server Configurations ---

PHP Version:              			7.1.33
MySQL Version:            			5.7.26
Web Server Info:          			Apache


--- PHP Configurations ---

PHP Memory Limit:         			640M
PHP Upload Max Size:      			300M
PHP Post Max Size:        			300M
PHP Upload Max Filesize:  			300M
PHP Time Limit:           			120
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			No


--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			N/A
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function exist on your web server.
Exif:				          PHP Exif library is installed on your web server.


--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			/home/clients/ef4f22c1fd864ad322af8c3169dede6f/tmp
Use Cookies:              			On
Use Only Cookies:         			On


--- WordPress Active Plugins ---

                Add Shortcodes Actions And Filters: 2.0.9
Admin Menu Editor Pro: 2.7
BackWPup: 3.7.0
bbPress: 2.5.14
Better Notifications for WP: 1.7.5
BNFW - Conditional Notifications Add-on: 1.0.8
Download Attachments: 1.2.23
Enhanced Media Library: 2.7.2
Events Manager: 5.9.7.1
GD bbPress Attachments: 3.2
Heartbeat Control by WP Rocket: 2.0
Query Monitor: 3.5.2
Server Status: 1.3.2
Simple History: 2.28.1
Ultimate Member: 2.0.43
User Role Editor: 4.52.1
User Switching: 1.5.3
WP Crontrol: 1.7.1
wpDiscuz: 5.3.5
WP FullCalendar: 1.2
WP Hide & Security Enhancer: 1.5.8.2
WP Mail Logging: 1.8.5

### End Install Info ###
```

</details>

As a side note, I think the Install info you ask to copy/past here contains way too much sensitive information for a **public post**.

Thanks.

**Comment by nikitasinelnikov** [comment]
Hi @Indigo744 

1) Please make sure that updates are enabled in your Wordpress install. More info about disabling: https://www.wpbeginner.com/wp-tutorials/how-to-disable-automatic-updates-in-wordpress/

2) Other issues can be connected with other active plugins before Ultimate Member in the plugins list. Please try to temporarily deactivate them and re-activate Ultimate Member plugin then. Maybe some of the plugins above clear update notice for Ultimate Member.

3) You could update the Ultimate Member plugin manually via FTP every time.

Let me know,
Thanks!

**Comment by Indigo744** [comment]
Thanks for your reply.

UM is the only plugin which doesn't offer any update. I was able to update a dozen of plugins, before manually checking UM.

Maybe I'll try the manual update through FTP and hope it will fix the issue.

I'll keep you posted.

**Comment by Indigo744** [comment]
@nikitasinelnikov alright so I think I know what is the issue.

**My WordPress install is still on 4.9**. I though you would saw it, since it is in the env details I pasted.

It seems that starting with Ultimate Member 2.1.0 you drop the compatibility with 4.9.

This is something that is [NOT mentioned anywhere in the changelog regarding 2.1.0](https://github.com/ultimatemember/ultimatemember/blob/master/readme.txt#L201).

And the [WordPress version bump was made very discreetly in a commit without saying anything](https://github.com/ultimatemember/ultimatemember/commit/245ddd4270cf527b1f16801fac511c4d7c95cb0c#diff-eb6b6c90251ab33cee784713c451e6d8).

I know I shouldn't feel entitled from anything from you guys since you provide a free plugin that works quite well. And I thank you for that.

But still, I must say that this is NOT a good way to manage a project by updating a major dependencies in a minor revision (2.1). **This is a breaking change**, it should be documented as such and done in a major release (3.0).

Also, you know that WordPress 4.9 is not EOL and still supported by the WordPress community?

Anyway, I now understand why WP did not offers any update. I still don't understand why it couldn't, at least, propose to update to the latest support version for 4.9 which is UM 2.0.56. Another limitation of WP I guess.

So in the end, I updated manually the UM plugin to the latest version 2.0.56 supporting WP 4.9 in order to have the most recent security updates and fix.

**Comment by nikitasinelnikov** [comment]
Hi @Indigo744 

Thanks for letting me know, could I close this issue?

WP5.0 was released ~1year ago. Ultimate Member 2.1.x version is backward compatible with 2.0.x version. There were added a few new features, changed Member Directories template and there weren't the changes like between 1.3.x and 2.0.x versions at Apr 2018, when full plugin + extensions API was changed.

Btw. minimum WP version is displayed at the plugin page on wp.org https://wordpress.org/plugins/ultimate-member/

I hope you will update your WP installation to the newest version for getting the latest features and security fixes.

Regards

**Comment by Indigo744** [comment]
Well, maybe the code itself didn't changed that much, but the simple fact that your main dependency took a major update is enough to warrant a major bump.

**Versioning is not only about your code.** I wish more dev would understand this.

Anyway. Thanks.
