### ISSUE TITLE
German Translation errors

### ISSUE THREAD

**Issue by JagX308** [ultimatemember/ultimatemember#616]
These texts are grammatically incorrect and embarrassing on my site.
Please replace all occurrences of "Gebe" or "gebe" with "Gib" or "gib".
From: ultimate-member-de_DE.po

#: core/um-actions-login.php:18
msgid "Please enter your username or email"
msgstr "Gebe deinen Benutzernamen und deine E-Mail-Adresse ein"

#: core/um-actions-login.php:22
msgid "Please enter your username"
msgstr "Bitte gebe deinen Benutzernamen ein"

#: core/um-actions-login.php:26
msgid "Please enter your email"
msgstr "Bitte gebe deine E-Mail-Adresse ein"

#: core/um-builtin.php:978
msgid "Enter your username or email"
msgstr "Gebe deinen Benutzernamen und deine E-Mail-Adresse ein"

**Comment by nikitasinelnikov** [comment]
Hi @JagX308 

You could make the translations request here:
https://translate.wordpress.org/projects/wp-plugins/ultimate-member/dev/de/default/

Regards
