### ISSUE TITLE
ForumWP free extension bug!

### ISSUE THREAD

**Issue by ahmed9694** [ultimatemember/ultimatemember#621]
when i install the free extension and activate it wordpress says that the plugin has been activated but in the top i see an error like that : "Sorry. You must activate the ForumWP plugin to use the Ultimate Member - ForumWP." i have seen this bug on wordpress forum over a year and it has not been fixed till now. pls do you have any solution

**Comment by champsupertramp** [comment]
Hi @ahmed9694 

You must install the ForumWP plugin http://forumwpplugin.com

UM - ForumWP is an extension to integrate UM & ForumWP plugin.

Regards,

**Comment by ahmed9694** [comment]
bruhhh i am not a retard i already have it
