### ISSUE TITLE
Request Data Emails

### ISSUE THREAD

**Issue by hirenshah** [ultimatemember/ultimatemember#625]
@nikitasinelnikov 

Is there a template for the email that gets sent to the user when requesting a copy of their data?  I just tried to test this and the email failed due to the fact that it had no headers or body.

Also, I now cannot do anything with that feature because there is an incomplete request.  I would expect there to be a list of suck requests in the UI and for Admins to be able to manage scenarios like this.

Can you please advise?

**Comment by hirenshah** [comment]
Ahh, it is available under the WordPress Export Personal Data page.  I can cancel pending requests from there, so that part of the issue is sorted... but still don't know why the emails failed due to being completely blank.

**Comment by hirenshah** [comment]
Anyone?

**Comment by nikitasinelnikov** [comment]
Hi @hirenshah 

Sorry for the delay, there was a lot of staff regarding the latest release.

Ultimate Member uses WordPress Export Personal Data feature and WP native email notifications. Please make the conflict test and check 3rd party plugins maybe some of them filter these email notifications.

Let me know,
Regards

**Comment by hirenshah** [comment]
@nikitasinelnikov No worries, I can see things have been busy. I had figured out it used WP's built in functionality, and also assumed that something else may be blocking it.

I'm not even going to try disabling everything else because I have no doubt that it will work. Are you aware of anything else (ie debugging entries) I could add to try and actually narrow down what is actually happening when this particular email gets triggered? 

One thing you may need to look at is in the scenario where the process fails (in my case it was due to the fact that WP wouldn't send an empty email) UM doesn't actually cater for the failure scenario. From the Accounts page, I couldn't do anything because it just said that there was an incomplete request. I had to go and delete the failed entry from the Admin Export Data screen first.
