### ISSUE TITLE
Undefined property bug

### ISSUE THREAD

**Issue by Johnny99211** [ultimatemember/ultimatemember#626]
Please fix this error. It occurs since the last 3 releases. I need to fix it manually every update.

`Notice: Undefined property: um\core\Fields::$set_id in /wp-content/plugins/ultimate-member/includes/core/class-fields.php on line 4461`

**Comment by nikitasinelnikov** [comment]
Hi @Johnny99211 

Have you still have the issue in 2.1.4 version? 
https://github.com/ultimatemember/ultimatemember/releases/tag/2.1.4

Please let me know,
Thanks!

**Comment by Johnny99211** [comment]
No not longer.
