### ISSUE TITLE
Post type list as a drop-down options

### ISSUE THREAD

**Issue by codepaints** [ultimatemember/ultimatemember#633]
Is there any way to add all CPT post titles as a drop-down option in the registration form or elsewhere?

**Comment by champsupertramp** [comment]
Hi @codepaints 

You can use the callback function feature in UM select field settings to populate with your custom data. 

Please see: https://docs.ultimatemember.com/article/1539-choices-callback-feature-in-um-2-1

Regards,

**Comment by codepaints** [comment]
Great thanks a lot. Issue resolved.
