### ISSUE TITLE
Upgrade Crashed

### ISSUE THREAD

**Issue by hirenshah** [ultimatemember/ultimatemember#634]
I had v2.1.4 installed and after adding the recent merges from here, I saw an Upgrade option,. When running it:

`Upgrade Process Started...
Get Upgrades Packages...
Upgrades Packages are ready, start unpacking...

=================================================================
Prepare package "2.1.5" version...

Package "2.1.5" is ready. Start the execution...
Upgrade form fields...
Wrong AJAX response...
Your upgrade was crashed, please contact with support`

The upgrade option seems to be gone now.  There was nothing in the WordPress logs.  Everything seems to still be working.

I have a feeling it had something to do with the mycred updates, and it failed because I don't have/use MyCred.

**Comment by nikitasinelnikov** [comment]
Hi @hirenshah 

Please get the latest upgrades from wp.org. The master branch may not be stable. Please use RC or stable tagged versions here or officially released versions at wp.org.

Thanks!
