### ISSUE TITLE
Save setting issue 404 redirect

### ISSUE THREAD

**Issue by imsilenzi** [ultimatemember/ultimatemember#640]
Hello,
when i try to modify the email setting I'm redirect to this page
site.com/wp-admin/admin.php?page=um_options&tab=email&email=checkmail_email
with the settings not updated.
I tried to disable all plugins and change theme with default theme but doesn't work.
Thank you for help

**Comment by champsupertramp** [comment]
Hi @imsilenzi 

Do you have mod_security enabled in your server? If so, could you please try disabling it temporarily and see if you're still encountering the issue.

Regards,

**Comment by imsilenzi** [comment]
Yes, I contacted the hosting provider I asked to unlock the firewall. Now the problem is solved.
Thank u!
