### ISSUE TITLE
User Tags not returning any results

### ISSUE THREAD

**Issue by anasaboulkassim** [ultimatemember/ultimatemember#649]
Hi all
Not sure if this related to an update, ive done all of them, 
User Tags working as expected in the profile, but when we click on a Tag the search is not returning any results is this a know issue ?
User Tag Version 2.1.4

**Comment by nikitasinelnikov** [comment]
Hi @anasaboulkassim 

Sorry for the delay. You could contact here https://ultimatemember.com/support/ticket/ if you still have the issue.

Best Regards
