### ISSUE TITLE
how to use tabs for my custom profile with lots of fields

### ISSUE THREAD

**Issue by ghmercado** [ultimatemember/ultimatemember#650]
hi, i already know how to add fields and make my own template i just want to know how to use tabs to divide fields in profile this way. Any help appreciated thanks so much

![aa](https://user-images.githubusercontent.com/1407853/82627000-d16f3e00-9c1b-11ea-96ba-f30a850e4bbc.jpg)

**Comment by nikitasinelnikov** [comment]
Hi @ghmercado 

You could use Profile Tabs extension
https://ultimatemember.com/extensions/profile-tabs/

Thanks!
