### ISSUE TITLE
WordPress Menu is not editable anymore since the last update

### ISSUE THREAD

**Issue by maerni** [ultimatemember/ultimatemember#654]
Hi

Since the last update of Ultimate Member (2.1.6) we cannot edit our menus anymore.

We have the following error in the error log:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function um\\admin\\core\\Admin_Navmenu::wp_nav_menu_item_custom_fields(), 4 passed in /var/www/vhosts/fcallmendingen.ch/httpdocs/wp-includes/class-wp-hook.php on line 287 and exactly 5 expected in /var/www/vhosts/fcallmendingen.ch/httpdocs/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-navmenu.php:59

We think, that this here is the problem:

Tweak: nav-menu custom fields using 'wp_nav_menu_item_custom_fields' hook

Any idea, how to fix this?

Thanks very much.

Best regards
Mike

**Comment by bruce133** [comment]
I can confirm that there is a problem with editing menus, though I'm unsure of whether we're experiencing the same issue. In my case the Ultimate Member Menu Settings have disappeared, and when I save any changes afterwards the previously set UM menu settings are lost.

Before updating:

![image](https://user-images.githubusercontent.com/2420663/85014497-a7e7fa80-b166-11ea-8a05-37d9125d5dec.png)

After updating:

![image](https://user-images.githubusercontent.com/2420663/85014552-c51cc900-b166-11ea-9c56-f48f4ec59233.png)

**Comment by nikitasinelnikov** [comment]
Hi @maerni @bruce133 

What theme do you use on your website? Could you share the theme's files?

In the @maerni case, there is the 'wp_nav_menu_item_custom_fields' hook with 4 arguments in theme, but WP native hook contains 5 arguments.

In the @bruce133 case, it seems that your theme's mega menu feature doesn't contain 'wp_nav_menu_item_custom_fields' hook. 

Let me know,
Thanks!

**Comment by maerni** [comment]
Hi
@nikitasinelnikov we use the multi purpose them Enfold (https://kriesi.at/).
Which theme files do you need?
Best regards
Mike

**Comment by nikitasinelnikov** [comment]
Hi @maerni 

You could add the 5th argument in your theme's file. I'll fix the issue:
Details and file path here:
https://www.screencast.com/t/hzvX7EOq0

Best Regards

**Comment by maerni** [comment]
Hi @nikitasinelnikov 
Thanks very much. It works!
I will contact the Enfold developers to fix that.
Best regards
Mike

**Comment by bruce133** [comment]
> In the @bruce133 case, it seems that your theme's mega menu feature doesn't contain 'wp_nav_menu_item_custom_fields' hook.

Seems you were right. Updating the theme appears to have fixed it. Sorry about that, and thanks!
