### ISSUE TITLE
Description in SEO meta tags not working

### ISSUE THREAD

**Issue by gitblair** [ultimatemember/ultimatemember#655]
The um-actions-profile.php gathers the metas at line 660 and places the metas in the page source header. Other metas are working fine but any requesting the $description variable are empty.

Examples: 
<meta name="description" content="" />
<meta property="og:description" content="" />
<meta name="twitter:description" content="" />
and also in schema where it calls $description

Can be seen not working by viewing source on your browser.

**Comment by nikitasinelnikov** [comment]
Hi @gitblair 

Could you check the same issue in the latest Ultimate Member 2.1.7 version? 

Let me know,
Thanks!

**Comment by nikitasinelnikov** [comment]
Hi @gitblair 

Please feel free to re-open this thread if any other questions come up and we’d be happy to help.

Best Regards
