### ISSUE TITLE
Incorrect param for wp_authenticate_user filter

### ISSUE THREAD

**Issue by AndrewVasylchuk** [ultimatemember/ultimatemember#656]
Hello!

Looks like there is an issue on this line.

https://github.com/ultimatemember/ultimatemember/blob/af4a53a9fb8ee8f82651117d4e32e228af484c27/includes/core/um-actions-login.php#L71

The first param of the filter **wp_authenticate_user** can be WP_Error or WP_User, but there is a string ($user_name) and it makes some conflicts with other plugins.

Should be $user instead of $user_name

Can you check out and fix it please?

**Comment by nikitasinelnikov** [comment]
Hi @AndrewVasylchuk 

The issue has been already fixed

Thanks!
