### ISSUE TITLE
select2 as um.min.js

### ISSUE THREAD

**Issue by archergod** [ultimatemember/ultimatemember#66]
I found that this plugin use Select2 copied as um.min.js, is there any particular reason to do so? as when I include latest select2 in my project it get overridden by UM's version which is older version and I cannot change it without disabling it from UM's code only. 

Also, it do not mention original license of select2, isn't it that against the copyright ?

**Comment by champsupertramp** [comment]
@archergod It has the license: 
https://github.com/ultimatemember/ultimatemember/blob/master/assets/js/um-select.js

I will discuss this issue as a team.

**Comment by archergod** [comment]
I also observe that jQuery is included in the same file, can we instead use the one provided with Wordpress itself. I try to separate it out but see there are lot of plugins included, and it might be good to separate so other plugin won't break.

**Comment by ultimatemember** [comment]
We already use the WP enqueued jquery script. 

wp_register_script('um_minified', um_url . 'assets/js/um.min.js', array('jquery'), ultimatemember_version, true );
wp_enqueue_script('um_minified');

Please clarify if you see that we load jquery from our plugin or there's an error by replying to this issue again.

**Comment by archergod** [comment]
@ultimatemember the issue is not limited to jquery but that Select2 is duplicated in um.min.js as well as um-select.js, And when I want to use select2 in my code your older verison from um.min was in conflict.

Infact I completely Remove um_minified using wp_dequeue to get my plugin working and fortunately your plugin keeps working fine even after that. (to my project scope use of ultimate member), so seems like um.min.js is rather duplicated and using native lib as is it preferred.
