### ISSUE TITLE
Getting some TinyMCE bug when trying to edit my forms

### ISSUE THREAD

**Issue by skillmatic-co** [ultimatemember/ultimatemember#660]
Here is the error when I go to try to edit my registry form. I'm getting a 500 error and I cannot edit my forms:

> PHP Fatal error: Uncaught Error: Call to undefined method _WP_Editors::force_uncompressed_tinymce() in /nas/content/live/example/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-enqueue.php:680\nStack trace:\n#0 /nas/content/live/example/wp-includes/class-wp-hook.php(286): um\\admin\\core\\Admin_Enqueue->admin_footer_scripts('')\n#1 /nas/content/live/example/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)\n#2 /nas/content/live/example/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#3 /nas/content/live/example/wp-admin/admin-footer.php(72): do_action('admin_footer', '')\n#4 /nas/content/live/example/wp-admin/post.php(299): include('/nas/content/li...')\n#5 {main}\n thrown in /nas/content/live/example/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-enqueue.php on line 680, referer: https://example.wpengine.com/wp-admin/edit.php?post_type=um_form

**Comment by ashubawork** [comment]
This issue is not reproducible on WP 6.4.1 and UM 2.7.0
