### ISSUE TITLE
UltimateMember critical error

### ISSUE THREAD

**Issue by LordFenris** [ultimatemember/ultimatemember#662]
There was a fatal error in the menu cutomization option with the plug active.
Interestingly, the error does not appear when the Menu Icons plugin has been withdrawn to version 0.12.1.
The error also does not occur if I update the Menu Icon plugin to the latest version but disable the UltimateMembers plugin
I attach menu error screenshot 

Here is a full  Wordpress 
![Zrzut ekranu (166)](https://user-images.githubusercontent.com/30296954/88081926-5fff2d80-cb81-11ea-9db1-b0e855c50907.png)
error report
"WordPress has detected an error in its plugin: Ultimate Member.

Please visit the website (https://mmogspot.com/) and check that there are no visible problems. Then visit the page where the error was detected (https://mmogspot.com/wp-admin/nav-menus.php) and check for any apparent problems.

You may need the following information to solve the problem:
WordPress version 5.4.2
Current Theme: Godlike (version 2.9.1)
Current plugin: Ultimate Member (version 2.1.6)
PHP version: 7.2.32

line 59 , files /wp-content/plugins/ultimate-member/includes/admin/core/class-admin-navmenu.php. K
Uncaught ArgumentCountError: Too few arguments to function um\admin\core\Admin_Navmenu::wp_nav_menu_item_custom_fields(), 4 passed in /wp-includes/class-wp-hook.php on line 287 and exactly 5 expected in /wp-content/plugins/ultimate-member/includes/admin/core/class-admin-navmenu.php:59
Stack trace:
#0 /wp-includes/class-wp-hook.php(287): um\admin\core\Admin_Navmenu->wp_nav_menu_item_custom_fields('952', Object(WP_Post), 0, Object(stdClass))
#1 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wp-content/themes/godlike/admin/menu/backend-walker.php(306): do_action('wp_nav_menu_ite...', '952', Object(WP_Post), 0, Object(stdClass))
#4 /wp-includes/class-wp-walker.php(144): nK_Walker_Nav_Menu_Edit->start_el('', Object(WP_Post), 0, Object(stdClass))

**Comment by nikitasinelnikov** [comment]
Hi @LordFenris 

The main reason for the issue is there:

wp-content/themes/godlike/admin/menu/backend-walker.php line 306

Please edit this string to:

do_action( 'wp_nav_menu_item_custom_fields', $item_id, $item, $depth, $args, $id );

And report your theme developers about the issue with WP native hook
Thanks!
