### ISSUE TITLE
Message button

### ISSUE THREAD

**Issue by Soul27** [ultimatemember/ultimatemember#663]
Hi

Thanks for the awesome plugin.

I would like to add the message button in a custom post type, but I am not sure how to go about about it.

Can you please assist me with the hook that can work. The link to the custom post type is https://agrifreetrade.com/listings/avocado-16kg-bag/

I would really appreciate it.

It's a classifieds site and I want users to be able to text the person who listed.

**Comment by nikitasinelnikov** [comment]
Hi @Soul27 

Sorry for the delay,
You could use [ultimatemember_message_button user_id="{$user_id}"] where $user_id will be a CPT author, I think

Thanks!
