### ISSUE TITLE
Can't Download file on profile user

### ISSUE THREAD

**Issue by ullymuzakir** [ultimatemember/ultimatemember#669]
I can't open the user's upload file on their profile after updating the ultimate member. help me please

**Comment by nikitasinelnikov** [comment]
Hi @ullymuzakir 

Could you clarify some details, share the access to your website? I need to make some investigations for getting this fixed as 
soon as possible.

Let me know,
Thanks!

**Comment by ullymuzakir** [comment]
https://spmbbbg.com/login/

User = Dede
Pass = 123456789

You can try to download the file extension jpg or png.  I tried unable to open the file

**Comment by nikitasinelnikov** [comment]
Hi @ullymuzakir 

Please provide the install-info https://www.screencast.com/t/lB6qBgbN
It looks like a conflict between UM and some plugin, which customizes avatars.

Thanks!

**Comment by ullymuzakir** [comment]
### Begin Install Info ###

## Please include this information when posting support requests ##


--- Site Info ---

Site URL:					https://spmbbbg.com
Home URL:					https://spmbbbg.com
Multisite:					No

--- Hosting Provider ---

Host:						DBH: localhost, SRV: spmbbbg.com

--- User Browser ---

Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          85.0.4183.121 
User Agent String:        Mozilla/5.0 (Windows NT 10.0; Wi 
			  n64; x64) AppleWebKit/537.36 (KH
                          TML, like Gecko) Chrome/85.0.418
                          3.121 Safari/537.36
                          
---- Current User Details --

Role: administrator


--- WordPress Configurations ---

Version:						5.5.1
Language:					id_ID
Permalink Structure:			/%postname%/
Active Theme:				Divi 4.6.0
Page On Front:				Home (#17)
Page For Posts:				NIM Mahasiswa TA. 2020 (#0)
ABSPATH:					/home/spmbbbgc/public_html/
All Posts/Pages:				3
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Enabled
WP Table Prefix:          			Length: 5, Status: Acceptable
Memory Limit:   				40MB


--- UM Configurations ---

Version:						2.1.10
Upgraded From:            		2.1.5
Current URL Method:			
Cache User Profile:			Yes
Generate Slugs on Directories:	Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			No
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No


--- UM Pages Configuration ---

User:						https://spmbbbg.com/user/
Account:						https://spmbbbg.com/account/
Members:					https://spmbbbg.com/members/
Register:						https://spmbbbg.com/register/
Login:						https://spmbbbg.com/login/
Logout:						https://spmbbbg.com/logout/
Password Reset:				https://spmbbbg.com/password-reset/


--- UM Users Configuration ---

Default New User Role: 		subscriber
Profile Permalink Base:		user_login
User Display Name:			full_name
Force Name to Uppercase:		No
Redirect author to profile: 		Yes
Enable Members Directory:	Yes
Use Gravatars: 				Yes
Gravatar builtin image:		default
    UM Avatar as blank Gravatar: 	Yes
Require a strong password: 	Off


--- UM Access Configuration ---

Panic Key: 								
Global Site Access:						Site accessible to Everyone
Backend Login Screen for Guests:			No
Redirect to alternative login page:			
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		No
Enable the Reset Password Limit:			Yes
Reset Password Limit: 3Disable Reset Password Limit for Admins: No
Blacklist Words: 							5


--- UM Email Configurations ---

Mail appears from:  			SPMB STKIP BBG
Mail appears from address:  	panitia@spmbbbg.com
Use HTML for E-mails:   		Yes
Account Welcome Email:  		Yes
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	Yes
Account Deleted Email:  		Yes
Password Reset Email:   		Yes
Password Changed Email: 		Yes


--- UM Total Users ---

                All Users(1331)
administrator(5)
editor(4)
subscriber(1239)
um_angkatan-2020(107)
none(0)


--- UM Roles ---

                Administrator (administrator)
Editor (editor)
Author (author)
Contributor (contributor)
Subscriber (subscriber)
Angkatan 2020 (um_angkatan-2020)


--- UM Custom Templates ---

                N/A


--- UM Email HTML Templates ---

                N/A


--- Web Server Configurations ---

PHP Version:              			7.4.10
MySQL Version:            			5.5.5
Web Server Info:          			LiteSpeed


--- PHP Configurations ---

PHP Memory Limit:         			512M
PHP Upload Max Size:      			20M
PHP Post Max Size:        			20M
PHP Upload Max Filesize:  			20M
PHP Time Limit:           			300
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			Yes


--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			On (1)
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function doesn't exist on your web server.
Exif:				          PHP Exif library is installed on your web server.


--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			/opt/alt/php74/var/lib/php/session
Use Cookies:              			On
Use Only Cookies:         			On


--- WordPress Active Plugins ---

                Download Attachments: 1.2.24
Easy WP SMTP: 1.4.1
Jetpack by WordPress.com: 8.9.1
Join.chat: 4.0.10
PDF Poster: 1.6
Quiz And Survey Master: 7.1.3
Really Simple SSL: 3.3.5
Ultimate Member: 2.1.10
Ultimate Member - Terms & Conditions: 2.1.2
User Export (with their Meta Data): 0.6.7
User Role Editor: 4.56.1

### End Install Info ###

**Comment by ullymuzakir** [comment]
[03-Nov-2020 01:36:41 UTC] PHP Warning:  readfile() has been disabled for security reasons in /home/spmbbbgc/public_html/wp-content/plugins/ultimate-member/includes/core/class-files.php on line 245

this is what appears in the error log. How should I fix it? please

**Comment by champsupertramp** [comment]
Hi @ullymuzakir 
Sorry for the late  response. Could you please tell us if you're still experiencing the issue? Are you in a shared hosting?

Regards,

**Comment by ashubawork** [comment]
Hi @ullymuzakir 

This thread has been inactive for a while.

Please feel free to re-open this thread if any other questions come up and we’d be happy to help. 🙂

Regards
