### ISSUE TITLE
set_roles()

### ISSUE THREAD

**Issue by bruce133** [ultimatemember/ultimatemember#674]
### The documentation:
(source: https://ultimatemember.com/php-docs/classes/um.core.Roles_Capabilities.html#method_set_roles)

![image](https://user-images.githubusercontent.com/2420663/94695090-cb117100-0335-11eb-9f3c-43b49b8093d1.png)

### The actual code:

![image](https://user-images.githubusercontent.com/2420663/94695384-22afdc80-0336-11eb-815f-96c1ce47ad4e.png)

https://github.com/ultimatemember/ultimatemember/blob/b45b4fc140da1d30daaf3b1702babb4fa5170dc9/includes/core/class-roles-capabilities.php#L356

### Me after wasting precious time on this function:

![image](https://media.tenor.com/images/bcdbca0c0cd562f72ac2bf713f73192a/tenor.gif)

Thank you.

**Comment by champsupertramp** [comment]
Hi @bruce133  That line has been removed from the latest version.

You can use this code to change the user's role:
`UM()->roles()->set_role( $user_id, $role_slug);`

Regards,

**Comment by bruce133** [comment]
> You can use this code to change the user's role:
> `UM()->roles()->set_role( $user_id, $role_slug);`

Yes, I'm aware of that, however I needed to add _multiple roles_ to users, which is why I attempted to use set_role**s**() in the first place. I ended up circumventing UM anyway.
