### ISSUE TITLE
E-Mails shouldn't be saved in theme

### ISSUE THREAD

**Issue by SimonMayerhofer** [ultimatemember/ultimatemember#677]
Currently when editing the mails they are saved in the theme's directory. This is the wrong place to save them, as it's easy to override them, depending on the workflow.
For us we override the theme directory all the time. Same goes for parent themes as well as for child themes. Also e.g. for projects which use a continuous integration workflow, themes will be overriden automatically.

**Describe the solution you'd like**
Saving the changed e-mails in another directory. e.g. `/wp-content/uploads/ultimatemember/templates/email/`.

Another solution would be to at least provide a filter to be able change the output directory.

**Comment by nikitasinelnikov** [comment]
The issue will be fixed in v3.0 
There is a branch with the ability to set the base templates directory

https://github.com/ultimatemember/ultimatemember/tree/development/3.0

**Comment by nikitasinelnikov** [comment]
See the gist for changing base templates' dir https://gist.github.com/nikitasinelnikov/be3a798e907bb62effec50df9f696806
