### ISSUE TITLE
edit_users capability doesnot automatically assing the edit_user capability

### ISSUE THREAD

**Issue by sanzeeb3** [ultimatemember/ultimatemember#681]
**Expected behavior**
With all the capabilities assigned, I expect the administrator roles to be the same as the core administrator roles.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The newly added administrator role with all capabilities including edit_users fails for edit_user capability check:

```
if ( ! current_user_can( 'edit_user' ) ) {
   throw new Exception( 'You donot have enough permission to perform this action' );
}
```

While, there is no official `edit_user` capability, but WordPress core administrator roles map `edit_users` to `edit_user` as well. 

So, while you get that error with Ultimate Members administrators, this is not the case with WordPress core administrator users.

**To Reproduce**
1. Add a new user role with all capabilities similar to WordPress administrator roles.
2. Sign in with that user role.
3, Check the capabilitiy:

```
if ( ! current_user_can( 'edit_user' ) ) {
   throw new Exception( 'You donot have enough permission to perform this action' );
}
```
4. Sign in with core administrator user role.
5. Check the capability:

```
if ( ! current_user_can( 'edit_user' ) ) {
   throw new Exception( 'You donot have enough permission to perform this action' );
}
```
**WordPress Environment**
Latest version.

**Comment by yuriinalivaiko** [comment]
The function [current_user_can](https://developer.wordpress.org/reference/functions/current_user_can/) has two parameters. The second parameter depends on the capability you check. This parameter should be an ID of the user you want to edit for the capability 'edit_user'. 
Just use the capability 'edit_users' if you don't need to check the ability to edit a certain user.
In multisite the user must have 'manage_network_users' caps. If editing a super admin, the user must be a super admin.
