### ISSUE TITLE
Invalid "strong password" validation in the Registration form

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#686]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
When we enter the correct password, but in Cyrillic, into the registration form on the site with strong password settings, all the conditions for a strong password are met, but registration is not successful

**To Reproduce**
1. Go to wp-admin > UM > Forms > Default Registration > Password > Edit
2. Click on checkbox in field « Force strong password? »
3. Go to Site> Registration> Password and Confirm Password
4. Enter password – «Тест1234» > Press the «Register» button
5. Registration not successful and the error message "Your password must contain at least one lowercase letter, one capital letter and one number"

**Expected behavior**
User registration passed, the user page was opened

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**Comment by nikitasinelnikov** [comment]
It works properly in 2.6.5
