### ISSUE TITLE
Add setting "Privacy" for the field type "Divider"

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#688]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
There is no setting "Privacy" in the field type "Divider". There is no way to show this field type for the certain user role only.

**To Reproduce**
1. Go to wp-admin > UM > Forms > Default Registration
2. Add the field type "Divider" into the form
3. Look at the field settings. There is no setting "Privacy"

**Expected behavior**
The field type "Divider" should contain the setting "Privacy" and the setting "Select member roles" related to "Privacy". Look at the field type "Content Block" for example.

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**Comment by ashubawork** [comment]
https://github.com/ultimatemember/ultimatemember/tree/feature/divider_privacy_field
