### ISSUE TITLE
Multi-select field on profile page not displaying a value containing apostrophe

### ISSUE THREAD

**Issue by mansurahamed** [ultimatemember/ultimatemember#689]
On the user's profile page, the user can select the values from the multi-select field . Upon pressing the Update Profile button, the value with the apostrophe symbol disappears but when you edit the profile, it is still there.

The value is also correctly shown on the member search result. It only disappears on the user profile page.

This issue was preset since version 2.1.7.

**Comment by ashubawork** [comment]
Fixed issue - https://github.com/ultimatemember/ultimatemember/tree/fix/multi_select_apostrophe_issue%23689
