### ISSUE TITLE
Сonditional logic with the field type "User tags" doesn't work correctly

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#690]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
Select user tags in the field with conditional logic settings doesn't work correctly when we choose more than one user tags

**To Reproduce**
1. Go to wp-admin > UM > Forms > Default Registration
2. Add 3 field > Text Box - "Value First", "Value Second", "Value Third" > Add
3. Add field > User Tags "New Variant" > Add
4. Field "Value First" > Edit > Manage conditional fields support > Add new rule - show - New Variant - contains - 7 (value) > Update
5. Field "Value Second" > Edit > Manage conditional fields support > Add new rule - show - New Variant - contains - 5 (value) > Update
6. Field "Value Third" > Edit > Manage conditional fields support > Add new rule - show - New Variant - contains - 4 (value) > Update
7. Go to site > Open Registr form with fields
8. Click on-field "New Variant" and select value "Blogging" from the dropdown list
9. Click on-field "New Variant" and select value "Painting" from the dropdown list
10. We see an error when, after selecting the second value, the associated field did not open.

**Expected behavior**
Select several user tags, the fields with the conditional logic setting should work correctly and be displayed

**Screenshots**
https://www.screencast.com/t/anEki73RLpi
https://www.screencast.com/t/J3txHlvFj
https://www.screencast.com/t/jPiJMywd

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [x] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**Comment by ashubawork** [comment]
Fix in the Git - https://github.com/ultimatemember/user-tags/tree/fix/register_cond_logic
