### ISSUE TITLE
Checkbox "Administrator" is not displayed in UM Content restriction section

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#692]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
There is no "Administrator" checkbox in the page restriction section. We cannot restrict the pages to only admins.

**To Reproduce**
1. Go to wp-admin > Pages > Template page > Edit
2. Scroll down to "UM Content Restriction" and click
3. Mark checkbox "Restrict access to this content?"
4. In the drop-down list select - "Logged in users"
5. The item "Select which roles can access this content" does not contain a checkbox "Administrator"

**Expected behavior**
Section "Restrict access to this content" should contain the ability to configure all installed roles.

**Screenshots**
https://www.screencast.com/t/0wOaIX8QrEcQ
https://www.screencast.com/t/UQExptuBB9d

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**Comment by ashubawork** [comment]
Pull request https://github.com/ultimatemember/ultimatemember/pull/708
