### ISSUE TITLE
Requiring wp-load.php

### ISSUE THREAD

**Issue by yaharga** [ultimatemember/ultimatemember#7]
Of the following errors that occur: <blockquote>ERROR: Internal Server Error.</blockquote>

Mine turned out to be because of the following: <blockquote>[28-Apr-2015 15:20:47 Asia/Bahrain] PHP Warning:  require_once(../../../../../../wp-load.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/localppl/web/app/plugins/ultimate-member/core/lib/upload/um-image-upload.php on line 3
[28-Apr-2015 15:20:47 Asia/Bahrain] PHP Fatal error:  require_once(): Failed opening required '../../../../../../wp-load.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.7/lib/php') in /Applications/MAMP/htdocs/localppl/web/app/plugins/ultimate-member/core/lib/upload/um-image-upload.php on line 3</blockquote>

The wp-load is included in both um-image-upload and um-file-upload, so I'm guessing both would cause the error.

At first, I thought of contributing and adding a pull request to change the directory to <code>site_url()</code>, but after reading further I came across this post that says <a href="http://ottopress.com/2010/dont-include-wp-load-please/">it's not good to include wp-load</a>. I am using <a href="https://roots.io/bedrock/">Roots Bedrock</a> and the directory is different in it, which is causing the error.

**Comment by ultimatemember** [comment]
This issue is going to be fixed in one of the next patches

**Comment by yaharga** [comment]
That was super fast. Thank you!

**Comment by yaharga** [comment]
<blockquote>[01-May-2015 15:16:27 Asia/Bahrain] PHP Warning:  require_once(/Applications/wp-load.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/localppl/web/app/plugins/ultimate-member/core/lib/upload/um-image-upload.php on line 10
[01-May-2015 15:16:27 Asia/Bahrain] PHP Fatal error:  require_once(): Failed opening required '/Applications/wp-load.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.7/lib/php') in /Applications/MAMP/htdocs/localppl/web/app/plugins/ultimate-member/core/lib/upload/um-image-upload.php on line 10</blockquote>

Two patches later and the same issue continues. My <strong>wp-load.php</strong> is included in  <code>/Applications/MAMP/htdocs/localppl/web/wp/wp-load.php</code>.

My local homepage is <code>http://localppl/</code> whole my site url is <code>http://localppl/wp/</code>. So, you see, it's quite difficult to determine where wp-load.php is with the ability to move it almost anywhere. I'm not claiming I know nor have the solution, unfortunately, but I am trying my best to find out how to avoid it. I'll keep updating with whatever I would be able to find regarding a better solution.

Possible temporary solution may include adding a filter for developers to use to locate <strong>wp-load.php</strong> since it's more likely that developers would be the WP users who move <strong>wp-load.php</strong> around and away from its default location. I'll reopen the issue until resolved permanently. One of the recommended permanent solutions which is to attempt to refrain from requiring <strong>wp-load.php</strong>.

**Comment by ultimatemember** [comment]
Thanks for the heads up. Patched with https://github.com/geminilabs/ultimatemember/commit/4cc08e1ae000645b1eaa1ec2b1d2fad92a06c501 but seems not working for specific installs still

**Comment by BrandonShutter** [comment]
I'm still having this issue:

`FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/srv/www/wp-load.php): failed to open stream: No such file or directory in /srv/www/domain.com/releases/20170105215028/web/app/plugins/ultimate-member/core/lib/upload/um-image-upload.php on line 10`

Managing WordPress via Composer inside of a /wp directory
