### ISSUE TITLE
Indexing of Profiles

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#703]
**Is your feature request related to a problem? Please describe.**
There's no settings for users to hide their profile from the Search Engine

**Describe the solution you'd like**
Add a preference settings on the user account for Indexing profiles.

**Describe alternatives you've considered**
There's still no alternative solution that I'm aware of.

**Additional context**
Topic Created:
https://wordpress.org/support/topic/indexing-of-user-profiles/

**Comment by nikitasinelnikov** [comment]
Hi @champsupertramp 

Please check this option. It was added a few versions ago. 

https://www.screencast.com/t/pJi8spDHb

Best Regards

**Comment by jordanharriger** [comment]
Hey @nikitasinelnikov 

Thanks for implementing this feature. It would be awesome if we're able to set a default value on the backend and to allow control of this on a per Role basis.

Thanks!

**Comment by baddon250** [comment]
My profiles are not showing this option. These were existing profiles before the update came into place. I've tried updating the user roles and setting option to no, so I can index user pages and still they say noindex. I've also tried editing the option in settings->general->users and still no luck. Any ideas?

**Comment by baddon250** [comment]
The goal is to make profile pages indexed by search engines. I already have my users made into a sitemap and I'm getting noindex errors from google webmaster.

**Comment by baddon250** [comment]
![Screenshot 2022-01-10 22 10 52](https://user-images.githubusercontent.com/97500628/148890561-b4004462-4bc6-44fc-b961-d38e34591ca7.png)

**Comment by baddon250** [comment]
![Screenshot 2022-01-10 22 21 00](https://user-images.githubusercontent.com/97500628/148891687-5cbe921e-55ba-41df-9e7f-dfd4ea108de4.png)
