### ISSUE TITLE
pre_get_document_title vs wp_title on corp/um-filters-profile

### ISSUE THREAD

**Issue by mikeprince3** [ultimatemember/ultimatemember#71]
I have 1.3.36 installed and was getting "User | mydomain.com" for the page title on the user profile page. I switched the filter from 'pre_get_document_title' to 'wp_title' and the correct page title started displaying. I am using WP 4.4.1

**Comment by mikeprince3** [comment]
btw, I am using X Theme by themeco. I don't know enough about WP to know if this is how the theme should be but here's what the page title looks like:

<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php wp_title( '' ); ?></title>
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

**Comment by ultimatemember** [comment]
Does it work as expected if you change the X theme to another theme?
