### ISSUE TITLE
Popup title on top of wpadminbar

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#713]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
When you go to the site and scroll the page - in the upper left corner, a pop-up title appears on top of wpadminbar.

**To Reproduce**
1. Go to site
2. Scroll down and up
3. See pop-up title in the upper left corner

**Expected behavior**
The page does not display elements that close the wpadminbar elements

**Screenshots**
https://www.screencast.com/t/hIIOsAH14n

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**Comment by nikitasinelnikov** [comment]
There was an issue with active ForumWP or/and JobBoardWP
