### ISSUE TITLE
The slider filter in the members directory may not work

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#738]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The slider filter in the members directory may not work if the field contains integers with different numbers of digits.

**To Reproduce**
1. Go to the profile form settings and add a new field-number;
2. Go to users profiles and set these values in the new field-number: 4, 9, 11, 33;
3. Go to the members directory settings and add a filter for the new field-number;
4. Go to the members directory page and investigate the filter. The range starts from 11 and ends with 9. It's wrong.

**Expected behavior**
The range has to start from the minimum value (4) and ends with the maximum value (33).

**Screenshots**
![The slider filter in the members directory may not work](https://user-images.githubusercontent.com/28895658/106050524-f6437b80-60ef-11eb-940e-d494af4d66e9.png)

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**Comment by ashubawork** [comment]
Fixed https://github.com/ultimatemember/ultimatemember/pull/762
