### ISSUE TITLE
I have a wordpress and elementor website and with the UltimateUser plugin. All works as it should but when a user is logged in it seems to affect some blocks/assets formatting. Has anyone had something similar to this happen? 

### ISSUE THREAD

**Issue by MrJamesPorter** [ultimatemember/ultimatemember#739]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.ultimatemember.com

If you have a problem, you may want to start with the self help guide here: https://docs.ultimatemember.com/article/1507-ultimate-member-self-service-guide/

**Technical support for premium extensions or if you're a UltimateMember.com customer**
Please submit a ticket via the support page
https://ultimatemember.com/support/ticket/

**General questions**
- WordPress.org Forums: https://wordpress.org/support/plugin/ultimate-member/

**Comment by champsupertramp** [comment]
Please follow the bug reporting format.
