### ISSUE TITLE
Wrong local time in UM since WP 5.3

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#741]
**Describe the bug**
When trying to find out why users last login time (‘_um_last_login’) is always wrong and after reading this page about old WP time formats being replaced in WP5.3:

Source: https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

my question when will UM be updated to use the new WP 5.3 API functions?

Looking at the UM code for “_um_last_login” I found both
`update_user_meta( $this->id, '_um_last_login', time());`
and
`update_user_meta( $user_id, '_um_last_login', current_time( 'timestamp' ) );`

Searching for `current_time( 'timestamp' )` which is no longer a valid WP timestamp gave 22 hits.

**WordPress Topic**
https://wordpress.org/support/topic/wrong-local-time-in-um-since-wp-5-3/

**Comment by nikitasinelnikov** [comment]
Fixed in https://github.com/ultimatemember/ultimatemember/releases/tag/2.8.0
