### ISSUE TITLE
Missing Administrator role from the Menu visibility settings

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#766]
**Expected behavior**
With the administrator role, this allows us to display specific menu to be visible to Administrators only.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps below.

**To Reproduce**
1. Go to WP Admin > Appearance > Menus
2. Add or Edit a menu
3. See "Ultimate Member Menu Settings"
4.  see "Who can see this menu link?" and choose "Logged in Users"
5. see that Administrator role is missing from the list "Select the member roles that can see this link"

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
```
Copy and paste the install info from ** Ultimate Member > Settings > Install Info ** in WordPress admin.
```
</details>

**Comment by ashubawork** [comment]
Pull request https://github.com/ultimatemember/ultimatemember/pull/770
