### ISSUE TITLE
Translation of UM User (profile) page

### ISSUE THREAD

**Issue by meunier-d** [ultimatemember/ultimatemember#767]
Hi, 
I'm currently translating UM pages with WPML. 
I could translate the login, registration, and account pages. But I'm struggling with the User page. I can see the translation in my editor, but the link is not working in the language switcher. I'm re-directed to the English version. 
Could you please help?
https://learning.iarc.fr/edp/login/

Thank you very much!

**Comment by yuriinalivaiko** [comment]
Hi. Have you created the User (profile) page for each language?
Look at documentation: [How to translate pages and forms](https://docs.ultimatemember.com/article/1449-how-to-translate-plugin#forms)

Try to update WordPress rewrite rules. Go to the page [wp-admin > Settings > Permalinks] and click the "Save Changes" button. You shouldn't change anything on the page, just click a button. WordPress will update rewrite rules.
