### ISSUE TITLE
Force redirect for user role

### ISSUE THREAD

**Issue by marko-collab** [ultimatemember/ultimatemember#771]
Hi gents, 

I'd like to force redirect selected user role(s) to certain URL when they (re)visit website, without using additional plugins and whatsoever. 

In UM we have option to redirect member role to URL but "after log in" only,  which means that option will be worthless until member physically log out and log back in. That means it can be months until we manage user to be redirected on desired URL  

Maybe you want to create "**Force redirect**" option which will redirect user to selected URL once he's back to website.

Thanks and all the best

**Comment by ashubawork** [comment]
Hello @marko-collab 

You could use this hook - https://gist.github.com/ashubawork/ceea5e190440ba743b4a7a9f07dda2a3

Regards.
