### ISSUE TITLE
Permanently delete form field not delete the field from current form and all other UM forms.

### ISSUE THREAD

**Issue by nikitasinelnikov** [ultimatemember/ultimatemember#786]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
When you delete permanently custom form fields it's still on the current form and other UM forms

**To Reproduce**
1. Go to Ultimate Member > Forms > Edit Form
2. Click on '+' in the Form Builder and click to "Delete permanently" field in custom fields https://www.screencast.com/t/8auwHC54

**Expected behavior**
I guess that permanently delete the form's field must remove this field from all UM Forms.

Please change this alert and notify the users about permanently delete from all UM Forms https://www.screencast.com/t/YKYXX2C5pfFv

**Comment by ashubawork** [comment]
Pull request - https://github.com/ultimatemember/ultimatemember/pull/790
