### ISSUE TITLE
Call to missing filter

### ISSUE THREAD

**Issue by melvinsh** [ultimatemember/ultimatemember#79]
In `um-short-functions.php:1297`, ([here](https://github.com/ultimatemember/ultimatemember/blob/master/core/um-short-functions.php#L1297)), the function calls `apply_filters` with `um_user_display_name_filter`. 

It seems to me like this filter doesn't exist, so I think you could just `return $name` there.

**Comment by melvinsh** [comment]
@champsupertramp ?

**Comment by champsupertramp** [comment]
@melvinsh, hi, it looks like that filter has been removed? line 1297 ?

**Comment by melvinsh** [comment]
@champsupertramp It's on line 1307 now :smile:

**Comment by champsupertramp** [comment]
Hi, You can use that filter to  add format in display name:

```PHP
add_filter('um_user_display_name_filter','custom_user_display_name', 3);
function custom_user_display_name( $name, $user_id, $attr ){
  $name = '<span class="strike">'.$name.'</span>';
   return $name;
} 

```
