### ISSUE TITLE
UM access Controls

### ISSUE THREAD

**Issue by yuriinalivaiko** [ultimatemember/ultimatemember#793]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The block "UM access Controls" works wrong. Conditional fields are visible. 

**To Reproduce**
1. Go to [wp-admin > Ultimate Member > Settings > Misc] and turn on "Enable Gutenberg Blocks".
2. Go to [wp-admin > Posts] and add a new post.
3. Add block "Image" into the post's content.
4. Look at the block settings. The setting "Restrict access?" is turned off, but conditional settings "Who can access this content?", "What roles can access this content?", "Restriction Action" are visible.

**Expected behavior**
Conditional settings "Who can access this content?", "What roles can access this content?", "Restriction Action" must be hidden if the parent setting "Restrict access?" is turned off.

**Screenshots**
Image 1 - The block "UM access Controls"
![UM access Controls style issue](https://user-images.githubusercontent.com/78854651/112865669-a702d280-90c1-11eb-86cf-c6bf3bf7654a.png)

**Comment by champsupertramp** [comment]
Hi @yuriinalivaiko  is there also a fix for the style of option "What Roles can access this Content"  to make the height at least 300px? Let me know if i should create another issue for this.

Thank you

**Comment by yuriinalivaiko** [comment]
Yes, styles for the setting "What Roles can access this Content" has been fixed.
