### ISSUE TITLE
Restricted content message is showing twice and removing header

### ISSUE THREAD

**Issue by yuriinalivaiko** [ultimatemember/ultimatemember#799]
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
I'm using the Avada theme with Ultimate Member, I have a template set up in Avada which is working fine. When I got to a restricted page like it seems to be replacing the header with an extra restricted message.

**To Reproduce**
1. Install the Avada theme.
2. Go to the [wp-admin > Avada > Layouts].
3. Configure header for the global layout.
4. Go to the [wp-admin > Pages].
5. Create a new page with restricted access and custom Restrict Content message.
6. Log out and look at this page. You’ll see two Restrict Content messages and no header.

**Expected behavior**
Display a proper header and single restricted content message in the content area.

**WordPress Environment**
<details>
--- WordPress Configurations ---
Version:					5.7
Active Theme:				Avada Child 1.0.0
</details>

**Comment by freelancesam** [comment]
Hi @yuriinalivaiko 

This was my issue on behalf of my client. As this is now fixed, could you please remove the screenshots and the WordPress Environment details to protect the privacy of my client and my server as I didn't agree to make these public.

Thanks
