### ISSUE TITLE
There isn't possible to use spaces in username

### ISSUE THREAD

**Issue by nikitasinelnikov** [ultimatemember/ultimatemember#812]
**Expected behavior**
WP native regular expression provides an ability to use <space> in the username

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
There isn't possible to use spaces in the username field on the registration process.

**Comment by Hastibe** [comment]
I would prefer that users can't create usernames with spaces (such as for reasons stated in [this article](https://www.trickspanda.com/prevent-spaces-wordpress-usernames/) -- is the code in the article a way this new feature can be disabled or is there another recommended way to prevent the creation of usernames with spaces in them?
