### ISSUE TITLE
UM Gutenburg blocks are adding extra <p> tags above the forms, causing white spaces in the front-end

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#818]
**Is your feature request related to a problem? Please describe.**
The gutenberg blocks are rendering <p> tags above each UM form.
<img width="750" alt="Screen Shot 2021-04-19 at 4 09 55 PM" src="https://user-images.githubusercontent.com/12200688/115203301-e608ce80-a129-11eb-91d1-72c28f8a4684.png">

**Describe alternatives you've considered**
The alternative is to add the CSS to hide those extra `<p>` tags:
```
p.wp-block-um-block-um-forms{
    display:none;
}
```

**Comment by ashubawork** [comment]
Checked on WP 6.2.2 and UM 2.6.3 - there is no such issue.
