### ISSUE TITLE
User defined label text for the  “Confirm password” field

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#828]
**Is your feature request related to a problem? Please describe.**
Today you click for the  “Confirm password” field to be displayed during registration and UM is using the word Confirm and is adding the Label or Placeholder from the primary password field.  Limited user possibilities to use their own label text like in all the other primary password fields.

**Describe the solution you'd like**
An additional modal text field for the option to have user defined label text for the  “Confirm password” field.

**Describe alternatives you've considered**
Some users have found the plugin "Say What?" useful to change the text online by catching the text during processing.
https://wordpress.org/plugins/say-what/
Another solution is described in the UM documentation but is too difficult and takes too long time to implement for the average user
https://docs.ultimatemember.com/article/1578-change-english-text-in-forms

**Additional context**
User Support issue:
https://wordpress.org/support/topic/confirm-password-label-translate/

**Comment by yuriinalivaiko** [comment]
A label is used as a part of placeholder. It has to be modified too.
