### ISSUE TITLE
Profile Image Rotation

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#829]
**Describe the solution you'd like**
Since WordPress 5.3, automatic image rotation on upload has been integrated into core – https://core.trac.wordpress.org/ticket/14459. Ultimate Member seems to bypass this feature altogether when uploading portrait images on a phone.

**Additional Details***
The solution has been created by a report:
https://gist.github.com/cy-josh/451f8681bdf9f6d808698de938897b4a

Topic: https://wordpress.org/support/topic/profile-image-rotation/#post-14395971

**Comment by benjaminthedev** [comment]
@champsupertramp Any updates on this as I am experiencing the same issues as Josh. Thanks!

**Comment by genniec** [comment]
Hello, my client has just been asking when this will be fixed. Mobile users can't add landscape photos to their profile without having them rotated.

**Comment by ashubawork** [comment]
There is the "Change image orientation" (Ultimate Member - Settings - General - Uploads)
