### ISSUE TITLE
Documentation is incredibly sparse

### ISSUE THREAD

**Issue by dsifford** [ultimatemember/ultimatemember#83]
To quote your readme on WordPress.org

"[...]Developer friendly with dozens of actions and filters"

Where are these documented? I've looked on your site. Documentation is non-existent, less the 18 generic functions that you have listed in the "codex". Please consider fixing this.

**Comment by ultimatemember** [comment]
Hi dsifford,

Yes sorry for this, we will be making major improvements to developer documentation. We have just been swamped with support and development that last few months that we have not had a chance to work on it.

Thanks!

**Comment by dsifford** [comment]
:+1:
