### ISSUE TITLE
Conflicts with elementor

### ISSUE THREAD

**Issue by AzmayenFayek** [ultimatemember/ultimatemember#893]
Hi I've installed ultimate member plugin. But registration page is not showing when elementor is active. 
again if elementor is active and I click on registration button then that page doesn't show any form for first time. But if I click on "inspect" then the form shows automatically. If I refresh the page keeping "inspect" as it is then the registration form goes again. But if I close the "inspect" again then the form shows again. Don't know why this happening please solve the isssue

**Comment by champsupertramp** [comment]
Hi @AzmayenFayek 

Try adding this CSS: 
```
.um-register{ opacity: 1 !important; }
```

**Comment by AzmayenFayek** [comment]
Thanks Ultimatemember/Ultimatemember for solving this issue

**Comment by AzmayenFayek** [comment]
Hi, I'm using ultimate member and sportspress plugin. Problem is that if I register from wp default registration then new players profile details is created in sportspress. But for ultimate member registration sportspress can not catch those data. what could be the problem. Can you please solve it.
thanks in advance
