### ISSUE TITLE
Request to non-existent URL generates PHP Fatal error, not 404

### ISSUE THREAD

**Issue by joostdekeijzer** [ultimatemember/ultimatemember#897]
**Expected behavior**
Don't Fatal Error, do a 404.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
When requesting a non-existend URL like http://[your site]/i-dont-exist/ or http://[your site]/favicon.ico (if that does not exist) a PHP Fatal Error is generated.

````
[23-Aug-2021 13:54:50 UTC] PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, string given in /<sorry, private>/wp-content/plugins/ultimate-member/includes/core/class-access.php:169
Stack trace:
#0 /<sorry, private>/wp-content/plugins/ultimate-member/includes/core/class-access.php(169): array_keys('')
#1 /<sorry, private>/wp-content/plugins/ultimate-member/includes/core/class-access.php(421): um\core\Access->exclude_posts_array(false)
#2 /<sorry, private>/wp-includes/class-wp-hook.php(303): um\core\Access->exclude_posts(Object(WP_Query))
#3 /<sorry, private>/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /<sorry, private>/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#5 /<sorry, private>/wp-includes/class-wp-query.php(1784): do_action_ref_array('pre_get_posts', Array)
#6 /<sorry, private>/wp-includes/class-wp-query.php(3465): WP_Query->get_posts()
#7 /<sorry, private>/wp-includes/class-wp.php(629): WP_Query->query(Array)
#8 /<sorry, private>/wp-includes/class-wp.php(752): WP->query_posts()
#9 /<sorry, private>/wp-includes/functions.php(1291): WP->main('')
#10 /<sorry, private>/wp-blog-header.php(16): wp()
#11 /<sorry, private>/index.php(17): require('/<sorry, private>...')
#12 {main}
  thrown in /<sorry, private>/wp-content/plugins/ultimate-member/includes/core/class-access.php on line 169
````

**To Reproduce**
1. Go to a non-existent URL like http://[your site]/i-dont-exist/ or http://[your site]/favicon.ico (if that does not exist)
2. See error in php error.log

**Expected behavior**
Don't Fatal Error

**Screenshots**

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
```
Copy and paste the install info from ** Ultimate Member > Settings > Install Info ** in WordPress admin.
```
</details>

**Comment by nikitasinelnikov** [comment]
Hi @joostdekeijzer 

The fix has been added to the master branch. Please let me know if the issue is fixed.

Best Regards!

**Comment by joostdekeijzer** [comment]
Yes, solved.
