### ISSUE TITLE
Constant already defined

### ISSUE THREAD

**Issue by robincornett** [ultimatemember/ultimatemember#9]
I've just installed UM on a localhost to see if it might be a good option for a client. When I'm on any UM page, I get the following PHP Notice: Constant DONOTCACHEPAGE already defined, being called from wp-content/plugins/ultimate-member/core/um-cache.php:17. So I checked there and if you change the conditional to the following:

`if ( um_is_core_uri() && ! defined( 'DONOTCACHEPAGE' ) )`

so that it checks if the constant is already defined, the error goes away. Not sure if this will keep things all right with caching plugins, but thought I would report. Thanks!

**Comment by ultimatemember** [comment]
Will include in next minor update.
