### ISSUE TITLE
Where to change registered success message?

### ISSUE THREAD

**Issue by AzmayenFayek** [ultimatemember/ultimatemember#907]
I changed this message:
"Thank you for applying for membership to our site. We will review your details and send you an email letting you know whether your application has been successful or not." To ----->> "Thanks for registering"
here:
wp-content/plugins/ultimate-member/languages/ultimate-member-en_US.po and
wp-content/plugins/ultimate-member/includes/admin/templates/role/register.php

the code is like this
array(
				'id'		=> '_um_pending_message',
				'type'		=> 'textarea',
				'label'    		=> __( 'Personalize the custom message', 'ultimate-member' ),
				'value' 		=> ! empty( $role['_um_pending_message'] ) ? __( $role['_um_pending_message'], 'ultimate-member' ) : __('Thanks for registering. Please check your email for activation. ','ultimate-member'),
				'conditional'	=> array( '_um_pending_action', '=', 'show_message' )
			),

But this message is not changed.
will you please tell me where to change this default message

![image](https://user-images.githubusercontent.com/28837633/131239008-abcc7cf1-9c36-4309-b839-0882a9beb853.png)

**Comment by champsupertramp** [comment]
Hi @AzmayenFayek 

Have you tried changing it in the User Role settings > Registration Options 
<img width="964" alt="Screen Shot 2021-09-09 at 6 27 05 PM" src="https://user-images.githubusercontent.com/12200688/132669850-6352643f-20a8-4d44-a49c-92d150c374b0.png">

**Comment by AzmayenFayek** [comment]
O thanks for letting me know. Yes I changed it here. And it works now.

Btw do you have any option, redirect to the restricted pages after logging
in?
I mean clicked --> restricted page --> login page --> logged in & shows
that restricted page.

There is an option to custom url but I have three restricted page and I
need to show, that page(after logged in) where user clicked before.

**Comment by AzmayenFayek** [comment]
Got it. Thank you very much.
Being an admin can I download all the user info with their profile image at
a time?

**Comment by AzmayenFayek** [comment]
How can I change the directory for uploading image from "ultimate member"
plugin to wp library
