### ISSUE TITLE
Ampersand in dropdown field returns no members

### ISSUE THREAD

**Issue by aswin-giri** [ultimatemember/ultimatemember#910]
- [x ] I have deactivated other plugins and confirmed this bug occurs when only the Ultimate Member plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [ x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
If a dropdown field has "&" in the value, it gets saved as user meta however using the same meta key as a filter for member directory does not return any data as "&" gets converted to "&amp;" when sending the query.

**To Reproduce**
1. Add dropdown field to profile form.
2. Add multiple options with the "&" sign.
3.  Save the form and edit the user profile.
4. Select option with "&" sign and updated the profile so that this can be used for directory filter
5.  Add filter to member directory with the metadata just created
6. try to filter the directory

**Expected behavior**
Either database value should be saved as HTML entity "&amp;" or filter should just query what value is saved in the database

**Comment by nikitasinelnikov** [comment]
Hi @aswin-giri 

Please check if this issue is actual for 2.2.5 version. I guess it already has been fixed few versions ago.

Let me know,
Best Regards!

**Comment by ashubawork** [comment]
Hello @aswin-giri and @nikitasinelnikov 

Checked the WP 6.4.1 and the UM 2.7.0 - the шыыгу is not reproducible.

Regards
