### ISSUE TITLE
Display name does not update user profile change First name and Last name.

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/ultimatemember#923]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The User Display Name setting does not change the display of the First name and Last name if the value is set to - Default WP Display Name.

**To Reproduce**
1. Go to WP-Admin > Users > Select Users and click on > Display name publicly as - select "First Name Last Name" in dropdown item.
2. WP-Admin > UM > Settings > General > Users > User Display Name - select "Default WP Display Name" in dropdown item and save changes.
3. Go to site > Login as the user selected in p.1 > Gear button > Edit Profile > Edit "First name" and "Last name" fields and Update profile.
4. See in profile user display name, not changes.

**Comment by nikitasinelnikov** [comment]
Fixed in fc92903f97b8ea7cccf0b3c078caf90a4af2cf4a
