### ISSUE TITLE
Username Enumeration in Password Reset Form

### ISSUE THREAD

**Issue by ollielowson** [ultimatemember/ultimatemember#925]
We have been notified of a potential security issue in the Ultimate Member plugin, which appears to be arising from hard-coded logic, so I am mentioning it here in case you would like to make an update.

We have been notified that on submitting the forgotten password form, the response is different depending on whether the e-mail address or username itself exists in the system.

Recommended best practice is to use a generic message that says something along the lines of "Your request has been received, if an account is registered with those details we will send you a password reset link in an e-mail...", so that existence of accounts cannot be leaked.

The code in question is here:
https://github.com/wp-plugins/ultimate-member/blob/9bb3cb349244ac0eae0ee36098b52a1dcb38c360/core/um-actions-password.php#L92

I don't have time at the moment to make a pull request myself, but if I do get time and it has not been resolved, I will do so.

I hope this is helpful.

Kind regards,

Ollie Lowson

**Comment by nikitasinelnikov** [comment]
Hi @ollielowson 

It seems you have an outdated old version of Ultimate Member (at least the link points to the 1.1.4 code).
We still have this error code line in the newest 2.2.5 version but it's the WP native way to use the username or email address in the password reset form. The form has restrictions on the number of submissions and honeypot security.

You may change this line via PO-Edit or other tools for changing translation lines and remove mention of the email address or username.

Best Regards!

**Comment by ollielowson** [comment]
Sorry @nikitasinelnikov - I hadn't noticed that this was a mirror repository.

I have a possible solution, which if it works for us I will post as a PR on the correct repository in case it is useful for anyone else

**Comment by ollielowson** [comment]
I have raised PR: https://github.com/ultimatemember/ultimatemember/pull/927
