### ISSUE TITLE
UM not sending email after password has changed

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#936]
**Expected behavior**
User receiving a confirmation email after successful password change via "Reset my password"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [X] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [X] I can reproduce this bug consistently using the steps above.

**Describe the bug**
Core UM function "send" in "class-email.php" is called by the "password_changed" function in "class-user.php" with first parameter "um_user( 'user_email' )" empty and the "send" function can't validate the empty email address and returns to the caller without sending email confirmation of the password change.

**To Reproduce**
1. UM Settings -> Email -> Enable: "Password Changed Email" & "Password Reset Email" 
2. Go to the UM reset password page
3. Enter your username or email 
4. Click button: "Reset my password"
5. Message: "We have sent you a password reset link to your e-mail. Please check your inbox."
6. Click the link in the "Password Reset Email"
7. Enter new password & confirm password
8. Click button: "Change my password"
9. Only the WP "Password changed for user:" email is received by the site admin
10. The password change is only confirmed for the user on the UM screen with text on green background: "You have successfully changed your password."

**Expected behavior**
A confirmation email sent to the user email address as configured above in step 1.

**Do you use UM extensions?**
No

**WordPress Environment**
WP 5.8.1
UM 2.2.5

Code snippet to supply a valid email address for the "send" function:

```
`add_action( 'password_reset', 'um_password_reset_email', 10, 2 );

function um_password_reset_email( $user, $new_pass ) {

    um_fetch_user( $user->ID );
}`
```

UM Core update code for "class-password.php" ( addition of  `um_fetch_user( $user->ID );` ):

```
`				if ( ( ! $errors->get_error_code() ) ) {
					reset_password( $user, sanitize_text_field( $args['user_password'] ) );
					um_fetch_user( $user->ID ); // Add for empty email in send function
					// send the Password Changed Email
					UM()->user()->password_changed();

					// clear temporary data`
```

Note: The "$user" variable above is a local object to the "um_change_password_process_hook" function.

**Support Forum**
https://wordpress.org/support/topic/um-not-sending-email-after-password-has-changed/

**Comment by ashubawork** [comment]
Checked the WP 6.4.1 and the UM 2.7.0 - all emails are sent correctly.
