### ISSUE TITLE
Admin user profile page compares um_role with logged in user instead of context user

### ISSUE THREAD

**Issue by markuskothe** [ultimatemember/ultimatemember#94]
In this row, the user that is checked for um_role seems to be the logged in user instead of the context user?
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-user.php#L71

`um_user('role')
should be
$user->role
?`

**Comment by champsupertramp** [comment]
Hi @markuskothe  `$user->role` has the WP roles. `um_user('role')` has the UM community role.

**Comment by markuskothe** [comment]
hmm... still, um_user('role') returned the role for me as logged in Admin and not the user I was editing

**Comment by champsupertramp** [comment]
@markuskothe can you check my recent commit if this work for you?
https://github.com/ultimatemember/ultimatemember/blob/master/core/um-user.php#L60
