### ISSUE TITLE
Allow user to use custom user profile url slug

### ISSUE THREAD

**Issue by mansurahamed** [ultimatemember/ultimatemember#947]
Right now user can use only few predefined profile url slug to be set in Ultimate Member->Settings->General->Users->Profile Permalink Base. 

This is feature request to add any action hook which will allow user to use custom profile permalink slug as in um_user_profile_url_slug_user_login  meta value.

**Comment by nikitasinelnikov** [comment]
@mansurahamed
This feature has been added in the 2.7.0 version
https://github.com/ultimatemember/ultimatemember/releases/tag/2.7.0
