### ISSUE TITLE
Form validation does not respect User Tag custom fields

### ISSUE THREAD

**Issue by nickburne** [ultimatemember/ultimatemember#95]
I have a default registration form with a user tag custom field on it and have set it to required, but it doesn't work.

**Comment by nickburne** [comment]
We're looking into fixing this and will send a pull request.

**Comment by nickburne** [comment]
Same issue on profile forms as well as registration forms.

**Comment by champsupertramp** [comment]
Hi @nickburne , I think this will be fixed in the User Tags extension.

**Comment by nickburne** [comment]
@champsupertramp - didn't know which one it would be solved in (extension, core or both). Happy to have access to user tags github if we can help.

**Comment by nickburne** [comment]
@champsupertramp - looks like we are able to fix this in core

**Comment by nickburne** [comment]
@champsupertramp @jonfalcon hi guys, we have just done a pull request for this. Thanks!
