### ISSUE TITLE
Deactivating a user implies auto logout

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#970]
**Is your feature request related to a problem? Please describe.**
Administrators assumes that deactivating an account also implies logout of the user and the truth is that the user can still navigate in the site until the user decides to logout. 

**Describe the solution you'd like**
Deactivating also performs an auto logout of the user's all sessions like 
`WP -> All Users -> Edit User -> Sessions -> Log Out Everywhere` .

**Describe alternatives you've considered**
None

**Additional context**

**Comment by ashubawork** [comment]
Hello @MissVeronica 

Checked the WP 6.4.1 and the UM 2.7.0 - deactivated accounts are automatically logged out. Could you check this from your side?

Regards.

**Comment by MissVeronica** [comment]
> deactivated accounts are automatically logged  out.

Yes, I can confirm this issue is fixed.
