### ISSUE TITLE
User::password_reset_key is not cleared when switching user contexts

### ISSUE THREAD

**Issue by justdave** [ultimatemember/ultimatemember#991]
**Expected behavior**
Calling `UM()->password->reset_url()` after `um_fetch_user()` should produce a unique hash for each user it's called on.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
I am running a site where youth have member accounts on the site, and we create a companion parent account for them at the same time from the registration form, and send a welcome email to both users with a password reset link in it to set their password (generated from `UM()->password()->reset_url()` )
We are hooking `um_after_user_is_approved` to send out the email for the account created by UM processing the registration form, and then manually calling the same function with the user ID of the parent account immediately after using `wp_insert_user()` to create the parent account.
We are calling `um_fetch_user()` on the userid just before asking for the `reset_url`.  I should get a unique reset link specific to the account in question each time it's called.  Instead, I get a broken link with an invalid token from the second call to `reset_url`.  Each produced link has the correct userid parameter for the user it was called on in the returned URL, but both of them have the same hash, and examining the database shows only the one hash was written to the database on the first user, and the second one was never stored.
It appears that the password_reset_key is getting cached after the first time it's generated, and the cache is not aware of which user it's cached for.

Forcibly clearing the cache before calling it seems to work as a workaround. This is probably not a good workaround as I could theoretically call it more than once on the same user, and in that case I should get the same hash again instead of it generating another new one.  Basically the cache should exist, but needs to be user-aware.

**To Reproduce**
1. put the following code in your `um_after_user_is_approved` hook:
```
    um_fetch_user( $userid );
    $args = array(
        'activation_link' => UM()->password()->reset_url(),
    );
    um_reset_user();
```
2. hook `um_registration_complete` and create a second account from data passed in the registration form in addition to the one being automatically created, then call your `um_after_user_is_approved` hook manually on that account.

**Expected behavior**
Calling `UM()->password->reset_url()` after `um_fetch_user()` should produce a unique hash for each user it's called on.

The following code works around it:
```
    um_fetch_user( $userid );
    // do not use a cached copy!!!
    UM()->user()->password_reset_key = null;
    $args = array(
        'activation_link' => UM()->password()->reset_url(),
    );
    um_reset_user();
```

**Screenshots**
(nothing is applicable)

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [x] WooCommerce

**WordPress Environment**
<details>
```
### Begin Install Info ###

## Please include this information when posting support requests ##


--- Site Info ---

Site URL:					https://member-test.XXXX.org
Home URL:					https://member-test.XXXX.org
Multisite:					No

--- Hosting Provider ---

Host:						DBH: mysql.XXXX.org, SRV: member-test.XXXX.org

--- User Browser ---

Platform:                 Apple 
Browser Name:             Firefox  
Browser Version:          99.0 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10.15; rv:99.0) Gecko/201
                          00101 Firefox/99.0
                          
---- Current User Details --

Role: administrator, um_volunteer


--- WordPress Configurations ---

Version:						5.9.2
Language:					en_US
Permalink Structure:			/%year%/%monthnum%/%day%/%postname%/
Active Theme:				GRYS 1.0
Page On Front:				XXXX Members Only (#13)
Page For Posts:				 (#0)
ABSPATH:					/home/XXXX/member-test.XXXX.org/
All Posts/Pages:				7
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Enabled
WP Table Prefix:          			Length: 3, Status: Acceptable
Memory Limit:   				40MB


--- UM Configurations ---

Version:						2.3.1
Upgraded From:            		2.3.0
Current URL Method:			
Cache User Profile:			No
Generate Slugs on Directories:	Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			Yes
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No


--- UM Pages Configuration ---

User:						https://member-test.XXXX.org/user/
Account:						https://member-test.XXXX.org/account/
Members:					https://member-test.XXXX.org/musicians/
Register:						https://member-test.XXXX.org/no-access/
Login:						https://member-test.XXXX.org/login/
Logout:						https://member-test.XXXX.org/logout/
Password Reset:				https://member-test.XXXX.org/password-reset/


--- UM Users Configuration ---

Default New User Role: 		0
Profile Permalink Base:		name
User Display Name:			full_name
Force Name to Uppercase:		No
Redirect author to profile: 		Yes
Enable Members Directory:	Yes
Use Gravatars: 				No
Require a strong password: 	Off


--- UM Access Configuration ---

Panic Key: 								
Global Site Access:						Site accessible to Logged In Users
Custom Redirect URL:						https://member-test.XXXX.org/login/
Exclude the following URLs:				
Backend Login Screen for Guests:			No
Redirect to alternative login page:			
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		No
Enable the Reset Password Limit:			No
Blacklist Words: 							5


--- UM Email Configurations ---

Mail appears from:  			XXXXXXXXX
Mail appears from address:  	XXXX@XXXX.org
Use HTML for E-mails:   		Yes
Account Welcome Email:  		No
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	No
Account Deleted Email:  		No
Password Reset Email:   		Yes
Password Changed Email: 		Yes


--- UM Total Users ---

All Users(457)
administrator(13)
um_musician(112)
um_volunteer(9)
um_staff(4)
um_parent-guardian(182)
signup_sheet_manager(4)
um_audition-registered(1)
um_auditioning-parent(10)
um_audition-failed(6)
um_former-musician(46)
um_former-parent(80)
XXXX_audition_judge(7)
XXXX_XXXX_judge(3)
XXXX_XXXX_screener(3)
none(4)


--- UM Roles ---

Administrator (administrator)
Musician (um_musician)
Volunteer (um_volunteer)
Staff (um_staff)
Parent/Guardian (um_parent-guardian)
Sign-up Sheet Manager (signup_sheet_manager)
New Parent (um_new-parent)
Customer (customer)
Shop manager (shop_manager)
Audition Registered (um_audition-registered)
Audition Paid (um_audition-paid)
Auditioning Parent (um_auditioning-parent)
Audition Passed (um_audition-passed)
Audition Failed (um_audition-failed)
Former Musician (um_former-musician)
Former Parent (um_former-parent)
Returning Musician (um_returning-musician)
Returning Parent (um_returning-parent)
Audition Judge (XXXX_audition_judge)
Audition Screener (XXXX_audition_screener)
XXXX Judge (XXXX_XXXX_judge)
XXXX Screener (XXXX_XXXX_screener)


--- UM Custom Templates ---

				N/A


--- UM Email HTML Templates ---

				N/A


--- Web Server Configurations ---

PHP Version:              			7.4.15
MySQL Version:            			8.0.28
Web Server Info:          			Apache


--- PHP Configurations ---

PHP Memory Limit:         			256M
PHP Upload Max Size:      			512M
PHP Post Max Size:        			512M
PHP Upload Max Filesize:  			512M
PHP Time Limit:           			120
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			Yes


--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			N/A
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function exist on your web server.
Exif:				          PHP Exif library is installed on your web server.


--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			/tmp
Use Cookies:              			On
Use Only Cookies:         			On


--- WordPress Active Plugins ---

Advanced Order Export For WooCommerce: 3.2.2
All In One WP Security: 4.4.10
Allow Multiple Accounts: 3.0.4
Bulk Media Register: 1.25
Contact Form 7: 5.5.6
Contact Form DB: 2.10.37
Download Monitor: 4.5.8
Easy Updates Manager: 9.0.12
Git Updater: 10.7.2
XXXX Member Site custom additions: 1.0
Kadence Blocks – Gutenberg Blocks for Page Builder Features: 2.3.0
Members: 3.1.7
Simple Calendar: 3.1.36
Simple Login Log: 1.1.3
SMTP Mailing Queue: 1.4.7
Ultimate Member: 2.3.1
Virtue/Ascend/Pinnacle Toolkit: 4.9.6
Volunteer Sign Up Sheets: 3.7.1
WooCommerce: 6.3.1
WordPress Importer: 0.7
WordPress Users & WooCommerce Customers Import Export(BASIC): 2.2.8
WP Post Page Clone: 1.2
WP Reroute Email: 1.4.6

### End Install Info ###
					
```
</details>

**Comment by davidajohnson** [comment]
https://github.com/ultimatemember/ultimatemember/issues/1083 seems to be the same issue.

**Comment by justdave** [comment]
@nikitasinelnikov does the commit in 8b2770b12ea207129d91ffbdc30be6b9f4443c9d mean that my workaround above will begin crashing when this fix is picked up, and I'll need to remove it?

**Comment by nikitasinelnikov** [comment]
Hi @justdave 

Your workaround will be over functionality since 2.5.2 release. We moved from using class variable 'UM()->user()->password_reset_key' so reset password hash will be unique for each user and not cached.

Let me know if you have other questions,
Best Regards!
